### ISSUE TITLE
Allow operators to edit their host's TOC

### ISSUE THREAD

**Issue by wojake** [EvernodeXRPL/evernode-host#100]
During the beta phases, operators aren't able to edit their host's TOC. We're close to launch now, it's best to give them the right to edit and put up their own TOC.

**Comment by wojake** [comment]
I can't find where hosts store their TOC, on-chain and off-chain. So I'll just assume that it's stored on the dashboard.

Storing data on a Hook is costly, so we shouldn't store them on a Hook. Hosts should store their TOC on-chain, particularly on a `not-for-sale` URIToken with its URI field containing a pointer (link) to the host's TOC.

**Comment by ravinsp** [comment]
@wojake The ToS Egnlish text is shown on the dashboard. But the hash of that text is baked into every Lease URI Token issued by the host.

**Comment by ravinsp** [comment]
@wojake Regarding "Allow operators to edit their host's TOC", we are not going to make it customizable. Everyone plays by the same rules.

**Comment by wojake** [comment]
I'll be closing this issue then, but is this legally viable @ScottChamberlain?
