### ISSUE TITLE
Error Setting up node

### ISSUE THREAD

**Issue by BfgDaily** [EvernodeXRPL/evernode-host#102]
I followed the steps to setting up an Evernode. I received an error. it was settin up the Letsencrpt cerbot. 

There was an error during installation. this is the file /tmp/everrnode-beta/installer/-1688786311.log
![IMG-2797](https://github.com/EvernodeXRPL/evernode-host/assets/138955398/60176d66-7c7f-472c-ad62-df6f94615a00)

**Comment by ravinsp** [comment]
@BfgDaily You need to attach or copy/paste the contents of the file at `/tmp/everrnode-beta/installer-1688786311.log` here.

**Comment by BfgDaily** [comment]
@ravinsp Thanks for your assistance. I was able to get the node setup.
