### ISSUE TITLE
SWOP

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-host#103]
![Screen Shot 2023-08-07 at 22 48 01](https://github.com/EvernodeXRPL/evernode-host/assets/508629/91a7708b-522a-4365-a18a-6536ba5d0de3)

im not a 100% sure if this is evernode, as I run a few processes on the box but I have noticed the last few weeks that my swop is always full.

I can sit and watch swop climb after running
```sudo swapoff -a; sudo swapon -a```

**Comment by lathanbritz** [comment]
are there some commands to narrow this down to a javascript process / docker ?

as this would definitely help narrow the field for me unless other operators are facing similar issues.

**Comment by ravinsp** [comment]
@lathanbritz Probably `smem` command will help? https://www.cyberciti.biz/faq/linux-which-process-is-using-swap/
Try `smem -t -p`

**Comment by lathanbritz** [comment]
Thank you kindly yip that worked issue is not with evernode host
