### ISSUE TITLE
How can I collect my Evers?

### ISSUE THREAD

**Issue by mrnash88** [EvernodeXRPL/evernode-host#112]
I have accumulated some Evers now that I been hosting. I want to know how can I move my accumulated Evers that has been rewarded to me into a wallet? Thanks in advance.

**Comment by chalith** [comment]
The EVRs you are carrying are testnet EVRs they are not real money so you can't take them to your real wallet. For being part of Evernode beta net you'll receive real EVRs on the Airdrop which will happen in the near future.

**Comment by mrnash88** [comment]
first question: when will the EVRs airdrop be?
second question: how many EVRs are we gonna get?
third question: Will I be able to move the airdrop EVRs to my wallet? ...Thanks in advance.

**Comment by rippleitinnz** [comment]
What other benefits are you looking for in running an Evernode server, other than possibly receiving some EVRS?

**Comment by ravinsp** [comment]
@mrnash88 Evernode is currently in beta. Please watch [Twitter feed](https://twitter.com/EvernodeXRPL) for news updates.
