### ISSUE TITLE
Registration deposit question

### ISSUE THREAD

**Issue by mrnash88** [EvernodeXRPL/evernode-host#113]
I just looked at my registration deposit and it says it is at: 5120 but in the website: https://evernode.org/changes-to-beta-tester-airdrop-rewards/ it says:  **initial registration deposit for each new Host at 500 Evers**...Will I get reimbursed or is that my set registration fee? Thanks in advance.

**Comment by ravinsp** [comment]
500 EVR is the registration fee for the upcoming production "real" network with real money. 5120 EVR was the registration fee for the "fake" network with fake money used for the beta test network.

**Comment by mrnash88** [comment]
So how long will the "fake" network beta test that we're in going to last for? And when the "fake" network beta test is over will we be part of the "real" network when it takes effect? Also, while we are participating in the "fake" network will we be rewarded some certain amount of "real" EVRs during the process? Thanks in advance.

**Comment by ravinsp** [comment]
1. Current beta network may or may not have an end date and it is not dependent on the launch of the real production network.
2. There's no transition or migration from beta test network to production network.
3. There could be airdrops of real EVRs for contributors of the beta network, but that depends on the nature of the contribution and is at the discretion of Evernode labs.

**Comment by mrnash88** [comment]
Do you know when the upcoming production network will go live? and will it be open so that any one can become hosts? Thanks in advance.

**Comment by ravinsp** [comment]
Keep watching for updates on Twitter: https://twitter.com/EvernodeXRPL

**Comment by JohnCTOS** [comment]
Can you advise what the lease amount in EVR's should be during setup?

**Comment by mrnash88** [comment]
@JohnCTOS  lease amount can be whatever you want. But the most common amount I have seen is 2 evers. 
![Screenshot_20231229-060802_Chrome](https://github.com/EvernodeXRPL/evernode-host/assets/150109205/209d40e8-f318-4b1b-b442-f3f1fa20b23d)

**Comment by BimsaraFernando** [comment]
@mrnash88 ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
