### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by dan22101979** [EvernodeXRPL/evernode-host#114]
[installer-1700853727.log](https://github.com/EvernodeXRPL/evernode-host/files/13461823/installer-1700853727.log)
![error_during_installation](https://github.com/EvernodeXRPL/evernode-host/assets/133576171/f6e27c53-69ce-4cbd-b9cf-b3bd6460afdb)

**Comment by mrnash88** [comment]
open up the error log report that's in the evernode-beta folder and paste it here

type this bro: sudo gedit /tmp/evernode-beta/installer-1700853737.log

that way we can see what happened

**Comment by ravinsp** [comment]
@dan22101979 `Parked Domain name on Hostinger DNS system` Seems your domain thealphahost.online DNS is not configured.

From the log file:
```
Requesting a certificate for thealphahost.online

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: thealphahost.online
  Type:   unauthorized
  Detail: 84.32.84.32: Invalid response from http://thealphahost.online/.well-known/acme-challenge/GUqTIkmIrquPF3L3nDE8I5tmXESlTHavR4seVQUevaA: "<!doctype html><title>Parked Domain name on Hostinger DNS system</title><meta charset=utf-8><meta content=\"IE=edge,chrome=1\" htt"
```

**Comment by BimsaraFernando** [comment]
Hi @dan22101979 ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
