### ISSUE TITLE
Betatester airdrop question

### ISSUE THREAD

**Issue by mrnash88** [EvernodeXRPL/evernode-host#115]
I became a host early this month am I eligible for the beta tester airdrop?
 If so, what is the r-address? 
If not how can I qualify for future airdrops when you guys launch in december 18. Thanks in advance.

**Comment by BimsaraFernando** [comment]
Hi @mrnash88 ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
