### ISSUE TITLE
Run as a docker container : Grub GRUB_CMDLINE_LINUX update failed

### ISSUE THREAD

**Issue by VLEFF** [EvernodeXRPL/evernode-host#117]
Hi,

I'm working on creating a docker container that runs an Evernode Host, but I am not really sure if it is doable or not.
Since on your doc it's written that it only works on Ubuntu 20.04, and it need systemd to work, I started with this image : https://hub.docker.com/r/jrei/systemd-ubuntu

Has someone already achieved that?

For the moment, I'm stuck on the installation, I get this error : 

> \#curl -fsSL https://stevernode.blob.core.windows.net/evernode-beta-v3/setup.sh | sudo bash -s install
...
Setup will now begin the installation. Continue? [Y/n] y
Starting installation...
Installing prerequisites...
Installing dependencies
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
There was an error during installation. Please provide the file /tmp/evernode-beta/installer-1701710696.log to Evernode team. Thank you.

>\# more /tmp/evernode-beta/installer-1701710696.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 https://deb.nodesource.com/node_16.x focal InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.20).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
0 upgraded, 0 newly installed, 0 to remove and 14 not upgraded.
STAGE Configuring fstab
Updated fstab.
quotacheck: Mountpoint (or device) / not found or has no quota enabled.
quotacheck: Cannot find filesystem to check or filesystem not mounted with quota option.
quotaon: Mountpoint (or device) / not found or has no quota enabled.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
cp: cannot stat '/usr/share/doc/cgroup-tools/examples/cgred.conf': No such file or directory
STAGE Configuring grub
cp: cannot stat '/etc/default/grub': No such file or directory
sed: can't read /tmp/tmp.XIqoVd4sOK.tmp: No such file or directory
Grub GRUB_CMDLINE_LINUX update failed.

**Comment by BimsaraFernando** [comment]
Hi @VLEFF ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
