### ISSUE TITLE
There was an error during installation.

### ISSUE THREAD

**Issue by XJohnK** [EvernodeXRPL/evernode-host#123]
"Setting up letsencrypt certbot
There was an error during installation. Please provide the file /tmp/evernode-beta/installer-1703146672.log to Evernode team. Thank you."

I've just got this error and I have no idea of this..

[installer-1703146672.log](https://github.com/EvernodeXRPL/evernode-host/files/13739038/installer-1703146672.log)

**Comment by chalith** [comment]
@XJohnK can you run the command `command -v certbot` in your machine and send us the output

**Comment by chalith** [comment]
Can you try running this command and install again `snap install core && snap refresh core && snap install --classic certbot`

**Comment by XJohnK** [comment]
I ran that command ! Should I run this `curl -fsSL https://stevernode.blob.core.windows.net/evernode-beta-v3/setup.sh | sudo bash -s install command` again??

**Comment by rippleitinnz** [comment]
> I ran that command ! Should I run this `curl -fsSL https://stevernode.blob.core.windows.net/evernode-beta-v3/setup.sh | sudo bash -s install command` again??

Try a dry run on letsencrypt and get that sorted first.

I've got instructions on that site for the install of Evernode. If you have problems yell out.

https://noledger.net/#test-lets-encrypt-preparedness

**Comment by XJohnK** [comment]
Ah! gotcha! you're right! cheers mate!

**Comment by BimsaraFernando** [comment]
Hi @XJohnK ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
