### ISSUE TITLE
No XRPL Account

### ISSUE THREAD

**Issue by JoeSulf** [EvernodeXRPL/evernode-host#124]
I have been watching CryptoERI  video and installing Evernode Beta. I have got to where it is asking for the XRPL account address. In the video it said this is all automated? How do I do this for the Beta?

**Comment by chalith** [comment]
You can generate a funded account for beta in dashboard. https://dashboard.evernode.org/#/testnet-faucet

**Comment by JoeSulf** [comment]
Thankyou its all good now.

**Comment by BimsaraFernando** [comment]
Hi @JoeSulf ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
