### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by lucaelle01** [EvernodeXRPL/evernode-host#125]
Hi, if anyone can help... I am trying to install the beta but when I get to the domain name part i get an error message saying that my domain in unreachable or invalid.  Help please!

**Comment by JohnCTOS** [comment]
Have the same issue, 
I can ping the IP & hostname, 
Set the ingress ports as per pic
But domain verification fails.

Any ideas?

![ingress](https://github.com/EvernodeXRPL/evernode-host/assets/104563787/371dde4c-86fa-44d2-a7e3-b21dcef553a0)
![unreachable](https://github.com/EvernodeXRPL/evernode-host/assets/104563787/5d904f64-50f5-4bf8-a347-4a26cc3b563d)
![ping](https://github.com/EvernodeXRPL/evernode-host/assets/104563787/434c0931-2b91-4fc1-82a5-89d7f5ea31aa)

**Comment by BimsaraFernando** [comment]
Hi @lucaelle01 ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
