### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by x4evernode** [EvernodeXRPL/evernode-host#126]
I start the install using: 

curl -fsSL https://stevernode.blob.core.windows.net/evernode-beta-v3/setup.sh | sudo bash -s install

here's the end of the log: 

Checking the account condition...
To set up your host account, ensure a deposit of 18.8000000000000003 XAH to cover the regular transaction fees for the first three months.

Waiting for the process to complete...
Thank you. 9999.999948 XAH balance is there in your host account.

Preparing account with EVR trust-line...

Waiting for the process to complete...
Account preparation is successfull.

In order to register in Evernode you need to have 5120 EVR balance in your host account. Please deposit the required registration fee in EVRs.
You can scan the provided QR code in your wallet app to send funds:

Waiting for the process to complete...
Thank you. 6000 EVR balance is there in your host account.

Account setup is complete.

Do you want to subscribe for auto-updates?
NOTE: The auto-update service is offered subject to the terms set out in the Evernode Software Licence. [y/N]y

Auto updater will be enabled.

Setup will now begin the installation. Continue? [Y/n]Y

Starting installation...
Installing other prerequisites...
There was an error during installation. Please provide the file /tmp/evernode-beta/installer-1703615300.log to Evernode team. Thank you.
root@server:~# cat /tmp/evernode-beta/installer-1703615300.log
main: line 1139: ./prereq.sh: Permission denied

**Comment by x4evernode** [comment]
Can anyone please help with getting over this error?

**Comment by kithminisg** [comment]
@x4evernode , Have you tried the installation curl command under a non-root user login?

**Comment by x4evernode** [comment]
Hi @kithminisg, I have tried installing under a non root user and got the same error :(
Please help

**Comment by kithminisg** [comment]
@x4evernode , Could you please check whether your machine has a temporary directory  under the`/tmp`  (like `/tmp/tmp-XXXX`) path? If so it should contain the `prereq.sh` file. If you find such, please send the permission details of that one as a screenshot.

**Comment by x4evernode** [comment]
Looks like the installer /tmp/tmp.xxxxx directory is being created with root permissions when I'm using a non-root user:

xadmin@server:~$ sudo ls -la /tmp/
total 4
drwxrwxrwt  5 root   root    100 Jan  4 07:25 .
drwxr-xr-x 18 root   root   4096 Dec 23 12:52 ..
drwxr-xr-x  2 root   root     60 Jan  4 07:25 evernode-beta
drwxrwxr-x  3 xadmin xadmin   80 Jan  4 07:19 evernode-setup-helpers
drwx------  4 root   root    360 Jan  4 07:25 tmp.EVaqVwajGn
xadmin@server:~$ sudo ls -la /tmp/tmp.EVaqVwajGn/
total 2676
drwx------ 4 root        root            360 Jan  4 07:25 .
drwxrwxrwt 5 root        root            100 Jan  4 07:25 ..
-rw-rw-r-- 1 sashimbxrpl sashimbxrpl     876 Dec 20 10:36 beta-licence.txt
drwxr-xr-x 6 sashimbxrpl sashimbxrpl     120 Dec 20 10:36 contract_template
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    1143 Dec 20 10:36 docker-install.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    2189 Dec 20 10:36 docker-registry-install.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    1062 Dec 20 10:36 docker-registry-uninstall.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl  649584 Dec 20 10:36 hpfs
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   72096 Dec 20 10:36 libblake3.so
drwxrwxr-x 5 sashimbxrpl sashimbxrpl     120 Dec 20 10:36 mb-xrpl
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   10432 Dec 20 10:36 prereq.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl 1227640 Dec 20 10:36 sagent
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl  708144 Dec 20 10:36 sashi
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   18501 Dec 20 10:36 sashimono-install.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    8028 Dec 20 10:36 sashimono-uninstall.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    3119 Dec 20 10:36 user-cgcreate.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   11173 Dec 20 10:36 user-install.sh
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    3790 Dec 20 10:36 user-uninstall.sh

and when using the root user to run the installer:

Starting installation...
Installing other prerequisites...
There was an error during installation. Please provide the file /tmp/evernode-beta/installer-1704353709.log to Evernode team. Thank you.
root@server:~# ll /tmp/
total 4
drwxrwxrwt  5 root root  100 Jan  4 07:35 ./
drwxr-xr-x 18 root root 4096 Dec 23 12:52 ../
drwxr-xr-x  2 root root   60 Jan  4 07:35 evernode-beta/
drwxr-xr-x  3 root root   80 Jan  4 07:34 evernode-setup-helpers/
drwx------  4 root root  360 Jan  4 07:35 tmp.Tr500vmXYQ/
root@server:~# ll /tmp/tmp.Tr500vmXYQ/
total 2676
drwx------ 4 root        root            360 Jan  4 07:35 ./
drwxrwxrwt 5 root        root            100 Jan  4 07:35 ../
-rw-rw-r-- 1 sashimbxrpl sashimbxrpl     876 Dec 20 10:36 beta-licence.txt
drwxr-xr-x 6 sashimbxrpl sashimbxrpl     120 Dec 20 10:36 contract_template/
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    1143 Dec 20 10:36 docker-install.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    2189 Dec 20 10:36 docker-registry-install.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    1062 Dec 20 10:36 docker-registry-uninstall.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl  649584 Dec 20 10:36 hpfs*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   72096 Dec 20 10:36 libblake3.so*
drwxrwxr-x 5 sashimbxrpl sashimbxrpl     120 Dec 20 10:36 mb-xrpl/
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   10432 Dec 20 10:36 prereq.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl 1227640 Dec 20 10:36 sagent*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl  708144 Dec 20 10:36 sashi*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   18501 Dec 20 10:36 sashimono-install.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    8028 Dec 20 10:36 sashimono-uninstall.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    3119 Dec 20 10:36 user-cgcreate.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl   11173 Dec 20 10:36 user-install.sh*
-rwxrwxr-x 1 sashimbxrpl sashimbxrpl    3790 Dec 20 10:36 user-uninstall.sh*

**Comment by BimsaraFernando** [comment]
Hi @x4evernode ,
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
