### ISSUE TITLE
There was an error during installation. Please provide the file..

### ISSUE THREAD

**Issue by candidplayer** [EvernodeXRPL/evernode-host#127]
Please provide the file /tmp/evernode-beta/installer-1703687509.log to Evernode team. Thank you.
ubuntu@vps-c9d6230c:~$ cat /tmp/evernode-beta/installer-1703687509.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 https://deb.nodesource.com/node_16.x nodistro InRelease
Hit:2 http://nova.clouds.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:4 http://nova.clouds.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:5 http://nova.clouds.archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 114 kB in 1s (139 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Skipping adding existing rule
Skipping adding existing rule (v6)
Running certbot certonly
Requesting a certificate for vps-c9d6230c.vps.ovh.net
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
Error creating new order :: too many certificates already issued for "ovh.net". Retry after 2023-12-27T15:00:00Z: see https://letsencrypt.org/docs/rate-limits/
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for mor                                                             e details.
Error when setting up letsencrypt SSL certificate.
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
rm: cannot remove '/usr/bin/sashi': No such file or directory
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Attempting Evernode host deregistration...
node:internal/modules/cjs/loader:1031
  throw err;
  ^

Error: Cannot find module '/usr/bin/sashimono/mb-xrpl'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
can anyone help me with this please?

**Comment by ravinsp** [comment]
`Error creating new order :: too many certificates already issued for "ovh.net". Retry after 2023-12-27T15:00:00Z: see https://letsencrypt.org/docs/rate-limits/`
It seems letsecnrypt has issued many certificates to your domain `ovh.net` recently. They impose a max limit of 50 certificates per week for a specific domain. You'll have to try again after this period passes.

**Comment by candidplayer** [comment]
i tried again and got the same error
