### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by kdpnetstake** [EvernodeXRPL/evernode-host#128]
Hi,

This is the contents of the log file. I have attempted to load several times and this is a consistent error message.

Some sort of problem with npm and sqlite 3

Hope you can help

Thanks 

_---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 https://deb.nodesource.com/node_16.x nodistro InRelease
Hit:2 https://mirror.hetzner.com/ubuntu/packages focal InRelease
Hit:3 https://mirror.hetzner.com/ubuntu/packages focal-updates InRelease
Hit:4 https://mirror.hetzner.com/ubuntu/packages focal-backports InRelease
Hit:5 https://mirror.hetzner.com/ubuntu/security focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
jq is already the newest version (1.6-1ubuntu0.20.04.1).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Skipping adding existing rule
Skipping adding existing rule (v6)
Running certbot certonly
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-evernode.kdpnetstake.com.sh
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host registration on Evernode...
STAGE Configuring host Xahau account
Using registry: rQUhXd7sopuga3taru3jfvc1BgVbscrb1X
node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/bin/sashimono/mb-xrpl/lib/binding/napi-v3-linux-x64/node_sqlite3.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.1449 (/usr/bin/sashimono/mb-xrpl/index.js:1:1622)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.4400 (/usr/bin/sashimono/mb-xrpl/index.js:57:3848)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.2173 (/usr/bin/sashimono/mb-xrpl/index.js:57:3909) {
  code: 'ERR_DLOPEN_FAILED'
}
XRPLACC_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Attempting Evernode host deregistration...
node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/bin/sashimono/mb-xrpl/lib/binding/napi-v3-linux-x64/node_sqlite3.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.1449 (/usr/bin/sashimono/mb-xrpl/index.js:1:1622)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.4400 (/usr/bin/sashimono/mb-xrpl/index.js:57:3848)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.2173 (/usr/bin/sashimono/mb-xrpl/index.js:57:3909) {
  code: 'ERR_DLOPEN_FAILED'
}
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation._

**Comment by kithminisg** [comment]
@kdpnetstake, Could you please specify the installed `NodeJS` and `npm`  versions of your machine?

**Comment by kdpnetstake** [comment]
Hello Kithmini,

Thanks for your email.  I have checked the VM for the versions:

NodeJS is v16.20.2
NPM is 8.19.4

I can easily update and test if you think this is the reason for the error...

Many thanks,

Karen



________________________________

**Comment by kithminisg** [comment]
@kdpnetstake , In the beta network, these versions are ok. Could you please try again after clearing npm cache?
NOTE: Make sure whether the [System Requirements](https://docs.evernode.org/en/latest/hosts/evernode-host.html#system-requirements) are satisfied.

**Comment by kdpnetstake** [comment]
Thank you..I am using the wrong cpu, Arm64. I will rebuild and try again...

**Comment by kdpnetstake** [comment]
The installation has loaded fully and is now registered as a host.  Thanks for your help @kithminisg
