### ISSUE TITLE
Error in installation - log file attached

### ISSUE THREAD

**Issue by JohnCTOS** [EvernodeXRPL/evernode-host#129]
[installer-1703846492.log](https://github.com/EvernodeXRPL/evernode-host/files/13792733/installer-1703846492.log)

---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
Hit:2 https://deb.nodesource.com/node_16.x nodistro InRelease
Hit:3 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal InRelease
Get:4 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-updates InRelease [114 kB]
Hit:5 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-backports InRelease
Fetched 114 kB in 2s (54.7 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
openssl set to manually installed.
jq is already the newest version (1.6-1ubuntu0.20.04.1).
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200
Suggested packages:
  libnet-ldap-perl default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200 quota
  uidmap
0 upgraded, 8 newly installed, 1 to remove and 15 not upgraded.
Need to get 536 kB of archives.
After this operation, 2562 kB of additional disk space will be used.
Get:1 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal/universe arm64 libfuse3-3 arm64 3.9.0-2 [68.5 kB]
Get:2 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal/universe arm64 fuse3 arm64 3.9.0-2 [23.2 kB]
Get:3 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal/universe arm64 libcgroup1 arm64 0.41-10 [40.9 kB]
Get:4 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal/universe arm64 cgroup-tools arm64 0.41-10 [65.8 kB]
Get:5 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libnl-3-200 arm64 3.4.0-1ubuntu0.1 [51.2 kB]
Get:6 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 libnl-genl-3-200 arm64 3.4.0-1ubuntu0.1 [10.9 kB]
Get:7 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal/main arm64 quota arm64 4.05-1 [250 kB]
Get:8 http://af-johannesburg-1-ad-1.clouds.ports.ubuntu.com/ubuntu-ports focal-updates/universe arm64 uidmap arm64 1:4.8.1-1ubuntu5.20.04.4 [25.3 kB]
Preconfiguring packages ...
Fetched 536 kB in 2s (331 kB/s)
Selecting previously unselected package libfuse3-3:arm64.
(Reading database ... 111671 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_arm64.deb ...
Unpacking libfuse3-3:arm64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 111679 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 111669 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_arm64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package libcgroup1:arm64.
Preparing to unpack .../1-libcgroup1_0.41-10_arm64.deb ...
Unpacking libcgroup1:arm64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../2-cgroup-tools_0.41-10_arm64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libnl-3-200:arm64.
Preparing to unpack .../3-libnl-3-200_3.4.0-1ubuntu0.1_arm64.deb ...
Unpacking libnl-3-200:arm64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libnl-genl-3-200:arm64.
Preparing to unpack .../4-libnl-genl-3-200_3.4.0-1ubuntu0.1_arm64.deb ...
Unpacking libnl-genl-3-200:arm64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../5-quota_4.05-1_arm64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../6-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_arm64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:arm64 (3.9.0-2) ...
Setting up libnl-3-200:arm64 (3.4.0-1ubuntu0.1) ...
Setting up libcgroup1:arm64 (0.41-10) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up libnl-genl-3-200:arm64 (3.4.0-1ubuntu0.1) ...
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for systemd (245.4-4ubuntu3.22) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.15.0-1049-oracle
Unsupported platform on EFI system, doing nothing.
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
/dev/sda1 [/]: group quotas turned on
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for evernode-rsa.co.za

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/evernode-rsa.co.za/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/evernode-rsa.co.za/privkey.pem
This certificate expires on 2024-03-28.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-evernode-rsa.co.za.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host registration on Evernode...
STAGE Configuring host Xahau account
Using registry: rQUhXd7sopuga3taru3jfvc1BgVbscrb1X
node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/bin/sashimono/mb-xrpl/lib/binding/napi-v3-linux-x64/node_sqlite3.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.1449 (/usr/bin/sashimono/mb-xrpl/index.js:1:1622)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.4400 (/usr/bin/sashimono/mb-xrpl/index.js:57:3848)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.2173 (/usr/bin/sashimono/mb-xrpl/index.js:57:3909) {
  code: 'ERR_DLOPEN_FAILED'
}
XRPLACC_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Attempting Evernode host deregistration...
node:internal/modules/cjs/loader:1282
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/bin/sashimono/mb-xrpl/lib/binding/napi-v3-linux-x64/node_sqlite3.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1282:18)
    at Module.load (node:internal/modules/cjs/loader:1076:32)
    at Function.Module._load (node:internal/modules/cjs/loader:911:12)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.1449 (/usr/bin/sashimono/mb-xrpl/index.js:1:1622)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.4400 (/usr/bin/sashimono/mb-xrpl/index.js:57:3848)
    at __nccwpck_require__ (/usr/bin/sashimono/mb-xrpl/index.js:57:468595)
    at Object.2173 (/usr/bin/sashimono/mb-xrpl/index.js:57:3909) {
  code: 'ERR_DLOPEN_FAILED'
}
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
ubuntu@evershostv4:/tmp/evernode-beta$

**Comment by kithminisg** [comment]
@JohnCTOS, Could you please specify the installed `NodeJS` and `npm`  versions of your machine?

**Comment by kithminisg** [comment]
@JohnCTOS, Also please check whether your machine satisfies the [System Requirements](https://docs.evernode.org/en/latest/hosts/evernode-host.html#system-requirements).

**Comment by JohnCTOS** [comment]
Thanks I will check, i am travelling will confirm next week.

**Comment by JohnCTOS** [comment]
Hi  Kithmini Gunawardhana

Please see versions below

[image: image.png]

Regards

John

**Comment by JohnCTOS** [comment]
![unnamed](https://github.com/EvernodeXRPL/evernode-host/assets/104563787/57cb5f78-70f8-4a8f-a8a5-60cdecf98245)

**Comment by kithminisg** [comment]
@JohnCTOS , Have you checked the [System Requirements](https://docs.evernode.org/en/latest/hosts/evernode-host.html#system-requirements)? Especially the CPU.

**Comment by JohnCTOS** [comment]
Thanks see the issue could be its an ARM CPU, Im using an oracle cloud instance, will try spin up another with a CPU other than ARM?

![unnamed](https://github.com/EvernodeXRPL/evernode-host/assets/104563787/3be248fe-4121-44eb-98c6-4cc7c050809b)

**Comment by JohnCTOS** [comment]
![Untitled](https://github.com/EvernodeXRPL/evernode-host/assets/104563787/f7570609-1e29-403c-9ae7-9bf6d297fe41)

**Comment by BimsaraFernando** [comment]
Hi @JohnCTOS, 
Thank you for your contribution. This issue was raised prior to the live release and has not had recent activity. We are closing it now. If this problem persists or if you have further questions, please open a new issue.
