### ISSUE TITLE
Error during registration

### ISSUE THREAD

**Issue by an9218** [EvernodeXRPL/evernode-host#133]
I got error during registration host and receive back 250 EVR only instead of 500
Transaction ID 500 sent: 4ADACAE8A83F904437F2207876CF99E84EA58EC3BEB29A63B320D6E56C8AAC0C
Transaction ID 250 receive: 
45AEAB6011C4A40C6879AA2A995024F6EDAFB9CD7E0AEB92A5D7A414D04B809A

**Comment by VLEFF** [comment]
Same thing here
Lost 500 EVER so far (250 x2)

The error is trivial : cannot create directory ‘/home/sashimbxrpl/.config’: Permission denied
But losing 250 EVR each failed attempt is not

**Comment by chalith** [comment]
We are investigating on the issue. Will push a fix and refund of lost EVRs soon

**Comment by mezmac** [comment]
Same here. Just lost 500 EVR total on two failed attempts. Does anyone want the log?

**Comment by jellicoe** [comment]
happened to me also - running the install as root (not sudo) - get 

"mkdir: cannot create directory ‘/home/sashimbxrpl/.config’: Permission denied"

note: setup in install script calls curl $setup url with "sudo bash -s"

so if running with root it fails - then does the deregistration process and only refunds 250 EVR of the 500 sent at start of registration process - as per the design

- maybe the 500 EVR should only be sent right at the end to enable the host to run - or registry hook has a failed install function

**Comment by chalith** [comment]
@an9218 @VLEFF @mezmac @jellicoe thank you for the support. Hope your issues got resolved. Shall I close the issue?

**Comment by an9218** [comment]
@chalith

**Comment by an9218** [comment]
yes, issue is resolved. Thank
