### ISSUE TITLE
There was an error during installation.

### ISSUE THREAD

**Issue by XJohnK** [EvernodeXRPL/evernode-host#134]
There was an error during installation. Please provide the file /tmp/evernode/installer-1705306158.log to Evernode team. Thank you.

I got this error during installation.

[installer-1705306158.log](https://github.com/EvernodeXRPL/evernode-host/files/13936525/installer-1705306158.log)

please let me know how to fix it asap

Thank you.

**Comment by XJohnK** [comment]
same error with another host
[installer-1705306168.log](https://github.com/EvernodeXRPL/evernode-host/files/13936700/installer-1705306168.log)

**Comment by GabrielFilip** [comment]
Got the same error and lost 250 Evers. Will wait for any feedback.

`STAGE Creating lease offers for instance slots...
Transaction result: tesSUCCESS
Transaction result: tesSUCCESS
STAGE -p Created lease offer 1 of 3.
Transaction result: tesSUCCESS
Transaction result: tesSUCCESS
STAGE -p Created lease offer 2 of 3.
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.`

**Comment by VLEFF** [comment]
issue related : https://github.com/EvernodeXRPL/evernode-host/issues/133

**Comment by chalith** [comment]
We are investigating on the issue. Will push a fix and refund of lost EVRs soon

**Comment by GabrielFilip** [comment]
Thank you @chalith. Take your time and let me know if you need anything from us. I am happy to provide logs and do tests on my host.

**Comment by tissson** [comment]
Same Same.

[Installer 1705314224.txt](https://github.com/EvernodeXRPL/evernode-host/files/13937949/Installer.1705314224.txt)

**Comment by XJohnK** [comment]
> We are investigating on the issue. Will push a fix and refund of lost EVRs soon

Are you guys investigating now?

**Comment by chalith** [comment]
Thank you! @XJohnK yes we are working on it. We will come up with a fix and refunds for your lost EVRs soon.

**Comment by GabrielFilip** [comment]
Could it be that the XAH was not enough for all transactions? I had 0.76 XAH for 3 instances. I understood that it needs 0.2 per instance, but we are approaching the limit.
I added now more XAH.

**Comment by XJohnK** [comment]
For me, In each instance, there are 30 XAH

**Comment by mal-practice** [comment]
Related issue - #140 

Thanks for your hard work on this @chalith (and others!)

**Comment by ndurbin510** [comment]
Related issue: #142 

Thank you for all your work on resolving this!

**Comment by GabrielFilip** [comment]
Is there a possibility to get a discord invitation? Unfortunately it is not possible to join.
I retry the installation and it worked fine for me now, but unfortunately my host is inactive.

**Comment by tissson** [comment]
This is the official invitation;

https://discord.com/invite/6QyztTrWHq

**Comment by chalith** [comment]
@XJohnK @GabrielFilip @VLEFF @tissson thanks for the support. Hope your issues got resolved. Shall I close the issue?

**Comment by ay432** [comment]
Same issue: REG_FAILURE

Please tell me what to do next. There was not enough XAH, I deposited 27 XAH and installation failed.
Also, I have second installation and it succeeded with 37 XAH.
I added 30 more XAH to the failed host. Restarting the installation getting to the dead end when it asks for host address, and if I use my host address, it responds that host already registered, this is it.
My failed node is on the mainnet, Inactive, Heartbeat is 0, and only one slot displayed.
What I do next:
a. Deregister? How? What is the process? When 250 EVR's go back to account and what account it goes back to? What with XAH tokens I deposited?
b. Can I keep that node and registration, is there any way to recover it? Or it will happened automatically?

Please help, and explain what next with failed host?

root@xrplsmartnode:~# cat /tmp/evernode/installer-1705797271.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
openssl set to manually installed.
The following packages were automatically installed and are no longer required:
  eatmydata libeatmydata1 libfwupdplugin1 libpciaccess0 libxmlb1
  python3-importlib-metadata python3-jinja2 python3-json-pointer
  python3-jsonpatch python3-jsonschema python3-markupsafe
  python3-more-itertools python3-pyrsistent python3-xkit python3-zipp
  ubuntu-drivers-common
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libtirpc-common libtirpc3 quota
  uidmap
0 upgraded, 8 newly installed, 1 to remove and 0 not upgraded.
Need to get 574 kB of archives.
After this operation, 2693 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:6 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 574 kB in 0s (2434 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 118215 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 118223 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 118213 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../1-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../2-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../3-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../4-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../5-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../6-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for systemd (245.4-4ubuntu3.22) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-169-generic
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
/dev/vda2 [/]: group quotas turned on
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for xrplsmartnode.com

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/xrplsmartnode.com/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/xrplsmartnode.com/privkey.pem
This certificate expires on 2024-04-19.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-xrplsmartnode.com.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: US 800000 1614880 1649040 43210880 3                 Intel(R)_Xeon(R)_CPU_E5-2660_v3_2.60GHz 2 2599 xrplsmartnode@gmail.com _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer AEB50E5F1626C003C96C757C551A090235A8C86EBA39FBF21A806E177346A67B
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'xrplsmartnode.com'
Deleted all files relating to certificate xrplsmartnode.com.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/xrplsmartnode.com/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by chalith** [comment]
@ay432 you should transfer your registration before installing again. Try this https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration

**Comment by AndriiVlasiuk1991** [comment]
Good day @chalith 
[installer-1708023256.log](https://github.com/EvernodeXRPL/evernode-host/files/14301231/installer-1708023256.log)
I have a similar error described in this topic. I already tried to make a transfer, but I get :
STAGE -p Created lease offer 1 of 6.
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
Help please.

**Comment by chalith** [comment]
Did you resolve this issue? We have released a new installer version did you try with it? https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300

**Comment by BimsaraFernando** [comment]
Hi @XJohnK @AndriiVlasiuk1991 @ay432 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
