### ISSUE TITLE
Error with install - No warning XAH Balance is too low and can skip the funding step

### ISSUE THREAD

**Issue by TheMainlander** [EvernodeXRPL/evernode-host#135]
Hi EVR team,adding this minor bug from my install today on EVR Prod.

1. Installed Evernode
2. Funded with EVR
3. only .7 XAH in the wallet
4. Skip the funding step
5. Select "Do you want to subscribe for auto-updates?
NOTE: The auto-update service is offered subject to the terms set out in the Evernode Software Licence. [y/N] y" 
6. Evernode continues without a Balance check of XAH
7. Adds 2/3 hosts
8. Fails "REG_FAILURE" 

Log File

`Setting up letsencrypt certbot
Installing docker packages
Configuring host Xahau account
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Created lease offer 2 of 3.
There was an error during installation. Please provide the file /tmp/evernode/installer-1705316830.log to Evernode team. Thank you.
root@Evernode-Public-Beta-The-Mainlander-02:~# cat /tmp/evernode/installer-1705316830.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://mirrors.digitalocean.com/ubuntu focal InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Get:5 https://repos.insights.digitalocean.com/apt/do-agent main InRelease [5518 B]
Get:6 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease [5518 B]
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
Err:5 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 77B79B3FFAF7EF65
Err:6 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 35696F43FC7DB4C2
Reading package lists...
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repos.insights.digitalocean.com/apt/do-agent main InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 77B79B3FFAF7EF65
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 35696F43FC7DB4C2
W: Failed to fetch https://repos.insights.digitalocean.com/apt/do-agent/dists/main/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 77B79B3FFAF7EF65
W: Failed to fetch https://repos-droplet.digitalocean.com/apt/droplet-agent/dists/main/InRelease  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 35696F43FC7DB4C2
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Skipping adding existing rule
Skipping adding existing rule (v6)
Running certbot certonly
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-evr2.kumoever.app.sh
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host registration on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: SG 800000 1615040 10066320 25788400 3                 DO-Regular 1 2294 Kumo@kumoever.app _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer D8EF408FFFB95375488C3E47DF7462DFF2FA6D18ED73AED1A74385638788AAF0
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Transaction result: tesSUCCESS
Transaction result: tesSUCCESS
STAGE -p Created lease offer 1 of 3.
Transaction result: tesSUCCESS
Transaction result: tesSUCCESS
STAGE -p Created lease offer 2 of 3.
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Attempting Evernode host deregistration...
Deregistering host...
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (1EC262715F363277457ECECE379BF870DD7E12AB0E303E4B09B0712982475E24) of rE9kkUTado983bLcUYKriyVHsjDoULPjDf account
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (AD918C1E0FB767A3EC6CAC2ECC581286EBBB44001C304AA91E666E380B23DF91) of rE9kkUTado983bLcUYKriyVHsjDoULPjDf account
Transaction result: tesSUCCESS
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
root@Evernode-Public-Beta-The-Mainlander-02:~# `

**Comment by chalith** [comment]
@TheMainlander Thanks for the catch. We'll fix this

**Comment by chalith** [comment]
Thank you again. We've fixed this with the new release. Closing the issue.

**Comment by TheMainlander** [comment]
No, thank you @chalith for all your hard work and Evernode! Great job!
