### ISSUE TITLE
Error in instalation with my own cert

### ISSUE THREAD

**Issue by Alex132M** [EvernodeXRPL/evernode-host#137]
My provider doesn't open 80 port. So I generated certificates manually with command:
  openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 3650 -nodes -subj '/CN=smartnode.se'
  and uploaded certificates on website.
Commented out validate_inet_addr_domain function in installation script and enter path for certificate files manually.
But the installation failed and 250 EVR has gone. See attached log. 
I know that I am not supposed to do it but maybe you you can kindly help..
[installer-1705338351.log](https://github.com/EvernodeXRPL/evernode-host/files/13941806/installer-1705338351.log)

**Comment by chalith** [comment]
It looks like there was an error during activating a user service while installation. Hope you received the refunds? Can you try again?
About setting certificates. You can choose to configure your certificates instead of letsencrypt in your installation process. You don't have to alter the installation.

**Comment by Alex132M** [comment]
Many Thanks!! I got the refund. I asked my host provider to configure the ports and got the question from him:
"What user agent and ip are evernode using ?"
Could you please help to answer it?
And one more question: How to choose my own certificates during the installation? I did before for test network but I can't do it for main network because there is a check validate_inet_addr_domain  and it is always failed...

**Comment by Alex132M** [comment]
Tried new installation one more time but got the same error..
Installing Evernode Xahau message board...
Updated mb user .bashrc.
NO_MB_USER_SYSTEMD
[installer-1705338351_new_attempt.log](https://github.com/EvernodeXRPL/evernode-host/files/13976681/installer-1705338351_new_attempt.log)

**Comment by Alex132M** [comment]
Fixed the error with: sudo useradd sashimbxrpl

**Comment by chalith** [comment]
@Alex132M is your host up and running? If all is resolved can you close the issue?

**Comment by Alex132M** [comment]
Yes. Thanks! It can be closed.
