### ISSUE TITLE
Error during installation - failed after lease offer 2 of 6 created

### ISSUE THREAD

**Issue by mal-practice** [EvernodeXRPL/evernode-host#140]
Log file below - any assitance will be gratefully appreciated.

Thanks,

J.

[installer-1705304781.log](https://github.com/EvernodeXRPL/evernode-host/files/13942844/installer-1705304781.log)

**Comment by mal-practice** [comment]
After discussion with someone at the evernode end, I tried another install and it errored out at the same point. Another 250EVR gone.

Log below - any news on whether this is at my end or an installer issue yet?

[installer-1705391469.log](https://github.com/EvernodeXRPL/evernode-host/files/13946940/installer-1705391469.log)

Thanks,

J.

**Comment by mal-practice** [comment]
Sorry, third attempt after another conversation (and deleting the .config folder - which I missed) - same error.

[installer-1705393627.log](https://github.com/EvernodeXRPL/evernode-host/files/13947404/installer-1705393627.log)

Another 250EVR

**Comment by chalith** [comment]
We've checked your account history. It seems you don't have enough XAHs in your account to mint lease tokens.
We've found a bug in our required balance calculation and we will be fixing that in our next version release.
Meanwhile you can try funding your account with some additional XAHs.
Furthermore, we will refund your lost EVRs in our next refund process.

**Comment by mal-practice** [comment]
Thanks @chalith
