### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by enorym** [EvernodeXRPL/evernode-host#141]
[installer-1705373810.log](https://github.com/EvernodeXRPL/evernode-host/files/13944930/installer-1705373810.log)
Log file attached please assist.

**Comment by chalith** [comment]
When you were asked for a domain in the installation, Did you specify a domain address?

**Comment by enorym** [comment]
> When you were asked for a domain in the installation, Did you specify a domain address?

You are correct I was just using an ip.  I have since fixed this thank you!

**Comment by chalith** [comment]
Cool.. No worries! Closing the issue :)
