### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by ndurbin510** [EvernodeXRPL/evernode-host#142]
250 EVR burned.
No warning about any XAH amounts required for the suggested setup.
I would think a failed initial install would return your balance not tax hosts who don't startup.

`STAGE -p Created lease offer 5 of 12.
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE

`

[installer-1705398287.log](https://github.com/EvernodeXRPL/evernode-host/files/13948272/installer-1705398287.log)

**Comment by chalith** [comment]
We are addressing this issue and in the refund process for the registration failures. You'll receive the refunds soon

**Comment by ndurbin510** [comment]
Thank you.  I have received the refund.  When do you expect a patch for this issue?

**Comment by ndurbin510** [comment]
Issues seems to be related to not enough XAH.
Would have been helpful to get a prompt to require x number of XAH  when using wallets that already exist and validate that in addition to EVR.

Closing issue.
