### ISSUE TITLE
Issue during install

### ISSUE THREAD

**Issue by tissson** [EvernodeXRPL/evernode-host#143]
My 5th host suddently caused some issues setting it up:

[Installer 1705402841.txt](https://github.com/EvernodeXRPL/evernode-host/files/13949663/Installer.1705402841.txt)

There was an error during installation. Please provide the file /tmp/evernode/installer-1705402841.log to Evernode team. Thank you.
root@linux:~# ^C
root@linux:~# more /tmp/evernode/installer-1705402841.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://archive.canonical.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Ign:5 https://repo.virtuozzo.com/ctpreset/deb  InRelease
Hit:6 https://repo.virtuozzo.com/ctpreset/deb  Release
Ign:7 https://repo.virtuozzo.com/ctpreset/deb  Release.gpg
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Ign:8 https://repo.virtuozzo.com/ctpreset/deb  Translation-en
Hit:9 http://security.ubuntu.com/ubuntu focal-security InRelease
Fetched 114 kB in 6s (18.3 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
The following additional packages will be installed:
  libcgroup1 libfuse3-3
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 uidmap
0 upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 234 kB of archives.
After this operation, 1022 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Fetched 234 kB in 0s (488 kB/s)
Selecting previously unselected package libcgroup1:amd64.
(Reading database ...

Preparing to unpack .../libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libfuse3-3:amd64.
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
Selecting previously unselected package fuse3.
Preparing to unpack .../fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
STAGE Installing ufw
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  ufw
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 148 kB of archives.
After this operation, 849 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 ufw all 0.36-6ubuntu1.1 [148 kB]
Preconfiguring packages ...
Fetched 148 kB in 0s (381 kB/s)
Selecting previously unselected package ufw.
(Reading database ...

Preparing to unpack .../ufw_0.36-6ubuntu1.1_all.deb ...
Unpacking ufw (0.36-6ubuntu1.1) ...
Setting up ufw (0.36-6ubuntu1.1) ...

Creating config file /etc/ufw/before.rules with new version

Creating config file /etc/ufw/before6.rules with new version

Creating config file /etc/ufw/after.rules with new version

Creating config file /etc/ufw/after6.rules with new version
Created symlink /etc/systemd/system/multi-user.target.wants/ufw.service → /lib/systemd/system/ufw.service.
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for rsyslog (8.2001.0-1ubuntu1.3) ...
Processing triggers for systemd (245.4-4ubuntu3.22) ...
STAGE Installing snapd
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  dbus-user-session libfuse2 liblzo2-2 libpam-systemd squashfs-tools
Suggested packages:
  zenity | kdialog
The following NEW packages will be installed:
  dbus-user-session libfuse2 liblzo2-2 libpam-systemd snapd squashfs-tools
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
Need to get 38.3 MB of archives.
After this operation, 173 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 libpam-systemd amd64 245.4-4ubuntu3.22 [186 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal/main amd64 libfuse2 amd64 2.9.9-3 [82.0 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 dbus-user-session amd64 1.12.16-2ubuntu2.3 [9424 B]
Get:4 http://archive.ubuntu.com/ubuntu focal/main amd64 liblzo2-2 amd64 2.10-2 [50.8 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 squashfs-tools amd64 1:4.4-1ubuntu0.3 [117 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 snapd amd64 2.58+20.04.1 [37.9 MB]
Fetched 38.3 MB in 2s (20.5 MB/s)
Selecting previously unselected package libpam-systemd:amd64.
(Reading database ...

Preparing to unpack .../0-libpam-systemd_245.4-4ubuntu3.22_amd64.deb ...
Unpacking libpam-systemd:amd64 (245.4-4ubuntu3.22) ...
Selecting previously unselected package libfuse2:amd64.
Preparing to unpack .../1-libfuse2_2.9.9-3_amd64.deb ...
Unpacking libfuse2:amd64 (2.9.9-3) ...
Selecting previously unselected package dbus-user-session.
Preparing to unpack .../2-dbus-user-session_1.12.16-2ubuntu2.3_amd64.deb ...
Unpacking dbus-user-session (1.12.16-2ubuntu2.3) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../3-liblzo2-2_2.10-2_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.10-2) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../4-squashfs-tools_1%3a4.4-1ubuntu0.3_amd64.deb ...
Unpacking squashfs-tools (1:4.4-1ubuntu0.3) ...
Selecting previously unselected package snapd.
Preparing to unpack .../5-snapd_2.58+20.04.1_amd64.deb ...
Unpacking snapd (2.58+20.04.1) ...
Setting up liblzo2-2:amd64 (2.10-2) ...
Setting up libfuse2:amd64 (2.9.9-3) ...
Setting up libpam-systemd:amd64 (245.4-4ubuntu3.22) ...
Setting up squashfs-tools (1:4.4-1ubuntu0.3) ...
Setting up dbus-user-session (1.12.16-2ubuntu2.3) ...
Setting up snapd (2.58+20.04.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.aa-prompt-listener.service → /lib/systemd/system/s
napd.aa-prompt-listener.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.apparmor.service → /lib/systemd/system/snapd.appar
mor.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.autoimport.service → /lib/systemd/system/snapd.aut
oimport.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.core-fixup.service → /lib/systemd/system/snapd.cor
e-fixup.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.recovery-chooser-trigger.service → /lib/systemd/sy
stem/snapd.recovery-chooser-trigger.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.
service.
Created symlink /etc/systemd/system/cloud-final.service.wants/snapd.seeded.service → /lib/systemd/system/snapd.seede
d.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.service → /lib/systemd/system/snapd.service.
Created symlink /etc/systemd/system/timers.target.wants/snapd.snap-repair.timer → /lib/systemd/system/snapd.snap-rep
air.timer.
Created symlink /etc/systemd/system/sockets.target.wants/snapd.socket → /lib/systemd/system/snapd.socket.
Created symlink /etc/systemd/system/final.target.wants/snapd.system-shutdown.service → /lib/systemd/system/snapd.sys
tem-shutdown.service.
snapd.failure.service is a disabled or a static unit, not starting it.
snapd.mounts-pre.target is a disabled or a static unit, not starting it.
snapd.mounts.target is a disabled or a static unit, not starting it.
snapd.snap-repair.service is a disabled or a static unit, not starting it.
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
STAGE Configuring fstab
mount: /: permission denied.
Re mounting error.

**Comment by chalith** [comment]
In it the same after a reboot?

**Comment by tissson** [comment]
> In it the same after a reboot?

Yes, exactly.
![image](https://github.com/EvernodeXRPL/evernode-host/assets/36421358/fdca4f33-446b-4f36-94a6-be9f23823d4c)

**Comment by chalith** [comment]
We are doing some fstab operations to support disk quotas. To do that we do a remount operation on your root. As the error says it looks like server is not allowing that. Let us investigate more.

**Comment by tissson** [comment]
I received this input from the VPS supplier in the same regard;

"Hello Patrik,

I created a test a test VPS with the same OS as you have (Ubuntu 20.04) and on the same physical node. I then typed nano /etc/fstab and appended a valid kernel flag (noatime) to one of the arguments, and then ran mount -o remount /proc, and it completed successfully.

As such, I'd be curious to know the exact process you're following so I can attempt to reproduce this.

Kind Regards,
George"

**Comment by tissson** [comment]
The VPS provider tried destroying the old VPS and creating a new using FUSE, however not working even though.
They think there might be something to do with OpenVZ (compared to e.g. KVM).

Anything new?

**Comment by chalith** [comment]
Can you try running `mount -o remount /` as well

**Comment by tissson** [comment]
root@linux:~# sudo mount -o remount /
mount: /: permission denied.
root@linux:~#

**Comment by tissson** [comment]
Can confirm it's not working in the new patch either. Same issue (fstab)

**Comment by chalith** [comment]
It seems something with the VPS mount permissions or fstab configurations. Not sure. Need to investigate more

**Comment by tissson** [comment]
Hi,

Ok that's weird. After the VPS provider destroyed the VPS, and did below ;

""Hello Patrik,

I created a test a test VPS with the same OS as you have (Ubuntu 20.04) and on the same physical node. I then typed nano /etc/fstab and appended a valid kernel flag (noatime) to one of the arguments, and then ran mount -o remount /proc, and it completed successfully.

As such, I'd be curious to know the exact process you're following so I can attempt to reproduce this.

Kind Regards,
George""


They are very sure that the problem is actually on Evernode (installer) side, since there shouldnt be anything hindering the fstab from VPS side.

**Comment by chalith** [comment]
To be sure. Can you ask them to run `mount -o remount /` as well.

**Comment by tissson** [comment]
Hi,

Ill check, but wasnt that what they already tried?

"I created a test a test VPS with the same OS as you have (Ubuntu 20.04) and on the same physical node. I then typed nano /etc/fstab and appended a valid kernel flag (noatime) to one of the arguments, **and then ran mount -o remount /proc**, and it completed successfully."

**Comment by tissson** [comment]
Ok, seems to be OpenVZ issue, that's non fixable.

**_OpenVZ has a number of limitations and unfortunately, this looks to be a result of one of those limitations, and it does unfortunately appear a full virtualization VPS running something like KVM or Xen will be required, unless the Evernode team can find a workaround for OpenVZ based systems that doesn't involve needing to make file system level changes, i.e. modifying /etc/fstab.

Kind Regards,_**

**Comment by tissson** [comment]
@chalith anything you'd like to test or should we consider this non-workable.
Otherwise I will just ask for refund for this particular VPS, no need to keep it running if there isnt any planned fix either.

**Comment by chalith** [comment]
Ohh ok sorry for the delayed reply, For our contract instance quota limitations, we have to edit the /etc/fstab. There's no way around it. We can send you a refund if we haven't already. If we haven't please send us your host address.

**Comment by BimsaraFernando** [comment]
Hi @tissson ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
