### ISSUE TITLE
Problems during installation 

### ISSUE THREAD

**Issue by Thopfi** [EvernodeXRPL/evernode-host#144]
Good Morning , i need technical help...

I installed the node , send the XAH & EVR Funds and after that , my server rebooted , damn!
Now I´m again in the install mode and now i  should send the funds again...

I tried to reinstall the software but again , the node wants the funds.. 
In the Evernode Dashboard is my node online ?!?! 

I talked with ScottChamberlain via Discord and he told me that my Node should be derigstered and i get my funds back for a new installation...

Thx for help

**Comment by chalith** [comment]
Do you have your account secret inside `/home/sashimbxrpl/.evernode-host/.host-account-secret.key` (Do not share the content). Can you remember the way the installation failed? Did it exit with an error or did the installation hang?

**Comment by Thopfi** [comment]
Yes , the Secretkey is inside the folder.

The installation was aborted in the last step. It looked to me as if the server had a power failure , because after reconnect i got the login greetings from the hoster and the CLI was empty.

**Comment by chalith** [comment]
It looks like the server got stuck and rebooted and then lost the connection.
Your account seems to be registered in Evernode. You can try this and see whether you can transfer the existing registration https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration

**Comment by Thopfi** [comment]
I Can´t transfer. 
This comes up: Host is not registered and when i want to reinstall , i have low funds of EVR.

Specify the Xahau account address: rwy8YvWSJhDAo2RCjvcCAxpyZ7syxxxxx
Checking account rwy8YvWSJhDAo2RCjvcCAxpyZ7syxxxxx...
The account needs minimum balance of 500 EVR. Current balance is 5 EVR.

TX Fee: https://xahauexplorer.com/explorer/79C89FDED6DDB76FC59D6FCBDFC3B040A5833CAAD871CEAA5056ED2FC8DAB5D7

**Comment by chalith** [comment]
It seems your installation hang in an intermediate state. We'll provide you a solution to reinstall soon

**Comment by chalith** [comment]
Further note, Your registration token sell offer is in the Evernode registry. We'll give you a way to accept that offer and own the token soon so you can either re install or transfer without spending any EVRs using the same account

**Comment by Thopfi** [comment]
Ok fine , can u tell me when?

**Comment by chalith** [comment]
@Thopfi do you have EVRs and XAHs so you can fund the account?

If so, you can try funding your account with the amount you are asked to fund when you are trying to install using the same account. It'll tell that you have to have a balance of 500EVRs. But in the registration, you won't be charged any.
If you are charged we'll do a refund.

Or we can provide you with a script to claim your token and then you can transfer registration and reinstall on your machine.

**Comment by Thopfi** [comment]
Sorry , got no more EVR´s  , so i need the script to claim. Will i claim 500 EVR´s?

**Comment by chalith** [comment]
Try this, From any machine extract this zip file. Then go inside `claim-reg-token` directory. And then execute `node index.js <address> <secret>` replace the address and secret with yours. 
[claim-reg-token.zip](https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip)

After that. You'll have to do a transfer: https://docs.evernode.org/en/latest/hosts/maintenance.html

And then install using the same address.

Let us know if there're any issues

**Comment by Thopfi** [comment]
@chalith 
Hi , this shows up when i claimed:

Initiating the process...
mainnet
Claiming the token...
Sell offer found
Transaction result: tesSUCCESS
Token is successfully claimed.

And this  when i want to install & transfer the node:

Checking account rwy8YvWSJhDAo2RCjvcCAxpyZ7sy2Zgnar...
Host is already registered.

In addition:
I had to use this:

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer


Then start the **normal installation** again and confirm with “n” at “fresh install..”, then later add the address and the security key Path.
Normally the Path ist /home/sashimbxrpl/.evernode-host/.host-account-secret.key


and everything works fine!

Problems Solved!

**Comment by chalith** [comment]
Closing the issue since it's resolved!

**Comment by mauricetbm** [comment]
> Try this, From any machine extract this zip file. Then go inside `claim-reg-token` directory. And then execute `node index.js <address> <secret>` replace the address and secret with yours. [claim-reg-token.zip](https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip)
> 
> After that. You'll have to do a transfer: https://docs.evernode.org/en/latest/hosts/maintenance.html
> 
> And then install using the same address.
> 
> Let us know if there're any issues



> Try this, From any machine extract this zip file. Then go inside `claim-reg-token` directory. And then execute `node index.js <address> <secret>` replace the address and secret with yours. [claim-reg-token.zip](https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip)
> 
> After that. You'll have to do a transfer: https://docs.evernode.org/en/latest/hosts/maintenance.html
> 
> And then install using the same address.
> 
> Let us know if there're any issues

Sorry, when you say from any machine, does that mean open it on my laptop for example?
and then go inside 'claim-reg-token' directory? How do I do that?
I'm obviously a novice, but trying to learn fast. thank you

**Comment by KC-evernode** [comment]
> Good Morning , i need technical help...
> 
> I installed the node , send the XAH & EVR Funds and after that , my server rebooted , damn! Now I´m again in the install mode and now i should send the funds again...
> 
> I tried to reinstall the software but again , the node wants the funds.. In the Evernode Dashboard is my node online ?!?!
> 
> I talked with ScottChamberlain via Discord and he told me that my Node should be derigstered and i get my funds back for a new installation...
> 
> Thx for help

Hi, I have the same issue... what do I need to do please...?

**Comment by KC-evernode** [comment]
> Yes , the Secretkey is inside the folder.
> 
> The installation was aborted in the last step. It looked to me as if the server had a power failure , because after reconnect i got the login greetings from the hoster and the CLI was empty.

How do you open the folder? Working via a VPS...
