### ISSUE TITLE
Scott said raise this here - two failed installations ( same hostname) for different reasons

### ISSUE THREAD

**Issue by josepi909** [EvernodeXRPL/evernode-host#145]
Hi, 

I have 2 issues related to the same install/node ..

issue 1:
initial installation failed, and all 500 evrs taken, and these not included in the refund process.  tx's showing in the explorer

wallet generated during install - rpanSWcDUnozUKzGGc1kVjUQ6P9w1gXbC7
funding wallet - rDVBMoZ6QcMS12Ty3aBNwrNPPfvHHdvkde
hostname used during install - EVERNODE12.SPACEVEG.SPACE

issue 2:
I wiped the above server, made a clean unbuntu install and prepared to setup with fresh evrs/xah. A new IP addresses generated by the vps ( vultr). Installed using the SAME hostname as issue1 ( EVERNODE12.SPACEVEG.SPACE ). 

This Install worked ok, generating a new wallet ( rEenFDZfYYXuoXmwfKwbza7z3PX3wENKSM ) but for over 12 hours the the server is showing inactive, and the dashboard shows "outbound ip" with the  IPv6 loopback address 
![Evernode](https://github.com/EvernodeXRPL/evernode-host/assets/121140957/ed2bae99-eb6e-4e7c-afca-695b79b0b2a8)
as the outgoing address ( see attached image). no other servers seem to show this, so i suspect the reused of the hostname/ipv6 subnet has confused thing somewhere.. 

note: i have 14 other nodes all working fine, so funding wallet has a lot of tx's

hope you can help. 
thanks
AB.

**Comment by tissson** [comment]
I think there are a couple of servers (,mine also) showing this as outbound IP - however active.

**Comment by chalith** [comment]
In the 1st issue, It shows as registered but after installation, it didn't poke the hook. In installation did it fail showing any errors? And hope you have the secret for the wallet. So we can refund to the same address in refund process.
And for the 2nd issue, In the installation, it asks for ipv6 support. You can opt in and specify your ipv6 address. Did you specify that? And the server shows as active now. You said it hasn't been active for 12 hours after installation right? Is it before it became active?

**Comment by josepi909** [comment]
HI, 

1st issue, install just hung, no errors, from memory somewhere around the letsincrypt setup, but could be wrong. I saved the keys, so no issues there.

2nd issue, i specified IPv6 correctly i believe, all other nodes working fine and used the same process to obtain it. The dash board is still showing the node as inactive, and it has no accumulated reward amount, despite being up  - probably closer to 24 hours now.


<br class="Apple-interchange-newline">


![Evernode-2](https://github.com/EvernodeXRPL/evernode-host/assets/121140957/2e95464c-99f5-4bc3-a6fd-0121861598bb)

If its easier for you, im happy to kill it and restart fresh , assuming you can add the evrs back in the refund process.. so 500 for the failed instal , and 250 for the loss on issue 2, but happy to assist in troubleshooting if necessary.

thanks
ab

**Comment by josepi909** [comment]
i thought i had allowed for the change, but can only suspect i entered the ipv6 addr of the server i wiped after issue-1, so have now degistered the NFT via the transfer process, and have reinstalled  on the same host using the same keys, as this allows me to confirm the ipv6 address again.  Transfer process went fine, node registered on the network. will wait an hour and check the status..  thanks..

**Comment by josepi909** [comment]
fyi - there was an error during the uninstaller process when transfering . 
![Hyper](https://github.com/EvernodeXRPL/evernode-host/assets/121140957/e501fe4b-5584-4044-b770-32fa9c3bb69e)

**Comment by josepi909** [comment]
Think this issue 2 is just a dashboard issue - checked and last night rewards were received as expected - fyi

**Comment by chalith** [comment]
Okay, so no issue with rEenFDZfYYXuoXmwfKwbza7z3PX3wENKSM other than the outbound ip?
For rpanSWcDUnozUKzGGc1kVjUQ6P9w1gXbC7 it looks like the connection with letsencrypt hung and it couldn't generate the certificate. Did the transfer succeed even though it showed the certificate not found error?

**Comment by chalith** [comment]
Looking at the rpanSWcDUnozUKzGGc1kVjUQ6P9w1gXbC7 account history, l guess transfer hasn't succeed

**Comment by josepi909** [comment]
HI Chalith,
yes its seems the dash board is confused by the switch of addresses/FQDN...

 evernode12.spaceveg.space ( running under rEenFDZfYYXuoXmwfKwbza7z3PX3wENKSM) is working fine , collecting rewards, but the dashboard is showing the old address for this DNS name.(rpanSWcDUnozUKzGGc1kVjUQ6P9w1gXbC7). 

rpanSWcDUnozUKzGGc1kVjUQ6P9w1gXbC7 is the address where 500 EVRs transfer is lost. 

![Evernode](https://github.com/EvernodeXRPL/evernode-host/assets/121140957/16c3ee28-6673-4242-934a-7f7ccfcc82c8)

**Comment by josepi909** [comment]
" Did the transfer succeed even though it showed the certificate not found error? "
sorry - not sure what you mean, though rEenFDZfYYXuoXmwfKwbza7z3PX3wENKSM ( the second instance, was funded with fresh EVRs, not using the NFT from the first install..

**Comment by chalith** [comment]
I'm hoping that now `evernode` command is not working in your rpanSWcDUnozUKzGGc1kVjUQ6P9w1gXbC7 machine. Can you try https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration (Command starting with curl) in your local machine and see whether you can transfer

**Comment by josepi909** [comment]
HI Chalith,

I dont have access to this node, I destroyed it and rebuilt from scratch..i
only have the keys at this point.

regards
joe

**Comment by josepi909** [comment]
HI Chalith, 

Hope you are doing ok.. very busy i guess !
Please advise of next steps i need to take to resolve the missing evrs from the first issue in this ticket.. many thanks.
joe

**Comment by chalith** [comment]
Hi @josepi909. Still you can transfer your registration since you have your keys. You can try https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration (Command starting with curl) even in a fresh machine without installing Evernode

**Comment by josepi909** [comment]
thanks resolved now.
