### ISSUE TITLE
I kept getting this error every time i tried to install the node

### ISSUE THREAD

**Issue by atram766** [EvernodeXRPL/evernode-host#146]
I came across this error and my token was taken from my account. I hope someone can help.

root@vmi1259299:~# cat /tmp/evernode/installer-1705414387.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://asi-fs-y.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-y.contabo.net/ubuntu focal-updates InRelease
Hit:3 http://asi-fs-y.contabo.net/ubuntu focal-backports InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-105 linux-headers-5.4.0-105-generic
  linux-headers-5.4.0-62 linux-headers-5.4.0-62-generic
  linux-image-5.4.0-105-generic linux-image-5.4.0-62-generic
  linux-modules-5.4.0-105-generic linux-modules-5.4.0-62-generic
  linux-modules-extra-5.4.0-105-generic linux-modules-extra-5.4.0-62-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Skipping adding existing rule
Skipping adding existing rule (v6)
Running certbot certonly
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal; no action taken.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-a.xevernode.com.sh
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host registration on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: US 800000 13114320 3355440 300253040 18                 AMD_EPYC_7282_16-Core_Processor 6 2794 andyvt766@gmail.com _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer 76426CB85008D00DA2ED7E6289B7FE99E2DA0B985E7F693EF9291F5FBB496703
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Transaction result: tesSUCCESS
Transaction result: tesSUCCESS
STAGE -p Created lease offer 1 of 18.
Transaction result: tesSUCCESS
Transaction result: tesSUCCESS
STAGE -p Created lease offer 2 of 18.
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Attempting Evernode host deregistration...
Deregistering host...
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (4DED2328D2334B6522D125A90E9E463E3906B85358196CC59323C9B5B96048EE) of rECk7z7s4MnjVmaW5FwJHRFoa1kBUDNpd1 account
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (BA2995D24A52F516B4B311CC59C045C0309BB944BE8894A66A9576651E2D36D2) of rECk7z7s4MnjVmaW5FwJHRFoa1kBUDNpd1 account
Transaction result: tesSUCCESS
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
root@vmi1259299:~#

**Comment by chalith** [comment]
We've checked your account history. It seems you don't have enough XAHs in your account to mint lease tokens.
We've found a bug in our required balance calculation and we will be fixing that in our next version release.
Meanwhile you can try funding your account with some additional XAHs.
Furthermore, we will refund your lost EVRs in our next refund process.

**Comment by chalith** [comment]
Is this issue resolved now?

**Comment by atram766** [comment]
Thank you so much for taking the time to look into the issue. I  was able
to get the refund back. I already reinstalled it successfully.

**Comment by chalith** [comment]
@atram766 You are welcome. Don't hesitate to raise an issue if there's any problem. Closing the issue since it's now resolved.
