### ISSUE TITLE
Error during host setup installation

### ISSUE THREAD

**Issue by DeathHorizonv0** [EvernodeXRPL/evernode-host#147]
Hi, I was on the process of setting up a node for Evernode and I came to and error when the setup was running. I'm attaching the log file that was created during the installation process. 

Any help would be much appreciated.

[installer-1705420102.log](https://github.com/EvernodeXRPL/evernode-host/files/13952881/installer-1705420102.log)

**Comment by kithminisg** [comment]
There is a log message of a missing command. Could you please check whether your machine satisfies [system requirements](https://docs.evernode.org/en/latest/hosts/evernode-host.html#system-requirements). 
NOTE: Backup your Xahau account secret saved inside the machine, if you have to change the system.

**Comment by DeathHorizonv0** [comment]
Yes my machine satisfies system requirements.

Operating system: Ubuntu 20.04 64 bit (M1/ARM CPUs or WSL not supported. Any other Ubuntu versions are not supported.)

RAM: 2 GB minimum

Swap: 2 GB minimum

Disk space: 4 GB minimum free disk space for /home

**Comment by chalith** [comment]
Saw the following in your logs
```
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 7162 (unattended-upgr)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
```
Looks like package manager is open in your machine or another apt command is running in background. Can you reboot your machine and try again.

**Comment by DeathHorizonv0** [comment]
Rebooted the machine and tried again and now it comes up with another log error. 

[installer-1705503921.log](https://github.com/EvernodeXRPL/evernode-host/files/13965074/installer-1705503921.log)

**Comment by DeathHorizonv0** [comment]
This is the current error log I'm receiving 

[installer-1705520004.log](https://github.com/EvernodeXRPL/evernode-host/files/13967923/installer-1705520004.log)

**Comment by DeathHorizonv0** [comment]
Fixed the issue already was a problem with my VM and port 80 thanks for the help anyway and happy hosting!
