### ISSUE TITLE
Accidentally reinstalled Ubuntu, how do I regain control of the host?

### ISSUE THREAD

**Issue by NMAE123** [EvernodeXRPL/evernode-host#148]
I try to re-install node, but have trable 
Checking account rURYWrk4aqZnPLEAbVoF28U3uUV25SpcQi...
Host is already registered.

I saved the private key, but I don't know what to do.

**Comment by ndurbin510** [comment]
Have you checked out the Host documentation?
https://docs.evernode.org/en/latest/hosts/maintenance.html

There is also a discord: https://discord.com/invite/twh6jsd6Uw

**Comment by chalith** [comment]
@NMAE123 try this out https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration

**Comment by NMAE123** [comment]
all ok, thnks
