### ISSUE TITLE
Failed install x2

### ISSUE THREAD

**Issue by mal-practice** [EvernodeXRPL/evernode-host#149]
Hi,

Please see logs below - 2x failed installs - I know why (insufficient funds - XAH I suspect). I am on with sorting it but I believe that there were EVRs burned - is it possible to get these back?

Thanks and sorry,

J.
[installer-1705435326.log](https://github.com/EvernodeXRPL/evernode-host/files/13955352/installer-1705435326.log)
[installer-1705435999.log](https://github.com/EvernodeXRPL/evernode-host/files/13955353/installer-1705435999.log)

**Comment by chalith** [comment]
Yes, We will be fixing the issue in next release. And we are refunding your accounts with the burnt EVRs due to installation failures.

**Comment by chalith** [comment]
Can you send us your host r address?

**Comment by BimsaraFernando** [comment]
Hi @mal-practice , 
Thank you for your contribution. This issue has not had recent activity and we are closing it now, assuming you received the refund. If this problem persists or if you have further questions, please open a new issue.
