### ISSUE TITLE
Wrong Geolocation of host

### ISSUE THREAD

**Issue by Digifin** [EvernodeXRPL/evernode-host#151]
Installation went perfect, but host is showing on the dashboard with the wrong flag, France.
Host is UK based and with IP check is actually located in London.

Host account address: rn6rmixG3u1kxUuRderZvFppHXPbYPbeJx

![image](https://github.com/EvernodeXRPL/evernode-host/assets/53521582/1498579f-103f-4bd4-8180-02ef1ee84bd4)

Just a minor issue/glitch.

**Comment by Ekiserrepe** [comment]
Hosts rnWJK6jxgh2b9aCDTfdiJPWQmETfy1WrVU and rhp5h86rLQ1a2Hrm9PxBr2dCH8SP79YXjm are located in Spain. They are flagged as Germany. 

Thanks!

**Comment by chalith** [comment]
Thanks for the catch we'll investigate

**Comment by BimsaraFernando** [comment]
Hi @Digifin ,
Thank you for your contribution. The latest community built dashboards can be found at  https://dashboard.evernode.org/

This issue has not had recent activity and we are closing it now. If you have further questions, please open a new issue.
