### ISSUE TITLE
Devkit - Acquire/Audit Host error

### ISSUE THREAD

**Issue by everclub** [EvernodeXRPL/evernode-host#152]
I'm following this tutorial   https://docs.evernode.org/en/latest/sdk/evernode/tutorials/deploy-single.html 
Installed evdevkit ,
generated new keypair ,
set EV_TENANT_SECRET , EV_USER_PRIVATE_KEY and EV_NETWORK=mainnet
but after running this commands 
evdevkit acquire <host Xahau address>  or   evdevkit audit -h <host>
it shows an error: "'Host encryption key not set."
Tried different random hosts but the same error. 

The "tenant" wallet is activated with enough XAH and also 5 EVRs.

Here are some screenshots for both 'acquire' and 'audit' commands. 
![Screenshot-2024-01-17-171705](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/a6081f2f-0899-4908-af0b-5569900367a2)
![Screenshot-2024-01-17-172500](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/50e39f72-eccc-4115-abd7-781556c97206)

Thanks.

**Comment by chalith** [comment]
Thanks for trying out devkit. There are some hosts where the account preparation is not properly done due to an internal bug. We are fixing this in v0.8.1. Meanwhile, you can try with a host who has a domain in his ledger account info.

**Comment by everclub** [comment]
Tried with a host who has a domain in his ledger account info. I think it's working but until another error occur. 

Tx hash is here https://xahauexplorer.com/explorer/C3D17EDE0B82DBA211D35E80990D2D533AB582ED68F7760565BFA18D2378F0DE

![Screenshot 2024-01-18 085925](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/ff6c82fe-18da-4c02-91e3-31243af08ca0)

**Comment by everclub** [comment]
I need to UNDO this operation, I thought 'audit' means auditing and not 'acquiring' an instance and I don't know how to release the acquired space. What's the command to release the acquired instances ? 
![Screenshot 2024-01-18 at 09-30-43 Evernode](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/f110fcca-c059-4dee-86ae-3bee5730f750)

**Comment by everclub** [comment]
Issue resolved , I will close it now.
