### ISSUE TITLE
Failed installation - mkdir: cannot create directory

### ISSUE THREAD

**Issue by mal-practice** [EvernodeXRPL/evernode-host#153]
Hi,

I have three failed installation attempts as root with the error:

mkdir: cannot create directory ‘/home/sashimbxrpl/.config’: Permission denied

EVR not fully refunded.

Any idea when the fix for this permissions issue is going to be pushed out?

Thanks in advance.

Kind regards,

J.

[installer-1705524678.log](https://github.com/EvernodeXRPL/evernode-host/files/13968855/installer-1705524678.log)
[installer-1705526051.log](https://github.com/EvernodeXRPL/evernode-host/files/13968856/installer-1705526051.log)
[installer-1705525206.log](https://github.com/EvernodeXRPL/evernode-host/files/13968857/installer-1705525206.log)

**Comment by jellicoe** [comment]
see this ticket 150
https://github.com/EvernodeXRPL/evernode-host/issues/150

**Comment by mal-practice** [comment]
Thanks @jellicoe. Do you know if the patch has been pushed out?

**Comment by chalith** [comment]
@mal-practice hope you receive the refunds. Did you try the installation again?

**Comment by mal-practice** [comment]
@chalith - thank you - refund received. 

I have not tried to spin up that particular server again and spun up a completely new now which is registered on the network and working.

I can try and spin up the original (as the image is still there) later today.

If it works, I will close this ticket with a comment this evening. If not, I will add to the ticket with any update. 

Thanks again.

Kind regards,

J.
