### ISSUE TITLE
failed installation Evers Refund

### ISSUE THREAD

**Issue by mrnash88** [EvernodeXRPL/evernode-host#154]
Hi I was told on discord to let you guys know on here about my fail installation and refund please. Thanks.

**Comment by mrnash88** [comment]
![Screenshot from 2024-01-17 17-22-26](https://github.com/EvernodeXRPL/evernode-host/assets/150109205/9eef68b7-2da2-49e0-83eb-4172855fb62f)

**Comment by chalith** [comment]
Sure! we are working on refunds

**Comment by chalith** [comment]
Did you receive your refunds? And did you try the installation again?

**Comment by BimsaraFernando** [comment]
Hi @mrnash88 ,
Hope you received the refund. Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
