### ISSUE TITLE
Evernode host log errors

### ISSUE THREAD

**Issue by everclub** [EvernodeXRPL/evernode-host#156]
I see some errors inside evernode logs. Should I be worried about those errors? My host is up and running, active and acquiring EVRs since day 1. Uploading the full log file 
[evernode.rNSNLlRZc.log](https://github.com/EvernodeXRPL/evernode-host/files/13973638/evernode.rNSNLlRZc.log)

![Screenshot 2024-01-18 094940](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/28326c71-4f7b-462a-a4fb-dd6c08bf1430)

**Comment by kithminisg** [comment]
@everclub, Could you please check whether are there any network connectivity issues in your host? 
Anyway there might be occasional connection issues when trying to connect to Xahau network, due the network traffic condtion.

**Comment by everclub** [comment]
Connection is fine, I have 5 different hosts on different data centers and all of them show this error. Everything is fine, hosts are Active and sending heartbeats every hour.
Thanks.
