### ISSUE TITLE
Update to Sashimono (v0.8.1) failed.

### ISSUE THREAD

**Issue by AnderT** [EvernodeXRPL/evernode-host#157]
root@EverHost : /tmp/evernode# cat installer-1705564712.log
--- Sashimono installer (upgrade) ---
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode ...
useradd: warning: the home directory /home/sashimbxrpl already exists.
useradd: Not copying any file from skel directory into it.
STAGE Configuring Sashimono services
Creating cgroup rules ...
Configuring sashimono agent service ...
Existing Sashimono data directory found. Updating ...
Secret config file does not exist at /home/sashimbxrpl/.evernode-host/.host-account-secret.key
Evernode Xahau message board exiting with error.
Evernode update failed. You can try again later. If the problem persists, please uninstall and re-install Evernode.

**Comment by kithminisg** [comment]
@AnderT , Could you please check the existence of  `/home/sashimbxrpl/.evernode-host/.host-account-secret.key` file? 
Also please check that path matches with the `secretPath` attribute in  the `/etc/sashimono/mb-xrpl/mb-xrpl.cfg` configuration file.

**Comment by AnderT** [comment]
Yes, the file exists.

"secretPath": "/home/sashimbxrpl/.evernode-host/.host-account-secret.key",

Looks correct.

**Comment by AnderT** [comment]
Any thoughts? There goes my reputation, just missed my first heartbeat : (

**Comment by everclub** [comment]
So are we missing heartbeats if not updating ?

**Comment by chalith** [comment]
@AnderT you can also transfer and re-install with existing registration if you are ok with that.
But if not we can investigate the reason, can you check whether the `/home/sashimbxrpl/.evernode-host/.host-account-secret.key` is under the sashimbxrpl user permissions

@everclub no you are not

**Comment by AnderT** [comment]
@chalith -r -------- 1 1000 1000 58 Jan 15 08:00 /home/sashimbxrpl/.evernode-host/.host-account-secret.key

**Comment by AnderT** [comment]
Any update?

**Comment by chalith** [comment]
It seems you will have to transfer the registration. Can you backup your secret and follow this to transfer the installation https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration. After that you can re-install using the same account.

**Comment by AnderT** [comment]
root@EverHost:~# curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer
Found Sashimono v0.8.1...
Evernode host management tool 
Your system has a previous failed partial Evernode installation. 
You can repair previous Evernode installation by installing again. 
Supported commands: 
uninstall - Uninstall previous Evernode installation

How do I uninstall?

**Comment by AnderT** [comment]
Should I just re-install?

**Comment by kithminisg** [comment]
@AnderT, Could you please check whether `evernode` command exists in your VM?

**Comment by AnderT** [comment]
No, it did not.

I did an un-install, a transfer and an install.

Got this error:

---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu focal InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Hit:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease
Fetched 114 kB in 2s (59.0 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
The following packages were automatically installed and are no longer required:
  libfwupdplugin1 libxmlb1
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 5 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Rule added
Rule added (v6)
Running certbot certonly
Account registered.
Requesting a certificate for everhost.taylor.nu

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/everhost.taylor.nu/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/everhost.taylor.nu/privkey.pem
This certificate expires on 2024-04-17.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-everhost.taylor.nu.sh
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Secret config file does not exist at /home/sashimbxrpl/.evernode-host/.host-account-secret.key
Evernode Xahau message board exiting with error.
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'everhost.taylor.nu'
Deleted all files relating to certificate everhost.taylor.nu.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/everhost.taylor.nu/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rule deleted
Rule deleted (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by AnderT** [comment]
Having loads of fun : )

**Comment by AnderT** [comment]
Secret config file does not exist at /home/sashimbxrpl/.evernode-host/.host-account-secret.key

It really does!

**Comment by kithminisg** [comment]
Could you please send us the host address?

**Comment by AnderT** [comment]
Here you go : )

rwscXU5Scghfop6EccinzsarPvXzp9Kv4D

**Comment by AnderT** [comment]
I cannot see the deregistration on the ledger.

**Comment by kithminisg** [comment]
Sometimes your deregistration is also linked to the same issue. I think there is a permission issue in your VM setup. Could you please manually add this user and set the ownership of the directory as follows?

```        
useradd --shell /usr/sbin/nologin -m sashimbxrpl  2>/dev/null
chown -R sashimbxrpl:sashimbxrpl /home/sashimbxrpl
```
Then try the installation again.

**Comment by chalith** [comment]
@AnderT yes no deregistration. Your registration is transferred, so you'll be able to install using the same account

**Comment by AnderT** [comment]
Creating offers!!!! I think we are cooking again : )

**Comment by AnderT** [comment]
Awesome! Back up and running : )

Thanks so much for all your help.

**Comment by rippleitinnz** [comment]
@AnderT - please reopen this as you are not an isolated case. This bug I highlighted in the testnet and seems was simply ignored, and here it is again. I have lost access to my instance after a failed autoupdate, my secret has gone (again)

**Comment by AnderT** [comment]
It should still be here > /home/sashimbxrpl/.evernode-host/.host-account-secret.key

**Comment by rippleitinnz** [comment]
> It should still be here > /home/sashimbxrpl/.evernode-host/.host-account-secret.key

It' not. It no longer exists. Anyway. I had it backed up.

**Comment by BimsaraFernando** [comment]
Hope this issue got fixed with the latest Evernode updates. If you are still experiencing the issue, please reopen.
