### ISSUE TITLE
error during installation

### ISSUE THREAD

**Issue by inspectorjair** [EvernodeXRPL/evernode-host#161]
I NEED HELP!!

I WAS COMPLETING THE INSTALLATION, EVERYTHING WAS GOING WELL, I HAD ALREADY SENT THE 18.2 XAH AND THE 500 EVR TO THE ACCOUNT THEY ASSIGNED ME AND IN THE LAST PROCESS THE NEXT "

Setting up letsencrypt certbot

**There was an error during installation. Please provide the file /tmp/evernode/installer-1705562433.log to Evernode team. Thank you.**
root@vmi1610337:~# evernode status
evernode: command not found.

AND NOW THAT I OPEN PuTTY AGAIN and enter my assigned username and password that I acquired in CONTABO, nothing is saved, I have to enter all the commands again that I saw in a guide but when I enter the install command: 

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

After placing that command again it sends me the qr message so that I can deposit xah and evr again, when I already did it and a wallet was assigned, I have no idea how to get the seed phrase out of the directory, so I also need help If there is any tutorial or steps to follow to know where I should put a command to show me the secret phrase and enter directly from the xamman app into the new assigned wallet.

And finally I enter the dashboard and put the wallet where they asked me to deposit and the host is not active either, what is going to happen now?

**Comment by everclub** [comment]
This command

cat /home/sashimbxrpl/.evernode-host/.host-account-secret.key 

is going to show your secret key.

You can replace the secretkey inside that file with the old one which is already activated.

**Comment by inspectorjair** [comment]
Thank you very much, the cat command helped me know my seed phrase.

I just need someone from support to help me with the problem that is appearing and what is the reason why my node is not installed.
