### ISSUE TITLE
Help Issue error installation i send evr and xah

### ISSUE THREAD

**Issue by inspectorjair** [EvernodeXRPL/evernode-host#163]
@kithminisg  NEED HELP!!

I WAS COMPLETING THE INSTALLATION, EVERYTHING WAS GOING WELL, I HAD ALREADY SENT THE 18.2 XAH AND THE 500 EVR TO THE ACCOUNT THEY ASSIGNED ME AND IN THE LAST PROCESS THE NEXT "

Setting up letsencrypt certbot

There was an error during installation. Please provide the file /tmp/evernode/installer-1705562433.log to Evernode team. Thank you.
root@vmi1610337:~# evernode status
evernode: command not found.

@chalith @kithminisg  please tell me why can not completed my installation and what happened with my xah and evr that send in to the QR for my host.

[Installer.1705562433.txt](https://github.com/EvernodeXRPL/evernode-host/files/13976558/Installer.1705562433.txt)

**Comment by inspectorjair** [comment]
[Installer.1705562433.txt](https://github.com/EvernodeXRPL/evernode-host/files/13976548/Installer.1705562433.txt)

**Comment by chalith** [comment]
@inspectorjair is this resolved now? Saw your issue https://github.com/EvernodeXRPL/evernode-host/issues/162 has been closed.

**Comment by inspectorjair** [comment]
Yes Chalith i resolved but now mi question it´s 
When will I receive the 250 evers back, since the host is already validated and working, in fact I have already started to receive the first rewards but the 250 evrs were not deposited back to me?
Host: rUUv871RffTgu4TvwGK5jhkRtue6ggkRiG
Thanks

**Comment by inspectorjair** [comment]
> @inspectorjair¿Esto ya está resuelto? Vi que su [número 162](https://github.com/EvernodeXRPL/evernode-host/issues/162) se cerró.

Yes @chalith I resolved the issue #162 and #163 Thanks
