### ISSUE TITLE
host setup failed but registration went through

### ISSUE THREAD

**Issue by arbarodelegate** [EvernodeXRPL/evernode-host#164]
I setup a host a few days ago, but it failed during setup. However the 500 EVR for registration went through, after that is said my account didn't have enough funds..

Now I tried to use the transfer command, but now it says "Host is not registered".

Address is: rNGceFtSRWDNbveGmTNPpgnaZ8JLvd9F5y

How can I fix this?

**Comment by chalith** [comment]
@arbarodelegate can you refer to this solution and try to claim your token? https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923
Give us an update after trying this.

**Comment by arbarodelegate** [comment]
@chalith thank you, it is now resolved!

**Comment by chalith** [comment]
Closing since resolved
