### ISSUE TITLE
I'm running into this problem during installation: NO_MB_USER_SYSTEMD 

### ISSUE THREAD

**Issue by mrnash88** [EvernodeXRPL/evernode-host#168]
I have no clue what this is and your help would be very appreciated. Please help me solve this because I have no clue where to start. Here is the log:
![Screenshot from 2024-01-18 21-02-39](https://github.com/EvernodeXRPL/evernode-host/assets/150109205/0def0db7-ed16-4cf3-85f2-3c4347970427)

**Comment by chalith** [comment]
Has this happened due to an installation attempt? It seems the installation failed to start some user services. Did you retry?

**Comment by mrnash88** [comment]
yes this happened due to an installation attempt. So do you want me to retry it again?

**Comment by mrnash88** [comment]
oh wow that worked! Thank you very much chalith sir.
![Screenshot from 2024-01-18 21-24-08](https://github.com/EvernodeXRPL/evernode-host/assets/150109205/bbb0110a-00fb-4134-88a6-2910adc25714)

**Comment by chalith** [comment]
Closing the issue since now resolved!
