### ISSUE TITLE
Lost access to original host - Script fails

### ISSUE THREAD

**Issue by wilandtrading** [EvernodeXRPL/evernode-host#170]
I am a host operator and I unfortunately experienced an issue on one of my servers. After re-installing Ubuntu I tried the following command:

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

This command is taken from the chapter regarding Host Maintenance - https://docs.evernode.org/en/latest/hosts/maintenance.html . 

Upon running this command I get an error saying that the Xahau address is not registered. This must be wrong. This address has been active for at least a day and it has received rewards.

This is the address: rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC
I also have the secret key, but the script fails before I get to that part.

Please help me with this.

**Comment by chalith** [comment]
Checked the history of your account. It looks like this account is the one you received airdrop, but there were no registration transactions. Can you check whether you are giving the correct address that you used to have the host?

**Comment by wilandtrading** [comment]
Yes, this account is where I received the airdrop, but also the one where I scanned the QR code and paid the XAH/EVR fees while installing Evernode. I do have the secret code of course.

**Comment by chalith** [comment]
Yes, The one you have scanned is your host address. That's the one used to register your host in Evernode. Not the account you paid from.

**Comment by wilandtrading** [comment]
But its the same address. I received the airdrop on this r-address that I have mentioned in this thread. Then I also sent a few EVR from Bitrue to this very same address in order to have enough EVR (500). I then start installing on the server, and while choosing to be on the Xahau network (in xaman) I made sure to choose this r-address when scanning the QR code while installing Evernode.

So, this r-address (rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC) received the initial airdrop and was also used when scanning the QR code. So how come is it not registered in Evernode? It has been paid and the Evernode status was active for at least 36 hours or more.

I can also mention that I have another issue with another r-address where I have paid twice: rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY

Im a bit worried now about this whole thing, but lets focus on the first r-address which is the reason for this thread.  **rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC**

**Comment by wilandtrading** [comment]
The payment, and QR scanning was done from rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC.
When I look at the transaction details for this account then the payment of the XAH and EVR, when installing Evernode, went to this address: rax79x3gTq8i1LugNQr8MdVbhsV7nsAoKE

The secret key does not correspond to that address (rax79x3gTq8i1LugNQr8MdVbhsV7nsAoKE).

Please let me know what to do now. I can do a new installation, but then I need to be refunded what I have paid.
Im losing out on the rewards now so I would appreciate if you could help me swiftly.

**Comment by krazedegen** [comment]
> I am a host operator and I unfortunately experienced an issue on one of my servers. After re-installing Ubuntu I tried the following command:
> 
> curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer
> 
> This command is taken from the chapter regarding Host Maintenance - https://docs.evernode.org/en/latest/hosts/maintenance.html .
> 
> Upon running this command I get an error saying that the Xahau address is not registered. This must be wrong. This address has been active for at least a day and it has received rewards.
> 
> This is the address: rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC I also have the secret key, but the script fails before I get to that part.
> 
> Please help me with this.

what were you transfering from? Mainnet is a fresh install not transfer from testnet

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

**Comment by wilandtrading** [comment]
I had a server malfunction and I had to re-install Ubuntu all over, but I kept my secret key before doing the re-install of Ubuntu.

So after I had re-installed Ubuntu I ran the command I refer to in my initial post. I ran this command because while reading through the Evernode documentation I saw the following quote (under Host maintenance):

"However, if you have lost access to your original host (eg. damaged host), you can use the following command in any Linux terminal. You are required to possess the Xahau account address and secret of your original host."

But while running this command I experience the issue I have described in my initial post.

**Comment by wilandtrading** [comment]
UPDATE - I had to do a new installation. The new Host Address is rGAMf8NFUN5zLgLgvWj7UZM6e5QZjVMGu5 and this seems to work fine. Status is Active.

Can I please get refunded the payment I did for the previous host, which together with the secret key didnt work.

The old host address is rax79x3gTq8i1LugNQr8MdVbhsV7nsAoKE

The payment I would like to get refunded is the following:
On 17th of January:
From: rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC 
To: rax79x3gTq8i1LugNQr8MdVbhsV7nsAoKE
Amount 60 XAH

On 17th of January:
From: rpMmoK7dsx6QL6ivKrweh9d7SgroMqeieC 
To: rax79x3gTq8i1LugNQr8MdVbhsV7nsAoKE
Amount 510 EVR

I do have the secret for the old host address if you need it.

**Comment by wilandtrading** [comment]
Since I have the secret key I will do an installation with the transfer-option and see how it goes. If it doesnt work then I will just close the account and fix it through Xaman.
Im closing this issue. Thanks for the support anyway.
