### ISSUE TITLE
Host failed to Update to Sashimono (v0.8.1) , lost evers

### ISSUE THREAD

**Issue by rukicoder** [EvernodeXRPL/evernode-host#171]
Yesterday noticed that my host was inactive. SSH to it and did an evernode status.  I get a commnad not found message. I tried to find a solution in the discord and found https://github.com/EvernodeXRPL/evernode-host/issues/118. Followed the steps but each time I add my wallet: rEdxvtSbwhrQU4BQTV5unxAgeEg8KaECAW .  I keep getting this response : Host is already registered. Digged some more and found this: https://github.com/EvernodeXRPL/evernode-host/issues/157. Followed this https://github.com/EvernodeXRPL/evernode-host/issues/157#issuecomment-1898300160. and this caused my host to get deregistered.  I was forced to create a new install which is so frustrating. 
#update-failure

**Comment by rukicoder** [comment]
Any update on this? 
![evernode got deregistered](https://github.com/EvernodeXRPL/evernode-host/assets/80587579/72410911-b941-4f64-b20a-3f1e96281e9a)

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
