### ISSUE TITLE
Refund Request

### ISSUE THREAD

**Issue by wilandtrading** [EvernodeXRPL/evernode-host#174]
Hi,
One of of my hosts I experienced an issue while installing Evernode, and I had to pay twice.

**The first payment was on 17th of January 4:35 PM:**
From: rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY
To: rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA
Amount: 50 XAH

**Second payment was on 17th of January 4:37 PM:**
From: rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY
To: rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA
Amount: 501 EVR

**Third payment was on 17th of January 11:04 PM:**
From: rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY
To: rfZutdWCdYZ7h6PYFsB1rHVHyWscn8Fnzg
Amount: 50 XAH

**Fourth payment was on 17th of January 11:12 PM:**
From: rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY
To: rfZutdWCdYZ7h6PYFsB1rHVHyWscn8Fnzg
Amount: 510 EVR

Can I please get the first two payments refunded to rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY ? Those that were paid to rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA.

Thank you.

**Comment by vonstegen** [comment]
For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by wilandtrading** [comment]
Hi,
Im afraid that doesnt help me.
The installation failed before it completed and Im therefore not in possession of the secret key. I had to do payment (listed above) twice before the installation proceeded successfully. The first attempt was around 4 PM, then I tried the installation later on the same VPS, from the same Xahau account (rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY).

The first attempt was to the host address rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA. This failed, but the payment was taken from my Xahau account.

The second attempt was to the host address rfZutdWCdYZ7h6PYFsB1rHVHyWscn8Fnzg. This was successful and this installation is now Active and operative. 

Its the failed installation where I paid to rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA which I request a refund to. This installation failed even though the payment was taken and secret key was not accessible.

**Comment by wilandtrading** [comment]
As you can see both of these host addresses goes to the same domain, but its only rfZutdWCdYZ7h6PYFsB1rHVHyWscn8Fnzg were the installation was successfully completed.

The host address rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA took the payment, but the installation failed and I was not getting the secret key either. 

Can I please get refunded the EVR and XAH that I paid for the host address rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA.

They both were funded by the same Xahau account (rsY5PLsScuwWAVF9Sq7ZtJjNsbNRX2zjYY)

**Comment by chalith** [comment]
@wilandtrading the secret file which is generated for you will be in location `/home/sashimbxrpl/.evernode-host/.host-account-secret.key`. Can you try whether it's there? The registration payment hasn't gone through our registry account. It's still in `rDmRg2R6GXWyuHVquUHETseigHDoLFLwhA`

**Comment by wilandtrading** [comment]
Hi and thanks for your answer.
No, the secret key is missing, and thats whats strange with this
installation. The other installation I had issue with had the secret key
available, but this one doesnt.

Ok, is there a way to get access to these EVRs, or a refund to a Xahau
account, in this way I can use them in creating a new host installation?
Im not interested in having these EVRs idle somewhere, I want to use them
to create a host.
Im open for any suggestions for how to make this happen.

Thank you.

**Comment by BimsaraFernando** [comment]
Hi @wilandtrading ,
Is this issue resolved? If not please share the content inside /home/sashimbxrpl/ path using `ls` command.
