### ISSUE TITLE
Host randomly gets inactive

### ISSUE THREAD

**Issue by EpicShah** [EvernodeXRPL/evernode-host#175]
Why does a host get inactive? when auto update is enabled. Is it normal, im not running any extra commands other than normal  curl install and transfer commands. Every time that happens I have to go back and reinstall everything, is there a solution to this? Am i missing anything?

**Comment by EpicShah** [comment]
I have reinstalled a few times by transfer and install curl command, installation successful but still status "inactive"
![ever1](https://github.com/EvernodeXRPL/evernode-host/assets/123892683/71c447ca-e0a3-4991-9c89-b4d462a7bc0e)

**Comment by BimsaraFernando** [comment]
Hi, does this issue still persist with the new version? If not, please close the issue.
