### ISSUE TITLE
There was an error during installation.

### ISSUE THREAD

**Issue by herkimer9** [EvernodeXRPL/evernode-host#178]
[installer-1705732039.log](https://github.com/EvernodeXRPL/evernode-host/files/13996985/installer-1705732039.log)

I send you error log file.

I wonder why I can only run install with apach2. 
Whithout apach, Im keep having error message which says my domain address is invalid and unreachable. Could you plz help?

**Comment by vonstegen** [comment]
For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by BimsaraFernando** [comment]
Hi @herkimer9 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
