### ISSUE TITLE
New Node Setup Issues with 500 Evers

### ISSUE THREAD

**Issue by CryptocurrencyWorlds** [EvernodeXRPL/evernode-host#181]
Hi. 

Could you please refund 500 EVR?

Thank you.

rMffraunReVzYsmPXgvY86GSSfq1CWemZo

**Comment by vonstegen** [comment]
This SOLUTION may help if you had an ERROR during installation;

For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by CryptocurrencyWorlds** [comment]
Thank you, but didn't help in my case. 

The account needs minimum balance of 500 EVR. Current balance is 1.1 EVR.
Specify the Xahau account address:

**Comment by CryptocurrencyWorlds** [comment]
and transfer command gives this: 

Specify the Xahau account address: rMffraunReVzYsmPXgvY86GSSfq1CWemZo
Checking account rMffraunReVzYsmPXgvY86GSSfq1CWemZo...
Host is not registered.

**Comment by CryptocurrencyWorlds** [comment]
Thank you, issue is fixed by connecting to xahau explorer with Xaman wallet, completing NFT transaction, and then running those two commands above.

**Comment by chalith** [comment]
Closing the issue since now resolved
