### ISSUE TITLE
EVR gone but no NFT transfer/mint

### ISSUE THREAD

**Issue by lagoonlyrics** [EvernodeXRPL/evernode-host#182]
I think something went wrong during my node install. It completed but the last two lines of my status are:
Error occured when retrieving account info. 
Evernode Xahau message board exiting with error. 

It's been about 3 hours and no heartbeat. If I put the host address into the explorer, I see the transaction of the 500evr going out but no transaction from the registry hook sending the token. I tried delete and reinstall but it says I don't have enough evr in the host. I think I either need a evr refund or the nft to be delivered. Host: rDeELGVg9AMU3ggAwMCSVwqH3mmudBSzpz

**Comment by vonstegen** [comment]
Possible SOLUTION;

For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by lagoonlyrics** [comment]
Problem on the registry side. I had to manually approve the nft mint. Check discord.
