### ISSUE TITLE
How do I go about reinstalling the evernode host server?

### ISSUE THREAD

**Issue by EvernodeSoz** [EvernodeXRPL/evernode-host#183]
During the installation of the evernode host the installation failed at the ssl cert creation stage. Being new to command line linux, I had no idea of how to send the err log file to support, so I decided to install (add) a gui desktop to my server installation. in doing so, i totally screwed up the evernode install. I managed to recover my secret.key file but could not find the err log file to send to you.
My question is how do I go about reinstalling the evernode host server?

**Comment by ejla81** [comment]
I had a go at reinstalling after a similar problem, but it says Host is already registered 🤔
![20240120_113105](https://github.com/EvernodeXRPL/evernode-host/assets/157213308/416953fb-ffaa-4b27-99aa-a462e52c3668)

**Comment by EvernodeSoz** [comment]
Tried to reinstall and get error at same point.
attaching file this time 
[installer-1705809283.log](https://github.com/EvernodeXRPL/evernode-host/files/14000036/installer-1705809283.log)

**Comment by EvernodeSoz** [comment]
Have now had my SSL cert successfully received and registered on my server so that's all good, but now it's still causing an error

> Setting up letsencrypt certbot
> Setting up slirp4netns
> Installing docker packages
> Configuring host Xahau account
> Configuring Sashimono services
> There was an error during installation. Please provide the file /tmp/evernode/installer-1705829222.log to Evernode team. Thank you.`

Looking in the error log file specified it's all OK up untill...

> Installing Evernode Xahau message board...
> Updated mb user .bashrc
> NO_MB_USER_SYSTEMD
> Rolling back sashimono installation.

The problem seems to be around the NO_MB_USER_SYSTEMD line... but not sure what this is or even what the error is to be honest. Full error file provided here:

[installer-1705829222.log](https://github.com/EvernodeXRPL/evernode-host/files/14000706/installer-1705829222.log)

**Comment by EvernodeSoz** [comment]
finally after rerunning install a few times it registered.
