### ISSUE TITLE
Error during installation 

### ISSUE THREAD

**Issue by Petros9004** [EvernodeXRPL/evernode-host#185]
17.6 An error occurred while installing Evernode after inserting xah and 500 ever.

I would like a refund.

Wallet address:
rhz5pV5ZTL9RV3xYWWqV9JFwWFH62AFz5o

![error](https://github.com/EvernodeXRPL/evernode-host/assets/157224286/0e2bf463-6c8c-4d54-be61-506248c22187)

**Comment by Petros9004** [comment]
Checking the account condition...
To set up your host account, ensure a deposit of 17.6 XAH to cover the regular transaction fees for the first three months.

Waiting for the process to complete...
Thank you. 17.6 XAH balance is there in your host account.

Preparing host account...

Waiting for the process to complete...
Account preparation is successfull.


In order to register in Evernode you need to have 500 EVR balance in your host account. Please deposit the required registration fee in EVRs. 
You can scan the provided QR code in your wallet app to send funds:

Waiting for the process to complete...
Thank you. 500 EVR balance is there in your host account.

Account setup is complete.

Do you want to subscribe for auto-updates?
NOTE: The auto-update service is offered subject to the terms set out in the Evernode Software Licence. [y/N]y

Auto updater will be enabled.


Setup will now begin the installation. Continue? [Y/n]y

Starting installation...
Installing other prerequisites...
Installing dependencies
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0  1630k      0 --:--:-- --:--:-- --:--:-- 1630k
Done.

Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
There was an error during installation. Please provide the file /tmp/evernode/installer-1705754929.log to Evernode team. Thank you.

**Comment by Petros9004** [comment]
root@Ever2:~# sudo cat /tmp/evernode/installer-1705754929.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
The following packages were automatically installed and are no longer required:
  eatmydata libeatmydata1 python3-importlib-metadata python3-jinja2
  python3-json-pointer python3-jsonpatch python3-jsonschema python3-markupsafe
  python3-more-itertools python3-pyrsistent python3-zipp
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libtirpc-common libtirpc3 quota
  uidmap
The following packages will be upgraded:
  openssl
1 upgraded, 8 newly installed, 1 to remove and 285 not upgraded.
Need to get 1194 kB of archives.
After this operation, 2692 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 openssl amd64 1.1.1f-1ubuntu2.20 [620 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:7 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 1194 kB in 1s (1818 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 80695 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 80703 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 80693 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Preparing to unpack .../1-openssl_1.1.1f-1ubuntu2.20_amd64.deb ...
Unpacking openssl (1.1.1f-1ubuntu2.20) over (1.1.1f-1ubuntu2.1) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../2-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../3-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../4-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../5-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../6-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../7-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up openssl (1.1.1f-1ubuntu2.20) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Processing triggers for systemd (245.4-4ubuntu3.4) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.3) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-64-generic
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
/dev/vda2 [/]: group quotas turned on
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for petrosever.monster

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/petrosever.monster/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/petrosever.monster/privkey.pem
This certificate expires on 2024-04-19.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-petrosever.monster.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: US 800000 3224080 1649040 75240240 6                 Intel(R)_Xeon(R)_CPU_E5-2680_v4_2.40GHz 4 2399 petros9004@naver.com _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer D0D9A26335FF4177113191E4F5A6AE7D8EEEB3FA9CD441743AC50ABE4F36D05C
Accepting the sell offer..
The latest ledger sequence 2340774 is greater than the transaction's LastLedgerSequence (2340771).
Preliminary result: {
  "id": 38,
  "result": {
    "accepted": true,
    "account_sequence_available": 759070035,
    "account_sequence_next": 759070035,
    "applied": true,
    "broadcast": true,
    "engine_result": "tesSUCCESS",
    "engine_result_code": 0,
    "engine_result_message": "The transaction was applied. Only final in a validated ledger.",
    "kept": true,
    "open_ledger_cost": "12106",
    "queued": false,
    "tx_blob": "12002F2100005359242D3E7D52201B0023B7A3502409AE1368F712000A327CF875E05633CF7B7A08DEF2F09D1B51FED503335A9B52614000000000000001684000000000002F4A732103A96492C4985E8216CA26C427A15B37FB8F17A3B9A0E1FF559743FCF7AE4BFFDB744630440220459306B7FC5821FAC11C0FDE39C89E009A426ECB6DE2B8C0D04E1CCDA5A7D51C02204DEAFBEF23A2165A602D96EACFFFBF4AB2C390A88397A18D752B71AE4CC687AB81142BD25571D1A294DBFDE0E6B9E84B6C47FC002B9D",
    "tx_json": {
      "Account": "rhz5pV5ZTL9RV3xYWWqV9JFwWFH62AFz5o",
      "Amount": "1",
      "Fee": "12106",
      "LastLedgerSequence": 2340771,
      "NetworkID": 21337,
      "Sequence": 759070034,
      "SigningPubKey": "03A96492C4985E8216CA26C427A15B37FB8F17A3B9A0E1FF559743FCF7AE4BFFDB",
      "TransactionType": "URITokenBuy",
      "TxnSignature": "30440220459306B7FC5821FAC11C0FDE39C89E009A426ECB6DE2B8C0D04E1CCDA5A7D51C02204DEAFBEF23A2165A602D96EACFFFBF4AB2C390A88397A18D752B71AE4CC687AB",
      "URITokenID": "09AE1368F712000A327CF875E05633CF7B7A08DEF2F09D1B51FED503335A9B52",
      "hash": "B635750609A147A2DFE845A9EFED5C0B790B27D0C5CAE61333CEC459B22941EE"
    },
    "validated_ledger_index": 2340761
  },
  "type": "response"
}
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'petrosever.monster'
Deleted all files relating to certificate petrosever.monster.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/petrosever.monster/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by Petros9004** [comment]
oh I think I figured it out.

**Comment by gadget78** [comment]
what fixed it for you ?

**Comment by chalith** [comment]
Is all ok? Shall we close the issue?

**Comment by Petros9004** [comment]
oh and i have one question.

If I terminate my Evernode host, do I get 250 EVER back?


날짜: 2024.01.26 오후 04:32:48 (GMT+09:00)
제목: Re: [EvernodeXRPL/evernode-host] Error during installation (Issue #185)

Is all ok? Shall we close the issue?

**Comment by BimsaraFernando** [comment]
Yes you will get 250 EVRs back.
