### ISSUE TITLE
The host installation completed with an error and 500 EVRs were debited, but the host does not receive a heartbeat check pulse and the contracts were not registered

### ISSUE THREAD

**Issue by FUNDBaron** [EvernodeXRPL/evernode-host#186]
guys what should I do?

When registering the node, the installation completed with an error!
As a result, 500 EVR were debited and sent to the registration contract and the transaction was successful. 
[installer-1705754321.log](https://github.com/EvernodeXRPL/evernode-host/files/13998269/installer-1705754321.log)
<img width="1228" alt="Снимок экрана 2024-01-20 в 17 18 07" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/66091d93-a052-4dde-9d21-f0dd9b6d1cfb">
<img width="1253" alt="Снимок экрана 2024-01-20 в 17 20 09" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/01413e26-b8a6-4b3f-854f-ca3168e37b59">
<img width="1255" alt="Снимок экрана 2024-01-20 в 17 22 12" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/93be862e-95cc-4c82-b83e-7b57e9a5d959">

https://xahauexplorer.com/explorer/3AA33147E8BDF835FF135448123F34745086B57ACD1966D5FBD3E3A74F039F50

https://xahauexplorer.com/explorer/rhMi5u5JmXrhT6XtwtrSLQAGUado3tbTmb

And the dashboard shows that registration is completed. But in the end, the heartbeat check does not occur and the software version shows 0.0.0. And the contracts were not accepted.

In the end, I’m trying to make command a transfer for the node
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

 but the system tells me that this XAH address is not registered and tells me to top up by 500 EVRs, although the coins were written off and the transaction was completed successfully. As a result, I am in a hopeless circle where the system does not allow me to transfer the node and asks me to top up my balance EVR again.
 
 How can I re-register a host or perform a move?

**Comment by gadget78** [comment]
how far did you get with trying to transfer ?

**Comment by vonstegen** [comment]
Possible SOLUTION

For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by FUNDBaron** [comment]
> Possible SOLUTION
> 
> For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here: [#180 (comment)](https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147)

Unfortunately, this solves the problem only when 500 EVR have been debited, but the host has been registered and upon further calling, the script installs and "transfer" work. I had such a problem yesterday and I solved this problem using the same method. But there is another problem when the host is not registered and the installation was unsuccessful, but 500 EVR were written off and every time the script is run, the installation or transfer script requires you to top up the account address again with 500 EVR, although before this all transactions were completed and were successful.

**Comment by MDCryptoSniper23** [comment]
Hi, I completed everything instructed to do but still having an issue, it shows that my host is already registred but on the evernode dashbord its showing as inactive for some reason. I understand it needs to complete an speedtest to show active but another node that I was having the same problem with I followed your instructions and its now working, completed an speed test and now earning. I did both nodes at the same time. Im lost now.

**Comment by BimsaraFernando** [comment]
Hi, The latest version of the Evernode installer should fix the installation issue. If you are still having the issue, please reopen the issue.
