### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by Hillel1408** [EvernodeXRPL/evernode-host#187]
Hi
installation failed

https://xahauexplorer.com/explorer/rMKYCW4YnroPqYqSVKjLK1mqPCfSiCpzJz

how to reinstall?

<img width="582" alt="2024-01-20_15 10 46" src="https://github.com/EvernodeXRPL/evernode-host/assets/45196989/522c31b1-1000-4ea5-9ca1-d8191b51567d">

**Comment by Hillel1408** [comment]
not activated

<img width="265" alt="Снимок экрана 2024-01-20 в 18 14 17" src="https://github.com/EvernodeXRPL/evernode-host/assets/45196989/7b7492ca-2185-4434-8a3e-d21c486f6213">

**Comment by Hillel1408** [comment]
Can I please get refunded the payment?

https://xahauexplorer.com/explorer/14A9654912FDDB957893BFA8B10B901315C8F0AE44800BF3C7C2AD91F598A657

**Comment by FUNDBaron** [comment]
I have the exact same problem.
The installation failed with an error. 500 EVR coins have been debited from the balance. The transaction was completed successfully and I received a Registration Token Id:  AD514C17906BAAE1785BDD347A5851E5CCAFA88B90FE540F456A3FAA02FD6CF4

https://xahauexplorer.com/explorer/3AA33147E8BDF835FF135448123F34745086B57ACD1966D5FBD3E3A74F039F50
https://xahauexplorer.com/explorer/82AA28C439B9D1001865044AADBFD31FF16CA39F0F19B8466F9227DA830A5FE6

and my successful transaction
<img width="1495" alt="Снимок экрана 2024-01-20 в 19 13 19" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/8246a9a6-adab-42e7-a3f7-86818ca8eabe">
<img width="1496" alt="Снимок экрана 2024-01-20 в 19 14 03" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/817f3cc8-202e-44d0-9992-5d47a0a1a802">
<img width="1251" alt="Снимок экрана 2024-01-20 в 19 16 45" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/6ce5f5f7-4311-40ba-a019-dde2a2a2927d">
 
but in the end the system does not allow me to install the node, reinstall the node, or transfer it to another server. It constantly says that the account is not registered. Although everything was registered. how to return coins or how to start and re-register and activate the node?

**Comment by vonstegen** [comment]
I'm having the same issue and now it's asking for more funds even though I funded this node with 510EVRs;

Starting installation...
Installing other prerequisites...
Installing dependencies
Installing snapd
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0  2830k      0 --:--:-- --:--:-- --:--:-- 2830k
Done.

Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
There was an error during installation. Please provide the file /tmp/evernode/installer-1705767412.log to Evernode team. Thank you.

**Comment by vonstegen** [comment]
Here is the installer-1705767412.log
[evernode_issue_001.txt](https://github.com/EvernodeXRPL/evernode-host/files/13998718/evernode_issue_001.txt)

**Comment by vonstegen** [comment]
SOLUTION to the above problem;

For anyone else that experiences a similar issue to the one that I described, I have found a solution and posted it here:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902236147

**Comment by Hillel1408** [comment]
restarted the node
this helped

<img width="978" alt="Снимок экрана 2024-01-20 в 23 48 24" src="https://github.com/EvernodeXRPL/evernode-host/assets/45196989/5be06f37-793f-4ac3-a886-a34ab9f74d9c">

the question is closed
