### ISSUE TITLE
Installation issue. 2 accounts same problem.

### ISSUE THREAD

**Issue by alcinun** [EvernodeXRPL/evernode-host#193]
Hey friends at Evernode. My issue was seemed to be reported by other users. (Failure during instance creation) And the fix was described as transfer curling-point secret key-reinstalling.
On my account: rNCVELFtWMUFd4FUC97ba7cSD8nL1t1dgZ
The transfer process was smooth, until the end it said it has to reboot. And when I followed the instructions further. The installation didn't accept the transfer. 
I retried the transfer process to make sure, and now it says "host is not registered"
On my account: rdU9m8L8L7g9PZVw1uK1hGTwyddBfQVRJ
I was able to seamlessly complete the transfer command with no reboots.
I started the install command, everything went smoothly during the new installation transfer.
Until the end it was another failed installation.
Both now appear as *unregistered* on the transfer command, and on the registry show orange lights instead of red. After transferring.
I'm requesting a reimbursement for these. As they seem to be troubled.

[image](https://github.com/EvernodeXRPL/evernode-host/assets/156863606/9c48e163-1952-41e4-82c7-67a00d23ea33)

**Comment by alcinun** [comment]
![image](https://github.com/EvernodeXRPL/evernode-host/assets/156863606/60d6ebec-2fab-4772-a6af-604c6becdbd8)

**Comment by rippleitinnz** [comment]
The 'Transfer' process doesn't transfer anything, all it does it deregister your account/secret do that it can then be used again. 

Once you've completed the 'transfer' pr cess successfully you then need to do a new install of Evernode and select N when it ask is you want to do a fresh install

**Comment by alcinun** [comment]
> The 'Transfer' process doesn't transfer anything, all it does it deregister your account/secret do that it can then be used again. 
> 
> Once you've completed the 'transfer' pr cess successfully you then need to do a new install of Evernode and select N when it ask is you want to do a fresh install 

Uhhh yes I stated I did that.

**Comment by alcinun** [comment]
> The 'Transfer' process doesn't transfer anything, all it does it deregister your account/secret do that it can then be used again. 
> 
> Once you've completed the 'transfer' pr cess successfully you then need to do a new install of Evernode and select N when it ask is you want to do a fresh install 

I'm quite aware on what the transfer does. I'm not aware on why it's not working for me. I have other hosts cleared.

**Comment by alcinun** [comment]
> The 'Transfer' process doesn't transfer anything, all it does it deregister your account/secret do that it can then be used again. 
> 
> Once you've completed the 'transfer' pr cess successfully you then need to do a new install of Evernode and select N when it ask is you want to do a fresh install 

Should I send another 500 evrs?
