### ISSUE TITLE
Failed install on  Evernode Registry Hook

### ISSUE THREAD

**Issue by krazedegen** [EvernodeXRPL/evernode-host#194]
Failed on install. It ate the Evernode NFT. seems to be in your Registry Hook.
Requesting a way for you to push it back or 500 evrs? Thank you

I  attempted to 

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

and

url -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

but it just wants 500 more Evr. 

Registration Token Id | 6CFE457F833557C952639C115F51BA3FC54A3440409ACFE712ADFC09DFFC4DA8

Executing register with params: DE 800000 1614880 1677680 2658340 3
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer 7E7064A3EC224FF70EC263AB01E7D9B3962AD67B8E9F8E6A6E674430D2CF65A0D
Accepting the sell offer...
Transaction failed with error terMAX_LEDGER
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
![image](https://github.com/EvernodeXRPL/evernode-host/assets/118998133/de3a2e37-93d8-48da-bbaa-ad041577dda9)

**Comment by thuynhgit** [comment]
same thing like you , what can i do now

**Comment by krazedegen** [comment]
> same thing like you , what can i do now

Fill out an issue.
