### ISSUE TITLE
Error in Install - 

### ISSUE THREAD

**Issue by rowrowrown** [EvernodeXRPL/evernode-host#196]
Hi, Not sure if I'm the only one who experienced this.
I tried installing but it did not run

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

![Screenshot 2024-01-21 155336](https://github.com/EvernodeXRPL/evernode-host/assets/101297513/5d43c4e2-7c25-40f7-916d-7b10d3c537e4)

**Comment by du1ana** [comment]
Seems you don't have curl installed. Try running the following commands:

sudo apt-get update
sudo apt-get install curl
