### ISSUE TITLE
tefMAX_LEDGER error

### ISSUE THREAD

**Issue by everclub** [EvernodeXRPL/evernode-host#197]
Today I was waiting for host rewards to show up in my wallet but nothing.
When checked the host log I see this error:  Heartbeat tx error Transaction failed with error tefMAX_LEDGER

Rewards are still not showing up even after 2 hours. Do I get the missing rewards in the next day or they are lost? I also see another error on the other host: Transaction failed with error telCAN_NOT_QUEUE_FEE
Thanks. 

![Screenshot 2024-01-21 095320](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/3e6252de-bdda-4f6d-a572-b970d6101d7a)
![Screenshot 2024-01-21 095421](https://github.com/EvernodeXRPL/evernode-host/assets/156933754/8cf04436-b502-4cb5-b51b-8d6ac431292e)

**Comment by BimsaraFernando** [comment]
Hi, The latest version of the Evernode installer should fix this issue. If you are still having the issue, please reopen the issue.
