### ISSUE TITLE
There was an error during installation.

### ISSUE THREAD

**Issue by metamorphosis143** [EvernodeXRPL/evernode-host#200]
I've tried running the transfer and install command several times, but nothing works.

[installer-1705842684.log](https://github.com/EvernodeXRPL/evernode-host/files/14001422/installer-1705842684.log)

**Comment by BimsaraFernando** [comment]
Hi @metamorphosis143 ,
It seems like your host is up and running. If you have already solved, please close the issue.

After the latest Evernode Installer update release we have improved the installation script with bug fixes. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)  
If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )  
Thank you!

**Comment by BimsaraFernando** [comment]
Hi @metamorphosis143 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
