### ISSUE TITLE
I have attempted to use the Auto-Update feature on the node but that nuked it

### ISSUE THREAD

**Issue by cbistriceanu** [EvernodeXRPL/evernode-host#201]
Hi guys,

My node evrnd2.everxrpl.com with the address r3HJHT8zQXdaR874K4MjNbyUTLPxrdvvWB got registered fine on January 17th. Today January 27th, I have attempted to run the Evernode upgrade and sadly it failed with the Auto-Update feature. I have attempted a few times to use the Transfer feature but as my initial attempt failed I believe the command is not registering anymore. I have attempted to run the repair but I am getting stuck on the steps on being asked about the Xahau address. Once I input that, I am told that the address is already registered. I do have the funds to re-register the node so it will become operational once more but I would really appreciate the refund. 

Happy to provide more details and logs if needed. 
![image](https://github.com/EvernodeXRPL/evernode-host/assets/40581355/2e0088fb-0894-49ab-865d-e6847bb5f823)

**Comment by cbistriceanu** [comment]
I have uninstalled the host and did received the 250 EVR back. However, I have re-installed the node but again the installer failed and now I am in the same position as before as the transfer process does not seem to work and host is not registering. Here is the log on the failure 

![image](https://github.com/EvernodeXRPL/evernode-host/assets/40581355/94726c2a-b6f2-4b41-81e8-cf2c6bd83d67)

**Comment by cbistriceanu** [comment]
I have managed to Transfer in the end and got my node running again. However, in the process I have lost 250 ERV's. I would really appreciate if that can be refunded.  The issue was related to the certbot which seem to fail after too many attempts to install. I have had to rename my host in order to reinstall and register the host correctly. 



Many thanks.

**Comment by chalith** [comment]
Hope you received the refund.
Transactions:
1BFF1403E03F96D750DF950CEBBC456A71B88B2FA780EBC977C1D5805F360C11
ADCE69A206506D9EC81BDF0BE3A11158B1BB5A9A7B1635334318D957F5323A55

**Comment by cbistriceanu** [comment]
Many thanks Chalith! All good and thanks for the refund
