### ISSUE TITLE
Invalid Path after "Host Already Registered Error”

### ISSUE THREAD

**Issue by forevernode** [EvernodeXRPL/evernode-host#202]
I had "Host Already Registered Error” After a Reinstall
so I ran this script:
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer
and put my public key & secret key
but it said "Invaild Path" 
I checked my public & secret key several times if they are correct..
How can I fix this problem? thank you!

**Comment by EpicShah** [comment]
you need to run proper permission to the secret key path
sounds like you uninstalled everything, maybe the reason for the installer to not being able to find your secret key path, you should have run the transfer command and then install command.

**Comment by chalith** [comment]
@forevernode you can refer to this for setting your secret key https://github.com/EvernodeXRPL/evernode-host/issues/223#issuecomment-1905323601

**Comment by forevernode** [comment]
root@EVRCH4:~# /home/sashimbxrpl/.evernode-host/.host-account-secret.key
-bash: /home/sashimbxrpl/.evernode-host/.host-account-secret.key: Permission denied
I tried and it said "permission denied" how can I get refund my 500EVR??

**Comment by chalith** [comment]
In transfer process when you are asked for secret path dod you provide `/home/sashimbxrpl/.evernode-host/.host-account-secret.key` as input. If you you should do that. And also if this not works can you send your host address.

**Comment by BimsaraFernando** [comment]
Hi @forevernode ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
