### ISSUE TITLE
Do not recognize HOST

### ISSUE THREAD

**Issue by Petros9004** [EvernodeXRPL/evernode-host#205]
I registered by paying 500ever, but the HOST is not recognized.

I tried trasfer and reinstalled "N", but both show up as unregistered HOST.

![호스트에러](https://github.com/EvernodeXRPL/evernode-host/assets/157224286/112d9046-2876-4c3c-8a97-efff6c44feec)

**Comment by Petros9004** [comment]
I rebooted my VPS.

it still doesn't recognize HOST.

I think NFT is something wrong.

this is my address.

rGMeebVayx5RYR5J1QxpBi5qzpxTQTRKC

**Comment by Petros9004** [comment]
I figuted it out. thx.

**Comment by EpicShah** [comment]
what was the issue? Evernode has also acknowledged this issue and working on it. The hosts become inactive

**Comment by EpicShah** [comment]
what exactly did you figure out, share thanks

**Comment by chalith** [comment]
@Petros9004 shall I close the issue if it's resolved?

**Comment by Petros9004** [comment]
네이버 메일 앱에서 보냈습니다.
날짜: 2024.01.23 오후 03:20:13 (GMT+09:00)
제목: Re: [EvernodeXRPL/evernode-host] Do not recognize HOST (Issue #205)

@Petros9004 shall I close the issue if it's resolved?
