### ISSUE TITLE
Inactive host >> Transfer >>Failed installation

### ISSUE THREAD

**Issue by EpicShah** [EvernodeXRPL/evernode-host#206]
Hi there have you found any solution to this issue yet, the hosts become inactive randomly and don't start on their own! That is lost rewards for the host nodes. Can you guys please find a fix for this. @ of my nodes are not running (not producing any heartbeats).

Evernode has acknowledged this issue on X.
![ever1](https://github.com/EvernodeXRPL/evernode-host/assets/123892683/08215d99-fb14-450c-906a-634a5fad7a3f)
![ever2](https://github.com/EvernodeXRPL/evernode-host/assets/123892683/e7ee8f8e-3e9a-4512-8153-d5433a69e9d6)

**Comment by chalith** [comment]
@EpicShah is your host still inactive?

**Comment by EpicShah** [comment]
it is not getting installed, it was active and i tried to install after transfer

**Comment by chalith** [comment]
Is this related to issue https://github.com/EvernodeXRPL/evernode-host/issues/210

**Comment by BimsaraFernando** [comment]
Hi @EpicShah   ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
