### ISSUE TITLE
Errors during installation - please refund

### ISSUE THREAD

**Issue by samreid11** [EvernodeXRPL/evernode-host#207]
Just got this error: 

There was an error during installation. Please provide the file /tmp/evernode/installer-1705880291.log to Evernode team. 

Tried to fix with info from Discord and now it is saying:

Now saying this when accessing the host despite already sending 500 EVR: The account needs minimum balance of 500 EVR. Current balance is 0 EVR.

**Comment by chalith** [comment]
Can you attach the file in this location `/tmp/evernode/installer-1705880291.log`

**Comment by samreid11** [comment]
How do I find the file? I'm new to this VPS process and using Racknerd

**Comment by samreid11** [comment]
Please guide me on how to find this file or just refund the EVR and I'll go on my way. This has been a nightmare

**Comment by samreid11** [comment]
is anyone there please?

**Comment by samreid11** [comment]
Here are the 2 affected host addresses, please refund the EVR to my wallet that I sent the EVR from

rwMpeEJRm6UazfvcS7mZQhHjrW3vYKFXjD
rL2hZZeET9rhWdCcERMq1FeAJhnA36gQcN

**Comment by chalith** [comment]
For rwMpeEJRm6UazfvcS7mZQhHjrW3vYKFXjD, Your token is ready to be claimed in the registration account. Can you try this solution https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923

**Comment by chalith** [comment]
For rL2hZZeET9rhWdCcERMq1FeAJhnA36gQcN you have tried transferring but the installation failed again. Am I right?

You can ssh into the VM and then run `cat /tmp/evernode/installer-1705880291.log` and then post the output here.

**Comment by samreid11** [comment]
Just tried both fixes again and both times it says host is not registered. I dont know how to SSH and view the log and I dont have any more time to waste on this, it has been a mental battle and huge waste of like 10 hours. Please refund both accounts

**Comment by samreid11** [comment]
Tried again and both say host is not registered

**Comment by samreid11** [comment]
[log1.txt](https://github.com/EvernodeXRPL/evernode-host/files/14030787/log1.txt)
Here is the log for rwMpeEJRm6UazfvcS7mZQhHjrW3vYKFXjD

**Comment by samreid11** [comment]
I was expecting to wake up to an update now that i have sent you the log, It has been over 24 hours, please reply with a fix or send refunds

**Comment by chalith** [comment]
![image](https://github.com/EvernodeXRPL/evernode-host/assets/14144162/f5846b51-d20b-4fdc-be34-d088298e2f74)
Did you try this fix for rwMpeEJRm6UazfvcS7mZQhHjrW3vYKFXjD?
First you should download the file and extract and run the command, Then transfer and then install again

**Comment by chalith** [comment]
And check this more detailed solution as well https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902611178

**Comment by samreid11** [comment]
I have no time or energy to try anything further. Please contact me when the deregister function is working so I can get my tokens back

**Comment by samreid11** [comment]
Any update on the deregister function please?

**Comment by samreid11** [comment]
please reply, this is starting to get a little ridiculous

**Comment by samreid11** [comment]
I have 1 working nodes, 2 failed, I want to exit this project it has been a nightmare. I just need clear step by step instructions on how to get out please

**Comment by BimsaraFernando** [comment]
Please follow the latest installation steps in the documentation
https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation. 
https://docs.evernode.org/en/latest/hosts/maintenance.html
The installation issue should be fixed by now.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
