### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by deanlzook** [EvernodeXRPL/evernode-host#208]
the install failed, I tried the transfer method but it shows not registered to transfer. When I try to reinstall it doesn't work either.

Specify the Xahau account address: rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X
Checking account rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X...
The account needs minimum balance of 500 EVR. Current balance is 2 EVR

I put a few extra EVR but it doesn't seems to recognize the 500 that was paid.

Evernode dashboard shows the 500 registration fee. as does the explorer

Registration Token Id	C233478BEB0EC5D33C40B95B57589C094725B8BA1F9511B83CBC6CD9DBA6AE50
Host Email	evernodenet@snitzcreek.com
Instances	
To Let	Leased	Total
6	0	6
CPU Model	
Intel(R) Xeon(R) CPU E5-2695 v4 2.10GHz, 2099 MHz, 4 cores
Instance Size	
13.33% CPU, 0.96GB RAM, 12.03GB Disk
Last Heartbeat Index	0
Registered on Xahau Ledger	2380249
Registration Fee	500
Version	0.0.0
Registered on Timestamp	1705881101
Accumulated Reward Amount	0
Last Vote Timestamp	0
Host Reputation	200

the explorer doesn't show any NFT or ability to buy

not sure what the next step should be.

**Comment by deanlzook** [comment]
This is how I got my install to finish after it had failed as described above. 

I moved 500 additional Evers to the XAH address of the machine and the install completed with the additional 500 EVR.
 
The 500 EVR now shows as a balance in said account and I can move the tokens back to my originating wallet address from within Xaman.

You will first need to have imported the failed node XAH address into your Xaman wallet with the secret key

I didn't have a clean install yet. In my first failed install the transfer method worked and the next time I ran the install script it went mostly smooth.

One shouldn't need to use an additional 500 Evers just to get this done but the nice thing I had some extra in my wallet and at the end of the day no EVR was "lost" and the node is running.

This was the point in the install script where I added more EVR to the address. Reason I had 2 EVR was I originally sent 502 when I ran the install the first time. If I had sent only 500 when I installed it would have shown current balance 0 EVR

Specify the Xahau account address: rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X
Checking account rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X...
The account needs minimum balance of 500 EVR. Current balance is 2 EVR.

>>>> At this point in the install I was stuck so I used Xaman wallet  to transfer 500 EVR to the rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X account ,after I pasted the account address at the prompt the next time it saw the extra EVR and the install finished.

Specify the Xahau account address: rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X
Checking account rEDkGRFLmPUkNzjtGB6SiB62iDtFL33d3X...
Specify the path of the Host Account secret: /home/sashimbxrpl/.evernode-host/.host-account-secret.key
Checking account keys...

the install finished after this. My balance shows 500 EVR which I can leave in the wallet or move back to the origination wallet.

**Comment by chalith** [comment]
Has everything worked out? Shall I close the issue?

**Comment by deanlzook** [comment]
Yes, each of the problems i experienced were resolved and are running. Thanks. I listed how it was resolved. Sent from my iPhoneOn Jan 23, 2024, at 1:12 AM, Chalith Desaman ***@***.***> wrote:﻿
Has everything worked out? Shall I close the issue?
