### ISSUE TITLE
Inactive host -> Transfer -> Failed installation 

### ISSUE THREAD

**Issue by CallDrop** [EvernodeXRPL/evernode-host#209]
The host has been running for over 5 days with no issues.
Became inactive yesterday as the heartbeats were not going through.
followed the instructions to "transfer" using this command:
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

Then proceeded to install once the transfer was successfull:
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

I go through the whole installation process without any issues until the very end when I get this error:

> Downloading setup support files...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  880k  100  880k    0     0   526k      0  0:00:01  0:00:01 --:--:--  783k
> Done.
> 
> Setting up letsencrypt certbot
> Installing docker packages
> Configuring host Xahau account
> Configuring Sashimono services
> Configuring Xahau message board service
> Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
> There was an error during installation. Please provide the file /tmp/evernode/installer-1705888299.log to Evernode team. Thank you.

the error in the log file is as such:

> Installed Evernode Xahau message board.
> Registering host on Evernode...
> STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
> Executing register with params: IN 800000 1615040 1677680 35740960 3                 DO-Regular 1 1996 dubai.evernode@gmail.com _
> Registering host...
> Burning unsold URITokens related to the previous leases.
> sell offer
> Transaction result: tesSUCCESS
> Waiting for the sell offer A181C77FC0A2D16C17C07C16272E92565149DA499D514714C452A437BFA6CA09
> Accepting the sell offer..
> The latest ledger sequence 2382555 is greater than the transaction's LastLedgerSequence (2382554).
> Preliminary result: {
>   "id": 42,
>   "result": {
>     "accepted": true,
>     "account_sequence_available": 758620739,
>     "account_sequence_next": 758620739,
>     "applied": true,
>     "broadcast": true,
>     "engine_result": "tesSUCCESS",
>     "engine_result_code": 0,
>     "engine_result_message": "The transaction was applied. Only final in a validated ledger.",
>     "kept": true,
>     "open_ledger_cost": "12106",
>     "queued": false,
>     "tx_blob": "12002F2100005359242D37A242201B00245ADA5024BEA518B9FB52798EAD68FF03AADB1A06293C50E69C19D2F0091F6B32E8F85727614000000000000001684000000000002F4A73210200CA23B6B8F1DA9D4F57FEBEDF626D55D0007620BC12E0E50445413140CCE9FE744730450221009C92DE7D6A54556BB898E253AF04F51FF3D6571DBE012E70EE2F890096F3430A022033870C1D59E7856FDE1C71CCB08A94B19D202BD9A52F89D3B939D01A7912F40A81143815B929B8CFC4A803830AEC638716A420E8DBEF",
>     "tx_json": {
>       "Account": "rafY1azgVHvLadMkkVMvybau4JMS8VVyND",
>       "Amount": "1",
>       "Fee": "12106",
>       "LastLedgerSequence": 2382554,
>       "NetworkID": 21337,
>       "Sequence": 758620738,
>       "SigningPubKey": "0200CA23B6B8F1DA9D4F57FEBEDF626D55D0007620BC12E0E50445413140CCE9FE",
>       "TransactionType": "URITokenBuy",
>       "TxnSignature": "30450221009C92DE7D6A54556BB898E253AF04F51FF3D6571DBE012E70EE2F890096F3430A022033870C1D59E7856FDE1C71CCB08A94B19D202BD9A52F89D3B939D01A7912F40A",
>       "URITokenID": "BEA518B9FB52798EAD68FF03AADB1A06293C50E69C19D2F0091F6B32E8F85727",
>       "hash": "FDF4E73359965B1C8895B3A96FF23CC929CA0CF654204BBE32B4DE75E0AE146E"
>     },
>     "validated_ledger_index": 2382544
>   },
>   "type": "response"
> }
> Evernode Xahau message board exiting with error.
> REG_FAILURE
> Rolling back sashimono installation.

have been trying this for almost 12 hours now ... really do not know what to do next, need help

**Comment by CallDrop** [comment]
The NFT:

<img width="779" alt="Screenshot 2024-01-22 at 6 15 32 AM" src="https://github.com/EvernodeXRPL/evernode-host/assets/157332516/23cbc87d-ecc3-4213-95bc-0c5a2a3a42b9">

**Comment by EpicShah** [comment]
having the same issue, this team is too overwhelmed to respond, losing on rewards!

**Comment by CallDrop** [comment]
I kept on trying ... and finally the installation went through successfully ...
I believe, and I might be mistaken, I could have been due to high network traffic, now that things are a bit "calmer", the request went through and the host registered.
however ... the host is now in an "inactive" state ...
I will keep an eye on it and update this section accordingly.

**Update, the heartbeat got sent 30 minutes after the registration happened. Then got the next heartbeat an hour after that ... so everything looks like its back on track.**

**Comment by EpicShah** [comment]
awesome man

**Comment by chalith** [comment]
@CallDrop hope your issue is fixed now. Shall I close the issue?

**Comment by CallDrop** [comment]
@chalith 
Yes, the issue is resolved and we can close it.
Thank you Chalith and the whole evernode team for all the amazing work done !
