### ISSUE TITLE
500evr Taken but no working host. Can Any One HELP?

### ISSUE THREAD

**Issue by EvernodeSoz** [EvernodeXRPL/evernode-host#211]
500evr registration fee taken but installation failed and rolled back right at the end. 
No tmp log file. that also disappeared after reboot.
When trying to reinstall it stops and waits at the 500evr check. 

I've tried to follow some of the community's solutions but none work for me or are out of me depth of following.
Can someone guide me through this. I don't particularly want to pump in 500 more evrs with the chance of loosing 500 more.
I quite like the method of buying 500 for a minimal amount of Xah, but couldn't quite follow it.

Can Any One HELP?

**Comment by ariellozanod** [comment]
Did you check the transaction in the Xahau Network (Miannet)
Go here: https://xahau.xrpl.org/ and search the transactions with your host address.
Maybe, this is not going to solve the problem but at least you will have the evidence of the 500 EVRs transaction
-Good luck !

**Comment by EvernodeSoz** [comment]
checked it at 
https://xahauexplorer.com/ 
and yes 500 EVRs were taken as fee.

**Comment by ariellozanod** [comment]
I am in the same way

**Comment by chalith** [comment]
@EvernodeSoz can you send your host r address?

**Comment by EvernodeSoz** [comment]
raF5GWYjW8U2XbDj6qZbSiwRmy7JBT1Zn

**Comment by EvernodeSoz** [comment]
A call out to the Evernode coders. 
This seems to be a common issue. Maybe a tweak to the installation code to check if the 500 EVR registration fee has already been deducted.

**Comment by ariellozanod** [comment]
> @EvernodeSoz can you send your host r address?

@chalith hi bro: I am in the same situation (very worry about the EVRs lost): My host r address is rDG7CnZHHSjRGNMPBWHu2DshwcBhwCTixZ

![2024-01-22_12-44-07](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/27acb1df-736c-42f2-9c3d-b068b41667a6)

I take this screenshot from Xahau Mainnet to check if the transaction was applied and it was. Even, I guess that's the reason that host appears registered. But I don't know why the EVRs are in  **0** 

![2024-01-22_12-47-02](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/00ef083e-9a68-4c4a-9d93-28e986b4376d)

![2024-01-22_12-52-17](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/f65525ba-68b5-489e-801e-933412f43392)

Thank your for time @chalith  !

**Comment by ariellozanod** [comment]
When I check Payment details on Xahau Mainnet as you can see in this image below, to the left we got a success install process that finish with URITOKENs SUCCESS, meanwhile, to the right we got only two URITOKENs SUCCESS and the rest are failed starting with the **URITOKENMINT** step.

I guess the trouble is near of this step during the Install Process.

![2024-01-22_13-33-54](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/843718ea-bbe3-44e9-998f-41a47fa38ec4)

- - - - - - - - - - - - - -
How we can access to Evernode CLI ?

Thank you @chalith

**Comment by chalith** [comment]
@ariellozanod did you sort it out? Seems your host is up and running

**Comment by chalith** [comment]
@EvernodeSoz Can you check the address you sent raF5GWYjW8U2XbDj6qZbSiwRmy7JBT1Zn. Seems it's invalid. Meanwhile can you try if this works https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923

**Comment by EvernodeSoz** [comment]
> @EvernodeSoz Can you check the address you sent raF5GWYjW8U2XbDj6qZbSiwRmy7JBT1Zn. Seems it's invalid. Meanwhile can you try if this works [#144 (comment)](https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923)

Something is very wrong.
The address is correct. I have a snapshot of the 500EVRs reg fee,
![reg fee transaction](https://github.com/EvernodeXRPL/evernode-host/assets/157209397/c29bd451-9f69-4aba-922c-eeb3cd412d5d)
and I can view the account in my Xumm wallet.

But your right. I keep getting unknown account when I run the node index.js and transfer routines.
![node index](https://github.com/EvernodeXRPL/evernode-host/assets/157209397/cae644e1-94dd-4357-8dae-44559db409de)

and also syntax errors in the install routine with no address displaying.
![install syntax errors](https://github.com/EvernodeXRPL/evernode-host/assets/157209397/8c7f7d6f-7627-4a3a-84fd-368cd4b656a4)

somehow between installing and transferring things got screwed.

**Comment by suntree19** [comment]
Same error.
Account address: rMtcL4otcaGYHYmRqAVNxGoWpbRwh3PbRs
help me
