### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by ggarijoon** [EvernodeXRPL/evernode-host#212]
[err.txt](https://github.com/EvernodeXRPL/evernode-host/files/14006815/err.txt)

Installation stopped due to an error during installation after sending 500 evr.

After that, it is not installed even if it is as below

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

**Comment by chalith** [comment]
@ggarijoon looks like your registration token isn't automatically claimed. Can you try this solution https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923

**Comment by ggarijoon** [comment]
I don't know how to find the clamp-reg-token.zip

**Comment by ggarijoon** [comment]
I don't know what the reason is, but it's been solved
Thank you!

**Comment by chalith** [comment]
Nice! shall I close the issue now?
