### ISSUE TITLE
Please tell me how to register a key.

### ISSUE THREAD

**Issue by shinho75** [EvernodeXRPL/evernode-host#213]
Issue #2 - You’ve Paid the 500 $EVR & 17.6 $XAH but messed up the Install or closed it before it could complete

Specify the Xahau account address: rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc
Checking account rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc...
Specify the path of the Host Account secret: /home/sashimbxrpl/.evernode-host/.host-account-secret.key
Invalid Path.

xumm registered as family seed

**Comment by chalith** [comment]
Can you try this https://github.com/EvernodeXRPL/evernode-host/issues/223#issuecomment-1905323601

**Comment by shinho75** [comment]
Thank you. I've worked it out

**Comment by chalith** [comment]
Closing the issue since now resolved!
