### ISSUE TITLE
please..help me.

### ISSUE THREAD

**Issue by shinho75** [EvernodeXRPL/evernode-host#214]
2 errors out of 6 installations. 

1. rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc(xumm registered as family seed)   
   There was an error during installation. There is no key folder during reinstallation, and installation cannot be done just because it is not registered on the host.

2. rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc(xumm registered as family seed)
   There was an error during installation. When reinstalling, the installation will not work because there is no 500 evr.

**Comment by chalith** [comment]
rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc is up and running? What's the second address?

**Comment by shinho75** [comment]
Thank you. I've worked it out

**Comment by chalith** [comment]
Closing the issue since now resolved!
