### ISSUE TITLE
Lost 500 EVR during instalation of host

### ISSUE THREAD

**Issue by an9218** [EvernodeXRPL/evernode-host#215]
I get error during instalation, but 500 EVR didn't returned. And I can't continue instalation without EVRs. 
ID: F0694C9689FCD5AF19801F1644285BDB4EC8B6D2A54C42907D03045A4872157D

**Comment by chalith** [comment]
Your registration token is in the registry account waiting to be claimed. Can you try this solution https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923

**Comment by an9218** [comment]
it's works. Problem resolved!
