### ISSUE TITLE
ENCOUNTER A ERROR DURING INTALLATION PLEASE HELP

### ISSUE THREAD

**Issue by jojoevernodes** [EvernodeXRPL/evernode-host#217]
Setting up letsencrypt certbot
There was an error during installation. Please provide the file /tmp/evernode/installer-1705929051.log to Evernode team. Thank you.
root@vmi1616776:~# client_loop: send disconnect: Connection reset

C:\WINDOWS\system32>/home/sashimbxrpl/.evernode-host/.host-account-secret.keySetting up letsencrypt certbot
The system cannot find the path specified.

C:\WINDOWS\system32>There was an error during installation. Please provide the file /tmp/evernode/installer-1705929051.log to Evernode team. Thank you.
'There' is not recognized as an internal or external command,
operable program or batch file.

C:\WINDOWS\system32>root@vmi1616776:~# client_loop: send disconnect: Connection resetSetting up letsencrypt certbot
The filename, directory name, or volume label syntax is incorrect.

C:\WINDOWS\system32>There was an error during installation. Please provide the file /tmp/evernode/installer-1705929051.log to Evernode team. Thank you.
'There' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chalith** [comment]
Can you run `cat /tmp/evernode/installer-1705929051.log` inside your VM and put the logs here.

**Comment by jojoevernodes** [comment]
> Can you run `cat /tmp/evernode/installer-1705929051.log` inside your VM and put the logs here.

here's the log 
--Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://asi-fs-d.contabo.net/ubuntu focal InRelease
Hit:2 http://asi-fs-d.contabo.net/ubuntu focal-updates InRelease
Hit:3 http://asi-fs-d.contabo.net/ubuntu focal-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-62 linux-headers-5.4.0-62-generic
  linux-image-5.4.0-62-generic linux-modules-5.4.0-62-generic
  linux-modules-extra-5.4.0-62-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libtirpc-common libtirpc3 quota
  uidmap
0 upgraded, 8 newly installed, 1 to remove and 0 not upgraded.
Need to get 574 kB of archives.
After this operation, 2693 kB of additional disk space will be used.
Get:1 http://asi-fs-d.contabo.net/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://asi-fs-d.contabo.net/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://asi-fs-d.contabo.net/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:4 http://asi-fs-d.contabo.net/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:5 http://asi-fs-d.contabo.net/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:6 http://asi-fs-d.contabo.net/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:7 http://asi-fs-d.contabo.net/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:8 http://asi-fs-d.contabo.net/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 574 kB in 0s (5245 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 142683 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 142691 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 142681 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../1-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../2-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../3-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../4-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../5-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../6-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for systemd (245.4-4ubuntu3.22) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-169-generic
Adding br_netfilter
STAGE Installing snapd
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  linux-headers-5.4.0-62 linux-headers-5.4.0-62-generic
  linux-image-5.4.0-62-generic linux-modules-5.4.0-62-generic
  linux-modules-extra-5.4.0-62-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  dbus-user-session liblzo2-2 squashfs-tools
Suggested packages:
  zenity | kdialog
The following NEW packages will be installed:
  dbus-user-session liblzo2-2 snapd squashfs-tools
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 38.1 MB of archives.
After this operation, 172 MB of additional disk space will be used.
Get:1 http://asi-fs-d.contabo.net/ubuntu focal-updates/main amd64 dbus-user-session amd64 1.12.16-2ubuntu2.3 [9424 B]
Get:2 http://asi-fs-d.contabo.net/ubuntu focal/main amd64 liblzo2-2 amd64 2.10-2 [50.8 kB]
Get:3 http://asi-fs-d.contabo.net/ubuntu focal-updates/main amd64 squashfs-tools amd64 1:4.4-1ubuntu0.3 [117 kB]
Get:4 http://asi-fs-d.contabo.net/ubuntu focal-updates/main amd64 snapd amd64 2.58+20.04.1 [37.9 MB]
Fetched 38.1 MB in 2s (23.1 MB/s)
Selecting previously unselected package dbus-user-session.
(Reading database ... 142827 files and directories currently installed.)
Preparing to unpack .../dbus-user-session_1.12.16-2ubuntu2.3_amd64.deb ...
Unpacking dbus-user-session (1.12.16-2ubuntu2.3) ...
Selecting previously unselected package liblzo2-2:amd64.
Preparing to unpack .../liblzo2-2_2.10-2_amd64.deb ...
Unpacking liblzo2-2:amd64 (2.10-2) ...
Selecting previously unselected package squashfs-tools.
Preparing to unpack .../squashfs-tools_1%3a4.4-1ubuntu0.3_amd64.deb ...
Unpacking squashfs-tools (1:4.4-1ubuntu0.3) ...
Selecting previously unselected package snapd.
Preparing to unpack .../snapd_2.58+20.04.1_amd64.deb ...
Unpacking snapd (2.58+20.04.1) ...
Setting up liblzo2-2:amd64 (2.10-2) ...
Setting up dbus-user-session (1.12.16-2ubuntu2.3) ...
Setting up squashfs-tools (1:4.4-1ubuntu0.3) ...
Setting up snapd (2.58+20.04.1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.aa-prompt-listener.service → /lib/systemd/system/snapd.aa-prompt-listener.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.apparmor.service → /lib/systemd/system/snapd.apparmor.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.autoimport.service → /lib/systemd/system/snapd.autoimport.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.core-fixup.service → /lib/systemd/system/snapd.core-fixup.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.recovery-chooser-trigger.service → /lib/systemd/system/snapd.recovery-chooser-trigger.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.service.
Created symlink /etc/systemd/system/cloud-final.service.wants/snapd.seeded.service → /lib/systemd/system/snapd.seeded.service.
Created symlink /etc/systemd/system/multi-user.target.wants/snapd.service → /lib/systemd/system/snapd.service.
Created symlink /etc/systemd/system/timers.target.wants/snapd.snap-repair.timer → /lib/systemd/system/snapd.snap-repair.timer.
Created symlink /etc/systemd/system/sockets.target.wants/snapd.socket → /lib/systemd/system/snapd.socket.
Created symlink /etc/systemd/system/final.target.wants/snapd.system-shutdown.service → /lib/systemd/system/snapd.system-shutdown.service.
snapd.failure.service is a disabled or a static unit, not starting it.
snapd.mounts-pre.target is a disabled or a static unit, not starting it.
snapd.mounts.target is a disabled or a static unit, not starting it.
snapd.snap-repair.service is a disabled or a static unit, not starting it.
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
STAGE Configuring fstab
Updated fstab.
/dev/sda3 [/]: group quotas turned on
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
2024-01-22T14:11:49+01:00 INFO Waiting for automatic snapd restart...
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Requested name 84.247.181.36 is an IP address. The Let's Encrypt certificate authority will not issue certificates for a bare IP address.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /tmp/certbot-log-tpeja2nx/log or re-run Certbot with -v for more details.
Error when setting up letsencrypt SSL certificate.
Rolling back sashimono installation.
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
rm: cannot remove '/usr/bin/sashi': No such file or directory
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Deleting message board user...
Deleting binaries...
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
root@vmi1616776:~#

**Comment by jojoevernodes** [comment]
> Can you run `cat /tmp/evernode/installer-1705929051.log` inside your VM and put the logs here.

hello sir good day please review the log i really need your help

**Comment by chalith** [comment]
@jojoevernodes is this the same issue? https://github.com/EvernodeXRPL/evernode-host/issues/246

**Comment by jojoevernodes** [comment]
> @jojoevernodes is this the same issue? #246

yes sir

**Comment by BimsaraFernando** [comment]
Did you manage to resolve this issue? If not please reopen the issue.
