### ISSUE TITLE
is inactive host transfer the solution or wait for an update ? thanks 

### ISSUE THREAD

**Issue by Franklyn7878** [EvernodeXRPL/evernode-host#218]

**Comment by EpicShah** [comment]
these inactive hosts are pain in the ass, im regretting messing with inactive host. I think the best approach is to not tinker with it.

**Comment by chalith** [comment]
You should transfer and install if your host is inactive

**Comment by BimsaraFernando** [comment]
@Franklyn7878 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
