### ISSUE TITLE
You can't transfer or reinstall because you don't have 500 evr.

### ISSUE THREAD

**Issue by shinho75** [EvernodeXRPL/evernode-host#219]
Specify the Xahau account address: rK3rj3QX1dLa8WQmYp6b7dA9khGYVnjGc4
Checking account rK3rj3QX1dLa8WQmYp6b7dA9khGYVnjGc4...
The account needs minimum balance of 500 EVR. Current balance is 0.99999999 EVR.

You can't transfer or reinstall because you don't have 500 evr.

**Comment by evernodeau** [comment]
I have the same issue, I looked at the steps [here](https://github.com/EvernodeXRPL/evernode-host/issues/180), unfortunately my registry NFT is burnt. my account is = rU3KjDa8kG8HsF2MR9fvx95tkoEHhd6R4k

**Comment by evernodeau** [comment]
Fixed it, I had to purchase the NFT with the same wallet, now it's working. check out --> https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902611178

**Comment by chalith** [comment]
@shinho75 Did you resolve the issue? It seems rK3rj3QX1dLa8WQmYp6b7dA9khGYVnjGc4 is up and running. Can you close the issue if everything's ok?

**Comment by BimsaraFernando** [comment]
Hi @shinho75 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
