### ISSUE TITLE
My installation stalled at Registering host on Evernote registry.... Please help.

### ISSUE THREAD

**Issue by XRPSonic** [EvernodeXRPL/evernode-host#221]
**During the installation process,**

_Setup will now begin the installation. Continue? [Y/n]y

Starting installation...
Installing other prerequisites...
Installing dependencies
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0  2700k      0 --:--:-- --:--:-- --:--:-- 2700k
Done.

Setting up letsencrypt certbot
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
There was an error during installation. Please provide the file /tmp/evernode/installer-1705940793.log to Evernode team. Thank you._

It stopped while registering my host.
Here's my documentation down below.

 GNU nano 4.8              /tmp/evernode/installer-1705940793.log                        
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:3 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease
Hit:5 http://us.archive.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.4).
The following packages were automatically installed and are no longer required:
  eatmydata libeatmydata1 python3-importlib-metadata python3-jinja2
  python3-json-pointer python3-jsonpatch python3-jsonschema python3-markupsafe
  python3-more-itertools python3-pyrsistent python3-zipp
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 285 not upgraded.
STAGE Configuring fstab
fstab already configured.
STAGE Configuring fuse
Fuse config already updated.
STAGE Configuring cgroup rules engine
STAGE Configuring grub
Grub already configured.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for evers05.mainnode.net

**Comment by evernodeau** [comment]
Same happened wit h 2 of my nodes, it maybe a network overload issue?

**Comment by chalith** [comment]
Yes this could be. Can you send us the full log file? Did the registration transaction go through with 500EVRs? If not can you retry.

**Comment by evernodeau** [comment]
I've resolved it
