### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by shinho75** [EvernodeXRPL/evernode-host#223]
root@chicago3evr:~# /home/sashimbxrpl/.evernode-host/.host-account-secret.key
-bash: /home/sashimbxrpl/.evernode-host/.host-account-secret.key: No such file or directory

Specify the Xahau account address: rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc
Checking account rhUaqGHAamhiB4JwcTiXifGdNPMB4rnofc...
Specify the path of the Host Account secret: /home/sashimbxrpl/.evernode-host/.host-account-secret.key
Invalid Path.

i have family seed
Please tell me how to install as a family seed instead of Specify the path to a host account secret.

**Comment by chalith** [comment]
Create a file in `/home/sashimbxrpl/.evernode-host/.host-account-secret.key` or any place you prefer with the following content.
```
{ "xrpl": { "secret": "<family-seed>" } }
```
Replace with your family seed

**Comment by shinho75** [comment]
Thank you. I've worked it out

**Comment by chalith** [comment]
Nice to hear, Closing the issue since resolved!
