### ISSUE TITLE
install error(deposit completed

### ISSUE THREAD

**Issue by cOoNni** [EvernodeXRPL/evernode-host#225]
end of installation step
on the QR code screen
after deposing evr and xah.
but, i watch the error message,
there was a message to ask the staff

i couldn't take a screenshot..

my acccount is  rnRwRqH9Lv7Swy7kpXkHm2ieExB1SJ7v6U
please, help me

**Comment by cOoNni** [comment]
i don't know secret key.
how do i get the command to reset the secret key.

**Comment by chalith** [comment]
@cOoNni you can see your secret key by `cat /home/sashimbxrpl/.evernode-host/.host-account-secret.key`
Then try this to install again https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration

**Comment by BimsaraFernando** [comment]
Hi @cOoNni ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
