### ISSUE TITLE
Withdraw $EVR tokens from host account address.

### ISSUE THREAD

**Issue by ay432** [EvernodeXRPL/evernode-host#226]
Hello, could you please confirm when it will be possible to withdraw $EVR tokens from host account address, or how I can transfer $EVR from host address to Xaman address.

**Comment by jellicoe** [comment]
one easy way is to set the regular key for you node to a xaman xrp address that can sign transactions for your node 

in the terminal on the evernode server type in 

>evernode regkey set rAddressofWalletyouControlInXaman

then in xaman

add the rAddress of the node as an existing read only wallet

then the address you control in Xaman can now sign and send funds for the node - its really easy

**Comment by ay432** [comment]
> one easy way is to set the regular key for you node to a xaman xrp address that can sign transactions for your node
> 
> in the terminal on the evernode server type in
> 
> > evernode regkey set rAddressofWalletyouControlInXaman
> 
> then in xaman
> 
> add the rAddress of the node as an existing read only wallet
> 
> then the address you control in Xaman can now sign and send funds for the node - its really easy

Thank you! Works perfect!

**Comment by chalith** [comment]
Closing since issue is now resolved
