### ISSUE TITLE
new error "tecHOOK_REJECTED"

### ISSUE THREAD

**Issue by XJohnK** [EvernodeXRPL/evernode-host#227]
I got new error during installation.

I still have 500 EVR and XAU.

[installer-1706045728.log](https://github.com/EvernodeXRPL/evernode-host/files/14030145/installer-1706045728.log)

This is the log.

please help me!

**Comment by evernodeau** [comment]
I'm getting the same too

**Comment by chalith** [comment]
@XJohnK @evernodeau are you still getting the error?

**Comment by evernodeau** [comment]
I'm not

**Comment by BimsaraFernando** [comment]
Hi @XJohnK ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
