### ISSUE TITLE
Installation Failed 500 EVR burnt NO NFT

### ISSUE THREAD

**Issue by cHs-crypto** [EvernodeXRPL/evernode-host#229]
Initial Installation Attempt 20 Jan 2024
[installer-1705718234.log](https://github.com/EvernodeXRPL/evernode-host/files/14021316/installer-1705718234.log)

![XUMM wallet Screenshot (evernode ac)](https://github.com/EvernodeXRPL/evernode-host/assets/157472485/5c776272-46aa-4602-ad26-bde46a4d55ce)
![XUMM wallet Screenshot (evernode ac events)](https://github.com/EvernodeXRPL/evernode-host/assets/157472485/192aa4e9-98c5-4848-bf6d-7f735cb00bac)
[terminal log from install(transfer) 24 Jan 2024.txt](https://github.com/EvernodeXRPL/evernode-host/files/14031042/terminal.log.from.install.transfer.24.Jan.2024.txt)

24 Jan 2024
https://xahauexplorer.com/explorer/rhNuVefxuByH79De7MVVeQ3dkEwGC4i6jL

https://xahauexplorer.com/nft/2D2044B2D7A9EEAB05457288CA776A1E34D02084FBA60A2CDAF1A936DEF781C4

**Comment by chalith** [comment]
@cHs-crypto looks like your host is up and running? Is all resolved now? If so shall we close the issue?

**Comment by BimsaraFernando** [comment]
Hi @cHs-crypto ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.

**Comment by cHs-crypto** [comment]
Thanks yes it was fixed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
