### ISSUE TITLE
Ran the re instal using transfer method it fails multiple times

### ISSUE THREAD

**Issue by sojournease** [EvernodeXRPL/evernode-host#230]
I followed the thread showing how to go through the "transfer" reinstall process after I hit the typical error message at end of my instal.

I followed steps, it completed that step then hit thre erro again. So I ran it again as instructed and each time I do this I get to entering the domain and it says domain unreachable. I research and confirm it's the IPV6 that cause that message. So I contact my host and they correct something. I run the entire process again, succeed in round one, go through it again and hit the same issue ast the same spot: Unreachable domain

I can't ask my host again for help without paying for support. Something's going on during this the initial "tranfer" instal that when I go to reinstal the 2nd time the IPV6 is messed up.

Just for the sake of clarifying one step in the initial transfer re-instal - I of course select n to when asked if this is a fresh instal. Then a message if I want the same host to be the same as transferee? (wording is something like that) I have been pressing Y. 
Just thought I'd mention this in case it matters.

Yet I can check the host address and have a token ID and it appears as the node is still registered. But the filed that shows Version number it is blank. 0.0.0

Trying to provide as much info as possible in case it helps.

**Comment by jellicoe** [comment]
Ok so do you have a DNS domain pointing to the IP address of your servers
IP address? What is it?

**Comment by sojournease** [comment]
IP all good and I confirmed that when Ubuntu is rebooted each time it needs new IPV6 settings redone each time. 

So I was able to proceed with proper transfer process.  It did show more lines of info which I saw lead me to the end and the mssage  - you are now ready to instal Evernode on this server

Then began the instal  selected n for not a fresh install continued thru to entering the lease amount and get to this point:

Creating Message-board User...
Specify the Xahau account address: rEaQ8YZR2H4gt1VioyRmqNX6qjDcbNLckR (that's the address I had originally used when reaching the error message leading me to go thorugh this transfer process and re instal)
Checking account rEaQ8YZR2H4gt1VioyRmqNX6qjDcbNLckR...
Host is already registered.
Specify the Xahau account address:

****
So it seems each time I do this It shows as still registered. Yet when doing the transfer install it goes through and completes the de-registration and completes the entire process ready for the full instal.

Groundhog day for me so far. Going in circles. I know I'll figure it out! :) With help, which I greatly appreciate!

**Comment by jellicoe** [comment]
Evernode just put out a tweet

there are some fixes they will implement tonight - these might apply to you

https://twitter.com/EvernodeXRPL/status/1750035646956322844

**Comment by sojournease** [comment]
much appreciates I'll follow it. Seems strange to hit what's happening so best I just wait for a fix. Have you went through this process of having to transfer and then reinstal? Hope not for your sake! Or maybe you did all really smooth...I say with a jealous tone....

**Comment by chalith** [comment]
@sojournease looks like your host is up and running? Shall I close the issue?

**Comment by sojournease** [comment]
Yes, Please do. Thanks for the follow up.
