### ISSUE TITLE
Transaction failed with error terQUEUED

### ISSUE THREAD

**Issue by Kokonat33** [EvernodeXRPL/evernode-host#232]
Hi, I was trying to transfer my host,  when I crate host it was error but it’s took 500ever, I got my seed  and following instructions for reinstalling host and I get another error……. Registering host...
Burning unsold URITokens related to the previous leases.
Transaction failed with error terQUEUED
Evernode Xahau message board exiting with error.
REG_FAILURE

**Comment by CraftLord** [comment]
Possible solution.:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902611178

**Comment by chalith** [comment]
@Kokonat33 did the mentioned solution work for you?

**Comment by BimsaraFernando** [comment]
Hi @Kokonat33 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
