### ISSUE TITLE
Installation failed, 500 EVR already got paid.

### ISSUE THREAD

**Issue by XJohnK** [EvernodeXRPL/evernode-host#234]
After initial installation, 500 EVR was gone, I put command 

```
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer
```

and it says "Host is not registered."

How can I get a refund?

Xahau account address: rNDVG4wcS6EJDhpcBPnFUFCnEMhqqcbspF

![image](https://github.com/EvernodeXRPL/evernode-host/assets/94948536/845c7417-730b-4b44-9827-2ee2e6630491)

![error1](https://github.com/EvernodeXRPL/evernode-host/assets/94948536/21e74b04-8440-40e1-8a61-f92f897c920f)

![error2](https://github.com/EvernodeXRPL/evernode-host/assets/94948536/f57efa55-66f4-4196-bfb0-43c0511a784f)

Please help me

Thank you for your help and effort.

**Comment by Sato-07** [comment]
I have the exact same problem, but I can still see my account on the dashboard. How can I go about fixing it?

**Comment by CraftLord** [comment]
See:
https://github.com/EvernodeXRPL/evernode-host/issues/180#issuecomment-1902611178

and specifically the link to:
https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923

You can fix the registration this way and after that you should be able to transfer again.

**Comment by chalith** [comment]
@XJohnK looks like you have fixed your host. Shall I close the issue?

**Comment by Bitbob589** [comment]
I have the same issue I need help with.

**Comment by Bitbob589** [comment]
> @XJohnK looks like you have fixed your host. Shall I close the issue?

Hey Chalith, with your comment below, How do we execute node index.js, do we open it with visual studio and enter the address in there? 

'Try this, From any machine extract this zip file. Then go inside claim-reg-token directory. And then execute node index.js <address> <secret> replace the address and secret with yours.
[claim-reg-token.zip](https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip)

After that. You'll have to do a transfer: https://docs.evernode.org/en/latest/hosts/maintenance.html

And then install using the same address.

Let us know if there're any issues'

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
