### ISSUE TITLE
letsencrypt certbot

### ISSUE THREAD

**Issue by dankenneth23** [EvernodeXRPL/evernode-host#236]
upon failed registration of host, sashimono uninstaller clean ups and deletes certificates for the registered domain.

letsencrypt implements 5 certificate limit per week and revoking previously issued certificates does not reset the limit.

hence the issue of "too many certificates (5) already issued for this exact set of domains in the last 168 hours" appears after multiple reinstallations.

**Comment by chalith** [comment]
We are working on a fix for this it will be included in our updates
