### ISSUE TITLE
error. REG_FAILURE

### ISSUE THREAD

**Issue by Kokonat33** [EvernodeXRPL/evernode-host#237]
I was  create a host and I get this error:
Evernode Xahau message board exiting with error.
REG_FAILURE

**Comment by chalith** [comment]
Can you provide us with your log file and account address?

**Comment by BimsaraFernando** [comment]
Hi @Kokonat33 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
