### ISSUE TITLE
Hello Everyone,

### ISSUE THREAD

**Issue by ariellozanod** [EvernodeXRPL/evernode-host#238]
Hello Everyone,

We would like to inform you about the recent Sashimono patch update designed to address certain network connectivity issues. To ensure optimal performance and functionality, all hosts are kindly requested to follow the instructions below.

Run the following command to initiate the patch update process for your Message Board bundle.
```
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/patch/sashimono/patches/update-message-board.sh | sudo bash -s
```
The script will automatically restart the Message Board upon the successful completion of the update.

If you encounter any issues or have questions during the patch update process, please reach out to us.

_NOTE: This patch update will not result in any modification to the version number._

Thank you !!!
**The Evernode Team**

_Originally posted by @kithminisg in https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1907979558_

**Comment by ariellozanod** [comment]
Is this necessary ?

There was so much frustration to be able to make the hosts running that now I have a huge fear of running that command on the console. Especially because when something bad happens and we look for help, it either doesn't come, or it takes so long that we make fatal decisions.

**Comment by chalith** [comment]
This is a light update that would only replace one file. This update is necessary for your heartbeat to function without interruption.

**Comment by ariellozanod** [comment]
thank you !
