### ISSUE TITLE
error occurred after paying xah and ever : specify the xahau account address

### ISSUE THREAD

**Issue by hhlink** [EvernodeXRPL/evernode-host#240]
hi,

 i was installing a new node and after the qr appeared i paid xah and ever. but there was an error message before fully installed. 
i've checked my account and  both xah and ever were sent to my new reward xahau account and also checked that i have a secret code for the new node. Then I rebooted, and tried to reinstalled then I've got a message that says "specify the xahau account address: ' 
So I tried both the new account for the reward and my checking account for the ever deposit payment since I don't know what xahau account address it is asking for. and where can I find it? 

can anyone help me how to solve the issue?

**Comment by kithminisg** [comment]
Could you please specify your host's XAHAU r-address?

**Comment by hhlink** [comment]
> Could you please specify your host's XAHAU r-address?

sure! here it is : 

rMa65abjhZ1SuVcjLoL6SiigvrMGLkMPK9

Thanks!

**Comment by kithminisg** [comment]
Your installation is partially completed for the provided one. Do you know if the `evernode` command exists in your machine?

- If not, You can try following the command in a separate machine to transfer your registration. In the transfer, it asks for a transferee (Future owner of your Reg Token). If you do not provide a separate Xahau account as the transferee, it will consider the current registration Xahau account as the transferee.

```
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

```

- Then try the evernode install command to re-install. There you need to choose `migration` as the option in the Setup process. Then you need to specify that transferee address according to your previous action. (If you have not specified a separate transferee, you need to provide the account related to your registration.)

```
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install
```
NOTE : To re-install you need to have 0.00000001 EVRs in your wallet. It would be better if you could note down your account key separately before the above steps.

**Comment by hhlink** [comment]
problem solved!


thank you so much for all of your help!
