### ISSUE TITLE
Reinstallation after installation error “Host is not registered” issue

### ISSUE THREAD

**Issue by suntree19** [EvernodeXRPL/evernode-host#242]
Account address: rMtcL4otcaGYHYmRqAVNxGoWpbRwh3PbRs

I received the secret key

![11](https://github.com/EvernodeXRPL/evernode-host/assets/157563001/b174ba82-0d80-4514-952a-45fe730bbaf9)
![101](https://github.com/EvernodeXRPL/evernode-host/assets/157563001/716f9b4a-e20c-46a3-8aec-b489633b3a56)

NFT minting error
Can I get a refund?

**Comment by chalith** [comment]
Why did you burn your registration URI token? Transaction: D1C71A0498525F4B95E703C2CB35EAD5043AB54970474B1616A3D16A3A55C5F7

**Comment by suntree19** [comment]
I don't know why I did that...
