### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by jino2ac** [EvernodeXRPL/evernode-host#243]
Hello, I am contacting you following a problem on one of my hosts, in fact during the heartbeat problem that there was a few days ago I wanted to set up a node which did not work. My 500evr was debited but I cannot activate the node. I am sending you the screenshot of the transaction. If there is a procedure to activate the node, or start from scratch, please let me know. If you need any other information, do not hesitate to get back to me. Good day

**Comment by jino2ac** [comment]
![Capture d’écran 2024-01-25 à 8 53 32 AM](https://github.com/EvernodeXRPL/evernode-host/assets/157683862/f18aae45-4421-4af0-b913-ad2953dfc57b)

**Comment by jino2ac** [comment]
and same for this one 
![Capture d’écran 2024-01-25 à 8 57 57 AM](https://github.com/EvernodeXRPL/evernode-host/assets/157683862/7aaf5f91-0821-410d-9e6c-01296aae5cec)

**Comment by chalith** [comment]
This might be the solution for you https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923. Try this and reply if it isn't working

**Comment by BimsaraFernando** [comment]
Hi @jino2ac ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
