### ISSUE TITLE
I deleted the secret key file..

### ISSUE THREAD

**Issue by herkimer9** [EvernodeXRPL/evernode-host#244]
I deleted the secret key file(but I have the secret key information) and uninstalled evernode and then I installed it again.

After that there is an 'syntax error' message.

help plz..

**Comment by chalith** [comment]
Probably the secret key file format might be invalid. Try this. https://github.com/EvernodeXRPL/evernode-host/issues/223#issuecomment-1905323601

**Comment by BimsaraFernando** [comment]
Hi @herkimer9 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
