### ISSUE TITLE
Rippled server check error

### ISSUE THREAD

**Issue by an9218** [EvernodeXRPL/evernode-host#245]
During instalation can't pass the checking of wss://xahau.network, also tried xahau.org. Instalation is stuck.

**Comment by chalith** [comment]
This could be due to a failed attempt of dependency download during installation. Can you try removing `/tmp/evernode-setup-helpers`. Command `rm -r /tmp/evernode-setup-helpers`

**Comment by an9218** [comment]
@chalith it doesn't help

**Comment by BimsaraFernando** [comment]
Hi @an9218 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
