### ISSUE TITLE
Multiple failed installations 

### ISSUE THREAD

**Issue by coovxrp** [EvernodeXRPL/evernode-host#248]
we can't retry when theres a ledger # mismatch? lol 
![image](https://github.com/EvernodeXRPL/evernode-host/assets/102495348/b02f8acf-30ef-405e-9ddb-73080de668f7)
re install has to delete all existing leases? wow. and fails to do so even. lol 
![image](https://github.com/EvernodeXRPL/evernode-host/assets/102495348/bbae33c7-e5a1-46a6-805e-23951b8cadb4)

**Comment by chalith** [comment]
This happens when there's a high volume of transactions going on the network. We are working on a fix for this

**Comment by BimsaraFernando** [comment]
Hi @coovxrp ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
