### ISSUE TITLE
IPV6 only setup, github links in install script

### ISSUE THREAD

**Issue by sorud** [EvernodeXRPL/evernode-host#249]
Hello,
afaik github does not support ipv6 hence links in install script don't work in ipv6 only enviroment. It breaks on releases check at api.github.com which points to ipv4 address.

Evernode cli also doesn't work in ipv6 only setup. Host itself looks ok looking only on heartbeats and dashboard status.

Cheers
soru

**Comment by chalith** [comment]
Were you able to install Evernode on your machine?

**Comment by sorud** [comment]
yes, I was able to attach ipv4 interface to that machine for evernode installation purpose only..
