### ISSUE TITLE
failed installation after sending 500 EVRS and 30 XAH

### ISSUE THREAD

**Issue by gt679** [EvernodeXRPL/evernode-host#250]
"please provide the file /tmp/evernode/installer-1706225737.log to evernode team"

how to fix this?

**Comment by chalith** [comment]
Execute `cat /tmp/evernode/installer-1706225737.log` in your VM and send us the output here.

**Comment by gt679** [comment]
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-122-generic x86_64)
 * Documentation:  https://help.ubuntu.com/
 * Management:     https://landscape.canonical.com/
 * Support:        https://ubuntu.com/advantage
  System information as of Fri Jan 26 04:05:32 UTC 2024
  System load:  0.0                Users logged in:       0
  Usage of /:   4.0% of 116.12GB   IPv4 address for eth0: 134.122.44.82
  Memory usage: 10%                IPv4 address for eth0: 10.20.0.7
  Swap usage:   0%                 IPv4 address for eth1: 10.118.0.4
  Processes:    135
79 updates can be applied immediately.
10 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable
New release '22.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

1 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log
*** System restart required ***
Last login: Thu Jan 25 23:17:49 2024 from 198.211.111.194
root@ubuntu-s-2vcpu-4gb-120gb-intel-tor1-01:~# cat /tmp/evernode/installer-1706225737.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://mirrors.digitalocean.com/ubuntu focal InRelease
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:5 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:6 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:7 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
openssl set to manually installed.
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200
  libtirpc-common libtirpc3 quota uidmap
0 upgraded, 10 newly installed, 1 to remove and 75 not upgraded.
Need to get 640 kB of archives.
After this operation, 2936 kB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:5 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-3-200 amd64 3.4.0-1ubuntu0.1 [54.4 kB]
Get:6 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-genl-3-200 amd64 3.4.0-1ubuntu0.1 [11.2 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:8 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:9 http://mirrors.digitalocean.com/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:10 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 640 kB in 0s (2231 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 100243 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.
(Reading database ... 100251 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 100241 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../1-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../2-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libnl-3-200:amd64.
Preparing to unpack .../3-libnl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libnl-genl-3-200:amd64.
Preparing to unpack .../4-libnl-genl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../5-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../6-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../7-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../8-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for systemd (245.4-4ubuntu3.20) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-169-generic
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
quotaon: using //aquota.group on /dev/vda1 [/]: No such process
quotaon: Quota format not supported in kernel.
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for [hashkj.online](http://hashkj.online/)
Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/[hashkj.online/fullchain.pem](http://hashkj.online/fullchain.pem)
Key is saved at:         /etc/letsencrypt/live/[hashkj.online/privkey.pem](http://hashkj.online/privkey.pem)
This certificate expires on 2024-04-24.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-hashkj.online.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: CA 800000 3220800 1677680 93843600 6                 DO-Premium-Intel 2 2494 [3everreal@mail.com](mailto:3everreal@mail.com) _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
The latest ledger sequence 2488330 is greater than the transaction's LastLedgerSequence (2488329).
Preliminary result: {
  "id": 29,
  "result": {
    "accepted": true,
    "account_sequence_available": 759540834,
    "account_sequence_next": 759540834,
    "applied": true,
    "broadcast": true,
    "engine_result": "tesSUCCESS",
    "engine_result_code": 0,
    "engine_result_message": "The transaction was applied. Only final in a validated ledger.",
    "kept": true,
    "open_ledger_cost": "12426",
    "queued": false,
    "tx_blob": "1200002100005359242D45AC61201B0025F80961D511C37937E080000000000000000000000000004556520000000000A3B6B1B61181DB9C81EED4F3D5109F6CFC31109B68400000000000308A732103015FF54FB7908A919AD618440FDE7F9742A57029EDCC25DDDEAB0FC272D8541B7446304402207FBDD4A801A07D9550D1581CF18E0CAE98A86BB0FFAB016AC73BE028769AB55F0220317136914D8A43076D72E89517A53CA91504AFFC4076E79C95A6DACBE1C140818114A5ED569F01318EBA57CB65A0850717B7855257258314087F22F5833A4953C52B3AB781144A2BE5C18F33F9F1F013E017701820455652010000000000000000000000000000000000000000000000000000000270190A65766E486F7374526567E1E0177018204556520100000000000000000000000000000000000000000000000000000003701980434100350C0022130000936E010006000000444F2D5072656D69756D2D496E74656C0000000000000000000000000000000000000000000000000200BE09200000000000000000000000000000000000000000000000000033657665727265616C406D61696C2E636F6D00000000000000000000000000000000000000000000E1F1",
    "tx_json": {
      "Account": "rG3LFDDZJ1GJdSaJNum5ao1aXpYiEivfJQ",
      "Amount": {
        "currency": "EVR",
        "issuer": "rEvernodee8dJLaFsujS6q1EiXvZYmHXr8",
        "value": "500"
      },
      "Destination": "rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH",
      "Fee": "12426",
      "HookParameters": [
        {
          "HookParameter": {
            "HookParameterName": "4556520100000000000000000000000000000000000000000000000000000002",
            "HookParameterValue": "65766E486F7374526567"
          }
        },
        {
          "HookParameter": {
            "HookParameterName": "4556520100000000000000000000000000000000000000000000000000000003",
            "HookParameterValue": "434100350C0022130000936E010006000000444F2D5072656D69756D2D496E74656C0000000000000000000000000000000000000000000000000200BE09200000000000000000000000000000000000000000000000000033657665727265616C406D61696C2E636F6D00000000000000000000000000000000000000000000"
          }
        }
      ],
      "LastLedgerSequence": 2488329,
      "Memos": [],
      "NetworkID": 21337,
      "Sequence": 759540833,
      "SigningPubKey": "03015FF54FB7908A919AD618440FDE7F9742A57029EDCC25DDDEAB0FC272D8541B",
      "TransactionType": "Payment",
      "TxnSignature": "304402207FBDD4A801A07D9550D1581CF18E0CAE98A86BB0FFAB016AC73BE028769AB55F0220317136914D8A43076D72E89517A53CA91504AFFC4076E79C95A6DACBE1C14081",
      "hash": "FD504A0A9FBDD453D9240C524B7F454B5F5FFD99AACBFBAA387A9199FB25F586"
    },
    "validated_ledger_index": 2488320
  },
  "type": "response"
}
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for '[hashkj.online](http://hashkj.online/)'
Deleted all files relating to certificate [hashkj.online](http://hashkj.online/).
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/[hashkj.online/cert.pem](http://hashkj.online/cert.pem).
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
root@ubuntu-s-2vcpu-4gb-120gb-intel-tor1-01:~#

**Comment by gt679** [comment]
Hi,

I sent in Github, would you like me to post here or there?

 

 
 

Sent: Thursday, January 25, 2024 at 7:40 PM

**Comment by gt679** [comment]
Hi I have a question regarding setting up multiple hosts....do I need separate r addresses for each host account or can I send multiple sets of 500 evers and XAH tokens to to the registry hook from same address?

Thanks

 
 

Sent: Thursday, January 25, 2024 at 7:40 PM

**Comment by chalith** [comment]
Hope this solution will help you to fix it https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923
About the second question, No you can't you have to have a separate address for each host

**Comment by gt679** [comment]
Thank you for your help.
regarding second question ; so i understand. Say I am setting up two hosts. My 500 evrs and 30 xah need to come from two different xaman accounts or can they come from the same one?

**Comment by chalith** [comment]
In that case you can fund from the same account

**Comment by gt679** [comment]
thank you

 
 

Sent: Friday, January 26, 2024 at 12:42 AM

**Comment by gt679** [comment]
Hi regarding solution #144(comment) I have a question before doing this;

 

Should I run the javascript from the hosting provider terminal or from my local terminal?

 

 

 
 

Sent: Thursday, January 25, 2024 at 11:16 PM

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
