### ISSUE TITLE
4 Hours no rewards 

### ISSUE THREAD

**Issue by gt679** [EvernodeXRPL/evernode-host#253]
Hi,
Can someone please tell me how to get my rewards and send heartbeats. This is my status page

Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-169-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
 * Management:     https://landscape.canonical.com/
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Jan 26 03:53:31 UTC 2024

  System load:  0.0                Users logged in:       0
  Usage of /:   4.1% of 116.12GB   IPv4 address for eth0: 165.22.236.228
  Memory usage: 8%                 IPv4 address for eth0: 10.20.0.6
  Swap usage:   0%                 IPv4 address for eth1: 10.118.0.3
  Processes:    133

79 updates can be applied immediately.
10 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

New release '22.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

1 updates could not be installed automatically. For more details,
see /var/log/unattended-upgrades/unattended-upgrades.log

Last login: Fri Jan 26 01:45:18 2024 from 162.243.190.66
root@ubuntu-s-2vcpu-4gb-120gb-intel-tor1-01:~# evernode status

Host account address: r4hpb9zizjW1QV6yEfcA1uoht8m5imxk2a

█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ █ ██▀▀  ▀▄██▀██ ▄▄▄▄▄ ████
████ █   █ █  ▀█ █▄█▀▄ █▀█ █   █ ████
████ █▄▄▄█ █▀  █▄███▀ ▄▀▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄█ ▀▄▀▄▀ ▀ █▄█▄▄▄▄▄▄▄████
████ ▄█▀▄▄▄▀▀█▄█▄ ▀▀▀ ▀ ▄▀▀▄▀ ▄▄ ████
████▀   ▄▄▄   ▄█▀█▀▄  █▀▄▄ █▄▀█▀ ████
████▄  ▄█▄▄▄▀█▀▄▀▄▄▀▄▄█▄▄ █  ▀▀ ▀████
████ ▀█ ▄▄▄▄ █▀ ▄ ▄▄▀ ▄▀▀▄   ▀█ ▄████
████ ▄ ▀█▄▄▄▀▄ █▄ ▀ ▀ ▄▄▄ █▀▀ ▀▀▀████
███████▄▄▀▄▄  ▀█▀█▀   ██ ▀▄  █▄▀ ████
████▄▄██▄▄▄█▀ █▄▀▄▄   ▀  ▄▄▄ ▀██▀████
████ ▄▄▄▄▄ █▀▄  ▄ ▄ █  ▀ █▄█  █▄▄████
████ █   █ █▄▄▀█▄ ▀ ▀▄▄▄ ▄▄ ▄▀██▀████
████ █▄▄▄█ █▀▀▄█▀█▀ ▀  ▀ █▀██▀▄  ████
████▄▄▄▄▄▄▄█▄█▄▄█▄▄▄█▄██▄█▄██▄█▄█████
█████████████████████████████████████
█████████████████████████████████████

Governor address: rBvKgF3jSZWdJcwSsmoJspoXLLDVLDp6jg
Registry address: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Heartbeat address: rHktfGUbjqzU4GsYCMc1pDjdHXb5CJamto
Registration URIToken: 95277E5B5417C0C9E1E0E5A701E3F274DA040675EBABAB6916893B300308B3D5
EVR balance: 1
Host status: active
NOTE: The host is marked as active after sending the first heartbeat.

Sashimono agent status: active
Sashimono message board status: active

Your account details are stored in /etc/sashimono/mb-xrpl/mb-xrpl.cfg
root@ubuntu-s-2vcpu-4gb-120gb-intel-tor1-01:~# 

--

**Comment by chalith** [comment]
Rewards are accumulated and distributed in 24-hour cycles. So you'll receive the reward in the next cycle

**Comment by gt679** [comment]
Whats the deal with the heartbeat then - don't we physically have to do something on our hosts/computers every hour in order to get the rewards or has it been changed to an automtaic process?

 
 

Sent: Thursday, January 25, 2024 at 11:17 PM

**Comment by BimsaraFernando** [comment]
Closing the issue. If the issue still persists, please reopen.
