### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by mb589arts** [EvernodeXRPL/evernode-host#256]
Submitted the 500 evers and 19 XAH as well, but got error while installing!
Heres the log file:

[installer-1706286989.log](https://github.com/EvernodeXRPL/evernode-host/files/14067472/installer-1706286989.log)

 I followed the instructions https://docs.evernode.org/en/latest/hosts/possible-errors.html, then the error occurred again. And now, when I try to transfer, it says in the console that such a host is not registered. If I try to install it, then 500 EVR is required from me again.

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
