### ISSUE TITLE
Evernode Accumulated Reward Amount not released

### ISSUE THREAD

**Issue by ay432** [EvernodeXRPL/evernode-host#257]
Hello!
One of my nodes retains daily Accumulated Reward Amount since last 24 hours already passed, that means that $EVR in Accumulated Reward Amount still visible on Evernode Dashboard, $EVR balance in top left corner still zero since I withdraw it the night before (Accumulated Reward Amount  not available in connected XAMAN wallet too). Please explain if it's normal and we can just wait until next 24 hours cycle is over, or there is a command to release Accumulated Reward Amount , or something out of ordinary happening?

Thank you!!!

**Comment by ay432** [comment]
Just needed to install Manual Patch:curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/patch/sashimono/patches/update-message-board.sh | sudo bash -s

**Comment by BimsaraFernando** [comment]
Hi @ay432 , is this issue resolved? if so, please close the issue.
Thank you!

**Comment by BimsaraFernando** [comment]
Hi @ay432 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
