### ISSUE TITLE
Host registration failed, 500 evr was deducted

### ISSUE THREAD

**Issue by Levii010** [EvernodeXRPL/evernode-host#258]
There was an error during installation. Please provide the file /tmp/evernode/installer-1706287891.log to Evernode team. Thank you.

If i try " curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer " command then it gives me response " Host is not registered. "

xahau explorer 
![image](https://github.com/EvernodeXRPL/evernode-host/assets/138702784/59f2932b-2a49-411a-802a-fc84487a3ffd)

**Comment by Levii010** [comment]
when trying to install, then the response~ " Checking account rHDeECi9i56VNQKnPhvSLLZmQDLPkZkgL6...
The account needs minimum balance of 500 EVR. Current balance is 2 EVR. "

**Comment by Levii010** [comment]
![image](https://github.com/EvernodeXRPL/evernode-host/assets/138702784/00df7659-3370-4a47-a4ff-30c6108cb43d)

**Comment by Levii010** [comment]
**Issue Solved, here is what i did:-**

First make sure you have saved your secret key, Get here; 👇
sudo nano /home/sashimbxrpl/.evernode-host/.host-account-secret.key 
%%Save your key, you can also import it to xaman wallet

**Now to fix the issue, run these commands 👇**

cd ..
cd home
mkdir claim-reg-token
apt install unzip
cd claim-reg-token
wget https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip
unzip claim-reg-token.zip
cd claim-reg-token
node index.js <address> <secret>

%% **Do not include <,> when providing your address and secret key** 

If your claim token is successful then initiate transfer 👇

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

When asked for secret path:- /home/sashimbxrpl/.evernode-host/.host-account-secret.key

Then again run install 👇

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

Go through the setup process again. **When it asks “Will you be installing a fresh installation of the Evernode Host Software?” enter “n” for no**
It will ask for your public key to your existing host account. Enter it
It will ask for your secret key to your host account. Enter it
Installation will now continue as normal

Thanks supaKilla for helping me in discord

**Comment by cHs-crypto** [comment]
I have tried this but it failed with

Initiating the process...
mainnet
Claiming the token...
Sell offer found
Error occurred: Transaction failed with error terQUEUED
discord: cryptoHarvs

**Comment by MarkoinFr** [comment]
It would be worthwhile to mention that the token claim process is carried out on a working host. So the instructions would read:

Issue Solved, here is what i did:-

First make sure you have saved your secret key, Get here; 👇
sudo nano /home/sashimbxrpl/.evernode-host/.host-account-secret.key
%%Save your key, you can also import it to xaman wallet

Now to fix the issue, run these commands **on a working host**👇

cd ..
cd home
mkdir claim-reg-token
apt install unzip
cd claim-reg-token
wget https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip
unzip claim-reg-token.zip
cd claim-reg-token
node index.js

%% Do not include <,> when providing your address and secret key

If your claim token is successful then initiate transfer **on your broken host**👇

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

When asked for secret path:- /home/sashimbxrpl/.evernode-host/.host-account-secret.key

Then again run install 👇

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

Go through the setup process again. When it asks “Will you be installing a fresh installation of the Evernode Host Software?” enter “n” for no
It will ask for your public key to your existing host account. Enter it
It will ask for your secret key to your host account. Enter it
Installation will now continue as normal

Thanks supaKilla for helping me in discord

**Comment by Levii010** [comment]
thanks, 

I am closing this Issue
