### ISSUE TITLE
Failed installion

### ISSUE THREAD

**Issue by pickleballaddict001** [EvernodeXRPL/evernode-host#259]
It appears installation failed at bulletin board. See attached log.
[evernode-install-log.txt](https://github.com/EvernodeXRPL/evernode-host/files/14068948/evernode-install-log.txt)

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
