### ISSUE TITLE
Can not change the 'leaseamt' from 1 EVRs

### ISSUE THREAD

**Issue by spearsja74** [EvernodeXRPL/evernode-host#260]
During installation I wasn't allowed to use anything less than '1 EVRs' for the Leaseamt. Thinking I could change after installation. I used "evernode config leaseamt <lease amount>" but everything under 1 Evrs was "Invalid lease amount".  I was able to change it to a higher amount, 2 EVRs and 1.1 EVRs worked just fine.  Thank you

**Comment by BimsaraFernando** [comment]
Hi @spearsja74 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
