### ISSUE TITLE
Evernode Xahau message board exiting with error. REG_FAILURE

### ISSUE THREAD

**Issue by TheMainlander** [EvernodeXRPL/evernode-host#261]
Welcome to Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-122-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Fri Jan 26 21:48:22 UTC 2024

  System load:  0.42               Users logged in:       0
  Usage of /:   36.4% of 48.27GB   IPv4 address for eth0: 178.128.217.127
  Memory usage: 10%                IPv4 address for eth0: 10.15.0.28
  Swap usage:   0%                 IPv4 address for eth1: 10.104.0.25
  Processes:    115

189 updates can be applied immediately.
139 of these updates are standard security updates.
To see these additional updates run: apt list --upgradable

New release '22.04.3 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Last login: Fri Jan 26 21:43:22 2024 from 162.243.188.66
root@Evernode-Prod-The-Mainlander-05:~# ip -6 addr add 2400:6180:0:d0::136b:9002/64 dev eth0
root@Evernode-Prod-The-Mainlander-05:~# ip -6 -br addr
lo               UNKNOWN        ::1/128 
eth0             UP             2400:6180:0:d0::136b:9002/64 fe80::9c7e:47ff:fe5d:33fb/64 
eth1             UP             fe80::f0a9:a8ff:feb2:1c52/64 
root@Evernode-Prod-The-Mainlander-05:~# curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install
jq command not found. Installing..

Found Sashimono v0.8.1...
This will install Sashimono, Evernode's contract instance management software, and register your system as an Evernode host. 
Make sure your system does not currently contain any other workloads important to you since we will be making modifications to your system configuration. 

Continue? [Y/n]
System check complete. Your system is capable of becoming an Evernode host.

Checking initial level prerequisites...
Installing nodejs...
qrencode command not found. Installing..

***********************************************************************************************************************

EVERNODE SOFTWARE LICENCE AGREEMENT

By using this EVERNODE CLI Tool, you agree to be bound by the terms and conditions of the EVERNODE SOFTWARE LICENCE. 
For full details, please refer to the licence document available at: 
https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/license/evernode-license.pdf

***********************************************************************************************************************

Do you accept the terms of the licence agreement? [Y/n]y

Are you performing a fresh Evernode installation? 
NOTE: Pressing 'n' implies that you are in the process of transferring from a previous installation in mainnet. [Y/n]y

Downloading Environment configuration...

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   655  100   655    0     0  36388      0 --:--:-- --:--:-- --:--:-- 36388

Checking Evernode mainnet environment details...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0   518k      0  0:00:01  0:00:01 --:--:-- 1040k
Done.

Do you want to connect to the default rippled server (wss://xahau.network)? [Y/n]y

Checking server wss://xahau.network...
Using Rippled server 'wss://xahau.network'.

Specify the contact email address for your host (this will be published on the host registry and is publicly visible to anyone): kumo@kumoever.app
Using the contact email address 'kumo@kumoever.app'.

Please specify the domain name that this host is reachable at: 
Invalid or unreachable domain name.
Please specify the domain name that this host is reachable at: evr5.kumoever.app
Verifying domain evr5.kumoever.app on port 80...
Domain verification successful.

Evernode can automatically setup free SSL certificates and renewals for 'evr5.kumoever.app' using Let's Encrypt (https://letsencrypt.org/). 
Do you want to setup Let's Encrypt automatic SSL (recommended)? [Y/n]y

Do you agree to have Let's Encrypt send SSL certificate notifications to your email 'kumo@kumoever.app' (required)? [Y/n]y

Do you agree with Let's Encrypt Terms of Service at https://letsencrypt.org/documents/LE-SA-v1.3-September-21-2022.pdf ? [Y/n]y

Using 'evr5.kumoever.app' as host internet address.

Checking country code...
Using GeoLite2 data created by MaxMind, available from https://www.maxmind.com
Using 'SG' as country code.

If your host has IPv6 support, Evernode can assign individual outbound IPv6 addresses to each contract instance. This will prevent your host's primary IP address from getting blocked by external services in case many contracts on your host attempt to contact the same external service.

Does your host have an IPv6 subnet assigned to it? The CIDR notation for this usually looks like "xxxx:xxxx:xxxx:xxxx::/64" [Y/n]y

Please specify the IPv6 subnet CIDR assigned to this host: 2400:6180:0:d0::136b:9002/64

Do you want to allocate the entire address range of the subnet 2400:6180:0:d0::/64 to Evernode? [Y/n]y

Using 2400:6180:0:d0::/64 IPv6 subnet on eth0 for contract instances.

Using 'cgrulesengd' as cgroups rules engine service.

Based on your system resources, we have chosen the following allocation:
 1.62 GB memory
 13.42 GB Swap
 25.72 GB disk space
 Distributed among 3 contract instances

Is this the allocation you want to use? [Y/n]y

Using allocation 1.62 GB memory, 13.42 GB Swap, 25.72 GB disk space, distributed among 3 contract instances.

Selected default port ranges (Peer: 22861-22864, User: 26201-26204). This needs to be publicly reachable over internet. 

Are these the ports you want to use? [Y/n]y

Using peer port range 22861-22864 and user port range 26201-26204).

Specify the lease amount in EVRs for your contract instances (per moment charge per contract): 0.0000001
Lease amount set as 0.0000001 EVRs per Moment.

Creating Message-board User...

Do you want to use the default key file path /home/sashimbxrpl/.evernode-host/.host-account-secret.key to save the new account key? [Y/n]y

Key file saved successfully at /home/sashimbxrpl/.evernode-host/.host-account-secret.key
Your host account with the address rU9cp6PDU2XKtA89Aza6AQWFkBNHiBi2Ew will be on Xahau mainnet. 
The secret key of the account is located at /home/sashimbxrpl/.evernode-host/.host-account-secret.key. 
NOTE: It is your responsibility to safeguard/backup this file in a secure manner. 
If you lose it, you will not be able to access any funds in your Host account. NO ONE else can recover it. 

This is the account that will represent this host on the Evernode host registry. You need to load up the account with following funds in order to continue with the installation. 
1. At least 17 XAH to cover regular transaction fees for the first three months. 
2. At least 500 EVR to cover Evernode registration fee. 

You can scan the following QR code in your wallet app to send funds based on the account condition:

█████████████████████████████████████
█████████████████████████████████████
████ ▄▄▄▄▄ █▀█ █▄   ▀▀██ █ ▄▄▄▄▄ ████
████ █   █ █▀▀▀█ ▄▀ ████▀█ █   █ ████
████ █▄▄▄█ █▀ █▀▀██▄▄▀▄█ █ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀ ▀▄█ █ █ █▄█▄▄▄▄▄▄▄████
████▄▄▄ ▄▀▄ ▄▄▀▄▀▀▀▀█ ▀█▀▄▀ ▀▄█ ▀████
████▄  ▀██▄▀▄█▄█▀ ▄▄ ▄▄▀▀▀█▄█ ▄██████
█████▀█▀▀█▄▄▄▄▄█▄█▄▄ █▀▀▄▀█▀ ▄▄▄ ████
██████ ▄█▀▄  ██ ▄█▀  ▄ █▄▄██▄██▄█████
████▀█▄ ▄▀▄▀▄▄▄▄▀▀▀ ▀▀▀▀▀▄▀   ▄██████
████ █ █▄▄▄▀▀  █▀ ▄▄█▄▀▀█ ▄█▀▀▄▀▀████
████▄██▄▄▄▄▄ ███▄█▄▄▄▀▀  ▄▄▄ ▄█▄▀████
████ ▄▄▄▄▄ █▄▀▀ ▄█▀ ▄█   █▄█ ▀█▀▀████
████ █   █ █  ▄▄▀▀▀█▀ ▀▀▄ ▄ ▄▀█ ▀████
████ █▄▄▄█ █ ▄▄█▀ ▄▄██▄██▀ ▀ ▀█ █████
████▄▄▄▄▄▄▄█▄███▄█▄▄███▄███▄▄▄███████
█████████████████████████████████████
█████████████████████████████████████

Checking the account condition...
To set up your host account, ensure a deposit of 17 XAH to cover the regular transaction fees for the first three months.

Waiting for the process to complete...
Thank you. 17 XAH balance is there in your host account.

Preparing host account...

Waiting for the process to complete...
Account preparation is successfull.

In order to register in Evernode you need to have 500 EVR balance in your host account. Please deposit the required registration fee in EVRs. 
You can scan the provided QR code in your wallet app to send funds:

Waiting for the process to complete...
Thank you. 500 EVR balance is there in your host account.

Account setup is complete.

Do you want to subscribe for auto-updates?
NOTE: The auto-update service is offered subject to the terms set out in the Evernode Software Licence. [y/N]y

Auto updater will be enabled.

Setup will now begin the installation. Continue? [Y/n]y

Starting installation...
Installing other prerequisites...
Installing dependencies
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0  1546k      0 --:--:-- --:--:-- --:--:-- 15.9M
Done.

Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
There was an error during installation. Please provide the file /tmp/evernode/installer-1706306195.log to Evernode team. Thank you.
root@Evernode-Prod-The-Mainlander-05:~# sudo cat /etc/sashimono/mb-xrpl/secret.cfg
cat: /etc/sashimono/mb-xrpl/secret.cfg: No such file or directory
root@Evernode-Prod-The-Mainlander-05:~# cat /tmp/evernode/installer-1706306195.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://mirrors.digitalocean.com/ubuntu focal InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Hit:4 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:5 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200
  libtirpc-common libtirpc3 quota uidmap
The following packages will be upgraded:
  openssl
1 upgraded, 10 newly installed, 1 to remove and 182 not upgraded.
Need to get 1260 kB of archives.
After this operation, 2935 kB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 openssl amd64 1.1.1f-1ubuntu2.20 [620 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:5 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:6 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-3-200 amd64 3.4.0-1ubuntu0.1 [54.4 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-genl-3-200 amd64 3.4.0-1ubuntu0.1 [11.2 kB]
Get:8 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:9 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:10 http://mirrors.digitalocean.com/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:11 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 1260 kB in 0s (6890 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 69120 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 69128 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 69118 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Preparing to unpack .../1-openssl_1.1.1f-1ubuntu2.20_amd64.deb ...
Unpacking openssl (1.1.1f-1ubuntu2.20) over (1.1.1f-1ubuntu2.16) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../2-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../3-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libnl-3-200:amd64.
Preparing to unpack .../4-libnl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libnl-genl-3-200:amd64.
Preparing to unpack .../5-libnl-genl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../6-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../7-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../8-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../9-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up openssl (1.1.1f-1ubuntu2.20) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-122-generic
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
quotaon: using //aquota.group on /dev/vda1 [/]: No such process
quotaon: Quota format not supported in kernel.
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for evr5.kumoever.app

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/evr5.kumoever.app/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/evr5.kumoever.app/privkey.pem
This certificate expires on 2024-04-25.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-evr5.kumoever.app.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: SG 800000 1624640 13421760 25727920 3                 DO-Regular 1 1996 kumo@kumoever.app _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer 69C7B6C28522E0733C9D72BE6D919824EBCE21222ACA364B9B800278E2B393E2
Accepting the sell offer..
The latest ledger sequence 2513225 is greater than the transaction's LastLedgerSequence (2513224).
Preliminary result: {
  "id": 43,
  "result": {
    "accepted": true,
    "account_sequence_available": 759621266,
    "account_sequence_next": 759621266,
    "applied": true,
    "broadcast": true,
    "engine_result": "tesSUCCESS",
    "engine_result_code": 0,
    "engine_result_message": "The transaction was applied. Only final in a validated ledger.",
    "kept": true,
    "open_ledger_cost": "12224",
    "queued": false,
    "tx_blob": "12002F2100005359242D46E691201B0026594850247225920E309C20A3E1B1CF0AE27BD3E3D9CB6B0500E32EAC7BC9BDDCD163C226614000000000000001684000000000002FC073210350C4ED3F689DA892C3F74DA28115CF195C85D93F310468F55243EF94A2E78BC07446304402204D116E57319A27C715CD198AD332150C9A2E54B25336FEDD9A798988E2D02E54022062165792D836CFB950695D004A9A668A57F662E1AAD6DE80FCE089188D86895681147A49F3C7295D8F6E442D5EBF0253D5ED57A29ED9",
    "tx_json": {
      "Account": "rU9cp6PDU2XKtA89Aza6AQWFkBNHiBi2Ew",
      "Amount": "1",
      "Fee": "12224",
      "LastLedgerSequence": 2513224,
      "NetworkID": 21337,
      "Sequence": 759621265,
      "SigningPubKey": "0350C4ED3F689DA892C3F74DA28115CF195C85D93F310468F55243EF94A2E78BC0",
      "TransactionType": "URITokenBuy",
      "TxnSignature": "304402204D116E57319A27C715CD198AD332150C9A2E54B25336FEDD9A798988E2D02E54022062165792D836CFB950695D004A9A668A57F662E1AAD6DE80FCE089188D868956",
      "URITokenID": "7225920E309C20A3E1B1CF0AE27BD3E3D9CB6B0500E32EAC7BC9BDDCD163C226",
      "hash": "0D683DA755A5CE5F99FD6932AAA3B22FBF375DB21082741C34C3E29467A41EA6"
    },
    "validated_ledger_index": 2513214
  },
  "type": "response"
}
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'evr5.kumoever.app'
Deleted all files relating to certificate evr5.kumoever.app.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/evr5.kumoever.app/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
