### ISSUE TITLE
Offer lease NFT creation error --- Failed install (attached logs)

### ISSUE THREAD

**Issue by black-nest** [EvernodeXRPL/evernode-host#262]
**From log:**
STAGE -p Created lease offer 2 of 6.
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.

I also tried to reconduct the installation using the same wallet seed key but it was requesting an additional 500 evers. 
[installer-1706308276.log](https://github.com/EvernodeXRPL/evernode-host/files/14070010/installer-1706308276.log)

**Comment by black-nest** [comment]
I have attempted to transfer the host but I fear the process did not complete correctly or something went wrong. The output i recieved when i tried to transfer the host was:

> host-3a:~$ curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer
> Found Sashimono v0.8.1...
> 
> Downloading Environment configuration...
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   655  100   655    0     0   5598      0 --:--:-- --:--:-- --:--:--  5646
> 
> Checking Evernode mainnet environment details...
> Downloading setup support files...
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100  880k  100  880k    0     0   659k      0  0:00:01  0:00:01 --:--:-- 1010k
> Done.
> 
> Do you want to connect to the default rippled server (wss://xahau.network)? [Y/n]y
> 
> Checking server wss://xahau.network...
> Using Rippled server 'wss://xahau.network'.
> 
> Specify the Xahau account address: rN8dxHR4YrGAEx6L1f6m6nZyovLL24GKpe
> Checking account rN8dxHR4YrGAEx6L1f6m6nZyovLL24GKpe...
> Specify the path of the Host Account secret: /home/XXXXXX/temp
> Checking account keys...
> 
> Do you want to set the current host account as the transferee's account? [Y/n]Y
> 
> 
> This will deregister rN8dxHR4YrGAEx6L1f6m6nZyovLL24GKpe from Evernode while allowing you to transfer the registration to same account. 
> 
> Are you sure you want to transfer Evernode registration? [Y/n]Y
> 
> Transfer process was sucessfully initiated. You can now install and register Evernode using the account .
> host-3a:

Any one know if i have now officially lost my registration?

**Comment by chalith** [comment]
@black-nest Run the installation again using this https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation and follow the instructions. For the host account give your previous host address `rN8dxHR4YrGAEx6L1f6m6nZyovLL24GKpe`

**Comment by black-nest** [comment]
@chalith - Thank you! Seems this process now works with the latest updates. I promise I tried this before :).

Thank you for your support!
