### ISSUE TITLE
Transfer failed, host is unregistered now saying I need 500 EVRS to reg again

### ISSUE THREAD

**Issue by DylanMartino** [EvernodeXRPL/evernode-host#264]
Specify the Xahau account address: rLBiN1cWzmkY4VH8nyPbEC5S7XJDj7myKZ
Checking account rLBiN1cWzmkY4VH8nyPbEC5S7XJDj7myKZ...
The account needs minimum balance of 500 EVR. Current balance is 43.80341758709537 EVR.
Specify the Xahau account address:

Can this please be looked into?

Kind regards,
Dylan

**Comment by ariellozanod** [comment]
How did you fix it ? I am in the same trouble
