### ISSUE TITLE
Resolving Error 1705688786.log(nnnnnnnnnn.log) “An error occurred during installation. Please provide the /tmp/evernode/installer-1705688786.log(nnnnnnnnnn.log) file to the Evernode team. Thank you."

### ISSUE THREAD

**Issue by LexBulk** [EvernodeXRPL/evernode-host#265]
Everything from the forum is collected here to solve this error, maybe this method will help with other errors as well.
1 First you need to get your private key here is the command: sudo nano /home/sashimbxrpl/.evernode-host/.host-account-secret.key
2 download the archive and unzip the archive to the root of the problem host. download the archive here https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923
3 run the command node index.js < address > < secret >
4 run curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer
5 send 2Evr to your address
6 curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install
6.1 at the place where the question will appear: 
               Are you performing a fresh installation of Evernode?
               NOTE. Pressing "n" means that you are in the process of migrating from a previous installation on the main network. [Y/n]n (press n)
7 reboot the VPS

**Comment by lendlycagata** [comment]
hi there, I was having same issue in GCP VM
![image](https://github.com/EvernodeXRPL/evernode-host/assets/38574713/c24d43ab-3ca4-46f3-a9e4-2854c45c82b6)
tried running the claim token it didn't got through
![claim-token](https://github.com/EvernodeXRPL/evernode-host/assets/38574713/27013284-c3a5-41a4-9e2a-fc124094460a)
My plan is to recreate my VM - can I just do 
run curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer then curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install
BTW I got no more EVR
![420083459_1478561322693463_5802817858898615307_n](https://github.com/EvernodeXRPL/evernode-host/assets/38574713/4130b5b7-2878-46be-9c8e-218dbd2000a6)

**Comment by BimsaraFernando** [comment]
Closing this since the Evernode installation process is enhanced with the latest releases.
