### ISSUE TITLE
error, 1706357626.log

### ISSUE THREAD

**Issue by cOoNni** [EvernodeXRPL/evernode-host#266]
an error occured during installaion. 1706357626.log

what should i do to solve this ploblem.

![1706](https://github.com/EvernodeXRPL/evernode-host/assets/157492996/6f8fb3f0-d807-456e-9f43-1915010dd0d4)

**Comment by LexBulk** [comment]
that's what I described https://github.com/EvernodeXRPL/evernode-host/issues/265#issue-2103528946

**Comment by BimsaraFernando** [comment]
Hi @cOoNni , if the issue is already resolved, please close the issue.
If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )
Thank you.

**Comment by BimsaraFernando** [comment]
Hi @cOoNni ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
