### ISSUE TITLE
/tmp/evernode/installer-1706389043.log

### ISSUE THREAD

**Issue by TodL33** [EvernodeXRPL/evernode-host#270]
I'm kinda stuck... I successfully sent my Xau and Evr but...There was an error during installation. Please provide the file /tmp/evernode/installer-1706389043.log to Evernode team. 
Thank you.

**Comment by LexBulk** [comment]
https://github.com/EvernodeXRPL/evernode-host/issues/265#issue-2103528946

**Comment by TodL33** [comment]
I unzipped the claim-reg-token folderI made the node index.js <my XAU account address> <my secret key>     "Initiating the process...mainnet    Claiming the token...    ***@***.*** :~/Downloads/claim-reg-token"
"claiming the token..." but it DIDN'T SAY successfully claimed---And it went back to the prompt inside the folder. Did I do something wrong? 
Thanks!

    On Saturday, January 27, 2024 at 06:25:37 PM EST, LexBulk ***@***.***> wrote:  
 
 


#265 (comment)

**Comment by TodL33** [comment]
I also just tried doing the command again...node index.js <my XAU account address>  <{ "xrpl": { "secret": "xxxxxxxxxxxxxxx" } }>
And it said "Invalid args: Usage `node claim-reg-token <host-address> <host-secret>`"
I'm thinking maybe this was the correct way, but the first way I did it screwed it up?
Thank you for your patience and time.


    On Saturday, January 27, 2024 at 06:25:37 PM EST, LexBulk ***@***.***> wrote:  
 
 


#265 (comment)

**Comment by LexBulk** [comment]
add your wallet with your private key to Xaman 
so that you have access to the wallet so that you can withdraw funds from there because during the installation you may have a problem that it will not show the already deposited EVRs and that the system will miss you, you will transfer 500EVRs, then you will withdraw them back.
Unzip the archive as written
try using: node index.js address secret
run it
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

**Comment by TodL33** [comment]
Thank you!! I am working on these steps, very slowly. Please be patient with me as i am completely new to Linux. :)
    On Sunday, January 28, 2024 at 09:34:15 AM EST, LexBulk ***@***.***> wrote:  
 
 


add your wallet with your private key to Xaman
so that you have access to the wallet so that you can withdraw funds from there because during the installation you may have a problem that it will not show the already deposited EVRs and that the system will miss you, you will transfer 500EVRs, then you will withdraw them back.
Unzip the archive as written
try using: node index.js address secret
run it
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

**Comment by LexBulk** [comment]
> Дякую тобі!! Я працюю над цими кроками, дуже повільно. Будь ласка, будьте терплячі зі мною, оскільки я зовсім новачок у Linux. :) У неділю, 28 січня 2024 року о 09:34:15 ранку EST, LexBulk ***@***.***> написав: додайте свій гаманець із закритим ключем до Xaman, щоб мати доступ до гаманця щоб ви могли зняти кошти звідти, тому що під час інсталяції у вас може виникнути проблема, що він не показуватиме вже внесені EVR і що система пропустить вас, ви переведете 500 EVR, а потім знімете їх назад. Розпакуйте архів, як написано, спробуйте використати: node index.js address secret run it curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install — надішліть відповідь на цей електронний лист безпосередньо, перегляньте його на GitHub або скасуйте підписку. Ви отримали це, тому що ви є автором ланцюжка. ID повідомлення: ***@***.***>

Did you succeed?

**Comment by TodL33** [comment]
I am still having a hard time understanding what "unzip the archive (node index.js) to root of the problem host. download the archive here" means?Where is "here"? Does that mean I have to unzip it into the root file?
-Tod
    On Monday, January 29, 2024 at 01:42:40 PM EST, LexBulk ***@***.***> wrote:  
 
 



Дякую тобі!! Я працюю над цими кроками, дуже повільно. Будь ласка, будьте терплячі зі мною, оскільки я зовсім новачок у Linux. :) У неділю, 28 січня 2024 року о 09:34:15 ранку EST, LexBulk @.> написав: додайте свій гаманець із закритим ключем до Xaman, щоб мати доступ до гаманця щоб ви могли зняти кошти звідти, тому що під час інсталяції у вас може виникнути проблема, що він не показуватиме вже внесені EVR і що система пропустить вас, ви переведете 500 EVR, а потім знімете їх назад. Розпакуйте архів, як написано, спробуйте використати: node index.js address secret run it curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install — надішліть відповідь на цей електронний лист безпосередньо, перегляньте його на GitHub або скасуйте підписку. Ви отримали це, тому що ви є автором ланцюжка. ID повідомлення: @.>


Did you succeed?

**Comment by TodL33** [comment]
Okay, so now  as I see it... I DO extract to the node index.js into the root file. 
I am trying now to figure out how to get the permissions to do this. I was able to change the permissions in the root folder:"owner access" - changed to "create and delete files""group access" - also changed to "create and delete files" (maybe should change this one back)"Others access" - is set to "Access files" (maybe should change this one back)But even after changing these i couldn't do it by right clicking on the node index.js file and unzip to the root file because of permissions.    On Tuesday, January 30, 2024 at 10:06:37 PM EST, Tod LoRusso ***@***.***> wrote:  
 
  I am still having a hard time understanding what "unzip the archive (node index.js) to root of the problem host. download the archive here" means?Where is "here"? Does that mean I have to unzip it into the root file?
-Tod
    On Monday, January 29, 2024 at 01:42:40 PM EST, LexBulk ***@***.***> wrote:  
 
 



Дякую тобі!! Я працюю над цими кроками, дуже повільно. Будь ласка, будьте терплячі зі мною, оскільки я зовсім новачок у Linux. :) У неділю, 28 січня 2024 року о 09:34:15 ранку EST, LexBulk @.> написав: додайте свій гаманець із закритим ключем до Xaman, щоб мати доступ до гаманця щоб ви могли зняти кошти звідти, тому що під час інсталяції у вас може виникнути проблема, що він не показуватиме вже внесені EVR і що система пропустить вас, ви переведете 500 EVR, а потім знімете їх назад. Розпакуйте архів, як написано, спробуйте використати: node index.js address secret run it curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install — надішліть відповідь на цей електронний лист безпосередньо, перегляньте його на GitHub або скасуйте підписку. Ви отримали це, тому що ви є автором ланцюжка. ID повідомлення: @.>


Did you succeed?

**Comment by TodL33** [comment]
I'm seeing i need to get ssh keys from ubuntu.  It's getting late, will try to complete this tomorrow evening.thank you.
    On Tuesday, January 30, 2024 at 10:29:12 PM EST, Tod LoRusso ***@***.***> wrote:  
 
  Okay, so now  as I see it... I DO extract to the node index.js into the root file. 
I am trying now to figure out how to get the permissions to do this. I was able to change the permissions in the root folder:"owner access" - changed to "create and delete files""group access" - also changed to "create and delete files" (maybe should change this one back)"Others access" - is set to "Access files" (maybe should change this one back)But even after changing these i couldn't do it by right clicking on the node index.js file and unzip to the root file because of permissions.    On Tuesday, January 30, 2024 at 10:06:37 PM EST, Tod LoRusso ***@***.***> wrote:  
 
  I am still having a hard time understanding what "unzip the archive (node index.js) to root of the problem host. download the archive here" means?Where is "here"? Does that mean I have to unzip it into the root file?
-Tod
    On Monday, January 29, 2024 at 01:42:40 PM EST, LexBulk ***@***.***> wrote:  
 
 



Дякую тобі!! Я працюю над цими кроками, дуже повільно. Будь ласка, будьте терплячі зі мною, оскільки я зовсім новачок у Linux. :) У неділю, 28 січня 2024 року о 09:34:15 ранку EST, LexBulk @.> написав: додайте свій гаманець із закритим ключем до Xaman, щоб мати доступ до гаманця щоб ви могли зняти кошти звідти, тому що під час інсталяції у вас може виникнути проблема, що він не показуватиме вже внесені EVR і що система пропустить вас, ви переведете 500 EVR, а потім знімете їх назад. Розпакуйте архів, як написано, спробуйте використати: node index.js address secret run it curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install — надішліть відповідь на цей електронний лист безпосередньо, перегляньте його на GitHub або скасуйте підписку. Ви отримали це, тому що ви є автором ланцюжка. ID повідомлення: @.>


Did you succeed?

**Comment by TodL33** [comment]
Okay, I finally figured it out successfully and ran it! This time i got ERROR CODE:  /tmp/evernode/installer-1706773089

    On Sunday, January 28, 2024 at 09:34:15 AM EST, LexBulk ***@***.***> wrote:  
 
 


add your wallet with your private key to Xaman
so that you have access to the wallet so that you can withdraw funds from there because during the installation you may have a problem that it will not show the already deposited EVRs and that the system will miss you, you will transfer 500EVRs, then you will withdraw them back.
Unzip the archive as written
try using: node index.js address secret
run it
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install
