### ISSUE TITLE
Error 1706407471.log 

### ISSUE THREAD

**Issue by EnzoRacing** [EvernodeXRPL/evernode-host#271]
I got the following error during installation

Please provide the file /tmp/evernode/installer-1706407471.log to Evernode team. 
Thank you.

Has anyone seen this error before?
Thanks

**Comment by BimsaraFernando** [comment]
Hi, Please locate /tmp/evernode/installer-1706407471.log and share logs. 
After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve issues. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300) 
If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration ) 
If the error is already resolved, please close the issue
Thank you!

**Comment by BimsaraFernando** [comment]
Hi @EnzoRacing ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
