### ISSUE TITLE
Added the Patch before Evernode Install copy-paste error (REG_FAILURE)

### ISSUE THREAD

**Issue by TheMainlander** [EvernodeXRPL/evernode-host#272]
@chalith FYI second node failure.

Do you want to connect to the default rippled server (wss://xahau.network)? [Y/n]y

Checking server wss://xahau.network...
Using Rippled server 'wss://xahau.network'.

Creating Message-board User...
Specify the Xahau account address:
Specify the Xahau account address: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Checking account rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH...
Host is not registered.
Specify the Xahau account address: 

---

Log:

Last login: Sun Jan 28 04:03:18 2024 from 162.243.188.66
root@Evernode-Prod-The-Mainlander-08:~# cat /tmp/evernode/installer-1706408995.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://mirrors.digitalocean.com/ubuntu focal InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Hit:4 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:5 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:6 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
openssl set to manually installed.
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200
  libtirpc-common libtirpc3 quota uidmap
0 upgraded, 10 newly installed, 1 to remove and 0 not upgraded.
Need to get 640 kB of archives.
After this operation, 2936 kB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:5 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-3-200 amd64 3.4.0-1ubuntu0.1 [54.4 kB]
Get:6 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-genl-3-200 amd64 3.4.0-1ubuntu0.1 [11.2 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:8 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:9 http://mirrors.digitalocean.com/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:10 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 640 kB in 0s (2912 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 100471 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 100479 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 100469 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../1-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../2-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libnl-3-200:amd64.
Preparing to unpack .../3-libnl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libnl-genl-3-200:amd64.
Preparing to unpack .../4-libnl-genl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../5-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../6-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../7-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../8-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for systemd (245.4-4ubuntu3.23) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-170-generic
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
quotaon: using //aquota.group on /dev/vda1 [/]: No such process
quotaon: Quota format not supported in kernel.
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for evr8.kumoever.app

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/evr8.kumoever.app/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/evr8.kumoever.app/privkey.pem
This certificate expires on 2024-04-27.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-evr8.kumoever.app.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: SG 800000 1615040 13421760 25322880 3                 DO-Regular 1 2494 kumo@kumoever.app _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer 9E826DA88BEC5154D218257025876585D9BA280258784B7450B595F0E4B2D7B4
Accepting the sell offer..
Transaction result: tesSUCCESS
STAGE Creating lease offers for instance slots...
Offer lease NFT creation error.
Evernode Xahau message board exiting with error.
_**REG_FAILURE**_
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'evr8.kumoever.app'
Deleted all files relating to certificate evr8.kumoever.app.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/evr8.kumoever.app/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.

**Comment by TheMainlander** [comment]
@chalith Yep, 3rd Node just failed.

:(

Accepting the sell offer..
Transaction failed with error tefMAX_LEDGER
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'evr10.kumoever.app'
Deleted all files relating to certificate evr10.kumoever.app.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/evr10.kumoever.app/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.


---

Log:

Setup will now begin the installation. Continue? [Y/n]y

Starting installation...
Installing other prerequisites...
Installing dependencies
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  880k  100  880k    0     0   379k      0  0:00:02  0:00:02 --:--:-- 1121k
Done.

Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
There was an error during installation. Please provide the file /tmp/evernode/installer-1706419802.log to Evernode team. Thank you.
root@EVR-10:~# cat ^M
cat: ''$'\r': No such file or directory
root@EVR-10:~# cat /tmp/evernode/installer-1706419802.log
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 http://mirrors.digitalocean.com/ubuntu focal InRelease
Hit:2 http://mirrors.digitalocean.com/ubuntu focal-updates InRelease
Hit:3 http://mirrors.digitalocean.com/ubuntu focal-backports InRelease
Hit:4 https://repos.insights.digitalocean.com/apt/do-agent main InRelease
Hit:5 https://repos-droplet.digitalocean.com/apt/droplet-agent main InRelease
Hit:6 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:7 http://security.ubuntu.com/ubuntu focal-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.20).
openssl set to manually installed.
The following additional packages will be installed:
  libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200 libtirpc-common libtirpc3
Suggested packages:
  libnet-ldap-perl rpcbind default-mta | mail-transport-agent
The following packages will be REMOVED:
  fuse
The following NEW packages will be installed:
  cgroup-tools fuse3 libcgroup1 libfuse3-3 libnl-3-200 libnl-genl-3-200
  libtirpc-common libtirpc3 quota uidmap
0 upgraded, 10 newly installed, 1 to remove and 0 not upgraded.
Need to get 640 kB of archives.
After this operation, 2936 kB of additional disk space will be used.
Get:1 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libfuse3-3 amd64 3.9.0-2 [74.0 kB]
Get:2 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 fuse3 amd64 3.9.0-2 [24.7 kB]
Get:3 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 libcgroup1 amd64 0.41-10 [42.9 kB]
Get:4 http://mirrors.digitalocean.com/ubuntu focal/universe amd64 cgroup-tools amd64 0.41-10 [66.2 kB]
Get:5 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-3-200 amd64 3.4.0-1ubuntu0.1 [54.4 kB]
Get:6 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libnl-genl-3-200 amd64 3.4.0-1ubuntu0.1 [11.2 kB]
Get:7 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc-common all 1.2.5-1ubuntu0.1 [7712 B]
Get:8 http://mirrors.digitalocean.com/ubuntu focal-updates/main amd64 libtirpc3 amd64 1.2.5-1ubuntu0.1 [77.9 kB]
Get:9 http://mirrors.digitalocean.com/ubuntu focal/main amd64 quota amd64 4.05-1 [254 kB]
Get:10 http://mirrors.digitalocean.com/ubuntu focal-updates/universe amd64 uidmap amd64 1:4.8.1-1ubuntu5.20.04.4 [26.4 kB]
Preconfiguring packages ...
Fetched 640 kB in 0s (3008 kB/s)
Selecting previously unselected package libfuse3-3:amd64.
(Reading database ... 100471 files and directories currently installed.)
Preparing to unpack .../libfuse3-3_3.9.0-2_amd64.deb ...
Unpacking libfuse3-3:amd64 (3.9.0-2) ...
dpkg: fuse: dependency problems, but removing anyway as you requested:
 ntfs-3g depends on fuse.

(Reading database ... 100479 files and directories currently installed.)
Removing fuse (2.9.9-3) ...
update-initramfs: deferring update (trigger activated)
Selecting previously unselected package fuse3.
(Reading database ... 100469 files and directories currently installed.)
Preparing to unpack .../0-fuse3_3.9.0-2_amd64.deb ...
Unpacking fuse3 (3.9.0-2) ...
Selecting previously unselected package libcgroup1:amd64.
Preparing to unpack .../1-libcgroup1_0.41-10_amd64.deb ...
Unpacking libcgroup1:amd64 (0.41-10) ...
Selecting previously unselected package cgroup-tools.
Preparing to unpack .../2-cgroup-tools_0.41-10_amd64.deb ...
Unpacking cgroup-tools (0.41-10) ...
Selecting previously unselected package libnl-3-200:amd64.
Preparing to unpack .../3-libnl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libnl-genl-3-200:amd64.
Preparing to unpack .../4-libnl-genl-3-200_3.4.0-1ubuntu0.1_amd64.deb ...
Unpacking libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Selecting previously unselected package libtirpc-common.
Preparing to unpack .../5-libtirpc-common_1.2.5-1ubuntu0.1_all.deb ...
Unpacking libtirpc-common (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package libtirpc3:amd64.
Preparing to unpack .../6-libtirpc3_1.2.5-1ubuntu0.1_amd64.deb ...
Unpacking libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Selecting previously unselected package quota.
Preparing to unpack .../7-quota_4.05-1_amd64.deb ...
Unpacking quota (4.05-1) ...
Selecting previously unselected package uidmap.
Preparing to unpack .../8-uidmap_1%3a4.8.1-1ubuntu5.20.04.4_amd64.deb ...
Unpacking uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libtirpc-common (1.2.5-1ubuntu0.1) ...
Setting up uidmap (1:4.8.1-1ubuntu5.20.04.4) ...
Setting up libfuse3-3:amd64 (3.9.0-2) ...
Setting up libnl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up libcgroup1:amd64 (0.41-10) ...
Setting up libtirpc3:amd64 (1.2.5-1ubuntu0.1) ...
Setting up cgroup-tools (0.41-10) ...
Setting up fuse3 (3.9.0-2) ...
Installing new version of config file /etc/fuse.conf ...
update-initramfs: deferring update (trigger activated)
Setting up libnl-genl-3-200:amd64 (3.4.0-1ubuntu0.1) ...
Setting up quota (4.05-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Processing triggers for systemd (245.4-4ubuntu3.23) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.4.0-170-generic
Adding br_netfilter
STAGE Configuring fstab
Updated fstab.
quotaon: using //aquota.group on /dev/vda1 [/]: No such process
quotaon: Quota format not supported in kernel.
STAGE Configuring fuse
Updated fuse config.
STAGE Configuring cgroup rules engine
Created symlink /etc/systemd/system/multi-user.target.wants/cgrulesengd.service → /etc/systemd/system/cgrulesengd.service.
STAGE Configuring grub
Updated grub. System needs to be rebooted to apply grub changes.
---Sashimono installer---
STAGE Setting up letsencrypt certbot
core 16-2.60.4 from Canonical** installed
snap "core" has no updates available
certbot 2.8.0 from Certbot Project (certbot-eff**) installed
Rules updated
Rules updated (v6)
Running certbot certonly
Account registered.
Requesting a certificate for evr10.kumoever.app

Successfully received certificate.
Certificate is saved at: /etc/letsencrypt/live/evr10.kumoever.app/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/evr10.kumoever.app/privkey.pem
This certificate expires on 2024-04-27.
These files will be updated when the certificate renews.
Certbot has set up a scheduled task to automatically renew this certificate in the background.
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
If you like Certbot, please consider supporting our work by:
 * Donating to ISRG / Let's Encrypt:   https://letsencrypt.org/donate
 * Donating to EFF:                    https://eff.org/donate-le
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Setting up certbot deploy hook /etc/letsencrypt/renewal-hooks/deploy/sashimono-evr10.kumoever.app.sh
STAGE Setting up slirp4netns
STAGE Installing docker packages
Installing rootless docker packages into /usr/bin/sashimono/dockerbin
Private docker registry installation skipped
Configuaring host setup on Evernode...
STAGE Configuring host Xahau account
Using registry: rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
STAGE Configuring Sashimono services
Creating cgroup rules...
Restarting the 'cgrulesengd' service.
Configuring sashimono agent service...
Config file created at /etc/sashimono/sa.cfg
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service → /etc/systemd/system/sashimono-cgcreate.service.
Created symlink /etc/systemd/system/multi-user.target.wants/sashimono-agent.service → /etc/systemd/system/sashimono-agent.service.
Installing Evernode Xahau message board...
Updated mb user .bashrc.
STAGE Configuring Xahau message board service
Created symlink /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service → /home/sashimbxrpl/.config/systemd/user/sashimono-mb-xrpl.service.
Installed Evernode Xahau message board.
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: SG 800000 1615040 13421760 25490640 3                 DO-Regular 1 2199 kumo@kumoever.app _
Registering host...
Burning unsold URITokens related to the previous leases.
No initiated transfers were found.
Transaction result: tesSUCCESS
Waiting for the sell offer B3A46C9D0CF0316A5B66C293647D715FA01D601C287C3C4AE59A967C45A814C5
Accepting the sell offer..
Transaction failed with error tefMAX_LEDGER
Evernode Xahau message board exiting with error.
REG_FAILURE
Rolling back sashimono installation.
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Deleting message board user...
Deleting binaries...
Cleaning up letsencrypt ssl certs for 'evr10.kumoever.app'
Deleted all files relating to certificate evr10.kumoever.app.
Congratulations! You have successfully revoked the certificate that was located at /etc/letsencrypt/live/evr10.kumoever.app/cert.pem.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Cleaning up firewall rule for SSL validation
Rules updated
Rules updated (v6)
Account deactivated.
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Deleting data directory...
Sashimono uninstalled successfully.
Rolled back the installation.
root@EVR-10:~#

**Comment by TheMainlander** [comment]
![image](https://github.com/EvernodeXRPL/evernode-host/assets/38913700/85fb89aa-5435-45d3-bde1-e1f799d42520)

**Comment by tristopitsot** [comment]
I have the same problem, how can I solve it? Help me

**Comment by TheMainlander** [comment]
OK, 2 of the 3 are Fixed. 

Just this one to go ...

rnZA4nWiK7QuxTXHS5hCBrEaNQ13xar5df

**Comment by TheMainlander** [comment]
I am getting this error:

`Specify the Xahau account address: y
Invalid Xahau account address.
Specify the Xahau account address: rnZA4nWiK7QuxTXHS5hCBrEaNQ13xar5df
Checking account rnZA4nWiK7QuxTXHS5hCBrEaNQ13xar5df...
Host is not registered.
Specify the Xahau account address:`

**Comment by TheMainlander** [comment]
@chalith Can we have a look at this one next week, please? I am still blocked. -->
FIXED.

**Comment by tristopitsot** [comment]
Hi. I was transferring the host from one server to another and instead of
clicking the old user, the new user clicked.Evernode has also bought a mint
url token. Now it is not possible to register , writes such a user is
already registered , which I only did both the transfer and the new
server.What should I do?

**Comment by TheMainlander** [comment]
@raviw-geveo @chalith --> Please close this issue.

**Comment by TheMainlander** [comment]
> Hi. I was transferring the host from one server to another and instead of clicking the old user, the new user clicked.Evernode has also bought a mint url token. Now it is not possible to register, writes such a user is already registered, and I only did both the transfer and the new server. What should I do?

@tristopitsot 

If you have not already, please join Discord and post the issue if it is still open to this channel: https://discord.com/channels/953758352280813618/1006193024151339048

:)
