### ISSUE TITLE
3 Failed Transfers attempts / says to send to this to team

### ISSUE THREAD

**Issue by gt679** [EvernodeXRPL/evernode-host#273]
Hi can someone please help, I am unsure how to resolve. I've tried to do transfers with no success and check if i own the NFTs. my NFT's are there.

Here is what my failed install says /tmp/evernode/installer-1706417183.log

running cat command this is the result below. Can some please direct me to a fix

**Comment by juanchomardel** [comment]
the same happend to me, if you can contact the evernode team please let me know

**Comment by BimsaraFernando** [comment]
Hi @gt679, please locate  /tmp/evernode/installer-1706417183.log and share the logs. 

If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration ) . If the problem already solved, please close the issue. 
Thank you

**Comment by gt679** [comment]
Hi I have resolved this thank you

 

 
 

Sent: Thursday, March 14, 2024 at 5:13 AM
