### ISSUE TITLE
I can't continue the installation

### ISSUE THREAD

**Issue by tristopitsot** [EvernodeXRPL/evernode-host#274]
How can I solve it? Help me
I can't continue the installation

Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Created lease offer 3 of 3.
main: line 1131: stage: command not found
Enabling Evernode auto update service...
Created symlink /etc/systemd/system/multi-user.target.wants/evernode-auto-update.service → /etc/systemd/system/evernode-auto-update.service.
Enabling Evernode auto update timer...
Created symlink /etc/systemd/system/timers.target.wants/evernode-auto-update.timer → /etc/systemd/system/evernode-auto-update.timer.
Starting Evernode auto update timer...
Installation successful! Installation log can be found at /tmp/evernode/installer-1706320361.log

Your system is now registered on Evernode. You can check your system status with 'evernode status' command.
Your system needs to be rebooted in order to complete Sashimono installation.
Reboot now? [Y/n]Y

**Comment by chalith** [comment]
Reaching this point means you have completed the installation. Did you resolve the issue? If so you can close the issue

**Comment by BimsaraFernando** [comment]
Hi @tristopitsot ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
