### ISSUE TITLE
Evernode Mainnet shows HOST REGISTERED but SSH Session shows Host NOT REGISTERED...Where are the funds ? 😒

### ISSUE THREAD

**Issue by ariellozanod** [EvernodeXRPL/evernode-host#277]
I tried to install a host a couple of days ago; the result was:

**Evernode Mainnet shows HOST REGISTERED but SSH Session shows Host NOT REGISTERED**
...and **Where are the funds ?**

I've tried everything with all the variants

Also, the payment was sent but the status is that it appears without recognizing it because when I try to install or transfer again, the process request funds again.

   - Evernode Mainnet webpage status:

![2024-01-28_13-26-34](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/1ddad43e-e90c-400e-9ba9-341f2596671c)

As you can see the host has Registered Info with data, is Inactive and says There're no available leases!

![2024-01-28_14-47-42](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/7ecf9364-e900-442f-b8f3-9a63c52fe6e0)

   - Evernode SSH session says Host is not registered (How is that possible?)

 
![2024-01-28_13-28-11](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/6b794440-176c-42e2-b102-3611ff9cb18e)

![2024-01-28_13-20-51](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/94ee0c48-1bff-4161-b388-ae75c4dfcc0f)

![2024-01-28_13-39-05](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/f0fa7ade-d4d9-43b3-8889-e1c597c8b627)

Host address: rEcWF3uXbBrfcxaY5b28Kj7Ge6gEmEk1DG
Seed address for transfer: r4fEBN473zSBoQz4KfgAViLgkk4Bre8Nec

![2024-01-28_13-49-25](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/e8e3c22e-ad2f-4c02-bfc9-39bd8aa7d714)

![2024-01-28_13-54-10](https://github.com/EvernodeXRPL/evernode-host/assets/73303558/865f5cb8-2f01-472f-bcc8-1877d87b7d4c)

Hi @chalith

**Comment by Bitbob589** [comment]
I have the same issue. did you find a fix?

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
