### ISSUE TITLE
Try this, From any machine extract this zip file. Then go inside `claim-reg-token` directory. And then execute `node index.js <address> <secret>` replace the address and secret with yours.

### ISSUE THREAD

**Issue by zagran2** [EvernodeXRPL/evernode-host#279]
Try this, From any machine extract this zip file. Then go inside `claim-reg-token` directory. And then execute `node index.js <address> <secret>` replace the address and secret with yours. 
[claim-reg-token.zip](https://github.com/EvernodeXRPL/evernode-host/files/13976069/claim-reg-token.zip)

After that. You'll have to do a transfer: https://docs.evernode.org/en/latest/hosts/maintenance.html

And then install using the same address.

Let us know if there're any issues

_Originally posted by @chalith in https://github.com/EvernodeXRPL/evernode-host/issues/144#issuecomment-1898322923_
            
I did everything as written, does not pass registration and deletes everything, although the host in the register is registered. please see what's wrong?
----------------------------------------------------------------------------------------------------
Registering host on Evernode...
STAGE Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Executing register with params: DE 800000 1624480 1677680 15889600 3                 Intel(R)_Xeon(R)_CPU_E5-2697_v4_2.30GHz 2 2299 cloud@xencom.net _
Registering host...
Burning unsold URITokens related to the previous leases.
sell offer
The latest ledger sequence 2572239 is greater than the transaction's LastLedgerSequence (2572238).
Preliminary result: {
  "id": 35,
  "result": {
    "accepted": true,
    "account_sequence_available": 759067041,
    "account_sequence_next": 759067041,
    "applied": true,
    "broadcast": true,
    "engine_result": "tesSUCCESS",
    "engine_result_code": 0,
    "engine_result_message": "The transaction was applied. Only final in a validated ledger.",
    "kept": true,
    "open_ledger_cost": "12426",
    "queued": false,
    "tx_blob": "1200002100005359242D3E71A0201B00273FCE61D2838D7EA4C680000000000000000000000000004556520000000000A3B6B1B61181DB9C81EED4F3D5109F6CFC31109B68400000000000308A7321023ACB91B48960D51D38903E44BB91ED781E273D2BDB14CC3F16A490A4F0D4F9C474463044022078B6AF3C9CAA8AB078958EF363B80C3A274F6BEF755B27FDFD3439DCFC6A0FA80220464252D764591FAF7051A75598DDE9C1ACDA89B6D9AEB103521F8DFEF5BFA6A08114E18D9DF909223BB78AC8D8727A1BBF6DBE75726F8314087F22F5833A4953C52B3AB781144A2BE5C18F33F9F1F013E017701820455652010000000000000000000000000000000000000000000000000000000270190A65766E486F7374526567E1E0177018204556520100000000000000000000000000000000000000000000000000000003701980444500350C00E60C0000113E000003000000496E74656C2852292058656F6E285229204350552045352D3236393720763420322E333047487A000200FB082000000000000000000000000000000000000000000000000000636C6F75644078656E636F6D2E6E6574000000000000000000000000000000000000000000000000E1F1",
    "tx_json": {
      "Account": "rMZcgt2avvZJA9pVb8eXqdiYSn1SYwDZjV",
      "Amount": {
        "currency": "EVR",
        "issuer": "rEvernodee8dJLaFsujS6q1EiXvZYmHXr8",
        "value": "0.00000001"
      },
      "Destination": "rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH",
      "Fee": "12426",
      "HookParameters": [
        {
          "HookParameter": {
            "HookParameterName": "4556520100000000000000000000000000000000000000000000000000000002",
            "HookParameterValue": "65766E486F7374526567"
          }
        },
        {
          "HookParameter": {
            "HookParameterName": "4556520100000000000000000000000000000000000000000000000000000003",
            "HookParameterValue": "444500350C00E60C0000113E000003000000496E74656C2852292058656F6E285229204350552045352D3236393720763420322E333047487A000200FB082000000000000000000000000000000000000000000000000000636C6F75644078656E636F6D2E6E6574000000000000000000000000000000000000000000000000"
          }
        }
      ],
      "LastLedgerSequence": 2572238,
      "Memos": [],
      "NetworkID": 21337,
      "Sequence": 759067040,
      "SigningPubKey": "023ACB91B48960D51D38903E44BB91ED781E273D2BDB14CC3F16A490A4F0D4F9C4",
      "TransactionType": "Payment",
      "TxnSignature": "3044022078B6AF3C9CAA8AB078958EF363B80C3A274F6BEF755B27FDFD3439DCFC6A0FA80220464252D764591FAF7051A75598DDE9C1ACDA89B6D9AEB103521F8DFEF5BFA6A0",
      "hash": "42722A88DA1D82D5D448A43DF8837900701B27DAA8FF3B4F9EC36C6293AB3EED"
    },
    "validated_ledger_index": 2572229
  },
  "type": "response"
}
Evernode Xahau message board exiting with error.
REG_FAILURE
-----------------------------------------------------------

**Comment by chalith** [comment]
@zagran2 did you resolve this issue? There a new installer did you try with it? https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300

**Comment by BimsaraFernando** [comment]
Hi @zagran2 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
