### ISSUE TITLE
Rewards still accumulating, but not distributing anymore.

### ISSUE THREAD

**Issue by lilfoot4677** [EvernodeXRPL/evernode-host#281]
I have multiple hosts all working fine... One host still accumulating but suddenly stopped distributing. Should I transfer and reinstall?

**Comment by lilfoot4677** [comment]
Ended up abandoning my host and creating another one, I did too much messing around with burning tokens and changing code. Hard lesson learned. Also, I believe there are three things that helped me setup 6 hosts .. 1. Keep extra 500 evers cause it asked me for it a few times even though I already paid and it worked, also got to keep it. 2. Stay away from updates, no more updates or Auto updates for a while. 3. Get use to saving host names and passwords and learn about the commands and I seem to always get it to work. Note: be careful changing codes, mostly just run the installs and copy paste as much as possible, cause I went through hell on two host I set-up. Hope this helps. Run multiple installs and transfers... Keep at it... Also If you get mad enough and can't fix your host like I did, reset your server, (hard reboot/delete the whole server and start over, but, before going back to Ubuntu and starting clean, you better have your passwords and host ID because it's gone after. I have some tokens stuck in the accumulated dashboard contacts, but it's my fault for going into the xahau ledger and burning tokens,... Everything was going good until I decided to start updating stuff.... DO NOT UPDATE UBUNTU AFTER YOUR HOST IS ONLINE.. IN FACT, I WOULD SCARED TO UPDATE ANYTHING!!!! DONT UPDATE NOTHING AFTER THE HOST IS RUNNING, UNLESS EVERNODE TELLS YOU TOO!!.. I LEARNED A BIG LESSON!

**Comment by BimsaraFernando** [comment]
Hi @lilfoot4677, good to hear you have solved the issue. Please don't update Ubuntu version since it clashes with the existing dependencies. We have released a new installer addressing the enhancements and the bug fixes.
Closing the issue.
