### ISSUE TITLE
Host connection error

### ISSUE THREAD

**Issue by kirkyb** [EvernodeXRPL/evernode-host#283]
All 3 of my hosts are currently offline and the dashboard is only showing 188 hosts online at 00:25am UK 30/01/24.

Code: ERR_UNHANDLED_REJECTION
![Screenshot_2024-01-30-00-05-47-551_com android chrome-edit](https://github.com/EvernodeXRPL/evernode-host/assets/30548482/fad79211-c4a3-4b62-a074-68ba8ceb9737)

**Comment by zagran2** [comment]
I guess everyone is like this! hosts constantly fall off from wss://xahau.network . so earnings are less. I have all hosts with different accrual per day.

**Comment by ObiTwo2** [comment]
There's an issue with the network.

**Comment by zagran2** [comment]
I'm connected, but it keeps crashing to inactive.
Host status: **inactive**
NOTE: The host is marked as active after sending the first heartbeat.
Sashimono agent status: active
Sashimono message board status: active

**Comment by ObiTwo2** [comment]
Zagran2, it should e back up, try rebooting and host status should go back to active.

**Comment by zagran2** [comment]
I'm connected, but I'm constantly inactive during the day and not only for me. I think it's the developers' tricks. I'll create a separate appeal on this topic.

**Comment by BimsaraFernando** [comment]
Hope this issue got resolved with the latest Evernode updates. If the issue still persists, please reopen the issue.
