### ISSUE TITLE
Host Install Failed at End

### ISSUE THREAD

**Issue by mauricetbm** [EvernodeXRPL/evernode-host#284]
The installation failed right at the end and I didn't capture the message because it has happened two other times and was resolved with reinstall or transfer.

This one I can't figure out, but I'm a novice, so that isn't a shocker...
xahua: rBgp81BzXqw852Tt2UvQExQ8a1RAthjngb

I tried reinstall first and it said there wasn't enough evr in the account. 
So, then I tried transfer but it says "Host is not registered" (pic)
<img width="779" alt="Screen Shot 2024-01-29 at 8 17 33 PM" src="https://github.com/EvernodeXRPL/evernode-host/assets/157976597/d4e531ae-307b-42fc-9476-ce71e1016db2">

Txn registery shows at total of 20 XAH, 502 EVR, Host Registered and a "New NFT sell offer created". (pic)
<img width="1157" alt="Screen Shot 2024-01-29 at 8 16 58 PM" src="https://github.com/EvernodeXRPL/evernode-host/assets/157976597/2c000d55-cf64-4f8a-8b63-9e2161345308">

I think I'm supposed to manually complete that NFT transfer but can't figure out how.

How do I fix this please?

thanks so much

**Comment by BimsaraFernando** [comment]
seems you have resolved the issue. your host is active and running.
closing the issue.
