### ISSUE TITLE
Host connection error - developer fraud?

### ISSUE THREAD

**Issue by zagran2** [EvernodeXRPL/evernode-host#285]
I demand a detailed answer!

for 6 hours of network downtime as you would expect accruals did not follow! accrual of remuneration is made on active hosts. during 6 hours all hosts were inactive, active remained about 200 hosts - apparently hosts of developers?
I have several hosts in work, and all have different accrual for the day, apparently periodically go inactive. Developers - again a question for you!
You have recruited in the work of hosts and now terrorize the network?
announcement from telegram below
=================================================
Do you want to launch Evernode hosts without any errors, double payments, etc.?

✔️ Magnetic uses its own XAHAU nodes to ensure that all transactions are successful.
✔️ We constantly check the servers for activity and immediately solve possible problems.
✔️ You receive 50% of the profit immediately as the tokens arrive to the host wallet
✔️ We have already launched several hundred hosts for dozens of people and are ready continue to help you with this.

✅ Current reward for evernode host: 50 EVR/daily (50% = 25 EVR)

To launch a host, write to us in telegram and we will send you detailed conditions:
https://t.me/X_Magnetic
===================================================

I would appreciate it, who knows direct contacts of the management, higher developers and sponsors, please send me, I'm not going to tolerate these outlaws

**Comment by zagran2** [comment]
today's record on earnings - from 24 to 27,5 EVR per host per day! uptime - 100% on hosts. network downtime due to developers' fault - priceless!

**Comment by zagran2** [comment]
https://t.me/X_Magnetic - Richard closed the messages, how many people have they scammed ?

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
