### ISSUE TITLE
Using your own Xahaud - websocket error if you're already hosting.

### ISSUE THREAD

**Issue by rippleitinnz** [EvernodeXRPL/evernode-host#287]
A new issue in trying to use my own websocket from Xahaud.

ws is ws://127.0.0.1:6008
```
root@evernode-host:/usr/bin/sashimono/evernode-setup-helpers# evernode config rippled ws://127.0.0.1:6008
Checking server ws://127.0.0.1:6008...
mkfifo: cannot create fifo '/usr/bin/sashimono/evernode-setup-helpers/helper_fifo': Permission denied
cat: /usr/bin/sashimono/evernode-setup-helpers/helper_fifo: No such file or directory

rm: cannot remove '/usr/bin/sashimono/evernode-setup-helpers/helper_fifo': No such file or directory
Could not communicate with the rippled server.

Usage: evernode config rippled | evernode config rippled <rippled server>

 ```
 
 I can create the file outside of Evernode but the ws hangs on connecting.
 
 If i try and add the new server info it can't create file. 
 
 Permissions right though the tree are root and running as root.
 
 Thoughts?

**Comment by rippleitinnz** [comment]
I have resolved this simply by altering the server component in /etc/sashimono/mb-xrpl/mb-xrpl.cfg then rebooted.

```
Your current rippled server is: ws://127.0.0.1:6010
```

However, the underlying issue still needs a resolution.

**Comment by BimsaraFernando** [comment]
Closing the issue. Hope this issue is resolved in the new version of Evernode. If you are still having the issue please reopen.
