### ISSUE TITLE
Unable to do install...  server not recognized as Ubuntu 20.04

### ISSUE THREAD

**Issue by Pal5135** [EvernodeXRPL/evernode-host#288]
Unable to Install when executing command for install. I continue to get the following two error codes on Termius when executing the install command::

"Your system does not meet following Evernode system requirements:
 OS: ubuntu "22.04" (required: Ubuntu 20.04)
 Swap: 0 GB (required: 2 GB Swap)"
"Evernode host registration requires Ubuntu 20.04 with minimum 2 GB RAM, 2 GB Swap and 4 GB free disk space for /home. Aborting setup."

I am currently running an active VPS  on Ionos, which meets the required Ubuntu 20.04 for the Evernode install. These are my current configurations: 

Type: Virtual Machine
OS: Ubuntu 20.04 
Size: VPS L
CPU: 4 vCore
RAM: 8 GB
Disk: 240 GB SSD

Is the issue with Termius?  There is a welcome message at the top of the page after connecting my VPS that states: 
"Welcome to Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-92-generic x86_64)"
* Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro
  System information as of Tue Jan 30 11:35:03 UTC 2024

How do I remedy this, so that my VPS is recognized as having the correct required OS: Ubuntu 20.04 ?

Thank you!

**Comment by ariellozanod** [comment]
Hi !

Finally...How did you solve it ?
I have the same problem...4vCPU but in the installation says 0 SWAP

**Comment by Pal5135** [comment]
I watched this guy’s video and he explained it in detail. I was able to finally move forward.TUTORIAL: HOW TO SETUP EVERNODE & GET REWARDS!!youtu.beEVER NODE SETUP INSTALLxrpbags.linkP. LilavoisOn Feb 7, 2024, at 11:33 AM, akiaya ***@***.***> wrote:﻿
Hi !
Finally...How did you solve it ?
I have the same problem...4vCPU but in the installation says 0 SWAP
