### ISSUE TITLE
evernode config rippled command 

### ISSUE THREAD

**Issue by shortthefomo** [EvernodeXRPL/evernode-host#291]
using the documented command `evernode config rippled wss://<your node URL>` the Evernode change often 

A) times out and never completes.
B) incorrect sequence number is used when constructing URITokenCreateSellOffer's my guess is one tx fails which then throws the sequence number off as the ledger  result is not used but rather a local counter. not you should fetch the sequence number from the ledger after each submission rather.
C) Offer lease NFT creation error.

It is also worth renaming this from `evernode config rippled` to `evernode config xahaud` as this is now rather confusing

<img width="1450" alt="Screenshot 2024-01-30 at 16 08 24" src="https://github.com/EvernodeXRPL/evernode-host/assets/508629/0d89794c-1bf4-49a4-ac42-aafc0c20b408">
<img width="412" alt="Screenshot 2024-01-30 at 16 08 06" src="https://github.com/EvernodeXRPL/evernode-host/assets/508629/116a9bd8-6314-4901-bd71-bb73c5e97ed5">

**Comment by BimsaraFernando** [comment]
Closing the issue. Hope this issue is resolved in the new version of Evernode. If you are still having the issue please reopen.
