### ISSUE TITLE
How running your own xahaud node?

### ISSUE THREAD

**Issue by inspectorjair** [EvernodeXRPL/evernode-host#292]
Hi guys:

I want to run my own xahau node but I don't know how to start, I would like to know if the one that is currently running in a public one can I transfer it to a private one and thus avoid further congestion of the nodes, I would like to know if there is a tutorial that tells us how to run on our own node and if we can change the current one we have from public to private, Is there a tutorial that tells us step by step? thank s

**Comment by inspectorjair** [comment]
@chalith please do you know the answer, anybody??

**Comment by inspectorjair** [comment]
???

**Comment by BimsaraFernando** [comment]
Duplicate issue https://github.com/EvernodeXRPL/evernode-host/issues/308#issuecomment-1928500119
