### ISSUE TITLE
Host status: inactive

### ISSUE THREAD

**Issue by prodevr01** [EvernodeXRPL/evernode-host#293]
Host status: inactive
NOTE: The host is marked as active after sending the first heartbeat.

Sashimono agent status: active
Sashimono message board status: active

Host has been running fine why is it offline what do I need to check?

**Comment by BimsaraFernando** [comment]
Hi, if your host is still inactive, try following command and check whether there are any errors.
`evernode log`

Please close the issue if you have already resolved.

**Comment by prodevr01** [comment]
resolved after a few reboots

**Comment by prodevr01** [comment]
resolved after a few reboots
