### ISSUE TITLE
TRansfer from a host I no longer have access to

### ISSUE THREAD

**Issue by milligans618** [EvernodeXRPL/evernode-host#294]
Hoping someone can help: Lost access to my host. Trying to transfer to new host. able to put account address in then when it asks for me to specify the path of the host account secret: I put in { "xrpl": { "secret": "<your-secret>" } } and keep getting "Invalid Path".... What could I be doing wrong??????

**Comment by BimsaraFernando** [comment]
In the latest installer, you won't be asked a path, but you will be asked for your secret. You can continue from there.
https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300

Please close the issue when you have resolved.

**Comment by BimsaraFernando** [comment]
Hi @milligans618 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
