### ISSUE TITLE
Automatic reward transfer to main address

### ISSUE THREAD

**Issue by jino2ac** [EvernodeXRPL/evernode-host#296]
Good morning,

I would like to know if there is a way to automate the rewards received in the nodes to a "main" address?

thank you

**Comment by BimsaraFernando** [comment]
Hi, there is no direct command to transfer EVRs from the host account to the main account, But you can setup a hook in your host account. Below is a sample developed by the community.
https://github.com/tarviu/EvernodeHook2.7

**Comment by Rritchyx** [comment]
Hi
I'll have look further . Thanks

**Comment by BimsaraFernando** [comment]
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
