### ISSUE TITLE
ERROR CODE:  /tmp/evernode/installer-1706773089

### ISSUE THREAD

**Issue by TodL33** [EvernodeXRPL/evernode-host#302]
I did all this (below) successfully... but have this new error: ERROR CODE:  /tmp/evernode/installer-1706773089
Please let me know what i need to do,
Thank you.

 " add your wallet with your private key to Xaman
so that you have access to the wallet so that you can withdraw funds from there because during the installation you may have a problem that it will not show the already deposited EVRs and that the system will miss you, you will transfer 500EVRs, then you will withdraw them back.
Unzip the archive as written
try using: node index.js address secret
run it
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install "

**Comment by BimsaraFernando** [comment]
Hi, it seems the issue is related to https://github.com/EvernodeXRPL/evernode-host/issues/270 and is already resolved.
closing the issue.

**Comment by TodL33** [comment]
No, this issue was never solved. Please help.

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by TodL33** [comment]
/tmp/evernode/installer-1718350087 this is the new error I got. I submitted this error code in a fresh string.
