### ISSUE TITLE
How change since public node to own xahau node? please 

### ISSUE THREAD

**Issue by inspectorjair** [EvernodeXRPL/evernode-host#304]
Hi Guys, Is there a tutorial on how to create our own xahau node , i create my node public but i dont know how change since public to my own xahau node. please help me anybody???

**Comment by BimsaraFernando** [comment]
Duplicate issue (https://github.com/EvernodeXRPL/evernode-host/issues/308)
Please raise your issue in a Xahau related thread. https://github.com/Xahau/xahaud/issues
Thank you.
