### ISSUE TITLE
strange information in logs

### ISSUE THREAD

**Issue by kyjahub** [EvernodeXRPL/evernode-host#305]
I have failure messages in the log that contain several lists of words that look like dictionnary words in different languages. (Asian and English)
the kind of words asked for a password or seedphrase.

2 hosts on 10 I've checked have this type of messages

both hosts are up and running.

can you analize ?

attached screenshots of the file /tmp/evernode.b9FBm0UQU.log

![image_2024-02-04_122759232](https://github.com/EvernodeXRPL/evernode-host/assets/158814364/7655833c-3d33-4d4e-a872-f661f761b159)

![image_2024-02-04_122821486](https://github.com/EvernodeXRPL/evernode-host/assets/158814364/9a7a371d-5fc6-474b-bf79-a715bee7e8c7)

![image_2024-02-04_122847670](https://github.com/EvernodeXRPL/evernode-host/assets/158814364/dc1c7007-5c61-40b6-93eb-7d491135ee6e)

![image_2024-02-04_122908133](https://github.com/EvernodeXRPL/evernode-host/assets/158814364/6b7e0a83-31ce-4761-b984-32098f4a58bc)

![image_2024-02-04_122929657](https://github.com/EvernodeXRPL/evernode-host/assets/158814364/7d9e0192-f6d7-4a01-83f1-8840793086d1)

**Comment by BimsaraFernando** [comment]
Hi, this has been resolved in the new version.
Thank you!
