### ISSUE TITLE
Reinstall step needs minimum balance of 500 EVR

### ISSUE THREAD

**Issue by isnoor** [EvernodeXRPL/evernode-host#306]
Hi, I have stuck on the first registration process about hours. Then process stopped. I try to transfer process, done. Then when I try to reinstall process, Any errors "The account needs minimum balance of 500 EVR. Current balance is 0.99999999 EVR.". My Xahau account address: r4Z48SLMZ1ChiDk46vjDvEUhtVUuaHAPf1. I believed that I store my secret key.

**Comment by Ingamecredit** [comment]
Hello all, may we have some kind support with one of our setups. We have set up 5+ hosts on evernode and they all work perfectly except for one that looks to have failed. We sent across the 20 Xau and 500 Evrs. So we have been given the addy and it is showing the 500 transaction has gone through on the bithomp explorer. However it still shows as Inactive 

We were looking into the docs @ Transfer the host registration for Replacing a damaged host however we run into the same conditions. 

Is there a way to get the 500 Evers back and just start again or if we reboot the VPS will we loose the registration? 

Hope for some kind help, Cheers Simon

**Comment by BimsaraFernando** [comment]
Hi @isnoor ,

After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)  

If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration )

**Comment by Ingamecredit** [comment]
Hello Bimsara how are you?
We are still getting error saying that 500 evr required however as per
blockchain we have already paid the 500 registration fee


https://xahscan.com/account/r4Z48SLMZ1ChiDk46vjDvEUhtVUuaHAPf1


Appreciate your help

Please see attached blockchain scan and also the image showing minimum
required

**Comment by BimsaraFernando** [comment]
If you tried installing with the existing account r4Z48SLMZ1ChiDk46vjDvEUhtVUuaHAPf1 you will be able to acquire without  500 evr.
Did you try installing by selecting the existing account and giving the secret path of the r4Z48SLMZ1ChiDk46vjDvEUhtVUuaHAPf1 address?

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
