### ISSUE TITLE
There was an error during installation. Please provide the file /tmp/evernode/installer-1707066792

### ISSUE THREAD

**Issue by mikev99901** [EvernodeXRPL/evernode-host#307]
Hello and doog day,
There was an error during installation. Please provide the file /tmp/evernode/installer-1707066792
How to resolve this? 
Did reboot server and restart the installation, press N and continue use exsiting address and enter scrip for secret key path /home/sashimbxrpl/.evernode-host/.host-account-secret.key 
Was able to connect to install but then as process to install got that error msg > There was an error during installation. Please provide the file /tmp/evernode/installer-1707066792

**Comment by BigALDesigner** [comment]
I have the same issue 
There was an error during installation. Please provide the file /tmp/evernode/installer-1707142621.log to Evernode team. Thank you.

**Comment by BigALDesigner** [comment]
Re boot server and start over, worked for me although on the second attempt only.

**Comment by mikev99901** [comment]
> Re boot server and start over, worked for me although on the second attempt only.

I did try that also reboot server and start over but still error mesage installer-1707140591, what are the exact steps you did to get it to install finally? 
![installer-1707140591](https://github.com/EvernodeXRPL/evernode-host/assets/156852432/09c10f20-4897-407e-a01f-e507be85367e)

**Comment by BigALDesigner** [comment]
Hi, I did notice that when you are prompted to insert the secret key location, the line
/home/sas.......................................................ret.key.

**Take care not to copy and insert that full-stop at the end.**

**Comment by mikev99901** [comment]
Hey Bro... thank you for getting back.. Have tried but no luck, i'm bit new in to these configurations. As you noticed section > Specify the path of the Host Account secret: 
At this section seems enters someting incorrect, i do have the secret key, but how need to enter it exactly? 
These are the steps are doing, but not sure in what order need to enter the secret key. 
Have tried enter like this > sudo nano /home/sashimbxrpl/.evernode-host/.host-account-xxxxxxxxxxxxxxxxxxxxxx 
Don't know how to resolve 
![Screenshot 2024-02-08 220041](https://github.com/EvernodeXRPL/evernode-host/assets/156852432/d303c784-7fe6-4a03-aab0-7a07879b7fae)

**Comment by BigALDesigner** [comment]
Are you using an app such as Termius? If you are may I suggest rather trying your normal windows CMD prompt?
If you are new to CMD check that you use the original format command prompt and not Powershell
Will you be comfortable with this avenue? If you aren't I highly recommend watching,
https://www.youtube.com/watch?v=qnXe1gecux8&t=4564s

**Comment by mikev99901** [comment]
Yes i'm using Termius, dont have instructions to connect with server via
CMD prompt by my PC to cloud server running ubuntu

**Comment by BigALDesigner** [comment]
ok, so in cmd prompt type in
ssh root@your url
it will ask for your password
from your server provider manager menu find your server password and copy it
go back to cmd line and left click then right click your mouse (the password will not show for security reasons)
then press enter, you will then be in your server
then type the following in
evernode status
and press enter
go back to the document at
https://docs.google.com/document/d/1n8MSM4aeLN9lGIIFUceHbsVIMFTcX2uWxs00OQA-gDc/edit#heading=h.t8b1grs9rebj
and find where you are in the process

**Comment by BigALDesigner** [comment]
Once you are in cmd prompt you can do the same that you would have done in the other app, just copy and paste the lines from the text in the document.

**Comment by BigALDesigner** [comment]
the path to your secret key, just copy and paste the line as it is, do not insert your secret key

**Comment by BigALDesigner** [comment]
in addition you may need to do this as well before you continue, 
"You'll need to import the secret Key into your Xaman Wallet to get your public key"
Watch the installation video and what they do with the xaman app to create the account.

**Comment by BimsaraFernando** [comment]
Hi @mikev99901 ,
have you resolved the issue? After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)

**Comment by BimsaraFernando** [comment]
Hi @mikev99901 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
