### ISSUE TITLE
Evernode host installation failed, 500 Evers stuck in the process.

### ISSUE THREAD

**Issue by crtten** [EvernodeXRPL/evernode-host#309]
Hello,

This seems to be a not too uncommon issue on these message boards.

I have spun up 5 evernode hosts. 4 went fine, one failed the installation after the 18.2 XAH and 500 EVERS were paid. The error message told me to send the error log to the Evernode team, I'm guessing this is the correct place, so I'm attaching the log file to this post.
[installer-1707253841.log](https://github.com/EvernodeXRPL/evernode-host/files/14187779/installer-1707253841.log)

The installation failed on Creating lease offer 5 of 9.

I have the account address and the secret key, so I can access the account via the Xaman app, but there does not seem to be any way to retrieve the 500 Evers, from what I can tell, the Evers are converted to an NFT as part of the install process.

You can view the transaction history of the account here: 
https://xahau.xrplwin.com/account/rwsYdJ38HuuEekMVijYM8broGqTRGSSaA3

This shows the 500 Evers entering the account, and seemingly being converted to an NFT? I tried to add a second 500 Evers to the account in a second attempt at the installation, but that installation failed too, as the address was already register from the first installation attempt. You will notice that second attempt in the transaction history. I was able to recover those 500 Evers without issue.

Any ideas on how to recover the 500 Evers?

I also tried to reinstall the software as a NOT FRESH install. When the installation process asks for the account address and secret key, it says that the address is already registered and the installation halts. 

So reinstalling as a fresh install and a not fresh install both did not help.

Thank you for any help.

**Comment by scizot** [comment]
Did you try to do a "transfer", and then do a (not fresh) install after that? You might need to have a couple of Evers in the host account to cover fees... This is what happened to me when my NFT didn't mint but my 500 Evers were consumed. I did a transfer, then a non-fresh install, and then it successfully installed.

**Comment by crtten** [comment]
How does one do a "transfer"?

Because the installation failed, i'm not able to run any commands, ie: "evernode transfer" won't do anything because the installation failed.

> Did you try to do a "transfer", and then do a (not fresh) install after that? You might need to have a couple of Evers in the host account to cover fees... This is what happened to me when my NFT didn't mint but my 500 Evers were consumed. I did a transfer, then a non-fresh install, and then it successfully installed.

**Comment by scizot** [comment]
See https://github.com/EvernodeXRPL/evernode-docs/blob/main/docs/source/hosts/maintenance.md, and be sure to save the value of your secret key just in case something goes wrong (/home/sashimbxrpl/.evernode-host/.host-account-secret.key).  You can go do a "transfer" (while in a not-installed state) by running the evernode.sh installer using the command shown below (or also see the maintenance.md link I provided), then you'll be able re-install (after the "transfer") back to the same machine as a "not fresh" install... At least that is what worked for me in a very similar scenario.

Good luck! Take it one step at a time in the right sequence, and I think you'll recover. Also have a couple of EVRs in your host account in case the process needs it to transact.

--------------------------------------------------------------

Recovering from a Failed Update

In the event of a failure, the secret will not be deleted and will remain at the default secret file location or the custom location you have specified. If you wish to reinstall, use the following command and transfer the registration using the same account on a separate machine. Then try re-installing on your machine.

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

**Comment by BimsaraFernando** [comment]
Hi @crtten,
After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)

**Comment by BimsaraFernando** [comment]
Hi @crtten ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
