### ISSUE TITLE
/tmp/evernode/installer-1707327649.log

### ISSUE THREAD

**Issue by hips1986** [EvernodeXRPL/evernode-host#310]

**Comment by hips1986** [comment]
My istall failed with this log. Any help would be appreciated

**Comment by BimsaraFernando** [comment]
Hi, Please locate the log file /tmp/evernode/installer-1707327649.log and share.

After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300) 

Try installing it again. If it fails try transfer and reinstall. 
If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration)

**Comment by BimsaraFernando** [comment]
Hi @hips1986 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
