### ISSUE TITLE
Installation error => Completed normally. oh my god. thank you

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#312]
Do you want to connect to the default rippled server (wss://xahau.network)? [Y/n]y

Checking server wss://xahau.network...
Using Rippled server 'wss://xahau.network'.

Specify the Xahau account address: rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF
Checking account rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF...
Host is not registered.
Specify the Xahau account address: rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF
Checking account rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF...
Host is not registered.
Specify the Xahau account address: ^C

**Comment by BimsaraFernando** [comment]
Hi, it seems your issue is resolved.
We are closing the issue.
