### ISSUE TITLE
How to get 500 EVR refund after failed install ?

### ISSUE THREAD

**Issue by phist0** [EvernodeXRPL/evernode-host#316]
Installation failed on two nodes and attempt to transfer and re-install is requesting fresh 500 EVR for each of the two nodes. How to get the 500 EVR refund for both nodes ?  Installation logs attached for both nodes.
[ipa13_evernode_installer-1707606603.log](https://github.com/EvernodeXRPL/evernode-host/files/14235018/ipa13_evernode_installer-1707606603.log)
[ipa16_installer-1707625838.log](https://github.com/EvernodeXRPL/evernode-host/files/14235019/ipa16_installer-1707625838.log)

**Comment by BimsaraFernando** [comment]
Hi, It seems you have resolved your issue. Your hosts are up and running.
Closing the issue.
