### ISSUE TITLE
Suddenly the deposit wasn't made today. Please confirm.

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#317]
Deposit normal on the previous day (02.10)
Deposit normal on the previous day (02.11)
Today (02.12) there were no deposit transactions and the evernode status was normal.

Host account address: rMDFSGWhe7pVbkHaoP5G6dpWfybYbUaA5U
Host account address: rwR49GA9sVMLGBUir2mTVz7WheXTUQGBWF

Please confirm.

**Comment by MarkoinFr** [comment]
Me too, and a mate. No evr deposit today despite hourly heartbeats all day yesterday. 
For me in my timezone payments are normally made at 05:45'ish daily. But today this transaction did not occur, not even a heartbeat.

Affected wallets below

My public key: rsKbm5yHgXEsEjvK7HiKsjMrKjKjH12EKs
My mates public key: rP95u2gvjtDFuRiSqBZaKKC34wi8pkCvWJ

**Comment by MarkoinFr** [comment]
Apparently they accumulate if not auto paid daily. Check again tomorrow.

**Comment by BLUEDIAA** [comment]
I checked today and saw that the previous day's amount had been accumulated and deposited. thank you.

**Comment by BimsaraFernando** [comment]
Hi, looks like your issue is resolved. Closing the issue.
