### ISSUE TITLE
There was an error during installation. Please provide the file /tmp/evernode/installer-1707783289.log to Evernode team

### ISSUE THREAD

**Issue by sffpeu** [EvernodeXRPL/evernode-host#320]
Hello,

While installing this "error" message showed up. We have looked at some suggested solutions already (transferring host & reinstalling evernode) all of which resulted in the same failure. 

"There was an error during installation. Please provide the file /tmp/evernode/installer-1707783289.log to Evernode team. Thank you."

Can anyone help please? Also where can we locate the .log file?

Thanks!

**Comment by BimsaraFernando** [comment]
you can see the log file using this command
cat /tmp/evernode/installer-1707783289.log

After the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)

**Comment by BimsaraFernando** [comment]
Hi @futurexfuture ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
