### ISSUE TITLE
Error during installation how do i get my 500evr back?

### ISSUE THREAD

**Issue by xrparnie** [EvernodeXRPL/evernode-host#321]
Error during installation massage at the very end file /tmp/evernode/installer-1707786652.log  
Tried different things but can't install host, can't get my 500 evr back

**Comment by BimsaraFernando** [comment]
Hi, Please locate the log file here  /tmp/evernode/installer-1707786652.log and share.

after the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)

Try installing it again. If it fails try transfer and reinstall.

If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration)

**Comment by BimsaraFernando** [comment]
Hi @xrparnie ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
