### ISSUE TITLE
Issue installing my node

### ISSUE THREAD

**Issue by Furiousfreud** [EvernodeXRPL/evernode-host#322]
Hi I have ran into some issues installing my node, I got the message 'There was an error during installation. Please provide file tmp/evernode/installer-1707491548.log to Evernode team.  Thank you.
What should I do to solve the issue?

**Comment by BimsaraFernando** [comment]
Hi,  Please locate the log file here tmp/evernode/installer-1707491548.log and share.

after the latest Evernode Installer update release we have improved the installation script with bug fixes. Using the latest installation script will solve the issue. (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)

Try installing again if it fails try transfer and reinstall.

If you are transferring the host registration, please follow the transfer guide (https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration)

**Comment by BimsaraFernando** [comment]
Hi @Furiousfreud ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
