### ISSUE TITLE
Redeeming true to get evers back 

### ISSUE THREAD

**Issue by Valuate** [EvernodeXRPL/evernode-host#324]
I have two hosts for evernode which are not working (i think because wrong CPUmodel). The problem is that I have been messing around with the installations and now I have actually lost the installations but also the logs to. the secret key's. But among the messing around, I added both to Xaman in between, so I do have access to the accounts.

Now i was wondering if there is a possibility to redeeming my registration NFT with the registry hook trough Xaman? i am fine with the 50% back

**Comment by BimsaraFernando** [comment]
If you have the secrets, you can try installing with the latest installer 
https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300

**Comment by BimsaraFernando** [comment]
Hi @Valuate ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
