### ISSUE TITLE
Host Lost 

### ISSUE THREAD

**Issue by Bitbob589** [EvernodeXRPL/evernode-host#325]
Hi, I was having issues connecting my Evernode host to my Xahau node, and in the process, I had to reinstall my Ubuntu on my VPS and lost the host. I then realized I forgot to take note of the secret key, so I could not transfer the host. I wondered if there were any options to retrieve the host or purge it for a 250 EVR refund.

**Comment by EpicShah** [comment]
if u dont have secret key, its gone! cant be returned unfortunately, it happened to me already in the very beginning

**Comment by BimsaraFernando** [comment]
Once the account generation step is passed, your secret will be stored in the specified path. so you should back up your secret before trying any diagnostics.
