### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by herkimer9** [EvernodeXRPL/evernode-host#333]
I got this message 

Please specify the domain name that this host is reachable at: evernode3.xyz
Verifying domain evernode3.xyz on port 80...
mkfifo: cannot create fifo '/tmp/evernode-setup-helpers/helper_fifo': File exists
Invalid or unreachable domain name.

**Comment by BimsaraFernando** [comment]
Hi @herkimer9 ,
Please check whether you have entered a valid domain. Also, verify that you have a DNS record pointing to your VM's IP address. If all are satisfied try installing again with the latest installer (https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1976031300)

**Comment by BimsaraFernando** [comment]
Hi @herkimer9 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
