### ISSUE TITLE
Instalation error at end, Evernode not Running, lost my ERV

### ISSUE THREAD

**Issue by Xaycomindelo** [EvernodeXRPL/evernode-host#334]
Just finished evernode instalation on my server, paid all that asked to and at the very end gave me a error. 
The Log is empty, if I try to reinstall is asking for more 500EVR, I wont pay fee again.
If I follow the "Recovering from a Failed Update", terminal is giving me "host is not registered"

Please check for solution or return my EVR to my wallet address: r4M9PWk8xQM9hHRqchYRnRNNR1QzwChvqu

Thanks.

**Comment by Xaycomindelo** [comment]
Please Help.

**Comment by BLUEDIAA** [comment]
> You need to prepare the following 3 things: prepare your own host address, 1 evr required, prepare security file path
> New installation progress question: Proceed with “N”
=> After transferring, proceed with install.

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

**Comment by Xaycomindelo** [comment]
Still the same problem. When transfer:

Specify the Xahau account address: r4M9PWk8xQM9hHRqchYRnRNNR1QzwChvqu
Checking account r4M9PWk8xQM9hHRqchYRnRNNR1QzwChvqu...
Account not found.

New Install:
Creating Message-board User...
Specify the Xahau account address: r4M9PWk8xQM9hHRqchYRnRNNR1QzwChvqu
Checking account r4M9PWk8xQM9hHRqchYRnRNNR1QzwChvqu...
**Host is not registered.**

**Comment by BLUEDIAA** [comment]
Sorry, I'm not an expert on the evernode system. I was trying to help you by looking at the error message. If an error continues to occur, **you should join Discord and talk to people who work on the Evernode system to resolve the issue.** I'm sorry I couldn't help you.

**Comment by BimsaraFernando** [comment]
Please use the latest install command in the Evernode docs https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation . Use the existing host account secret and try again. If the issue persists, share the error log file content.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
