### ISSUE TITLE
Unsuccessful Installation

### ISSUE THREAD

**Issue by lendlycagata** [EvernodeXRPL/evernode-host#335]
error: There was an error during installation. Please provide the file /tmp/evernode/installer-1708388213.log to Evernode team. Thank you.

address : rw7sNZ6P39qeT4tmHP9CxUrPc2NtBf1goU

Host not registered

**Comment by BimsaraFernando** [comment]
Hi, it seems like your host rw7sNZ6P39qeT4tmHP9CxUrPc2NtBf1goU is up and running. If the problem is resolved, please close the issue.
Thank you!

**Comment by BimsaraFernando** [comment]
@lendlycagata ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
