### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by SWS9** [EvernodeXRPL/evernode-host#336]
I was installing Evernode.
500 EVR was withdrawn from my wallet.
Node installation stopped with an error.
What should I do?

address is 
rEgpUU4C3kYzemRBjoTRWrowHYG9zryjdB

I cannot find any NFTs in myNFT on xahauexplorer.

![스크린샷 2024-02-22 오후 1 32 23](https://github.com/EvernodeXRPL/evernode-host/assets/28282187/090a1b85-a6ae-4797-8c90-a9b6851244d9)

**Comment by BimsaraFernando** [comment]
It seems like your host rEgpUU4C3kYzemRBjoTRWrowHYG9zryjdB is up and running. Do you still encounter any errors? if the issue is resolved, please close the issue.
Thanks.

**Comment by mworks-proj** [comment]
Please update this issue. Looks like your node is on the heartbeat.

**Comment by BimsaraFernando** [comment]
Hi @SWS9 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
