### ISSUE TITLE
Transfer of NFT

### ISSUE THREAD

**Issue by kenmck3772** [EvernodeXRPL/evernode-host#339]
Is it possible to transfer an NFT to a new host. I have access to the wallet but no secret key.

 rn2avRyaJ29u1G5CLEVssh2391b3x4J6Ee

**Comment by kenmck3772** [comment]
I've got another 13 nodes working perfectly though.

**Comment by chalith** [comment]
> Is it possible to transfer an NFT to a new host. I have access to the wallet but no secret key.

Did you vipe the VM which you were trying to install rn2avRyaJ29u1G5CLEVssh2391b3x4J6Ee?

**Comment by BimsaraFernando** [comment]
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
