### ISSUE TITLE
InsufficientNetworkMode

### ISSUE THREAD

**Issue by Clevernode** [EvernodeXRPL/evernode-host#341]
![signal-2024-02-26-230224_002](https://github.com/EvernodeXRPL/evernode-host/assets/160278019/d9dfb9ad-232a-4175-80b0-d071ad2efa06)

After switching hosts to our own Xahau node today (halving?) there is an issue. 
Hosts appear offline, switching back to public Xahau node is not possible, see screenshot.

**Comment by chalith** [comment]
Are you still getting this error? InsufficientNetworkMode error can appear when the xahaud node you are trying to connect is in sync. This is temporary and be resolved after some time

**Comment by BimsaraFernando** [comment]
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If the issue still persists, please reopen.
