### ISSUE TITLE
I'm doing a maintenance

### ISSUE THREAD

**Issue by lendlycagata** [EvernodeXRPL/evernode-host#344]
Host: r9DJKDtBrHWaAemTFe65LcS55EjVc835Go

did transfer good,. then install failed /tmp/evernode/installer-1709225801.log 

tried again : Host is not registered

tried your solution 1, solution 2 

tried : claimed token node index.js <><>

sell offer was found - but not successful claiming the token

**Comment by lendlycagata** [comment]
![image](https://github.com/EvernodeXRPL/evernode-host/assets/38574713/d7d022ab-6a2a-413e-aa36-70ce5dfd7876)

**Comment by lendlycagata** [comment]
If you run **** transfer it will end up Host is not registered

If you run claim token: node index.js <><> - end up sell offer found then quit - no claim success message

If I run ***install in the new VPS/machine it may looks good at start but end up

![image](https://github.com/EvernodeXRPL/evernode-host/assets/38574713/c4d20751-613a-404c-8f0a-b9551f758dd3)

**Comment by lendlycagata** [comment]
tried to update 0.8.2 - still failed

**Comment by mworks-proj** [comment]
Are you connected to default  xahau wss?

**Comment by lendlycagata** [comment]
yes sir,. I done all TS in the documentation
somehow transaction was stuck somewhere in the system
I first run a transfer in the machine-2 good ,. then when I install it's stuck with log path..
and so I run the claim token -- won't end up good stop in seller found
tried my luck again in transfer then install many times same error,. and then when I run transfer on the third time message is HOST is not register.. I had this case before and it's just work fine just keep trying in install..

And so I decided to make a new install in machine-2 works good accumulating reward
Go back to bad-machine reformat and reinstall OS hoping I can reinstate
And since then tried everything
- uninstall - HOST not register
- claim token -- end up seller found and drop not success
- install - looks good at start but end up with log path error
- deregister -- error on the process of deregistration
- update - no evernode install in the machine
I'm end of the road @mworks-proj hope you can help me

**Comment by lendlycagata** [comment]
@mworks-proj -- any update? any idea how to fix this?

**Comment by lendlycagata** [comment]
Can somebody look into my host and tell me what to do?
r9DJKDtBrHWaAemTFe65LcS55EjVc835Go
uninstall - HOST not register
claim token -- end up seller found and drop not success
install - looks good at start but end up with log path error
deregister -- error on the process of deregistration
update - no evernode install in the machine

Can I still have my EVR back

**Comment by chalith** [comment]
Looks like your registration is in transfer mode. And you were trying with old installer. Try installing again with `curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-test-resources/main/sashimono/installer/evernode.sh | sudo bash -s install`

**Comment by lendlycagata** [comment]
@chalith thanks! your the man..
