### ISSUE TITLE
Problem Importing Private Key into XUMM on Linux - After XAH Deposit, Before EVR Deposit

### ISSUE THREAD

**Issue by razim88** [EvernodeXRPL/evernode-host#346]
Hello everyone,

I'm currently facing an issue with importing a private key into XUMM for my Evernode account on a Linux server. The situation is as follows: I've successfully deposited XAH, which is confirmed on the blockchain. Now, before moving forward with depositing 500 EVR, I aimed to ensure the account could be accurately imported into XUMM. However, I'm met with an "Invalid secret key" error during the attempt.

The steps taken were:

Opening and verifying the private key with nano, making sure there are no extraneous spaces or characters.
Trying to import the key into XUMM exactly as shown.
Encountering the error message in XUMM about the key being invalid.
I'm certain of the private key's correctness and formatting. After scouring system logs for any related activities that might have impacted this process, nothing unusual popped up.

In my search for solutions, I came across a case where someone resolved a similar issue by substituting their private key with that from another account. As my Evernode installation is still in progress and I'm awaiting the transfer of EVRs, I'm contemplating whether to halt the installation, switch the private key, and then restart the entire installation while retaining the newly changed key.

This leads me to a couple of questions:

Has anyone experienced something similar, or does anyone know how I might resolve this importing problem? I'd appreciate any advice on correctly importing the private key into XUMM or verifying the key's format.
Furthermore, what are considered best practices for storing the private key on an Evernode server? Is it possible to encrypt this key, and if so, would encryption interfere with Evernode's functionality?
Thank you in advance for your insights and assistance!

**Comment by chalith** [comment]
One solution is you can backup your host secret key then delete the key file from VM and then start over with a freshly generated account. But in this case you will have to find a way to transfer XAHs from the account you backed up without exporting it to XUMM

**Comment by BimsaraFernando** [comment]
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
