### ISSUE TITLE
Installation error Submitter log File

### ISSUE THREAD

**Issue by mrezagh1984** [EvernodeXRPL/evernode-host#347]
![Uploading WhatsApp Image 2024-03-04 at 1.36.18 PM.jpeg…]()
[installer-1709545692.log](https://github.com/EvernodeXRPL/evernode-host/files/14479844/installer-1709545692.log)
[installer-1709541532.log](https://github.com/EvernodeXRPL/evernode-host/files/14479846/installer-1709541532.log)

My 500 Evr Balance is lost kindly assist

**Comment by chalith** [comment]
Are you trying transfer a registration? Check EVR balance in your account? You should have 0.00000001EVRs in your account to install a transferred registration

**Comment by mrezagh1984** [comment]
I still have problem. My host is active my balance in daahboard is 1000 evr
but in my wallet balance is 0.9

**Comment by chalith** [comment]
Is this related to the same issue https://github.com/EvernodeXRPL/evernode-host/issues/348

**Comment by BimsaraFernando** [comment]
Hope this issue is resolved by now. If not please reopen
