### ISSUE TITLE
issue with account balance and last heartbeat sent

### ISSUE THREAD

**Issue by mrezagh1984** [EvernodeXRPL/evernode-host#348]
![WhatsApp Image 2024-03-04 at 4 30 53 PM](https://github.com/EvernodeXRPL/evernode-host/assets/162114844/3f055bf2-7f42-4c28-86b3-0d4680f7d0c2)
![WhatsApp Image 2024-03-04 at 4 22 53 PM](https://github.com/EvernodeXRPL/evernode-host/assets/162114844/625a1f11-ca20-4f6a-9702-c35eca8ca63d)
![WhatsApp Image 2024-03-04 at 4 22 23 PM](https://github.com/EvernodeXRPL/evernode-host/assets/162114844/ac4476b7-1bdd-49e2-afe0-2d7aa1b74faf)

Please guide me: my account balance in dashboard is 1000 Evr but in my wallet it does not show

Also In the dashboard last heart beat is stated 52 years ago

PLZ guide me this happened when I transfered my host due to host damage during installation

My evernode status sais it is active

**Comment by chalith** [comment]
It's not 1000. It's showing 1.000, Check here https://explorer.xahau.network/rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu/lines
- Did your installation succeed?
- Check whether you have a pending reboot. Try rebooting your machine.
- Further, you should run `evernode offerlease` and offer all the leases to be able to send heartbeats

**Comment by mrezagh1984** [comment]
I did all steps. I have transfered 500 evr twice.will it be returned

**Comment by mrezagh1984** [comment]
https://xahscan.com/account/rHWfFAv59jJMEV9kpqksRxZCzLjTWzQP2v

If you chick the transactions i have sent 500 evr twice by mistake. How can
i get it back

Thank you fir your assistance

**Comment by chalith** [comment]
This is the account you are registered in Evernode https://xahscan.com/account/rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu, And it's the host account. It's stored in your host VM.
Check what accounts you've sent 500EVRs and see they are in your control.

Try running `evernode status` and `evernode log` in your host and see if there're any erros

**Comment by BimsaraFernando** [comment]
Hope this issue is reolved by now. If not, please reopen.
