### ISSUE TITLE
Host reputation

### ISSUE THREAD

**Issue by an9218** [EvernodeXRPL/evernode-host#349]
After update I get 0 reputation of my node, but I can't understand why and how to resolve.
I have 18 instances, lease 0.001

domain: everhooks.link

**Comment by an9218** [comment]
already everything ok

**Comment by mworks-proj** [comment]
What was the solution?

**Comment by an9218** [comment]
> What was the solution?

after 1 hour about become to normal. But I tried change lease amount to 0.01 and back to 0.001.
