### ISSUE TITLE
No reward after 48 hours

### ISSUE THREAD

**Issue by siasiab1** [EvernodeXRPL/evernode-host#350]
Dear sir

My node is running with no issue and evernode status on ubento and on dashboard is ok but I have 0 accumulated rewads.
Heartbreak is ok everything is ok but no rewatds aftet 48 h
N5.evernodegateway.com

Plz assist

**Comment by chalith** [comment]
![image](https://github.com/EvernodeXRPL/evernode-host/assets/14144162/c2b9ee1b-9c91-4c07-bfb9-df3c6fc188d1)
![image](https://github.com/EvernodeXRPL/evernode-host/assets/14144162/2dd896ee-6e30-415f-8799-e8569184e72f)

Check your host's reputation and wether you adhere to these guidelines

What are your instance count and lease fee?

**Comment by siasiab1** [comment]
![Screenshot_20240306_131049_com server auditor ssh client](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/8345b3f4-5b1f-4cc9-8ddc-d9c123f6dd04)
Thank you for your assistance

How can i change instance. To change instance count do i have to reinstall or there is CLI for this

Wheni want to change instance it gives me invalid argument as attached

**Comment by chalith** [comment]
https://docs.evernode.org/en/latest/hosts/evernode-host.html#installation

Use `evernode config resources <ram> <swap> <disk> <Instance count>` and `evernode config leaseamt <lease amount>`

**Comment by siasiab1** [comment]
Plz check attaced photo it gives invalid argument i have not set ip v6

**Comment by chalith** [comment]
`evernode config resources 0 0 0 3` for instance count

**Comment by siasiab1** [comment]
thank you problom solved
 your assistance is highly appreciated

**Comment by siasiab1** [comment]
![Uploading 343434.png…]()
Dear sir on another node any evernode commande i enter gives me huge amount of code as attached
![121212121212](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/e3b4ff1c-bbc5-43dd-aa17-ae27a0a5c23e)
 Kindly assist

**Comment by chalith** [comment]
Is this still in version 0.8.1? Are you using `xahau.network` as your primary xahau server? Try again and check whether it resolves after some time.

**Comment by siasiab1** [comment]
how can I check primary server and and how can I change it

**Comment by chalith** [comment]
Do you have a own xahaud server?

**Comment by siasiab1** [comment]
I have vps server

**Comment by chalith** [comment]
Can you try `evernode status`. Whether it works

**Comment by siasiab1** [comment]
![343434](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/517f2b3a-4e5a-4b27-8e4c-ae57723dab65)
![Uploading 121212121212.png…]()
when I try evernode status it gives me code errors I have attached
![343434](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/517f2b3a-4e5a-4b27-8e4c-ae57723dab65)
