### ISSUE TITLE
two similar host. Host not unregistered

### ISSUE THREAD

**Issue by siasiab1** [EvernodeXRPL/evernode-host#351]
dear Sir,

I have INSTALLED a node first but than transfered it to a new host. But in the dashboard i still see 2 nodes with same domain and name. I could not get back my EVR from the forst onne that hast stated transfered in the dashboard (see attached scrfeen shot)

Did I uninstalled it wrong and can you provide guidance as to how I can uninstall it and get back my EVR . should I uninstall on a ubento that has no evernode installed?
![45454545](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/45de5eb6-2bcc-4191-bd68-2db33909c108)

**Comment by chalith** [comment]
Is the second one active and operating? Can you give me two host addresses?

**Comment by siasiab1** [comment]
n4.evernodegateway.com

both are with same host address

What address do you require

**Comment by siasiab1** [comment]
I need  to deregister and uninstall one of them to get 500 evr refund

**Comment by chalith** [comment]
So you have two VMs? One is evernode installed other one is transferred?

**Comment by siasiab1** [comment]
I have one VPS

first I installed and registed n4.evernodegateway.com but my installation was damaged. I uninstalled ubento and re installed it and transferd the first to new installed ubento

I have spent 500 Evr twice for same host and n4.evernodegateway.com domain

**Comment by chalith** [comment]
So you have installed evernode but the installation damaged. So you transferred and then uninstalled ubuntu?

**Comment by chalith** [comment]
In Evernode your identification is xahau address, not the domain. It seems you have transferred your first installation and then you again did a fresh installation. What you should've done is transfer your first registration and install using the same host address.

Now is your host active?

**Comment by siasiab1** [comment]
![33333333](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/9f814fd4-e096-4e95-96a1-ed638e9e3cb1)
First I installed ubento on my VPS
I registered host but my host  was damaged
I deleted my ubento without uninstalling and unregestering host

On the new ubento I ran transfer command. I taransferd and installed new host. transfer was ok but did not show my 500 EVR so I sent 500 Evr again. It registered my host successfully this time but in the dashboard I got two nodes with same name and now on the new host I get error running evernode commands and cant update or do anything

I can give you my ubento access if you want

**Comment by chalith** [comment]
Do you have your first xahau address and secret you got when you were installing?

**Comment by siasiab1** [comment]
yes I have both the first one and the second one. I have both

**Comment by chalith** [comment]
Guess you have since you had to specify that when you were transferring. Run `cat /etc/sashimono/mb-xrpl/mb-xrpl.cfg` and send the `address` you see.

**Comment by siasiab1** [comment]
rLtPbdgq56M9EA6xQ7LuzRYxjoGdMFtk1r

**Comment by chalith** [comment]
Is this the second one or first one?

**Comment by siasiab1** [comment]
the second one

**Comment by chalith** [comment]
what is the first one

**Comment by siasiab1** [comment]
rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu

This is the forst One wich has two 500 Evr blocked in it

**Comment by siasiab1** [comment]
![33333333](https://github.com/EvernodeXRPL/evernode-host/assets/43685983/15b33434-786d-45bc-b784-d8914ba9e278)
when I want to run evernode uninstall cli it gives me error (see attached photo)

**Comment by chalith** [comment]
So it seems now you have two hosts registered on Evernode. You could've used rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu when you were installing again on the VM, so you woudn;t have to spend 500 more.

If you deregister now you'll only get half of your registration fee since you have performed above operations. If you haven't transferred the first one you could get whole 500 back.

One option is you can install these on two machines and earn rewards so you won't miss any.

rLtPbdgq56M9EA6xQ7LuzRYxjoGdMFtk1r -registered
You can transfer this installation and reinstall on the machine.
rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu - transferred
You can directly install this on the machine

When installing only use `curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-test-resources/main/sashimono/installer/evernode.sh | sudo bash -s install`. You don't have to execute any other update commands since this gives you the latest

**Comment by siasiab1** [comment]
in new installation do I have to change domain to other than n4.evernodegateway.com?

and what do I have to do in order for the two  n4 domain to be removed from dashboard?

**Comment by chalith** [comment]
Are you planing to install on two machines? Specify the domain which points to your VM. For your current VM it would be `n4.evernodegateway.com`.

**Comment by siasiab1** [comment]
yes I plan to install on two machines.

**Comment by chalith** [comment]
Ok, when installing use rLtPbdgq56M9EA6xQ7LuzRYxjoGdMFtk1r for one machine and rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu for other. You will be asked your domain when installing, So give it the domain which points to your machine. So dashboard records will be updated with your new domains

**Comment by chalith** [comment]
Comment here if you get any errors in the process

**Comment by siasiab1** [comment]
Do you want to set the current host account as the transferee's account? [Y/n] 

what should i do now y or n. for transfering?

**Comment by chalith** [comment]
give it y. Default will be y anyways

**Comment by siasiab1** [comment]
thank you
I will give results

**Comment by siasiab1** [comment]
curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

there is difference between these two install links 

curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-test-resources/main/sashimono/installer/evernode.sh | sudo bash -s install

The last one says vernode-test-resources 

which one is correct?

**Comment by chalith** [comment]
The second one is correct, It's the latest version

**Comment by siasiab1** [comment]
thank you

**Comment by siasiab1** [comment]
Do you want to specify fallback rippled servers? [y/N] 

what should i state here?

**Comment by chalith** [comment]
If you don't have fallback servers just N

**Comment by siasiab1** [comment]
Do you want to set the current host account as the transferee's account? [Y/n
yes or no?

**Comment by chalith** [comment]
yes

**Comment by siasiab1** [comment]
Do you want to use the default key file path /home/sashimbxrpl/.evernode-host/.host-account-secret.key to save the new account key? [Y/n] 

yes or no?

**Comment by chalith** [comment]
yes

**Comment by siasiab1** [comment]
it whants xah again what shall i do

**Comment by chalith** [comment]
You can transfer from another account

**Comment by siasiab1** [comment]
Minted lease 6 of 6.
Installation successful! Installation log can be found at /tmp/evernode/installer-1709734535.log 

Your system is now registered on Evernode. You can check your system status with 'evernode status' command. 

NOTE: Installation will only mint the lease tokens. Please use 'evernode offerlease' command to create offers for the minted lease tokens. 
The host becomes eligible to send heartbeats after generating offers for minted lease tokens.
You need to logout and log back in, to complete Sashimono installation.

**Comment by chalith** [comment]
Run `evernode offerlease` command to offer leases

**Comment by siasiab1** [comment]
there is still two n4.evernodegateway.com on the dashboard and still not active


plz check dashboard

**Comment by chalith** [comment]
You have only installed one host yet right? Once you install the next host with next xahau address it will be resolved

**Comment by siasiab1** [comment]
for the next one should I do same process ?

**Comment by chalith** [comment]
Yes, You might not need to transfer if you've already done

**Comment by siasiab1** [comment]
This will deregister rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu from Evernode while allowing you to transfer the registration to same account. 
 Note: If there are partial registrations, This process will first complete the registration and then it will be deregistered. 

Are you sure you want to transfer Evernode registration? [Y/n] y

Error occured in transfer process. Check the error and try again.

**Comment by chalith** [comment]
rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu is already transferred right? You don't have to transfer again. Just install

**Comment by siasiab1** [comment]
installation and registered successfully. Now the dashboard should be updated

**Comment by siasiab1** [comment]
still dashboard shows same

**Comment by chalith** [comment]
If both are successful then it should be. I think it might not be immediately. It will take some time.

**Comment by siasiab1** [comment]
Thank you for your time and assistance. I is highly appreciated. You are the best

I will inform you if it was not fixed

**Comment by siasiab1** [comment]
whay n4.evernodegateway is offline?

the other one is ok

can you check dashborad plz

**Comment by chalith** [comment]
https://xahauexplorer.com/explorer/rLtPbdgq56M9EA6xQ7LuzRYxjoGdMFtk1r
https://xahauexplorer.com/explorer/rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu

Check under account information it's updated in the ledger.
Make sure to run `evernode offerlease` in the second host as well

**Comment by siasiab1** [comment]
I did on both but the forst one whixh is n4 is not online

**Comment by siasiab1** [comment]
There was an error in creating lease offers.
Starting the message board...

**Comment by siasiab1** [comment]
oot@node04-virtual-machine:~# evernode offerlease
Stopping the message board...
No unoffered leases.
CLI_OUT: LEASE_OFFER_ERR
MB_CLI_EXITED
There was an error in creating lease offers.
Starting the message board...

**Comment by siasiab1** [comment]
I think everything is ok now I have to give it time

**Comment by chalith** [comment]
Yes, heartbeat will be scheduled. Host will be active when it sends the heartbeat at the scheduled time within the next hour.

Close the issue if you think it's resolved

**Comment by siasiab1** [comment]
Thank you so much

**Comment by siasiab1** [comment]
rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu

I have sent 500 Evr twice to this account how can I get it back.
