### ISSUE TITLE
regarding issue #351 

### ISSUE THREAD

**Issue by siasiab1** [EvernodeXRPL/evernode-host#352]
rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu

regarding issue #351 I have sent 500 evr twice to this account. 500 spent for registration . the other 500 how can I get it back?

**Comment by chalith** [comment]
There's only one 500EVR transaction to that account in the history

https://xahscan.com/account/rGAu4imxWu5qWd4jEQekY4joJHYXDfxkcu

**Comment by siasiab1** [comment]
tnx
