### ISSUE TITLE
the host does not receive a pulse within 24 hours after updating to version 0.8.2

### ISSUE THREAD

**Issue by FUNDBaron** [EvernodeXRPL/evernode-host#355]
Guys, I don’t understand what’s wrong.
Yesterday I updated the nodes to version 0.8.2 and all the nodes were updated. But one node was updated successfully but did not receive a single heartbeat in 24 hours. in the end, . In the end, I decided to make the transfer and then an error occurred. I continued to transfer and eventually received a message that my host had been successfully transfered. Then I started installing this host again and everything was installed successfully, but within 24 hours the host did not receive more than one pulse heartbeat. I don't understand what to do.
all other nodes  receive a pulse every hour but one node no pulse

address node: rJdL47Mrx9RM89MnSCQ3KREwBqpj31XRZs

Why has the sashimono message board status: activating on this node for so long, while other nodes have been status active?
When will he change?

<img width="1002" alt="evr_node1" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/71d366b5-3dc1-409f-92f5-be4e3c08c6d8">
<img width="1325" alt="evr_node_1_1" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/56a0260f-00f5-48a2-a487-f8e33b14dfcb">
<img width="796" alt="Снимок экрана 2024-03-09 в 20 12 28" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/1247b330-dead-4282-8bb1-3d22e892678d">
<img width="393" alt="Снимок экрана 2024-03-09 в 20 13 35" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/5472ce5f-a051-4e99-8717-0b42983a2410">
<img width="1323" alt="Снимок экрана 2024-03-09 в 22 23 29" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/74c76683-2396-47a5-a06d-3ca5a57e7bfd">
<img width="1215" alt="Снимок экрана 2024-03-09 в 22 18 53" src="https://github.com/EvernodeXRPL/evernode-host/assets/24420426/b39acdbb-1ea6-4e24-bdbd-8c8062c55f84">

**Comment by chalith** [comment]
It seems you are having some issues with your systemd journal configurations. Did you try transferring registration and then viping the VPS and installing again?

**Comment by BimsaraFernando** [comment]
Hi @FUNDBaron ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
