### ISSUE TITLE
evernode status Error occurred while re-connecting to the primary server

### ISSUE THREAD

**Issue by siasiab1** [EvernodeXRPL/evernode-host#356]
root@88880:~# evernode status
Version: 0.8.2
Host account address: rUXbuGCWg5wGSgh8GSyZBeJPXhXBMSvW4J
Governor address: rBvKgF3jSZWdJcwSsmoJspoXLLDVLDp6jg
Error occurred while re-connecting to the primary server
Error occurred when retrieving account info.
MB_CLI_EXITED

**Comment by chalith** [comment]
Are you using the xahau.network as your xahaud server?

**Comment by siasiab1** [comment]
I have installed my own xahaud node

wss.evernodegateway.com

**Comment by chalith** [comment]
Is your xahaud server up and running? Firewall rules and ports are open?

**Comment by chalith** [comment]
duplicate https://github.com/EvernodeXRPL/evernode-host/issues/362

**Comment by BimsaraFernando** [comment]
@siasiab1 ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
