### ISSUE TITLE
Host Reputation set to zero

### ISSUE THREAD

**Issue by EvernodeSoz** [EvernodeXRPL/evernode-host#357]
After running my host for nearly 2 months, my reputation was set to 0 and I have stopped accumulating EVRS. Does anyone know why this could happen and how do I go about restoring my reputation back to 200? There doesn't seem to be anyone to contact officially on the Evernode.org site.

**Comment by chalith** [comment]
@EvernodeSoz check your host satisfies reputation requirements. https://docs.evernode.org/en/latest/hosts/evernode-host.html#host-reputation. Minimum 3 instances. Lease fee should be less than 0.3 and should not be 0. And you should be not in a sanctioned country

**Comment by EvernodeSoz** [comment]
Issue Fixed...
Dropped Lease amount to below maximum lease allowed and updated version.
