### ISSUE TITLE
Fresh New Build Show "Host Status: inactive"

### ISSUE THREAD

**Issue by tim2min** [EvernodeXRPL/evernode-host#358]
Hello I was told it could take some time before the host will show "Active" but that is not the case the Sashimono agent and message board status show "active"

Is there some other things I need to check or do?

**Comment by chalith** [comment]
If your host status shows inactive even after an hour. Check whether you have unoffered leases, If so execute `evernode offerlease`. If it's still inactive, Run `evernode log` and see whether there're any errors.

**Comment by BimsaraFernando** [comment]
Hi @tim2min ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
