### ISSUE TITLE
ip address disapeared issue

### ISSUE THREAD

**Issue by cOoNni** [EvernodeXRPL/evernode-host#359]
hello

due to the problem with the vps company server, node stopped
(ip address disappeared)

using the new ip address
i want to activate the node.
help me.. T.T

**Comment by chalith** [comment]
You can transfer and re install. https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration

**Comment by cOoNni** [comment]
thx,
i solve it :)

**Comment by chalith** [comment]
Anytime! Good to hear. Closing the issue since resolved
