### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Rebrovroman** [EvernodeXRPL/evernode-host#360]
Please provide the file /tmp/evernode/installer-1710351587.log to the Evernode team by visiting this link: https://github.com/EvernodeXRPL/evernode-host/issues. 
Thank you.

**Comment by chalith** [comment]
Locate the file in `/tmp/evernode/installer-1710351587.log` and send it here

**Comment by BimsaraFernando** [comment]
Hi @Rebrovroman ,
Thank you for your contribution. This issue has not had recent activity and we are closing it now. If this problem persists or if you have further questions, please open a new issue.
