### ISSUE TITLE
cannot connect to Xahau private node

### ISSUE THREAD

**Issue by siasiab1** [EvernodeXRPL/evernode-host#362]
I updated my Xahau node and my node status and info is ok. after updating my ever nodes cannot connect to iy and gives the following error:

node-s1@nodes1-virtual-machine:~$ sudo -i
[sudo] password for node-s1: 
root@nodes1-virtual-machine:~# evernode status
Version: 0.8.2
Host account address: ....................... (I deleted this)
Governor address: .................................. (I deleted this)
Error occurred while re-connecting to the primary server
Error occurred when retrieving account info.
MB_CLI_EXITED

**Comment by siasiab1** [comment]
root@nodes06-virtual-machine:~# evernode config xahaud wss://wss.evernodegateway.com
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  920k  100  920k    0     0  1512k      0 --:--:-- --:--:-- --:--:-- 1512k
Done.

Could not communicate with the xahaud server wss://wss.evernodegateway.com.

**Comment by chalith** [comment]
Is your xahaud server up and running? Firewall rules and ports are open?

**Comment by BimsaraFernando** [comment]
Hope this issue is resolved by now. If not please reopen with the latest findings.
