### ISSUE TITLE
Hi @crtten,

### ISSUE THREAD

**Issue by tnaa97** [EvernodeXRPL/evernode-host#363]
Hi @crtten,

I just had this issue after I sent my XAH and EVRs install failed. So I tried the Transfer/Update install method but my problem is that during the transfer when the node checks my account, it is not registered, and keeps asking for my Account, so ctrl+C and tried the Update install, but that wants more EVRs.

I am stuck, and would appreciate any help.

Here is my account: https://xahauexplorer.com/explorer/r48oe1AxjMRaZYhMpVTXtzFFTBMCBoF33t

The XAH was sent here: rDwHDhCyBzRFDhf3AVCp7iuDmnm8jYc2AC

So I tried again and errored out as below log file indicates. (Only the root user is configured on this node, so not sure why permission was denied...

Details:
 GNU nano 4.8                                      /tmp/evernode/installer-1710787937.log                                                 
---Sashimono prerequisites installer---
STAGE Installing dependencies
Hit:1 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3177 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [506 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2784 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [389 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1177 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [282 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal-security/main amd64 Packages [2779 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal-security/universe amd64 Packages [950 kB]
Fetched 12.3 MB in 4s (3484 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
quota is already the newest version (4.05-1).
cgroup-tools is already the newest version (0.41-10).
fuse3 is already the newest version (3.9.0-2).
curl is already the newest version (7.68.0-1ubuntu2.21).
openssl is already the newest version (1.1.1f-1ubuntu2.22).
uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.5).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Adding br_netfilter
modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/6.5.11-8-pve
STAGE Configuring fstab
mount: /: permission denied.
Re mounting error.

**Comment by chalith** [comment]
Your installation wasn't successful. So your host account `rDwHDhCyBzRFDhf3AVCp7iuDmnm8jYc2AC` is not registered yet, The EVRs and XAHs are in this account. The account secret is in your VM so don't vipe your VM without backing up the secret. You cannot perform any other operation until you are registered.

Looks like your VM is not allowing to change fstab configurations. Can you try executing `mount -o remount /` and see whether it's also failing. Also try rebooting the VM.

**Comment by tnaa97** [comment]
Thanks, I realized Containers are not supported.
