### ISSUE TITLE
How do I add the fallback address to my hosts?

### ISSUE THREAD

**Issue by sojournease** [EvernodeXRPL/evernode-host#365]
How do I add the fallback address to each host? Do I simply enter the required line of code when opening terminal for ach host?

I have 3 host and all are now connected to a private xahau node I'm renting. Yet no evrs are being sent so no rewards as of March 11th for all 3 hosts. I understand this is due to not having updated to xahau node in the required time frame. Yet it is now complete and trying to confirm any steps needed at this point. Heartbeats live and servers are all active and have been running smooth. Xahau payments are being processed regularly as expected yet no ever rewards.

I assume it's the lack of fallback causing this?

**Comment by du1ana** [comment]
Hi, please refer to [this documentation](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#no-rewards-even-if-the-host-is-active) to diagnose the issue. 

Lack of fallback servers is not a factor that affects rewards.

**Comment by sojournease** [comment]
When originally posting this I got an error when pressing submit so assumed it dod not get posted, hence the duplicate post as I redid it. I read that documentation. Where do I go to confirm the host status/health as mentioned in the doc?

Or since I did not update to 0.8.2 within the week required does that mean the hosts will no longer have the option of receiving rewards, no matter if I update or not?

**Comment by du1ana** [comment]
You will receive rewards if you have updated to v0.8.2 and have set the specified host configurations as instructed [here](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#no-rewards-even-if-the-host-is-active).

You can use the [`evernode config`](https://docs.evernode.org/en/latest/hosts/evernode-cli.html) command to view and update relevant host configurations.

**Comment by sojournease** [comment]
Thank you. Everything is reolved thx for the direction. Ticket is closed.
