### ISSUE TITLE
"There was an error during installation"

### ISSUE THREAD

**Issue by bumpper** [EvernodeXRPL/evernode-host#368]
Hi, I'm installing on a new host, but I am using my secret from an old host that had stopped working after the 0.8.2 upgrade.  It get towards the end of the installation process and then tells me there is an error.  I have attached the log file.  This is the message I get: 

**Setup will now begin the installation. Continue? [Y/n] y

Starting installation...
Installing other prerequisites...
Installing dependencies
Installing snapd
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Invalid registration please transfer or deregister and try again
Aborting the installation..
Setup will now begin the installation. Continue? [Y/n] y

Starting installation...
Installing other prerequisites...
Installing dependencies
Installing snapd
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Setting up letsencrypt certbot
Setting up slirp4netns
Installing docker packages
Configuring host Xahau account
Configuring Sashimono services
Configuring Xahau message board service
Registering host on Evernode registry rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH
Invalid registration please transfer or deregister and try again
Aborting the installation..
There was an error during installation. 
Please provide the file /tmp/evernode/installer-1712055662.log to the Evernode team by visiting this link: https://github.com/EvernodeXRPL/evernode-host/issues. 
Thank you.
Please provide the file /tmp/evernode/installer-1712055662.log to the Evernode team by visiting this link: https://github.com/EvernodeXRPL/evernode-host/issues. 
Thank you.**

[installer-1712055662.log](https://github.com/EvernodeXRPL/evernode-host/files/14840193/installer-1712055662.log)

**Comment by chalith** [comment]
Follow the transfer process and then try installing again [link](https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration)

**Comment by bumpper** [comment]
That worked!  Thank you :)
