### ISSUE TITLE
IPv6 subnet CIDR error

### ISSUE THREAD

**Issue by AfroPunx** [EvernodeXRPL/evernode-host#369]
Trying to spin up 2 new evernodes.  When attempting to "Please specify the IPv6 subnet CIDR assigned to this host:" it is rejecting my CIDR.  

IP address:  66.94.116.110

Website using for calculator:  https://iplocation.io/subnet-calculator/66.94.116.110

CIDR given:  66.94.116.0/24

When I attempt to use the above CIDR, my evernode installation prompts: "Minimum allowed prefix length for Evernode is 64."

I'm not sure why I'm not getting the correct IPv6 subnet CIDR.  I've used the same website and process for my CIDR for all my previous evernodes, so I'm not sure why I'm getting an error at this moment.  Thank you in advance for your assistance

**Comment by jellicoe** [comment]
you have to put in the IPv6 address

on ya server do ifconfig to find it out 

then enter it like below 

2001:19e0:ac00:4f47::/64

**Comment by AfroPunx** [comment]
My novice is showing :)

Thank you I was def using the wrong IP. (4 instead of 6). My nodes have installed successfully!

Thank you very much!!

**Comment by chalith** [comment]
Closing the issue since resolved
