### ISSUE TITLE
VPS needs daily restarting (Contabo)

### ISSUE THREAD

**Issue by AfroPunx** [EvernodeXRPL/evernode-host#370]
Hello,

My newest node (number 16) keeps having issues staying connected in my terminal.  Everyday for the past three days, it has sent heartbeats to XAHAU for a few hours, then it gives the error below in the reboot screen (even though I haven't rebooted my node).  When I open the terminal, it'll be on the screen when you are trying to reboot with the below error message:

👤 Starting a new connection to: "82.197.65.214" port "22"
⚙️ Starting address resolution of "82.197.65.214"
⚙️ Address resolution finished
⚙️ Connecting to "82.197.65.214" port "22"
😨 Connection failed: connection timed out. No more addresses to try.

Rebooting from the terminal doesn't solve the issue (and I verified my password in the Terminal Host is correct);  I need to actually go to my VPS provider (Contabo) and restart the server there.  When I do this, it will start working again (for less than 24 hours) before I get the reboot error again.  Has anyone seen this type of issue and know a resolution, other than restarting my VPS from Contabo on a daily basis....?

When this happens, it initially says my "Host Status = Inactive" until another heartbeat is send out.  I've received 10 EVRs so far to that node wallet so it works, just  not consistently.  This is the first week that I've ran this node (16).  Any suggestions(?)

**Comment by AfroPunx** [comment]
So FYI I'm still experiencing this issue.  My VPS will only stay connected for 24-48 hours before it kicks me off and refuses to reboot through the terminal.  My only solution is to restart the VPS directly thorough my Contabo profile.  I reached out to Contabo directly as well, but wanted to come. to the community for a possible solution.

I just wanted to know if anyone has reported an issue like this before?  What could possibly be the issue with this one server when all others seem to be working normally?   A simple restart seems to solve the issue everytime but its constantly happening.

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
