### ISSUE TITLE
2 x nodes that are faulty

### ISSUE THREAD

**Issue by samreid11** [EvernodeXRPL/evernode-host#371]
Hi

I have 2 nodes that I have been unable to get operational and would like to close them down and have the tokens refunded. Please can someone advise me the process to do so?

Many thanks

**Comment by chalith** [comment]
Have you been running them for some time or are they broken from the beginning?

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
