### ISSUE TITLE
Evernode stopped working

### ISSUE THREAD

**Issue by WonderingWarrior** [EvernodeXRPL/evernode-host#373]
Last login: Tue May  7 17:38:25 2024 from 41.1.69.154
root@Nevernode:~# evernode status
Version: 0.8.2
Host account address: rL2XPaKM7PNwGoitvQXst6aq9ezHrRmoj1
Governor address: rBvKgF3jSZWdJcwSsmoJspoXLLDVLDp6jg
Error occurred while re-connecting to the primary server
Error occurred when retrieving account info.
MB_CLI_EXITED

**Comment by WonderingWarrior** [comment]
root@vmi1716050:~# xahaud server_info
Loading: "/etc/opt/xahau/xahaud.cfg"
2024-May-07 18:26:40.876859963 UTC HTTPClient:NFO Connecting to 127.0.0.1:5009

{
   "result" : {
      "info" : {
         "build_version" : "2024.4.21-release+858",
         "closed_ledger" : {
            "age" : 20,
            "base_fee_native" : 1e-05,
            "base_fee_xrp" : 1e-05,
            "hash" : "EBEEEF6A3B4C6CAC8CD08911F5C5EC5F2AB69B47FBCF55793C4AED9095ACAF79",
            "reserve_base_native" : 1,
            "reserve_base_xrp" : 1,
            "reserve_inc_native" : 0.2,
            "reserve_inc_xrp" : 0.2,
            "seq" : 2
         },
         "complete_ledgers" : "empty",
         "hostid" : "vmi1716050.contaboserver.net",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 0,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientRPC"
               },
               {
                  "job_type" : "untrustedValidation",
                  "per_second" : 8
               },
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 8
               },
               {
                  "job_type" : "peerCommand",
                  "peak_time" : 1,
                  "per_second" : 107
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "network_id" : 21337,
         "node_size" : "medium",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 6,
         "pubkey_node" : "n9KwRXZZsL4e7fHohZr3H78GcRX5ugVsnhMFpeGz9cGrYj24PHiE",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "server_state_duration_us" : "20662377",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "21665109",
               "transitions" : "2"
            },
            "disconnected" : {
               "duration_us" : "1198888",
               "transitions" : "2"
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : "0"
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : "0"
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : "0"
            }
         },
         "time" : "2024-May-07 18:26:40.878596 UTC",
         "uptime" : 22,
         "validation_quorum" : 4294967295,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2025-May-07 00:00:00.000000000 UTC",
            "status" : "active"
         }
      },
      "native_currency_code" : "XAH",
      "status" : "success"
   }
}

**Comment by chalith** [comment]
Check if this is fixed after the latest patch
