### ISSUE TITLE
17/18 Evernodes not sending heartbeat in the last 24 hours

### ISSUE THREAD

**Issue by AfroPunx** [EvernodeXRPL/evernode-host#374]
I have 18 evernodes (afropunx.lol) and only 1 node is currently sending heartbeats atm (evr12.afropunx.lol).  

I have my own Xahau Node (wss.afropunx.xyz) and it is currently showing as running and active.  For some odd reason, my 12th evernode stopped sending heartbeats with the other evernodes yesterday, but it started sending out heartbeats again today a few hours ago (I've done nothing to the code of any of my evernodes or Xahau node).

I've tried restarting the VPS of all of my evernodes and xahau node, but it did not resolve the issue.  I have no idea why all of a sudden my evernodes stopped sending heartbeats, because I made no changes via my terminal ("Terminus")

when running EVERNODE STATUS on all of my nodes i receive the following error message:
Last login: Sun Apr  7 18:57:15 2024 from 174.68.186.178
root@vmi1640469:~# evernode status
Version: 0.8.2
Host account address: rnHqHc.................2w2o7pq1
Governor address: rBvKgF....................LLDVLDp6jg
Error occurred while re-connecting to the primary server
Connection closure already handled
Connection failure for wss://wss.afropunx.xyz (code:1000)
Re-initializing xrpl client.
Error occurred when retrieving account info.
MB_CLI_EXITED

From researching other closely related tickets, feedback from "chalith" was the below 2 questions:

1). Are you using the xahau.network as your xahaud server?
NO, ALL OF MY EVERNODES ARE RUNNING ON MY PRIVATE XAHAUD SERVER "AFROPUNX.XYZ"
2). Is your xahaud server up and running? Firewall rules and ports are open?
YES MY XAHAU NODE IS RUNNING.... FIREWALL RULES AND PORTS SHOULD STILL BE OPEN, NO CHANGES WERE MADE TO THE CODE IN THE PAST 24 HOURS WHEN THE HEARTBEATS STOPPED.

I know our nodes can only be down for 7 days, and mine have already been down for 24 hours.  Any assistance is very much appreciated.

**Comment by AfroPunx** [comment]
Issue Resolved

Looks like I missed the last Xahau Node update, my apologies

**Comment by chalith** [comment]
Closing the issue since resolved
