### ISSUE TITLE
How to change my server in Evernode

### ISSUE THREAD

**Issue by forevernode** [EvernodeXRPL/evernode-host#375]
The server(VPS) that I used was expired because I missed the payment so it's impossible to be recovered.. so I gonna buy new sever and want to change but I have no idea how to change.. Is it possible to change the sever in Evernode?? but I'll keep the domain.. Thank you!!

**Comment by chalith** [comment]
You can follow this: https://docs.evernode.org/en/latest/hosts/maintenance.html#transfer-the-host-registration
