### ISSUE TITLE
Cannot deregister Host

### ISSUE THREAD

**Issue by mikoto1121** [EvernodeXRPL/evernode-host#380]
Hy i need help, i try to uninstall my host, but when my host try to deregister the evernode it kere failing

![IMG_5886](https://github.com/EvernodeXRPL/evernode-host/assets/142647323/04757fe0-9acb-4d78-bfe9-96253dba8ce3)

**Comment by chalith** [comment]
Was your host account transferred before you tried to deregister? Or wasn't it active after you installing?

**Comment by mikoto1121** [comment]
1. Yesterday i try to update my evernode to 0.8.3 but it makes my host inactive and i try uninstall command and failing at deregister even using curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s deregister, then i try to use curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s transfer and keep failing and error.
2. Last i try using this command curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh | sudo bash -s install and editing secretkey file when qrcode appear, and check host inactive and try uninstall command again. Should i wait until my host sending heartbeat before try to uninstall again ?

**Comment by chalith** [comment]
Yes you should wait until it heartbeats. But if your host is inactive did you run the `evernode offerlease` command after installing? And did you apply this patch after installing 0.8.3? https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-2118837843

**Comment by mikoto1121** [comment]
Thanks, its active now. But ill try deregister later
