### ISSUE TITLE
Error while deleting tenant from an instance/Tenant using instanced without needed EVR

### ISSUE THREAD

**Issue by DeathHorizonv0** [EvernodeXRPL/evernode-host#381]
Tenant is using my instance without the required EVR needed for the lease. 

- I tried a high fee (1000 EVR) to check if it would auto delete but the tenant still remains connected and using resources for some reason switching from 2 instanced leased to 1.

![price](https://github.com/EvernodeXRPL/evernode-host/assets/156826959/0a0bede8-456d-4097-abe7-e58f629a371f)

- Using the **evernode delete** command outputs me the error in the screenshot.

![Capture](https://github.com/EvernodeXRPL/evernode-host/assets/156826959/7324fbbc-d537-4d8d-a0f7-bc510c941489)

- Currently leasing 2 instances and I can´t delete neither

![tenants](https://github.com/EvernodeXRPL/evernode-host/assets/156826959/2592d748-fd3a-4fa8-8c4e-0b62dd903407)

Tenant address: rDdV2oPnrK2oQm2VCjGwu324rgGnaEu8iB
My host address: rDeq3MCCbZUpgSNWMg234zEkSc7SMpyE12

**Comment by DeathHorizonv0** [comment]
**UPDATE**

The tenant is actually my own host reputation wallet.

It sometimes creates 2 leases but I am only able to remove one of them with the evernode delete command.

After opting-out from the reputation I still am unable to delete the instance.

**Comment by chalith** [comment]
We have found a possible cause. To verify can you run `sudo evernode delete` and after that send us the output of `evernode log` command.

**Comment by DeathHorizonv0** [comment]
Here it is
[evernode.m4uFdGC6U.log](https://github.com/EvernodeXRPL/evernode-host/files/15485201/evernode.m4uFdGC6U.log)

**Comment by chalith** [comment]
Closing the issue since fixed with new patch.
