### ISSUE TITLE
/tmp/evernode/installer-1718350087.log

### ISSUE THREAD

**Issue by TodL33** [EvernodeXRPL/evernode-host#382]
I got this new error code. /tmp/evernode/installer-1718350087.log

**Comment by BimsaraFernando** [comment]
Hi, please locate the file in /tmp/evernode/installer-1718350087.log and send the file content here.

**Comment by TodL33** [comment]
On Friday, June 14, 2024 at 05:49:30 AM EDT, Kavindu Bimsara Fernando ***@***.***> wrote:  
 
 


Hi, please locate the file in /tmp/evernode/installer-1718350087.log and send the file content here.

**Comment by du1ana** [comment]
@TodL33 run "cat /tmp/evernode/installer-1718350087.log" and send the log you get.

**Comment by TodL33** [comment]
Thank ***@***.***:~$ cat /tmp/evernode/installer-1718350087.log2024-06-14 07:28:23 ---Sashimono prerequisites installer---2024-06-14 07:28:23 STAGE Installing dependencies2024-06-14 07:28:23 Ign:1 cdrom://Ubuntu 20.04.6 LTS _Focal Fossa_ - Release amd64 (20230316) focal InRelease2024-06-14 07:28:23 Hit:2 cdrom://Ubuntu 20.04.6 LTS _Focal Fossa_ - Release amd64 (20230316) focal Release2024-06-14 07:28:23 Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease2024-06-14 07:28:23 Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease2024-06-14 07:28:23 Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease2024-06-14 07:28:23 Hit:7 http://us.archive.ubuntu.com/ubuntu focal InRelease2024-06-14 07:28:23 Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]2024-06-14 07:28:23 Hit:9 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease2024-06-14 07:28:23 Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [986 kB]2024-06-14 07:28:23 Get:11 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3359 kB]2024-06-14 07:28:23 Get:12 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [788 kB]2024-06-14 07:28:23 Get:13 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1194 kB]2024-06-14 07:28:23 Fetched 6455 kB in 3s (2446 kB/s)2024-06-14 07:28:23 Reading package lists...2024-06-14 07:28:23 Reading package lists...2024-06-14 07:28:23 Building dependency tree...2024-06-14 07:28:23 Reading state information...2024-06-14 07:28:23 quota is already the newest version (4.05-1).2024-06-14 07:28:23 cgroup-tools is already the newest version (0.41-10).2024-06-14 07:28:23 fuse3 is already the newest version (3.9.0-2).2024-06-14 07:28:23 curl is already the newest version (7.68.0-1ubuntu2.22).2024-06-14 07:28:23 openssl is already the newest version (1.1.1f-1ubuntu2.22).2024-06-14 07:28:23 uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.5).2024-06-14 07:28:23 0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.2024-06-14 07:28:23 STAGE Configuring fstab2024-06-14 07:28:23 fstab already configured.2024-06-14 07:28:23 STAGE Configuring fuse2024-06-14 07:28:23 Fuse config already updated.2024-06-14 07:28:23 STAGE Configuring cgroup rules engine2024-06-14 07:28:23 STAGE Configuring grub2024-06-14 07:28:23 Grub already configured.2024-06-14 07:28:53 ---Sashimono installer---2024-06-14 07:28:53 [STAGE] Setting up letsencrypt certbot2024-06-14 07:28:53 Skipping adding existing rule2024-06-14 07:28:53 Skipping adding existing rule (v6)2024-06-14 07:28:53 Running certbot certonly2024-06-14 07:28:53 Attempting command [certbot certonly -n -d tod1-Latitude-E5450 --agree-tos --email ***@***.*** --standalone] (attempt 1/3)2024-06-14 07:28:53 Saving debug log to /var/log/letsencrypt/letsencrypt.log2024-06-14 07:28:53 An unexpected error occurred:2024-06-14 07:28:53 Invalid identifiers requested :: Cannot issue for "tod1-latitude-e5450": Domain name needs at least one dot2024-06-14 07:28:53 Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.2024-06-14 07:28:53 Command failed, retrying in 5 seconds...2024-06-14 07:28:53 Attempting command [certbot certonly -n -d tod1-Latitude-E5450 --agree-tos --email ***@***.*** --standalone] (attempt 2/3)2024-06-14 07:28:53 Saving debug log to /var/log/letsencrypt/letsencrypt.log2024-06-14 07:28:53 An unexpected error occurred:2024-06-14 07:28:53 Invalid identifiers requested :: Cannot issue for "tod1-latitude-e5450": Domain name needs at least one dot2024-06-14 07:28:53 Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.2024-06-14 07:28:53 Command failed, retrying in 5 seconds...2024-06-14 07:28:53 Attempting command [certbot certonly -n -d tod1-Latitude-E5450 --agree-tos --email ***@***.*** --standalone] (attempt 3/3)2024-06-14 07:28:53 Saving debug log to /var/log/letsencrypt/letsencrypt.log2024-06-14 07:28:53 An unexpected error occurred:2024-06-14 07:28:53 Invalid identifiers requested :: Cannot issue for "tod1-latitude-e5450": Domain name needs at least one dot2024-06-14 07:28:53 Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.2024-06-14 07:28:53 Command failed, retrying in 5 seconds...2024-06-14 07:28:53 Max retries reached, failed setup certificates2024-06-14 07:28:53 Error when setting up letsencrypt SSL ***@***.***:~$ 


    On Monday, June 17, 2024 at 12:20:31 AM EDT, Dulana Peiris ***@***.***> wrote:  
 
 


@TodL33 run "cat /tmp/evernode/installer-1718350087.log" and send the log you get.

**Comment by TodL33** [comment]
Sure looks like its my host name that is the problem, but I will wait for you to answer.
    On Monday, June 17, 2024 at 12:44:41 AM EDT, Tod LoRusso ***@***.***> wrote:  
 
  Thank ***@***.***:~$ cat /tmp/evernode/installer-1718350087.log2024-06-14 07:28:23 ---Sashimono prerequisites installer---2024-06-14 07:28:23 STAGE Installing dependencies2024-06-14 07:28:23 Ign:1 cdrom://Ubuntu 20.04.6 LTS _Focal Fossa_ - Release amd64 (20230316) focal InRelease2024-06-14 07:28:23 Hit:2 cdrom://Ubuntu 20.04.6 LTS _Focal Fossa_ - Release amd64 (20230316) focal Release2024-06-14 07:28:23 Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease2024-06-14 07:28:23 Hit:4 https://deb.nodesource.com/node_20.x nodistro InRelease2024-06-14 07:28:23 Hit:6 http://security.ubuntu.com/ubuntu focal-security InRelease2024-06-14 07:28:23 Hit:7 http://us.archive.ubuntu.com/ubuntu focal InRelease2024-06-14 07:28:23 Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [128 kB]2024-06-14 07:28:23 Hit:9 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease2024-06-14 07:28:23 Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [986 kB]2024-06-14 07:28:23 Get:11 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3359 kB]2024-06-14 07:28:23 Get:12 http://us.archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [788 kB]2024-06-14 07:28:23 Get:13 http://us.archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1194 kB]2024-06-14 07:28:23 Fetched 6455 kB in 3s (2446 kB/s)2024-06-14 07:28:23 Reading package lists...2024-06-14 07:28:23 Reading package lists...2024-06-14 07:28:23 Building dependency tree...2024-06-14 07:28:23 Reading state information...2024-06-14 07:28:23 quota is already the newest version (4.05-1).2024-06-14 07:28:23 cgroup-tools is already the newest version (0.41-10).2024-06-14 07:28:23 fuse3 is already the newest version (3.9.0-2).2024-06-14 07:28:23 curl is already the newest version (7.68.0-1ubuntu2.22).2024-06-14 07:28:23 openssl is already the newest version (1.1.1f-1ubuntu2.22).2024-06-14 07:28:23 uidmap is already the newest version (1:4.8.1-1ubuntu5.20.04.5).2024-06-14 07:28:23 0 upgraded, 0 newly installed, 0 to remove and 71 not upgraded.2024-06-14 07:28:23 STAGE Configuring fstab2024-06-14 07:28:23 fstab already configured.2024-06-14 07:28:23 STAGE Configuring fuse2024-06-14 07:28:23 Fuse config already updated.2024-06-14 07:28:23 STAGE Configuring cgroup rules engine2024-06-14 07:28:23 STAGE Configuring grub2024-06-14 07:28:23 Grub already configured.2024-06-14 07:28:53 ---Sashimono installer---2024-06-14 07:28:53 [STAGE] Setting up letsencrypt certbot2024-06-14 07:28:53 Skipping adding existing rule2024-06-14 07:28:53 Skipping adding existing rule (v6)2024-06-14 07:28:53 Running certbot certonly2024-06-14 07:28:53 Attempting command [certbot certonly -n -d tod1-Latitude-E5450 --agree-tos --email ***@***.*** --standalone] (attempt 1/3)2024-06-14 07:28:53 Saving debug log to /var/log/letsencrypt/letsencrypt.log2024-06-14 07:28:53 An unexpected error occurred:2024-06-14 07:28:53 Invalid identifiers requested :: Cannot issue for "tod1-latitude-e5450": Domain name needs at least one dot2024-06-14 07:28:53 Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.2024-06-14 07:28:53 Command failed, retrying in 5 seconds...2024-06-14 07:28:53 Attempting command [certbot certonly -n -d tod1-Latitude-E5450 --agree-tos --email ***@***.*** --standalone] (attempt 2/3)2024-06-14 07:28:53 Saving debug log to /var/log/letsencrypt/letsencrypt.log2024-06-14 07:28:53 An unexpected error occurred:2024-06-14 07:28:53 Invalid identifiers requested :: Cannot issue for "tod1-latitude-e5450": Domain name needs at least one dot2024-06-14 07:28:53 Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.2024-06-14 07:28:53 Command failed, retrying in 5 seconds...2024-06-14 07:28:53 Attempting command [certbot certonly -n -d tod1-Latitude-E5450 --agree-tos --email ***@***.*** --standalone] (attempt 3/3)2024-06-14 07:28:53 Saving debug log to /var/log/letsencrypt/letsencrypt.log2024-06-14 07:28:53 An unexpected error occurred:2024-06-14 07:28:53 Invalid identifiers requested :: Cannot issue for "tod1-latitude-e5450": Domain name needs at least one dot2024-06-14 07:28:53 Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.2024-06-14 07:28:53 Command failed, retrying in 5 seconds...2024-06-14 07:28:53 Max retries reached, failed setup certificates2024-06-14 07:28:53 Error when setting up letsencrypt SSL ***@***.***:~$ 


    On Monday, June 17, 2024 at 12:20:31 AM EDT, Dulana Peiris ***@***.***> wrote:  
 
 


@TodL33 run "cat /tmp/evernode/installer-1718350087.log" and send the log you get.

**Comment by chalith** [comment]
Yes, The domain name you are providing seems to be invalid. Did you purchase a domain and configure a DNS for your IP?

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
