### ISSUE TITLE
Failed to retrieve latest version data

### ISSUE THREAD

**Issue by shinho75** [EvernodeXRPL/evernode-host#386]
Hello.
rGrbKs9Z5r5QHjXc1kfSDaAF25XEAWAdyx
After installing opt-in at 0.9.0 and rebooting, running the evernode state
Failed to retrieve the latest version data.
Please tell me the solution.

**Comment by chalith** [comment]
Usually a temporary issue. Is still the same?

**Comment by shinho75** [comment]
Hello.
It's the same situation even after a day.. I rebulled vps, transferred it, and reinstalled the evernode node. I'm not installing opt-in.

**Comment by chalith** [comment]
Is your host active in the dashboard? Is it ipv6 only?

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
