### ISSUE TITLE
No instances leased but Available Lease offers: 0 out of 3

### ISSUE THREAD

**Issue by jellicoe** [EvernodeXRPL/evernode-host#388]
My node has no running instances leased out but gets "No unoffered leases." when looking at evernode offerlease

evernode offerlease
Stopping the message board...
No unoffered leases.

and 'evernode status' says 

Available Lease offers: 0 out of 3

this means my host has not run the reputation contract for several days as it thinks all the instances are leased 

there are no contracts listed in "evernode reputationd status"

it looks like this all started after my node ran low on XAH and had a bunch of failed URITOKEN MINT transactions

now I have added 10+ XAH - it has not recovered running the reputation hook 

is there away to initiate these manually / or clear the registry or reputation hook for this node?

cheers

jellicoe

**Comment by chalith** [comment]
Try running `evernode config resources 0 0 0 4`

**Comment by du1ana** [comment]
Hi, this issue will be closed due to inactivity/obsolescence. If there are any unresolved concerns, please feel free to reopen the issue. Thank you!
