### ISSUE TITLE
scoreNumerator is still showing 0 and errors reported in rw.stdout.log file.

### ISSUE THREAD

**Issue by jracryptos** [EvernodeXRPL/evernode-host#391]
I have just opted in to the host reputation a few days ago. I was running v0.9.0 and then upgraded to v0.9.1. My score as remained at 0. When I checked the rw.stdout.log, I noticed an error which I am not seeing on my other nodes. It appears to never be able to complete generating the host file as it errors right at the end of the process.

File initialization completed.
Hash file percentage: 0.05 %
Hash file percentage: 9.81 %
Hash file percentage: 19.58 %
Hash file percentage: 29.35 %
Hash file percentage: 39.11 %
Hash file percentage: 48.88 %
Hash file percentage: 58.64 %
Hash file percentage: 68.41 %
Hash file percentage: 78.17 %
Hash file percentage: 87.94 %
Hash file percentage: 97.71 %
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at myContract (/contract/contract_fs/mnt/rw/state/index.js:921:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async invokeCallback (/contract/contract_fs/mnt/rw/state/index.js:60:9)

Can anyone shed light on what is going on and what steps I need to take to resolve this please? Thank you

**Comment by jracryptos** [comment]
The accompanying errors in the rw.stderr.log is as follows:

Execution lcl 2-2ca214594e179132cdca9a5af1e833664434eb682423fed963dc1a7d182ae49a
An error occurred: [Error: ENOENT: no such file or directory, read] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'read'
}
Execution lcl 5-32e652410a95ec5ef76a0e71395399464cd25be84610178846b33b0e0713b863
An error occurred: [Error: ENOENT: no such file or directory, read] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'read'

**Comment by chalith** [comment]
While there's a contract running can you execute `ls /home/<instance_user>/<instance_name>/contract_fs/seed/` and send the output

**Comment by jracryptos** [comment]
Here you go.

opinion.txt  patch.cfg  rep_hash.dat  state

Oh but seems the error has disappeared now and the error messages I was seeing before are now gone and processes appear to be executing but my score is still 0 for now.

**Comment by du1ana** [comment]
Hi @jracryptos what are the system specs of your host? It should be in `/etc/sashimono/sa.cfg`

**Comment by jracryptos** [comment]
I actually just reduced the lease count from 6 down to 3 so system spec now showing as below.

"max_mem_kbytes": 3211120,
        "max_swap_kbytes": 3355360,
        "max_cpu_us": 800000,
        "max_storage_kbytes": 41780400,
        "max_instance_count": 3

**Comment by jracryptos** [comment]
After the various recent code updates, my node appears to be functioning ok now. Thank you for all the help.
