### ISSUE TITLE
Sashimono Agent binary update error message

### ISSUE THREAD

**Issue by rowrowrown** [EvernodeXRPL/evernode-host#397]
curl: (22) The requested URL returned error: 404 
curl: (6) Could not resolve host: sashimono.sh
![Screenshot 2024-07-30 104440](https://github.com/user-attachments/assets/3bf8bb8f-4a4a-49d4-9bbb-39201caacea3)

**Comment by mauricetbm** [comment]
Same error. Please advise. Thank you so much

**Comment by Rritchyx** [comment]
Hello, if your evernode status is v0.9.0 or v0.9.1 maybe you could solve
this updating to v0.10.0 before update of sashimono agent v0.10.1
First step
curl -fsSL
https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/main/sashimono/installer/evernode.sh
| sudo bash -s update
Second step
curl -fsSL
https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/patch-v0.10.1/sashimono/patches/update-sashimono.sh
| sudo bash -s

Le mer. 31 juil. 2024, 00:01, mauricetbm ***@***.***> a
écrit :

**Comment by kithminisg** [comment]
@rowrowrown, I see extra space in the provided command ( `update- sashimono.sh`). Could you please double-check the command and execute it?

**Comment by rowrowrown** [comment]
@kithminisg thank you! That worked
