### ISSUE TITLE
The score is 0. The scoreNumberator is also 0.

### ISSUE THREAD

**Issue by shinho75** [EvernodeXRPL/evernode-host#398]
![20240801_143501](https://github.com/user-attachments/assets/3df0badf-de87-4caf-a391-f937611faa39)
![20240801_181848](https://github.com/user-attachments/assets/e90e5521-69f6-4766-b092-267562301e3c)

Please tell me the solution

**Comment by du1ana** [comment]
hi, based on the screenshots attached, it seems like your reputationd status is inactive at the moment. Run `evernode reputationd opt-in` to opt in for reputationd service. To further diagnose reputation score related issues after you have opted in, [please refer to this documentation](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#handling-reputation-assessment-observations)
