### ISSUE TITLE
0 Reputation

### ISSUE THREAD

**Issue by liamnibble2020** [EvernodeXRPL/evernode-host#403]
After the v11 update all my servers is now 0 reputation and no balance since then.

email: liamnibble@gmail.com

Address:
rnFVJLeaMsDnx3NXhJqNciWYhBmgsnzowE
r9izCiuxctYA9hnk9jRbYKVQ8cB5mMt8Jm
raXX11DecmQ7zeBgG4ZKu81EeqVvPZbpbx
rafB4dNhTxEWXynqfoo8qLqhgDwaq55PMx
r9DJKDtBrHWaAemTFe65LcS55EjVc835Go
rPY5m592T79t41VziFYF6FafWr7RJR9bG
rJYNm7JU9A77fx9NAbyDbJpLPcn6XUwhHA
rpJ8AT7p25ZPgvxyJF9q52tXEoHJVqtqCM
rw7sNZ6P39qeT4tmHP9CxUrPc2NtBf1goU
rD7tPL1kciW6htXVMGoi37KKiXLTBotqey

**Comment by liamnibble2020** [comment]
@chalith it looks like it's happening to multiple host after the update, any idea why this is happening? Can you provide resolution?

**Comment by liamnibble2020** [comment]
I successfully updated to version 12, and still reputation 0 and not getting reward

**Comment by du1ana** [comment]
hi, please run the following commands and send the logs you get:

Reputation log : 
`sudo -u sashireputationd bash -c 'journalctl --user -u sashimono-reputationd | tail -n 250'`

Sashi mb XRPL log : 
`sudo -u sashimbxrpl bash -c journalctl --user -u sashimono-mb-xrpl | tail -n 250`

**Comment by liamnibble2020** [comment]
@du1ana For Host account address: raXX11DecmQ7zeBgG4ZKu81EeqVvPZbpbx
[sashimbxrpl.txt](https://github.com/user-attachments/files/16798409/sashimbxrpl.txt)
[reputationd_log.txt](https://github.com/user-attachments/files/16798410/reputationd_log.txt)

**Comment by du1ana** [comment]
Seems like your reputation account has not been funded with EVRs, based on "Skipping reputation sender due to insufficient EVR balance in the reputation account." lines in your reputation log.

**Comment by liamnibble2020** [comment]
@du1ana what needs to be done? Is it Evernode suppose to fund the reputation account?

**Comment by du1ana** [comment]
Reputation account needs to be funded manually. [Please refer to this documentation for more details on setting up the reputation account](https://docs.evernode.org/en/latest/hosts/evernode-host-reputationd.html#setting-up-accounts).

**Comment by liamnibble2020** [comment]
@du1ana Based in the docs; correct me if I'm wrong, when I opt-in, I need to deposit initial XAH at least 2
Preparing reputation account**:rQsNQCmwvVjmfSEb6imbQLiBdxvgN3Yqty** | Reputation Hook:rsfTBRAbD2bYjVuXhJ2RReQXxR4K5birVW
It means I need to deposit EVR as well to **rQsNQCmwvVjmfSEb6imbQLiBdxvgN3Yqty**? If yes, how many EVR?

**Comment by du1ana** [comment]
To confirm if it's the correct account to be funded, you can run `evernode reputationd status` and check if the 'Host reputation-delegate account address' matches the one you're considering funding.

In the reputation account, **XAH** is used for transaction fees, while **EVR** is spent on instance acquisition fees when a contract instance is acquired. To determine how much EVR to fund, you can use the following formula:

EVR to be funded = (Your host's lease amount) * (Number of hours you want reputationd to run)
