### ISSUE TITLE
Failed re-installation.

### ISSUE THREAD

**Issue by AlexSw321** [EvernodeXRPL/evernode-host#418]
Hi! Got this message during installation:
[installer-1724581825.log](https://github.com/user-attachments/files/16739878/installer-1724581825.log)

Please provide the file /tmp/evernode/installer-1724581825.log to the Evernode team by visiting this link: https://github.com/EvernodeXRPL/evernode-host/issues.

**Comment by AlexSw321** [comment]
I tried to deregister but it failed. Please help.

Submission attempt 9 failed. Retrying...
Transaction result: tecHOOK_REJECTED

**Comment by du1ana** [comment]
Hi, please send your host account's r-address.

**Comment by du1ana** [comment]
Hi, [please refer to this documentation](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#cli-out-invalid-reg-error-on-installation)

**Comment by AlexSw321** [comment]
I fixed it yesterday

**Comment by AlexSw321** [comment]
x
