### ISSUE TITLE
connection failure code: 1000

### ISSUE THREAD

**Issue by Antoine0823** [EvernodeXRPL/evernode-host#424]
upgraded to 0.12.0 evernode host
after upgrade nothing works

Error occurred while re-connecting to the primary server
Error occurred while connecting to fallback server wss://wss.xxxxxxxx.com
Connection closure already handled
Connection failure for wss://wss.xxxxxxxxxxxx.com (code:1000)
Re-initializing xrpl client.
Error occurred when retrieving account info.
MB_CLI_EXITED

**Comment by Antoine0823** [comment]
When updating Xahau node I get the following

xahaud is running with PID: 681, but not in the expected location. It is running from: /opt/xahaud/downloads/2024.4.21-release+858
***Please stop xahaud first.***

how do I stop Xahaud?

**Comment by du1ana** [comment]
hi, you can use the following commands to start/stop/restart xahaud:

`systemctl start xahaud`
`systemctl restart xahaud`
`systemctl stop xahaud`

please refer [here for more info](https://github.com/Xahau/Xahau-Testnet-Docker/)

**Comment by Antoine0823** [comment]
-Stop and restart executed fine 
-Evernode host still doesn't connect
-ran a ping wss.brittecxahau.com (no problems there)

------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-ran xahau fallback but could not connect to server

root@Brittec1:~# evernode config xahaud-fallback wss://wss.brittecxahau.com
Downloading setup support files...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  922k  100  922k    0     0  4194k      0 --:--:-- --:--:-- --:--:-- 4194k
Done.

Could not communicate with the xahaud server wss://wss.brittecxahau.com.

Usage: evernode config xahaud-fallback | evernode config xahaud-fallback <fallback xahaud servers (comma seperated)>

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

{
   "result" : {
      "info" : {
         "build_version" : "2024.8.20-release+962",
         "closed_ledger" : {
            "age" : 19,
            "base_fee_native" : 1e-05,
            "base_fee_xrp" : 1e-05,
            "hash" : "1EB43D36375D6B2F54BD3204513E58264638897A7659FA2362342AAB94261E86",
            "reserve_base_native" : 1,
            "reserve_base_xrp" : 1,
            "reserve_inc_native" : 0.2,
            "reserve_inc_xrp" : 0.2,
            "seq" : 2
         },
         "complete_ledgers" : "empty",
         "hostid" : "vmi1734799.contaboserver.net",
         "io_latency_ms" : 1,
         "jq_trans_overflow" : "0",
         "last_close" : {
            "converge_time_s" : 0,
            "proposers" : 0
         },
         "load" : {
            "job_types" : [
               {
                  "in_progress" : 1,
                  "job_type" : "clientRPC"
               },
               {
                  "job_type" : "clientWebsocket",
                  "per_second" : 1
               },
               {
                  "job_type" : "untrustedValidation",
                  "peak_time" : 2,
                  "per_second" : 3
               },
               {
                  "job_type" : "ledgerRequest",
                  "peak_time" : 2,
                  "per_second" : 25
               },
               {
                  "job_type" : "untrustedProposal",
                  "peak_time" : 2,
                  "per_second" : 9
               },
               {
                  "job_type" : "peerCommand",
                  "peak_time" : 3,
                  "per_second" : 495
               }
            ],
            "threads" : 6
         },
         "load_factor" : 1,
         "network_id" : 21337,
         "node_size" : "medium",
         "peer_disconnects" : "0",
         "peer_disconnects_resources" : "0",
         "peers" : 10,
         "pubkey_node" : "n9MNr1pAHqLYCmn1gms3U5mY7rPyjQWyKC2WVLP745t94PeVKWAe",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "server_state_duration_us" : "21713982",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "22715216",
               "transitions" : "2"
            },
            "disconnected" : {
               "duration_us" : "1039808",
               "transitions" : "2"
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : "0"
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : "0"
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : "0"
            }
         },
         "time" : "2024-Aug-29 13:01:29.083985 UTC",
         "uptime" : 23,
         "validation_quorum" : 4294967295,
         "validator_list" : {
            "count" : 1,
            "expiration" : "2025-Aug-15 00:00:00.000000000 UTC",
            "status" : "active"
         }
      },
      "native_currency_code" : "XAH",
      "status" : "success"
   }

**Comment by Antoine0823** [comment]
I repeated the procedure and got the following:

root@vmi1734799:~# sudo nano /etc/sashimono/mb-xrpl/mb-xrpl.cfg
root@vmi1734799:~# wget -O update.sh https://raw.githubusercontent.com/Xahau/mainnet-docker/main/xahaud-install-update.sh
--2024-08-29 15:43:58--  https://raw.githubusercontent.com/Xahau/mainnet-docker/main/xahaud-install-update.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7338 (7.2K) [text/plain]
Saving to: ‘update.sh’

update.sh                         100%[=============================================================>]   7.17K  --.-KB/s    in 0s      

2024-08-29 15:44:00 (43.3 MB/s) - ‘update.sh’ saved [7338/7338]

root@vmi1734799:~# chmod +x update.sh
root@vmi1734799:~# sudo ./update.sh
xahaud is running with PID: 678, but not in the expected location. It is running from: /opt/xahaud/downloads/2024.8.20-release%2B962
***Please stop xahaud first.***
root@vmi1734799:~# systemctl stop xahaud
root@vmi1734799:~# chmod +x update.sh
root@vmi1734799:~# sudo ./update.sh
xahaud is not running. Continuing with installation
Fetching versions of xahaud...
2024.8.20-release%2B962 is available for download
File already downloaded: 2024.8.20-release%2B962
mkdir: cannot create directory ‘/etc/opt/xahau’: File exists
root@vmi1734799:~#

**Comment by du1ana** [comment]
Please raise this issue in [xahau repo](https://github.com/Xahau/mainnet-docker/)
