### ISSUE TITLE
Reputation rejected by the hook

### ISSUE THREAD

**Issue by metamorphosis143** [EvernodeXRPL/evernode-host#425]
[Reputationd log.txt](https://github.com/user-attachments/files/16831099/Reputationd.log.txt)

Reputation accounts will out of balance soon because its keep adding here :
![1](https://github.com/user-attachments/assets/0446002b-15fc-4a60-847d-41687b0574dd)

Here are the txs of RC account. 
![2](https://github.com/user-attachments/assets/b6a88cd4-6eee-4ce1-a60c-76f4b1e153a8)

**Comment by du1ana** [comment]
hi, please run the following commands and send the outputs you get:

MB-XRPL log : 
`sudo -u sashimbxrpl bash -c journalctl --user -u sashimono-mb-xrpl | tail -n 250`

Reputationd status : 
`evernode reputationd status`

**Comment by metamorphosis143** [comment]
> hi, please run the following commands and send the outputs you get:
> 
> MB-XRPL log : `sudo -u sashimbxrpl bash -c journalctl --user -u sashimono-mb-xrpl | tail -n 250`
> 
> Reputationd status : `evernode reputationd status`

[tec NoEntry.txt](https://github.com/user-attachments/files/16831652/tec.NoEntry.txt)

Evernode Reputation Hook address: rsfTBRAbD2bYjVuXhJ2RReQXxR4K5birVW
Host reputation-delegate account address: rMWwHGbBEVVNomhDzpRdvUNjJPu9hHJuTu
{
  "hostAddress": "rESe6x1qtLrWvFWA1JEc3n1Qu6MGSR38T",
  "lastRegisteredMoment": 6309,
  "scoreNumerator": 0,
  "scoreDenominator": 42,
  "score": 12,
  "lastResetMoment": 6308,
  "lastScoredMoment": 6308,
  "lastUniverseSize": 55,
  "valid": true,
  "moment": 6309,
  "orderedId": 5938,
  "reportedHostCount": 6810
}
REPUTATIOND_SUCCESS

**Comment by metamorphosis143** [comment]
solved
