### ISSUE TITLE
There was an "error" during installation

### ISSUE THREAD

**Issue by tim2min** [EvernodeXRPL/evernode-host#426]
Error trying to do a rebuild of server
[Trying To Do Re-Install Steps.txt](https://github.com/user-attachments/files/16841373/Trying.To.Do.Re-Install.Steps.txt)
[Installer Log Error-09-02-24.txt](https://github.com/user-attachments/files/16841374/Installer.Log.Error-09-02-24.txt)

**Comment by du1ana** [comment]
Hi, [please refer to this documentation](https://docs.evernode.org/en/latest/hosts/evernode-diagnostics.html#cli-out-invalid-reg-error-on-installation)

**Comment by tim2min** [comment]
I am seeking to just do a re-install, I have the secrets of the host and reputation, so your saying the "transfer" option is the way to go?...correct

**Comment by amchosts** [comment]
Hello trying to reinstall but keep getting the following error "Please provide the file /tmp/evernode/installer-1725831163.log to the Evernode team.

Please advise, Thanks!

**Comment by du1ana** [comment]
@tim2min yes, that is correct

**Comment by du1ana** [comment]
@tim2min i will be closing this issue. if there are any unresolved concerns, please reopen this issue.

**Comment by amchosts** [comment]
Hi was able to resolve that issue thanks but I have several hosts and all
are not receiving any rewards. All have active instances and everything
seems to be working ok but not getting any rewards!!!

Please advise thanks

**Comment by du1ana** [comment]
@amchosts right now the [rewards are paused](https://discord.com/channels/953758352280813618/956338783169687622/1280801206276587541) due to a bug in Xahau. While rewards are paused, please opt out of reputationd until further notice.

**Comment by amchosts** [comment]
Ok thanks

**Comment by amchosts** [comment]
How will Xahau let us know the bug issue is fixed ? I haven't seen an announcement about the bug issue from them or did I miss it ?

**Comment by du1ana** [comment]
The bug [was fixed in Xahaud](https://github.com/Xahau/xahaud/issues/356), and the [Xahau amendment is being processed](https://xahscan.com/amendment/8063140E9260799D6716756B891CEC3E7006C4E4F277AB84670663A88F94B9C4). We are planning to [resume rewards on  Wednesday at 6 pm AEST](https://discord.com/channels/953758352280813618/956338783169687622/1283339257754423327).

**Comment by amchosts** [comment]
Hi Dulana have rewards resumed ? I have opted back in but have no active
instances or rewards.

Thanks
Adrian

**Comment by du1ana** [comment]
hi @amchosts could you open up a new issue and send the following logs in the description:

Reputation log : 
`sudo -u sashireputationd bash -c 'journalctl --user -u sashimono-reputationd | tail -n 250'`

MB-XRPL log : 
`sudo -u sashimbxrpl bash -c journalctl --user -u sashimono-mb-xrpl | tail -n 250`
