### ISSUE TITLE
Failed installing Host

### ISSUE THREAD

**Issue by Icefox787** [EvernodeXRPL/evernode-host#437]
![image](https://github.com/user-attachments/assets/a5d38809-0399-452e-8164-ea846e43522f)
Is there a way to solve this? thank you

**Comment by du1ana** [comment]
are you using one of the following commands?
`curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-test-resources/main/sashimono/installer/evernode.sh | sudo bash -s install`

`curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-test-resources/main/sashimono/installer/evernode.sh | sudo bash -s update`

**Comment by Icefox787** [comment]
yes, the first one, already tried again and same error :/

**Comment by du1ana** [comment]
does your host machine satisfy [these requirements](https://docs.evernode.org/en/latest/hosts/evernode-host.html#system-requirements)? and also what is the filesystem type that you are using?

**Comment by Icefox787** [comment]
yes

**Comment by du1ana** [comment]
what is the filesystem type that you are using?

**Comment by Icefox787** [comment]
ubuntu 20.04.6 server, do you mean that?

**Comment by du1ana** [comment]
run `cat /etc/fstab` and send the output you get

**Comment by Icefox787** [comment]
can't use because I'm using a container
![image](https://github.com/user-attachments/assets/92b370e2-be56-48e4-b2a1-1b2ed220b7be)

**Comment by Icefox787** [comment]
I could manage to solve this, but now I have this other problem
![image](https://github.com/user-attachments/assets/bf8cf9b3-914d-4bdf-8932-dbd4c43550ac)

**Comment by du1ana** [comment]
You can't install/run Evernode in a containerized environment. it needs to run on either a VM or a bare metal machine.
