### ISSUE TITLE
Connection Issue with Xahau node

### ISSUE THREAD

**Issue by AfroPunx** [EvernodeXRPL/evernode-host#445]
Hello again.  I finally found another ticket with the same issue I keep encountering (Connection Issue, see below).  The ticket below says that this is actually an issue with the Xahau Node, not the Evernode.  Do you also provide support for Xahau nodes, or do you have a link for Xahau node support tickets?

I have no idea why my Xahau Node is not connecting;  it is updated to the current 9.11 release, and when I run status commands I only get one error (xahaud server_info, see below).  Are you able to assist?  If not, do you have a link for people who are offering paid access to their Xahau nodes?

*************************
*************************
Error occurred while re-connecting to the primary server
[
  'Primary server wss://wss.afropunx.xyz connection max attempts failed.'
]
MB_CLI_EXITED
*************************
*************************
[du1ana](https://github.com/du1ana) commented [on Aug 29](https://github.com/EvernodeXRPL/evernode-host/issues/406#issuecomment-2317131800)
hi, if you encounter this error frequently, there seems to be an issue with the xahaud node you have used as your primary server. can you check if it's running?
*************************
*************************
root@vmi1738918:~# xahaud server_info
Loading: "/etc/opt/xahau/xahaud.cfg"
2024-Oct-16 17:46:00.741497782 UTC HTTPClient:NFO Connecting to 127.0.0.1:5009

{
   "error" : "internal",
   "error_code" : 73,
   "error_message" : "Internal error.",
   "error_what" : "no response from server"
}

**Comment by du1ana** [comment]
Hi, it looks like there’s an issue with your Xahau configurations. The Evernode team doesn't provide support for this, but you can reach out to the Xahau Nodes channel on the Evernode Discord server for help. Do you have access to the Evernode Discord server?
