### ISSUE TITLE
uninstall  Error(확인 좀 해주세요. 미쳐버릴 지경입니다)

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#447]
Are you sure you want to uninstall Evernode? [Y/n] Y

Uninstalling...
---Sashimono uninstaller---
Removing Sashimono cgroup creation service...
Failed to stop sashimono-cgcreate.service: Unit sashimono-cgcreate.service not loaded.
Failed to disable unit: Unit file sashimono-cgcreate.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-cgcreate.service': No such file or directory
Removing Sashimono service...
Failed to stop sashimono-agent.service: Unit sashimono-agent.service not loaded.
Failed to disable unit: Unit file sashimono-agent.service does not exist.
rm: cannot remove '/etc/systemd/system/sashimono-agent.service': No such file or directory
Deleting binaries...
Deleting Sashimono CLI...
rm: cannot remove '/usr/bin/sashi': No such file or directory
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
groupdel: group 'sashiuser' does not exist
Attempting Evernode host deregistration...
CLI_OUT: REGISTERED
MB_CLI_SUCCESS
MB_CLI_SUCCESS
Deregistering host...
Transaction result: tecHOOK_REJECTED
{
  id: '07BBE12F01E11F2B5EB797377989A1A27E4E3140BAACF091DB36F1A9DF427EB7',
  code: 'tecHOOK_REJECTED',
  details: {
    Account: 'rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP',
    Amount: '1',
    Destination: 'rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH',
    Fee: '12982',
    HookParameters: [ [Object], [Object] ],
    LastLedgerSequence: 9330304,
    Memos: [],
    NetworkID: 21337,
    Sequence: 760796250,
    SigningPubKey: '03D8382E7424F9E29BD8440C1F97EDFEA012A04B2454FA057EC30524A2D29BF1A5',
    TransactionType: 'Payment',
    TxnSignature: '3045022100EAA2B579751AFC39DEFAFDEB96437586DAEF3C43D46A0BB9FCBE52F06339B31202203ED33725C9AB3C9C03BA6BBC88C016FBD968AE95936C0136938C6E33B1FFAD58',
    ctid: 'C08E5E6500B35359',
    date: 782845590,
    hash: '07BBE12F01E11F2B5EB797377989A1A27E4E3140BAACF091DB36F1A9DF427EB7',
    inLedger: 9330277,
    ledger_index: 9330277,
    meta: {
      AffectedNodes: [Array],
      HookExecutions: [Array],
      TransactionIndex: 179,
      TransactionResult: 'tecHOOK_REJECTED'
    },
    validated: true
  },
  hookExecutionResult: [ { result: 2, returnCode: 799, message: './src/registry.c' } ]
}

**Comment by du1ana** [comment]
closing this as it is duplicated with #448

**Comment by du1ana** [comment]
https://github.com/EvernodeXRPL/evernode-host/issues/457
