### ISSUE TITLE
uninstall Error( Ten Error) - 해결 좀 해주세요. 

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#448]
Evernode reputationd status: inactive
root@ever09:~# 
root@ever09:~# evernode uninstall

NOTE: By continuing with this, you will not LOSE the ACCOUNT SECRETs; those remain within the specified paths. 
The path where the registration account secret is saved can be found inside the configuration stored at '/etc/sashimono/mb-xrpl/mb-xrpl.cfg'. 
If you have configured a reputation account, the path where that account secret is saved can be found inside the configuration stored at /etc/sashimono/reputationd/reputationd.cfg

Are you sure you want to uninstall Evernode? [Y/n] Y

Uninstalling...
---Sashimono uninstaller---
Removed /home/sashimbxrpl/.config/systemd/user/default.target.wants/sashimono-mb-xrpl.service.
Removing Sashimono cgroup creation service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-cgcreate.service.
Removing Sashimono service...
Removed /etc/systemd/system/multi-user.target.wants/sashimono-agent.service.
Removing Sashimono private docker registry...
sashidockerreg does not exist.
Deleting binaries...
Deleting Sashimono CLI...
Deleting cgroup rules...
Restarting the 'cgrulesengd' service...
Attempting Evernode host deregistration...
CLI_OUT: REGISTERED
MB_CLI_SUCCESS
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (850E8B3A7CFEE0CB8A5649DD6122FB46C8568931EDF5BE0938DF48642D5C71D3) of rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP account
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (CFB36B58C9636153D042A5270D612FFDD051C5162F9AF1A6AF61665E61DE211E) of rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP account
Transaction result: tesSUCCESS
Burnt unsold hosting URIToken (F196B67AAC9B45FCCA6DC5F349304D7A709AD635A541B5EAC92F54CC3388E1A2) of rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP account
MB_CLI_SUCCESS
Deregistering host...
Transaction result: tecHOOK_REJECTED
{
  id: 'EB40D11E824CF7276E1DC5786AC22E748A10B7ECFD7B6EF1624ADDAD3F6B32E7',
  code: 'tecHOOK_REJECTED',
  details: {
    Account: 'rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP',
    Amount: '1',
    Destination: 'rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH',
    Fee: '12982',
    HookParameters: [ [Object], [Object] ],
    LastLedgerSequence: 9330637,
    Memos: [],
    NetworkID: 21337,
    Sequence: 760796283,
    SigningPubKey: '03D8382E7424F9E29BD8440C1F97EDFEA012A04B2454FA057EC30524A2D29BF1A5',
    TransactionType: 'Payment',
    TxnSignature: '304402200DD8E4A1C07C3A34F37CD1C91E0F18EACF06519EC1830F18A5D496AFDD736A1D02206C434F819C339C1BE08ED02A989ADF83BADAFD01DC0F90EFE206528AE7FAC3C9',
    ctid: 'C08E5FB100045359',
    date: 782846960,
    hash: 'EB40D11E824CF7276E1DC5786AC22E748A10B7ECFD7B6EF1624ADDAD3F6B32E7',
    inLedger: 9330609,
    ledger_index: 9330609,
    meta: {
      AffectedNodes: [Array],
      HookExecutions: [Array],
      TransactionIndex: 4,
      TransactionResult: 'tecHOOK_REJECTED'
    },
    validated: true
  },
  hookExecutionResult: [ { result: 2, returnCode: 799, message: './src/registry.c' } ]
}
Submission attempt 1 failed. Retrying...
Transaction result: tecHOOK_REJECTED
{
  id: '691E6565008565F4D95A8A0AC2F386F7DF8168FE4FA62AF3DEE4370CEE61AE4D',
  code: 'tecHOOK_REJECTED',
  details: {
    Account: 'rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP',
    Amount: '1',
    Destination: 'rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH',
    Fee: '12982',
    HookParameters: [ [Object], [Object] ],
    LastLedgerSequence: 9330642,
    Memos: [],
    NetworkID: 21337,
    Sequence: 760796284,
    SigningPubKey: '03D8382E7424F9E29BD8440C1F97EDFEA012A04B2454FA057EC30524A2D29BF1A5',
    TransactionType: 'Payment',
    TxnSignature: '304402201BCFB5CDC3DA3EBFA8AB3C1D5E3CDD458A38275DF5A426FB469B7B2CA36BB83002201412DF738FB73B0281D640070304C9E069BA4245F3188152ECD9F79703673C32',
    ctid: 'C08E5FB600055359',
    date: 782846972,
    hash: '691E6565008565F4D95A8A0AC2F386F7DF8168FE4FA62AF3DEE4370CEE61AE4D',
    inLedger: 9330614,
    ledger_index: 9330614,
    meta: {
      AffectedNodes: [Array],
      HookExecutions: [Array],
      TransactionIndex: 5,
      TransactionResult: 'tecHOOK_REJECTED'
    },
    validated: true
  },
  hookExecutionResult: [ { result: 2, returnCode: 799, message: './src/registry.c' } ]
}
Submission attempt 2 failed. Retrying...
Transaction result: tecHOOK_REJECTED
{
  id: '958FA794D567403E1C93674BDBAA9F64253F467CB07AE96A1E465A4946F466DE',
  code: 'tecHOOK_REJECTED',
  details: {
    Account: 'rwXYwChKnS9yLdfYXrokHJ75Yz1xyVzLxP',
    Amount: '1',
    Destination: 'rmv53yu8Wid6kj6AC6NvmiwSXNxRa8vTH',
    Fee: '12982',
    HookParameters: [ [Object], [Object] ],
    LastLedgerSequence: 9330647,
    Memos: [],
    NetworkID: 21337,
    Sequence: 760796285,
    SigningPubKey: '03D8382E7424F9E29BD8440C1F97EDFEA012A04B2454FA057EC30524A2D29BF1A5',
    TransactionType: 'Payment',
    TxnSignature: '3045022100CD8EEB2E487FED338E2520D042A1D1360DF8DFDC559E841378C72C0E4993554002203677EDFEE0FF1853EBE63BC9998CDE7B5600B6B4D79F2F5713B52C269D2E5B50',
    ctid: 'C08E5FBB00015359',
    date: 782846990,
    hash: '958FA794D567403E1C93674BDBAA9F64253F467CB07AE96A1E465A4946F466DE',
    inLedger: 9330619,
    ledger_index: 9330619,
    meta: {
      AffectedNodes: [Array],
      HookExecutions: [Array],
      TransactionIndex: 1,
      TransactionResult: 'tecHOOK_REJECTED'
    },
    validated: true
  },
  hookExecutionResult: [ { result: 2, returnCode: 799, message: './src/registry.c' } ]
}
Submission attempt 3 failed. Retrying...

**Comment by du1ana** [comment]
Hi, it seems you have tried uninstall before any heartbeat transaction has occurred after a transfer. Keep your host running until a heartbeat transaction is sent and the host status becomes Active and then try uninstalling.

**Comment by du1ana** [comment]
https://github.com/EvernodeXRPL/evernode-host/issues/457
