### ISSUE TITLE
evernode uninstall Error

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#451]
![image](https://github.com/user-attachments/assets/b9321a6a-ce87-4b8f-ae00-b8eb18f08a30)

To proceed with the uninstall, I have to do transfer install, transfer install, transfer install,,transfer install dozens of times. The system is a mess, and are you guys doing your job? I've uploaded it several times, but there's no improvement, and it seems like I'm going crazy. Do something about it. Improve it so that it can be done in one go. Don't you feel guilty about creating a garbage system while saying this?

**Comment by du1ana** [comment]
@BLUEDIAA are you still seeing "hookExecutionResult: [ { result: 2, returnCode: 799, message: './src/registry.c' } ]" in error log? Is your host active and sending heartbeats?

**Comment by du1ana** [comment]
run `evernode status` and send the output

**Comment by du1ana** [comment]
https://github.com/EvernodeXRPL/evernode-host/issues/457
