### ISSUE TITLE
Error with Reputation ID and Host ID address being the same

### ISSUE THREAD

**Issue by Ldnlul0910** [EvernodeXRPL/evernode-host#452]
Hi Evernode Hosts

Hope you're well. I have what I believe is an unusual issue with one of my evernode hosts and I was hoping to get your ideas for resolving this. 

My host address currently shows in my dashboard as NOK and seems to be missing. 
The reputationD address shows as OK, so is opted in, but this is using the host address and is not a new and unique reputationD address which is what would be needed.

Screenshot of my dashboard attached showing the missing host address and the incorrect reputationD address
<img width="940" alt="Screenshot dashboard 2024-10-30 225859" src="https://github.com/user-attachments/assets/77087cf6-0285-4b28-b857-a308fdc85d09">
Domain name: ldnlul0910.cfd

I've tried opting out, going to config to manually delete the reputationD address, and then opting back in. I was hoping a new unique address would be generated, but that plan didn't work as the host address was generated again so still a duplicate. 
I've also tried transfers and fresh installs, but the host address remains as NOK and missing. 

I would appreciate any feedback or suggestions. 

Many thanks,
Jessica

**Comment by du1ana** [comment]
hi, could you run `evernode status` and `evernode reputationd status` and send the outputs you get?

**Comment by Ldnlul0910** [comment]
Many thanks for your reply! 
This is the evernode status: 
<img width="653" alt="image" src="https://github.com/user-attachments/assets/6c513f75-f8d4-4bf8-a11f-61c3bdfcc08d">
This is the reputationd status: 
<img width="711" alt="image" src="https://github.com/user-attachments/assets/81c43b18-7c06-43af-9359-b25a6db7bf9c">

Looking forward to hearing your suggestions. 
Thank you,
Jessica

**Comment by du1ana** [comment]
run `cat /etc/sashimono/reputationd/reputationd.cfg` and check if the xrpl address field is there. also run the following commands and send the logs you get:

Reputation log :
sudo -u sashireputationd bash -c 'journalctl --user -u sashimono-reputationd | tail -n 250'

MB-XRPL log :
sudo -u sashimbxrpl bash -c journalctl --user -u sashimono-mb-xrpl | tail -n 250

**Comment by Ldnlul0910** [comment]
Hi Dulana,

Hope you're well, I appreciate your help on this.

I've now been running the three commands that you shared and have attached
screenshots of the logs here so you can check it as well.

The XRPL address is showing in the reputationd config, but an issue here is
that it is actually the Xaman host address and not a unique
reputation address as you would expect.
I noticed that the contracts instance section that follows is completely
empty (whereas this is completed with information for the nodes that are
working well).

[image: Terminus - xrpl address 2024-11-02.png]

I can't see any journal files due to permissions in either of the logs
(this is also the case for the nodes that are working well)

[image: Terminus Logs 2024-11-02.png]

Looking forward to hearing back from you.

Many thanks
Jessica

**Comment by Ldnlul0910** [comment]
Hi Dulana 

The issue has been resolved, thanks for your help. 

Many thanks
Jessica
