### ISSUE TITLE
sudo evernode offerlease Error

### ISSUE THREAD

**Issue by BLUEDIAA** [EvernodeXRPL/evernode-host#453]
root@ever20:~# sudo evernode offerlease
Stopping the message board...
No unoffered leases.
CLI_OUT: LEASE_OFFER_ERR
MB_CLI_EXITED
There was an error in creating lease offers.
Starting the message board...

**Comment by du1ana** [comment]
‘No unoffered leases’ indicates that all leases have already been offered. This is the expected result if you run the command after leases have been offered. Was there any issue related to your leases?

Also could you respond to the questions I have asked on previous issues you have posted?

**Comment by du1ana** [comment]
https://github.com/EvernodeXRPL/evernode-host/issues/457
