### ISSUE TITLE
Error occurred auditing the instance: Connection timeout.

### ISSUE THREAD

**Issue by lilmond** [EvernodeXRPL/evernode-host#459]
20241111 06:01:02 [dbg] My public key is: ed264...
Nov 11 06:01:02 vps2 node[122976]: 20241111 06:01:02 [dbg] Connecting to wss://66.70.178.113:3021
Nov 11 06:01:07 vps2 node[122976]: 20241111 06:01:07 [dbg] Missing-connections timeout reached.
Nov 11 06:01:07 vps2 node[122976]: 20241111 06:01:07 [err] Error occurred while reading the scores: wss://66.70.178.113:3021 connection failed.
Nov 11 06:03:01 vps2 node[122976]: 20241111 06:03:01 [dbg] Terminating existing instance 910449E6139278E06030DF92BB10E02D5EE88648431A64FF09C19B565A1121DB.
Nov 11 06:03:09 vps2 node[122976]: 20241111 06:03:09 [dbg] Transaction result: tesSUCCESS
Nov 11 06:03:09 vps2 node[122976]: 20241111 06:03:09 [dbg] Checking IPV4 support...
Nov 11 06:03:09 vps2 node[122976]: 20241111 06:03:09 [dbg] Checking version compatibility...
Nov 11 06:03:09 vps2 node[122976]: 20241111 06:03:09 [dbg] Checking SSL certificate validity...
Nov 11 06:03:09 vps2 node[122976]: 20241111 06:03:09 [dbg] All requirement checks passed.
Nov 11 06:03:09 vps2 node[122976]: 20241111 06:03:09 [dbg] Reporting reputations at Moment 7992 without scores...
Nov 11 06:03:17 vps2 node[122976]: 20241111 06:03:17 [dbg] Transaction result: tesSUCCESS
Nov 11 06:17:26 vps2 node[122976]: 20241111 06:17:26 [dbg] Preparing reputation contract for the Moment 7993...
Nov 11 06:17:28 vps2 node[122976]: 20241111 06:17:28 [dbg] Acquiring the reputation contract instance...
Nov 11 06:17:36 vps2 node[122976]: 20241111 06:17:36 [dbg] Transaction result: tesSUCCESS
Nov 11 06:17:36 vps2 node[122976]: 20241111 06:17:36 [dbg] Waiting for acquire response... (txHash: BCE0B91A16BFD30F3D3CCE338A44411F8A4AA16D19BB1C0E5AF58F2ACDCCA605)
Nov 11 06:18:10 vps2 node[122976]: 20241111 06:18:10 [dbg] Reputation contract created in instance {
Nov 11 06:18:10 vps2 node[122976]:   name: '11A9AEF47A396F12893C145B3FDE23A16FF8D8F8EA6833A3B2298E5409705013',
Nov 11 06:18:10 vps2 node[122976]:   pubkey: 'ed1d0...',
Nov 11 06:18:10 vps2 node[122976]:   contract_id: '1f2dac43-d39b-4849-9fe5-6c16f4d05da7',
Nov 11 06:18:10 vps2 node[122976]:   peer_port: '3001',
Nov 11 06:18:10 vps2 node[122976]:   user_port: '3021',
Nov 11 06:18:10 vps2 node[122976]:   gp_tcp_port: '3100',
Nov 11 06:18:10 vps2 node[122976]:   gp_udp_port: '3120',
Nov 11 06:18:10 vps2 node[122976]:   domain: 'nodec2.4evernode.xyz'
Nov 11 06:18:10 vps2 node[122976]: }
Nov 11 06:18:10 vps2 node[122976]: 20241111 06:18:10 [dbg] Waiting 10 seconds until instance is ready...
Nov 11 06:18:20 vps2 node[122976]: 20241111 06:18:20 [dbg] My public key is: ed324...
Nov 11 06:19:20 vps2 node[122976]: 20241111 06:19:20 [err] Error occurred auditing the instance: Connection timeout.
Nov 11 06:19:20 vps2 node[122976]: 20241111 06:19:20 [dbg] Skipping contract info update since instance audit has failed.
Nov 11 06:19:20 vps2 node[122976]: 20241111 06:19:20 [err] Connection error. Error: WebSocket was closed before the connection was established
Nov 11 06:19:20 vps2 node[122976]:     at WebSocket.close (/usr/bin/sashimono/reputationd/index.js:59:65316)
Nov 11 06:19:20 vps2 node[122976]:     at LobbyManager.terminate (/usr/bin/sashimono/reputationd/index.js:1:7177)
Nov 11 06:19:20 vps2 node[122976]:     at #G (/usr/bin/sashimono/reputationd/index.js:1:16721)
Nov 11 06:19:20 vps2 node[122976]:     at async Object.callback (/usr/bin/sashimono/reputationd/index.js:1:19731)
Nov 11 06:19:20 vps2 node[122976]:     at async #T (/usr/bin/sashimono/reputationd/index.js:1:11758)
Nov 11 06:19:20 vps2 node[122976]:     at async scheduler (/usr/bin/sashimono/reputationd/index.js:1:12918)
Nov 11 06:19:20 vps2 node[122976]:     at async Timeout._onTimeout (/usr/bin/sashimono/reputationd/index.js:1:12956)

**Comment by du1ana** [comment]
Hi, it seems like your user port is not accessible. Please make sure that all ports specified during installation are open.

**Comment by lilmond** [comment]
> Hi, it seems like your user port (3021) is not accessible. Please make sure that all ports specified during installation are open.

Hello, I retried the installation and made sure the ports were accessible from outside network before proceeding. Thanks for your reply!
