### ISSUE TITLE
NO_MB_USER_SYSTEMD

### ISSUE THREAD

**Issue by phist0** [EvernodeXRPL/evernode-host#461]
Setup will now begin the installation. Continue? [Y/n] y

Starting installation...
Installing other prerequisites...
Installing dependencies
Configuring fstab
Configuring fuse
Configuring cgroup rules engine
Configuring grub
Installing Sashimono...
Transferring certificate files
Installing docker packages
Configuring Sashimono services
Aborting the installation..
There was an error during installation.
Please provide the file

The last line of the file is: NO_MB_USER_SYSTEMD

How do I get past this ? Is there a way to enable verbose logging ?
[installer-1733174671.log](https://github.com/user-attachments/files/17984300/installer-1733174671.log)

**Comment by du1ana** [comment]
seems like user creation process was unsuccessful. could you restart the VM and try the installation again?

**Comment by phist0** [comment]
I have restarted several times, same issue.
Looking in /etc/passwd the sashimbxrpl and sashireputationd  users are created. In /etc/group sashimbxrpl, sashireputationd and sashiuser groups are created. 
Please what else can I try ?

I noticed on a working system there are two more usernames starting with sashi and followed by a long string of numbers. Is there a way I can pre-create these users and the setup will use them  ?

**Comment by du1ana** [comment]
`cat /etc/group | grep "sashi"`
`cat /etc/passwd | grep "sashi"`

could you run these and send the outputs you get?

as for usernames where `sashi<number>` format, these are users created for instances. you can't pre-create them.

**Comment by phist0** [comment]
cat /etc/group | grep "sashi"
sashiadmin:x:1001:sashireputationd,root,sashimbxrpl
sashimbxrpl:x:1002:
sashireputationd:x:1003:
sashiuser:x:1004:


cat /etc/passwd | grep "sashi"
sashimbxrpl:x:1001:1002::/home/sashimbxrpl:/usr/sbin/nologin
sashireputationd:x:1002:1003::/home/sashireputationd:/usr/sbin/nologin

**Comment by du1ana** [comment]
try evernode transfer. initiate it and then reinstall on your same machine.

**Comment by phist0** [comment]
# curl -fsSL https://raw.githubusercontent.com/EvernodeXRPL/evernode-resources/mai
n/sashimono/installer/evernode.sh | sudo bash -s transfer
Found Sashimono v0.12.1...
Downloading setup support files...
.
.
.

Are you sure you want to transfer Evernode registration? [Y/n] y

Pending sell offer found.
Host is not registered.
Error occured in transfer process. Check the error and try again.


Please note I initially already successfully transferred from an old VM with intent to install on this new VM and have been having issues installing on this new VM.




I'm suspecting an issue on the VM provider side, but what can I show them to convince them it's an issue on their side ? I have other VMs running perfectly ok on the same provider. 
If I spin up a VM on a different provider and the install works, how can I get evidence to show the provider to convince them it's an issue on their end ?

I'm not comfortable showing evernode specific logs to service provider. We have an experience with a provider refusing to provision infrastructure for us  when we told them we are running evernode, they claimed running evernode is mining and they don't allow mining on their platform.

**Comment by du1ana** [comment]
please send your host address. also are you using Contabo?

**Comment by phist0** [comment]
Not Contabo.
Thank you so much for your time. This issue  ( has ) is resolved ( itself ).

A brief background in case someone else runs into a similar scenario. What made this most baffling is that it was a batch of 20 VMs, 14 worked perfectly without a hitch except 6 that had this issue.

I did the apt update, apt upgrade, reboot sequence for close to one week before I came here. Just now when I saw your last message, I decided to do the sequence just one more time to fulfill all righteousness before responding and wonders upon wonders, it worked this time around.


What was different this time was, when I did:

# apt -y update


I got:

.
.
.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
5 packages can be upgraded. Run 'apt list --upgradable' to see them.



After that I did:

# apt list --upgradable
Listing... Done
libpq5/focal-updates,focal-security 12.22-0ubuntu0.20.04.1 amd64 [upgradable from: 12.20-0ubuntu0.20.04.1]
vim-common/focal-updates,focal-security 2:8.1.2269-1ubuntu5.29 all [upgradable from: 2:8.1.2269-1ubuntu5.26]
vim-runtime/focal-updates,focal-security 2:8.1.2269-1ubuntu5.29 all [upgradable from: 2:8.1.2269-1ubuntu5.26]
vim/focal-updates,focal-security 2:8.1.2269-1ubuntu5.29 amd64 [upgradable from: 2:8.1.2269-1ubuntu5.26]
xxd/focal-updates,focal-security 2:8.1.2269-1ubuntu5.29 amd64 [upgradable from: 2:8.1.2269-1ubuntu5.26]

And then:

# apt -y upgrade

.
.
.

Configuration file '/etc/apt/sources.list.d/ct-preset.list'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** ct-preset.list (Y/I/N/O/D/Z) [default=N] ? Y


Got several of the prompts above and answered Y to all of them, then rebooted and it worked. It didn't work without a reboot.  ( I can't recollect clearly but I may have seen those prompts previously and chose the default action)

**Comment by phist0** [comment]
https://github.com/EvernodeXRPL/evernode-host/issues/461#issuecomment-2514459906
