### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-host#67]
[installer-1670596093.log](https://github.com/EvernodeXRPL/evernode-host/files/10195656/installer-1670596093.log)

**Comment by lathanbritz** [comment]
parsed error log my self and was insufficient funds...

really this should be checked at the point where the secret is specified and a error message presented if there are insufficient funds.

**Comment by ravinsp** [comment]
@lathanbritz agree that this is bad UX. It would be good to show the error reason without having to dig into the log file. We will fix this in an update.

**Comment by ravinsp** [comment]
Latest version now performs account checks and displays relevant errors during the setup process.
