### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by josepi909** [EvernodeXRPL/evernode-host#69]
Install failing for some reason..
[installer-1671579044.log](https://github.com/EvernodeXRPL/evernode-host/files/10273740/installer-1671579044.log)

**Comment by kithminisg** [comment]
@josepi909 It seems the issue was due to the provided IP/domain address (45.76.135.240.vultrusercontent.com). Currently, Evernode accepts a maximum of 26 characters.

**Comment by josepi909** [comment]
thanks.. resolved now, node active with fqdn - evernode.spaceveg.space
