### ISSUE TITLE
Evernode commands not recognized

### ISSUE THREAD

**Issue by ThaReality** [EvernodeXRPL/evernode-host#72]
I was meant to report this a couple months back but, never got round to doing it.
So the problem is, I host about 4 nodes but 2 aren't working. 

When I enter evernode status, it doesn't recognize the commands, so I thought I'll just re-install it by appending uninstall to the initial install script but then was met with the message that evernode was already installed.

Please see below screenshot. None of the other commands work

![image](https://user-images.githubusercontent.com/75538827/215322042-a96a3618-abce-4b10-b2fe-8f755c528881.png)

**Comment by wojake** [comment]
Thanks for reporting, give this a read and I hope it helps: https://github.com/EvernodeXRPL/evernode-host/issues/71

**Comment by kithminisg** [comment]
We are closing this issue right now, as we are planning to move to a new Beta Testing environment on [Hooks Testnet V3](https://hooks-testnet-v3.xrpl-labs.com/)
