### ISSUE TITLE
Error starting node.

### ISSUE THREAD

**Issue by Cbuck18** [EvernodeXRPL/evernode-host#73]
The error said to send this to the team.

/tmp/evernode-beta/installer-1676642277.log

**Comment by wojake** [comment]
Hey @Cbuck18, thank you but you need to transfer the contents of the file from your server to this github issue. What you posted was the file's path ❤️

**Comment by kithminisg** [comment]
We are closing this issue right now, as we are planning to move to a new Beta Testing environment on [Hooks Testnet V3](https://hooks-testnet-v3.xrpl-labs.com/)
