### ISSUE TITLE
Host node transfer freeze

### ISSUE THREAD

**Issue by xVet** [EvernodeXRPL/evernode-host#74]
Hi there,

i m trying to transfer my node with the address : `"rGimyJdP7Lq79fHi3PhYnrgjUWLe9262Q3`

Using the  `node transfer` method it gets stuck at `initiating transfer`. 

I want to transfer my node to add the domain support that is required going forward.

logs:

[evernode.Qc0lv7fFg.log](https://github.com/EvernodeXRPL/evernode-host/files/10951573/evernode.Qc0lv7fFg.log)

 Note it says i m in `0.5.22` , according to : https://dashboard.evernode.org/#/host/rGimyJdP7Lq79fHi3PhYnrgjUWLe9262Q3
 
 i m not 

thx

**Comment by kithminisg** [comment]
We are closing this issue right now, as we are planning to move to a new Beta Testing environment on [Hooks Testnet V3](https://hooks-testnet-v3.xrpl-labs.com/)
