### ISSUE TITLE
Host transfer && new installation error

### ISSUE THREAD

**Issue by xVet** [EvernodeXRPL/evernode-host#75]
Hi,

i m in the process of adding my domains to my hosts. I was able to complete the node transfer process and delete evernode.

When i m re installing evernode i get a prompt in the middle of the process to message the Team because there is an error.

Host 1:
https://dashboard.evernode.org/#/host/rhQzmD98S9oR3PDTTAkZxT8KCfe7S4f9Y3

[installer-1678658480.log](https://github.com/EvernodeXRPL/evernode-host/files/10952214/installer-1678658480.log)

Host 2:
https://dashboard.evernode.org/#/host/rhQzmD98S9oR3PDTTAkZxT8KCfe7S4f9Y3

[installer-1678659472.log](https://github.com/EvernodeXRPL/evernode-host/files/10952224/installer-1678659472.log)

Thx

**Comment by chalith** [comment]
Hi @xVet, Looks like your VM does not have snap installed. You can install snap with `sudo apt update && sudo apt install snapd`. And then try installing again.

And did you able to do the transfer for 'rGimyJdP7Lq79fHi3PhYnrgjUWLe9262Q3' host that you've mentioned in issue https://github.com/EvernodeXRPL/evernode-host/issues/74#issue-1620449386?

**Comment by xVet** [comment]
> Hi @xVet, Looks like your VM does not have snap installed. You can install snap with `sudo apt update && sudo apt install snapd`. And then try installing again.
> 
> 
> 
> And did you able to do the transfer for 'rGimyJdP7Lq79fHi3PhYnrgjUWLe9262Q3' host that you've mentioned in your previous [issue](https://github.com/EvernodeXRPL/evernode-host/issues/74)?

Thank you i ll try it out asap!
No i wasn't, that Host in particular seems very stubborn 😆
