### ISSUE TITLE
The noob is back!

### ISSUE THREAD

**Issue by tissson** [EvernodeXRPL/evernode-host#77]
Hello people,

the noob is back - in other words me!
I am trying to figure out how to connect my host to a domain as per se.
I have the VPS where I have normally had the V2 running.

I uninstalled it - and created a dummy (test faucet) and got everything except for when I should put in domain it says: 
Invalid or unreachable domain name.

So, I suppose I am missing this whole _connect host to domain part,_ where do I start?

Is it the reverse DNS at the VPS provider that should match with the domain?

Patrik

**Comment by Franklyn7878** [comment]
i have the same problem here , im probably the noobest ever !! it keep telling me domain unreachable when install

**Comment by rippleitinnz** [comment]
> i have the same problem here , im probably the noobest ever !! it keep telling me domain unreachable when install 

What's your domain name? And where is it being hosted?
