### ISSUE TITLE
Getting Account not found

### ISSUE THREAD

**Issue by GabrielFilip** [EvernodeXRPL/evernode-host#78]
I backup my config file and secret, uninstalled the V2 and trying to install V3.
I am currently getting Account not found error.

**Comment by tissson** [comment]
I dont think there is any "must" using the old account as such, you can create a new using the faucet.

**Comment by GabrielFilip** [comment]
`In order to register in Evernode you need to have an XRPL account with sufficient Ever (EVR) balance.`

It seems that I need some EVR. I had previously around 190k in my V2 account.
What faucet can I use to create a new account and do I have to link it to my previous V2 account?
Thank you

**Comment by GabrielFilip** [comment]
I will launch the server with a test faucet. And see after how it goes.

**Comment by ravinsp** [comment]
Evernode faucet link is mentioned on the system requirements: https://github.com/EvernodeXRPL/evernode-host#system-requirements

**Comment by GabrielFilip** [comment]
Then all good. I am up and running. Thank you.
