### ISSUE TITLE
There was an error during installation.

### ISSUE THREAD

**Issue by herkimer9** [EvernodeXRPL/evernode-host#79]
Hi, I have a problem I got an error message which is  

"There was an error during installation."

I wonder if it is because of swap memory

I allocated 4GB swap partition but it appears 0GB on installation screen. I wonder why..

I send you file /tmp/evernode-beta/installer-1680860535.log 

I'm not familiar with linux hope this is a right way of sending you file!

Thank you!

[installer-1680860535.log](https://github.com/EvernodeXRPL/evernode-host/files/11178013/installer-1680860535.log)

**Comment by chard101** [comment]
The issue appears to be with your firewall setup.  The LetEncrypt SSL certificate is failing for your host www.evernode3.xyz.  The error indicates that port 80 on your firewall is closed, or if your host are behind a dedicated firewall you need to configure NAT / port forwarding.

Good luck!

**Comment by ravinsp** [comment]
@herkimer9 Please confirm or close this issue if you've solved this. Thank you.
