### ISSUE TITLE
Changing EVR moment lease amount results in an errror

### ISSUE THREAD

**Issue by chard101** [EvernodeXRPL/evernode-host#80]
When installing I set my lease amount to 3 EVR per moment.  I want to change it to 2 EVR however when I ran the command below I got an error:

sudo evernode config leaseamt 2

RippledError: invalidTransaction
    at RequestManager.handleResponse (/usr/bin/sashimono/mb-xrpl/index.js:39:88153)
    at Connection.onMessage (/usr/bin/sashimono/mb-xrpl/index.js:39:93682)
    at WebSocket.<anonymous> (/usr/bin/sashimono/mb-xrpl/index.js:39:94124)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (/usr/bin/sashimono/mb-xrpl/index.js:39:72909)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (/usr/bin/sashimono/mb-xrpl/index.js:39:44447)
    at /usr/bin/sashimono/mb-xrpl/index.js:39:43902
    at /usr/bin/sashimono/mb-xrpl/index.js:39:36364
    at /usr/bin/sashimono/mb-xrpl/index.js:39:37315 {
  data: {
    error: 'invalidTransaction',
    error_exception: "Field 'URITokenID' is required but missing.",
    id: 7,
    request: {
      command: 'fee',
      id: 7,
      tx_blob: '12002E210000535A24001DFABD201B001E46386840000000000000007300811499B703A8CE692B1BC01A28E1B21C503F32EBBE2A'
    },
    status: 'error',
    type: 'response'
  }
}
There was an error in updating message board configuration.
Starting the message board...

Changing the configuration exited with an error.
[sudo evernode config leaseamt.txt](https://github.com/EvernodeXRPL/evernode-host/files/11178391/sudo.evernode.config.leaseamt.txt)

**Comment by chard101** [comment]
Just to confirm I am running Ubuntu 20.04, I did try 22.04 first but the install failed.  :-)

**Comment by chalith** [comment]
@chard101 Thank you for reporting.
We've fixed the issue and released it with version 0.6.1.
You can try `sudo evernode config leaseamt 2` again after your host is updated to version 0.6.1.
You can update your host using `sudo evernode update`

**Comment by chalith** [comment]
@chard101 any update about the issue?

**Comment by chard101** [comment]
Yes sir, issue resolved when using version 0.6.1.  Feel free to close.

Thank you.
