### ISSUE TITLE
V3 upgrade issue

### ISSUE THREAD

**Issue by lathanbritz** [EvernodeXRPL/evernode-host#82]
its not finding my old address used r4DosiqK2PYcemac4ySY9B8VXP8aRzABbP when trying to setup the new v3 instance.

<img width="492" alt="Screen Shot 2023-04-07 at 10 23 32" src="https://user-images.githubusercontent.com/508629/230625204-15e2b3d7-2e0c-44d6-a692-44cd95694532.png">

**Comment by wojake** [comment]
You don't need to use your old host's XRPL account since the account is on another network. You'd have to generate a new account on the v3 testnet @ https://dashboard.evernode.org/#/testnet-faucet

**Comment by lathanbritz** [comment]
ty @wojake i thought had to use the old one because we had to back up keys.

**Comment by lathanbritz** [comment]
accross the line thanks
