### ISSUE TITLE
Have problem during uninstalling V2

### ISSUE THREAD

**Issue by 3H54N** [EvernodeXRPL/evernode-host#84]
Hello when i try to uninstalling evernode V2 it stuck on here:

Uninstalling...
---Sashimono uninstaller---
Detected 1 contract instances.
sashi1661344849977267802
Deleting 1 contract instances...

please let me know how to fix this
Thank you

**Comment by wojake** [comment]
After you've copied your host's XRPL account credential on the V2 testnet, you could start off with a brand new instance/state and install `evernode-host`.

**Comment by kasunkavinda** [comment]
Hi @3H54N 

Is it really stuck at "Deleting 1 contract instances..." or does it print "Uninstalling user 'sashi1661344849977267802'. as well?
Can you try out whether `evernode list` or `sashi list` commands work on your machine and paste the output here?

Thanks

**Comment by TheMainlander** [comment]
> After you've copied your host's XRPL account credential on the V2 testnet, you could start off with a brand new instance/state and install `evernode-host`.

Umm I'm back home after a holiday ... how do I "After you've copied your host's XRPL account credential on the V2 testnet" from my Nodes ... eek I'm such a noob!

**Comment by TheMainlander** [comment]
> First, copy your host's credentials. Run these 2 commands on your host's command line separately:
> 
> ```
> vim /etc/sashimono/mb-xrpl/mb-xrpl.cfg
> ```
> 
> ```
> sudo vim etc/sashimono/mb-xrpl/secret.cfg
> ```
> 
> After you're done with that, you may reinstall the Evernode Host software and reinitialize your host from there.
> 
> Faucet: https://dashboard.evernode.org/#/testnet-faucet

Thank you.

**Comment by TheMainlander** [comment]
Ok, step one and two are done but with Step 2 I got this:

"etc/sashimono/mb-xrpl/secret.cfg" [New DIRECTORY]"

**Comment by TheMainlander** [comment]
Ok, now I'm stuck I don't own a Domain!

**Comment by chalith** [comment]
@TheMainlander You have to own domains for your nodes and add DNS mappings for the node IPs. Then in the evernode installation provide the respective domain

**Comment by TheMainlander** [comment]
> @TheMainlander You have to own domains for your nodes and add DNS mappings for the node IPs. Then in the evernode installation provide the respective domain

So a unique domain per Node?

**Comment by chalith** [comment]
> > @TheMainlander You have to own domains for your nodes and add DNS mappings for the node IPs. Then in the evernode installation provide the respective domain
> 
> So a unique domain per Node?

You can have unique domain names like `myhost1.myhosting.com, myhost2.myhosting.com`.
https://github.com/EvernodeXRPL/evernode-host#domain-name

**Comment by TheMainlander** [comment]
In other words, I can add sub-domains?

**Comment by chalith** [comment]
> In other words, I can add sub-domains?

Yes

**Comment by TheMainlander** [comment]
Just configuring the domain now. 

Waiting on "Please specify the domain name that this host is reachable at:" domain propagation.

**Comment by TheMainlander** [comment]
Getting closer:

Setting up letsencrypt certbot
Installing docker packages
Configuring host xrpl account

**Comment by TheMainlander** [comment]
Done.

Thank you and 2 to go.

Your system is now registered on Evernode Beta V3. You can check your system status with 'evernode status' command.
You need to logout and log back in, to complete Sashimono installation.
root@Evernode-Beta-The-Mainlander:~#

**Comment by chalith** [comment]
> Hello when i try to uninstalling evernode V2 it stuck on here:
> 
> Uninstalling... ---Sashimono uninstaller--- Detected 1 contract instances. sashi1661344849977267802 Deleting 1 contract instances...
> 
> please let me know how to fix this Thank you

@TheMainlander is this issue yours too?

**Comment by TheMainlander** [comment]
> > Hello when i try to uninstalling evernode V2 it stuck on here:
> > Uninstalling... ---Sashimono uninstaller--- Detected 1 contract instances. sashi1661344849977267802 Deleting 1 contract instances...
> > please let me know how to fix this Thank you
> 
> @TheMainlander is this issue yours too?

No.

**Comment by chalith** [comment]
@3H54N Any update about uninstalling V2?

**Comment by TheMainlander** [comment]
@chalith all done, sorry for being 'high-maintenance' but I don't often do Networking! ;)

Public addys:

1. Address: rGYPizbATsej8iJ4kDeFf7tRysf6ggwcQY
2. Address: rE9kkUTado983bLcUYKriyVHsjDoULPjDf
3. Address: rPTefScX95J1Un4MjZfLDRF2T9zdfXycta

I think I lost my PK for the Privtae Beta and Public V2 beta ... more careful this time. :(

Thanks all!

@wojake
