### ISSUE TITLE
Node Issue 05/09/23 - evernodekaiser.com

### ISSUE THREAD

**Issue by vonstegen** [EvernodeXRPL/evernode-host#90]
domain: evernodekaiser.com
XRPL Address: rD6Lgdxzq3dr42JD4F1bwF86BaCwAaeQWu
Email: ajoechl@pm.me

root@evernodekaiser:~# vim /tmp/evernode.9EJSdRrUa.log 

System:
5.4.0-148-generic
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal

sa.cfg:
{
    "version": "0.6.1",
    "hp": {
        "host_address": "evernodekaiser.com",
        "init_peer_port": 22861,
        "init_user_port": 26201
    },
    "system": {
        "max_mem_kbytes": 6518560,
        "max_swap_kbytes": 1677680,
        "max_cpu_us": 800000,
        "max_storage_kbytes": 306178080,
        "max_instance_count": 12
    },
    "docker": {
        "registry_port": 0
    },
    "log": {
        "log_level": "inf",
        "max_mbytes_per_file": 10,
        "max_file_count": 50,
        "loggers": [
            "console"
        ]
    }
}
mb-xrpl.cfg:
{
  "version": "0.6.1",
  "xrpl": {
    "address": "rD6Lgdxzq3dr42JD4F1bwF86BaCwAaeQWu",
    "governorAddress": "rGVHr1PrfL93UAjyw3DWZoi9adz2sLp2yL",
    "rippledServer": "wss://hooks-testnet-v3.xrpl-labs.com",
    "leaseAmount": 10
  }
}
Sashimono log:
-- Logs begin at Tue 2023-05-09 10:12:54 EDT, end at Tue 2023-05-09 10:14:38 EDT. --
May 09 10:12:56 evernodekaiser.com systemd[1]: Started Running and monitoring sashimono agent..
May 09 10:12:56 evernodekaiser.com sagent[479]: 20230509 10:12:56 [inf][sa] Sashimono agent (version 0.6.1)
May 09 10:12:56 evernodekaiser.com sagent[479]: 20230509 10:12:56 [inf][sa] Log level: inf
May 09 10:12:56 evernodekaiser.com sagent[479]: 20230509 10:12:56 [inf][sa] Data dir: /etc/sashimono
May 09 10:12:56 evernodekaiser.com sagent[479]: 20230509 10:12:56 [inf][sa] Message processor started.

Message board log:
^[[0;1;39mHint: You are currently not seeing messages from other users and the system.^[[0m
"/tmp/evernode.9EJSdRrUa.log" 66L, 2458C

**Comment by chalith** [comment]
Closing the issue since now resolved
