### ISSUE TITLE
Unhandeled error after lost network connectivity

### ISSUE THREAD

**Issue by marklikeapenny** [EvernodeXRPL/evernode-host#91]
Evernode host found in state "Inactive" over night.
Have a look at the first line of the syslog.log file.

VPS needed a reboot. After that Evernode host was working ok again (status "Active")
 
[evernode.SjxSPwtBf.log](https://github.com/EvernodeXRPL/evernode-host/files/11480811/evernode.SjxSPwtBf.log)
[syslog.log](https://github.com/EvernodeXRPL/evernode-host/files/11480814/syslog.log)

**Comment by kithminisg** [comment]
@marklikeapenny, It appears that your host is inactive once again. Could you kindly share the latest logs with us for further investigation?

**Comment by marklikeapenny** [comment]
@kithminisg there you go.

The system seems to have some kind of network connectivity issue. It works fine after a soft reboot but network stalls overnight. I can see from syslog that the Evernode software keeps trying to reconnect all the time (with the unhandeled error), but the system itself is offline. I cannot even SSH into it without a soft reboot. Will try to sort that out with the provider. But at least with this you have a test case for a bad network connection - actually stuff to look for when debugging.

log attached. happy hunting!

[evernode.JOhGkhIDX.log](https://github.com/EvernodeXRPL/evernode-host/files/11494944/evernode.JOhGkhIDX.log)

**Comment by kithminisg** [comment]
After reviewing the logs, we also noticed that the issue may be due to a network connectivity problem on the VM. Therefore, we are closing this issue for now.

Thank you for your feedback. If you have any concerns or require additional assistance, please don't hesitate to post them here.

**Comment by marklikeapenny** [comment]
Hi!

Yes, I am also pretty sure that this VPS server has some issues with
network connectivity and that it is not the Evernode software that makes
the network stall out.

I reported the issue in the first place because from the Evernode log you
can see that there's an unhandled error in the Evernode software under
these conditions. And this is the part that hopefully will be helpful to
improve the Evernode codebase (catch and handle this exception gracefully).

The network going down is something I need to fix with the provider for
sure. I am not blaming this problem on the Evenode software at all.

Cheers,
Mark

**Comment by kithminisg** [comment]
@marklikeapenny,
The error was actually handled and logged according to its design, even though it may give the impression of being unhandled. BTW we do appreciate your insights to improve the software. 

Thank you.

**Comment by marklikeapenny** [comment]
Glad to help!
