### ISSUE TITLE
How can I change the email address associated with my host?

### ISSUE THREAD

**Issue by rippleitinnz** [EvernodeXRPL/evernode-host#96]
As the title says. How can I change my existing host's email account, without uninstalling and reinstalling?

**Comment by chalith** [comment]
Currently, we do not support changing email address. We'll give this support soon.
For now, you can uninstall and install or use transfer functionality and reinstall the host.

**Comment by rippleitinnz** [comment]
Thanks.

As a host, it concerns me that the email address is broadcast in the dashboard for numerous reasons - none more so than the dashboard being open to public viewing which has privacy issues. 

Is there a need for anyone other than Evernode to know my email?

**Comment by jellicoe** [comment]
I have raised this issue - seems only kiwis think this is weird

**Comment by jellicoe** [comment]
I love wo Jake but this was his answer "Wo Jake — 13/04/2023 02:12
All your host's transactions and account information is publicly available since it's on the XRP Ledger. Most, if not all businesses have a public email address in order for their potential customers to inquire certain things.?

**Comment by wojake** [comment]
I understand that it may seem like a privacy and security concern to host operators, and I can see the risk.

But it's presumed that host operators are providing a hosting service professionally in a way similar to any other VPS/Cloud provider on the general market (i.e. AWS, Google Cloud, Azure, Linode).

The rationale behind this parameter is that, there needs to be an autonomous off-chain channel that tenants or users could reach to contact a host operator to discuss a topic or relay a message. (This is important)

It goes without saying that this feature has its downsides as well, the ability for malicious actors to compromise a host operator's infrastructure and credentials. Having host operators' email address out in the public introduces attack vectors to hackers, they're able to relay malicious content (files, link, etc) to host operators and compromise their operation.

While this is a *realistic concern*, there are also steps that could be taken by host operators to combat this attack vector, I'll keep it short:
0. Differentiate your network from the host's
1. Implement a firewall on the host's network layer (and yours)
2. Implement rules on your email service to filter out any incoming files, links, images and exes.
3. If you truly don't want to put *any* of your email addresses up for reach, just put a fake one (maybe?)

If users want to send you a file, you have to trust them and use another means to communicate. I hope this helps 😄

**Comment by ravinsp** [comment]
I think wojake has explained it well. It's not "your" email. It's the email of your business. 
A business website would not publish the personal email address of the owner of that business. Rather, it would publish the company contact/head office email on the website. 
If you approach it like that, you won't have privacy concerns.

Please let us know if our setup wording/instructions is misleading and making you think about the email in a wrong manner.

**Comment by rippleitinnz** [comment]
"Email address for others to contact/report issues on your host"

There is nothing in there that suggests that this would be made publicly available to everybody other than Evernode and/or hosts.

I understand my security around email and email addresses I may use, however it should be made clear in your documentation how any information a host provides to Evernode is going to be used.

If I knew my email was going to be broadcast to the world I would have ensured that an email address was used that would fit my privacy concerns, as well as ensuring it wasn't going to affect me or my business as a possible spam/attack vector by using an email server not associated with my business. 

This is important and shouldn't be simply brushed aside using blockchain being public as an excuse. 

I still see no reason why a host needs to email me other than there being an issue, which should be handled by/through Evernode.

**Comment by ravinsp** [comment]
@rippleitinnz 
1. We will make this more clear and the purposes the email is used in the readme.
2. During the setup where you have to input the email, this is the prompt: `Specify the contact email address (this will be published on the ledger):`. We will update this message too since this seems to have not conveyed the message that it's really made public for the whole world.

**Comment by ScottChamberlain** [comment]
Ravin, this is a fair comment: 

“If I knew my email was going to be broadcast to the world I would have ensured that an email address was used that would fit my privacy concerns, as well as ensuring it wasn't going to affect me or my business as a possible spam/attack vector by using an email server not associated with my business.at the time of inputting the email, the Host should be prompted to confirm they are happy for that email to be published to the ledger and available publicly.”

We need ensure the Host is promoted not just to input their email but that they confirm it will be published to the ledger and publicly available. They need to be able to choose an appropriate email.

Email requirement is not an easy decision and we understand the concerns. It flows firstly from the SSL requirement. We need Hosts to have SSL or the contract user experience will be greatly retarded. The free SSL service requires an email. You don’t *need * to use the free SSL service, but, again, it was adopted for user convenience/scale. 

As a general rule, Hosts are businesses and need to be contactable. They may unknowingly be hosting copyrighted or other illegal content that might be subject to takedown notices. As a Host, you will want to be contactable so you can be advised of these problems and take action. Many jurisdictions have safe harbours for hosting problematic content that is not yours, but you generally need to respond promptly to take down requests to ensure you get the benefit of those immunities.

A Host that isn’t willing to be contactable by customers or regulatory authorities isn’t really the kind of host the evernode network wants to attract.

**Comment by jellicoe** [comment]
a work around is to use an email forwarder on the DNS domain you use for hosting the Evernodes at, so

evernode01@nodedomain.com forward to bob@gmail.com

**Comment by rippleitinnz** [comment]
> Ravin, this is a fair comment:
> 
> “If I knew my email was going to be broadcast to the world I would have ensured that an email address was used that would fit my privacy concerns, as well as ensuring it wasn't going to affect me or my business as a possible spam/attack vector by using an email server not associated with my business.at the time of inputting the email, the Host should be prompted to confirm they are happy for that email to be published to the ledger and available publicly.”
> 
> We need ensure the Host is promoted not just to input their email but that they confirm it will be published to the ledger and publicly available. They need to be able to choose an appropriate email.
> 
> Email requirement is not an easy decision and we understand the concerns. It flows firstly from the SSL requirement. We need Hosts to have SSL or the contract user experience will be greatly retarded. The free SSL service requires an email. You don’t *need * to use the free SSL service, but, again, it was adopted for user convenience/scale.
> 
> As a general rule, Hosts are businesses and need to be contactable. They may unknowingly be hosting copyrighted or other illegal content that might be subject to takedown notices. As a Host, you will want to be contactable so you can be advised of these problems and take action. Many jurisdictions have safe harbours for hosting problematic content that is not yours, but you generally need to respond promptly to take down requests to ensure you get the benefit of those immunities.
> 
> A Host that isn’t willing to be contactable by customers or regulatory authorities isn’t really the kind of host the evernode network wants to attract.

Totally get this. Even though the email is published in the ledger, in its native form it isn't humanly readable so takes some work to convert. 

I'm wondering if it needs to be broadcast in the dashboard as opposed to having it in the tenant agreement?

Different jurisdictions have different requirements for Privacy statements and how information is used so it needs to be relevant and certainly readily changeable in the event that it needs to be changed at short notice, without impacting your hosting abilites or any existing tenant's.

**Comment by ravintrmedia** [comment]
Added this description to clarify email usage on the Readme: https://github.com/EvernodeXRPL/evernode-host/blob/main/README.md#email-address

Let's keep this issue open until we provide the ability to change the email easily.

**Comment by ravinsp** [comment]
Added this description to clarify email usage on the Readme: https://github.com/EvernodeXRPL/evernode-host/blob/main/README.md#email-address

Let's keep this issue open until we provide the ability to change the email easily.

**Comment by chalith** [comment]
@rippleitinnz We've released a new version of Sashimono with email update capability. You can find the announcement [here](https://github.com/EvernodeXRPL/evernode-host/issues/70#issuecomment-1582061966)

**Comment by rippleitinnz** [comment]
Thanks so much! A welcome addition.

**Comment by jellicoe** [comment]
good work chalith and team !!!

**Comment by chalith** [comment]
Closing the issue since now it's addressed.
